LuccaSA/lucca-front

packages/scss/src/components/footer/component.scss
packages/scss/src/components/footer/exports.scss
packages/scss/src/components/footer/index.scss
packages/scss/src/components/footer/mods.scss
packages/scss/src/components/footer/vars.scss
packages/scss/src/components/index.scss
stories/documentation/structure/footer/footer-basic.stories.ts
stories/qa/footer/footer.stories.html
stories/qa/footer/footer.stories.ts

New component : Footer
-----
-----

[Components v3] Footer

---

packages/ng/establishment/src/lib/select/select-all/establishment-select-all.translate.ts

Remove capitalize on deselect french
-----
-----

Fix translation on deselect

---

packages/ng/styles/definitions/tooltip/_tooltip.scss

[Tooltip] Center text

---

packages/scss/src/components/actionIcon/component.scss
packages/scss/src/components/actionIcon/mods.scss
packages/scss/src/components/button/mods.scss

Darker hover/active states
-----

[Button & Action icons] Darker hover/active states

---

packages/scss/src/components/radioButtons/component.scss

Fix component breaking modal scroll
-----

[Radio Button] Fix component breaking modal scroll

---

Jenkinsfile

Use `commentOnPR` script in anticipation of switching to linux based CI builds 
-----

feat(ci): use commentOnPR script

---

packages/scss/src/components/button/component.scss
packages/scss/src/components/button/mods.scss
stories/qa/button/button.stories.html

Fix `<a>` button hover state
-----

[Button] Fix link element button hover state

---

packages/ng/material/style/_components.scss
packages/ng/material/style/components/_autocomplete.scss
packages/ng/material/style/components/_buttons.scss
packages/ng/material/style/components/_datepicker.scss
packages/ng/material/style/components/_dialog.scss
packages/ng/material/style/components/_input.scss
packages/ng/material/style/components/_menu.scss
packages/ng/material/style/components/_mixins.scss
packages/ng/material/style/components/_options.scss
packages/ng/material/style/components/_select.scss
packages/ng/material/style/components/_tooltip.scss
packages/ng/material/style/main.scss
packages/ng/styles/definitions/user/user-picture.scss

Material style as deprecated
https://prisme.lucca.io/94310e217/p/40c515-elements-deprecies
-----

Material style as deprecated

---

packages/scss/src/components/title/component.scss

Improve titles weight rendering
-----
https://github.com/LuccaSA/lucca-front/assets/25581936/847fd002-cda8-4c42-9da7-7d43ab2a261e
-----

Improve titles weight rendering

---

stories/documentation/actions/button/button-basic2.stories.ts

Improve ZH stories integration
-----

Improve ZH stories integration

---

stories/documentation/forms/checkbox-legacy/checkbox-basic.stories.ts
stories/documentation/forms/checkbox-legacy/checkbox-incomplete.stories.ts
stories/documentation/forms/checkbox/checkbox-basic.stories.ts
stories/documentation/forms/radio-legacy/radio-legacy-basic.stories.ts
stories/documentation/forms/radio-legacy/radio-legacy-helper.stories.ts
stories/documentation/forms/radio/radio-basic.stories.ts
stories/documentation/forms/switch-legacy/switch-legacy-basic.stories.ts
stories/documentation/forms/switch-legacy/switch-legacy-helper.stories.ts
stories/documentation/forms/switch/switch-basic.stories.ts
stories/documentation/forms/textfield-legacy/textfield-basic.stories.ts
stories/documentation/forms/textfield-legacy/textfield-clearable.stories.ts
stories/documentation/forms/textfield-legacy/textfield-feedback.stories.ts
stories/documentation/forms/textfield-legacy/textfield-filter.stories.ts
stories/documentation/forms/textfield-legacy/textfield-messages.stories.ts
stories/documentation/forms/textfield-legacy/textfield-multiline.stories.ts
stories/documentation/forms/textfield-legacy/textfield-password.stories.ts
stories/documentation/forms/textfield-legacy/textfield-radio.stories.ts
stories/documentation/forms/textfield-legacy/textfield-suffixes.stories.ts
stories/documentation/forms/textfield/textfield-basic.stories.ts

Improve stories format (remove empty lines, tabs, spaces) on zeroheight for : 
- Textfield
- Textfield (legacy)
- Swtich
- Switch (legacy)
- Checkbox
- Checkbox (legacy)
- Radio
- Radio (legacy)
-----
Current :
-----

ZH — Improve stories format

---

stories/documentation/feedback/callout/angular/callout-basic.stories.ts
stories/documentation/feedback/callout/angular/callout-icons.stories.ts
stories/documentation/feedback/callout/angular/callout-killable.stories.ts
stories/documentation/feedback/callout/angular/callout-tiny.stories.ts
stories/documentation/feedback/callout/html&css/callout-basic.stories.ts
stories/documentation/feedback/callout/html&css/callout-icons.stories.ts
stories/documentation/feedback/callout/html&css/callout-killable.stories.ts
stories/documentation/feedback/callout/html&css/callout-tiny.stories.ts
stories/documentation/forms/inline-message/angular/inline-message-basic.stories.ts
stories/documentation/forms/inline-message/html&css/inline-message-basic.stories.ts
stories/documentation/texts/new-badge/angular/new-badge.stories.ts
stories/documentation/texts/new-badge/html&css/new-badge.stories.ts
stories/documentation/texts/numeric-badge/angular/numeric-badge.stories.ts
stories/documentation/texts/numeric-badge/html&css/numeric-badge-basic.stories.ts

Display both Angular & HTML/CSS stories for
- New badge
- Numeric badge
- Inline message
- Callout
-----

Zh.stories.angular+css

---

stories/documentation/forms/inline-message/html&css/inline-message-basic.stories.ts

Fix inline message category URL
-----
As it was 
-----

[Storybook] Fix inline message category URL

---

packages/scss/src/components/file/states.scss
packages/scss/src/components/textfields/states.scss

[icon] Fix states

---

packages/ng/api/select/input/api-select-input.component.scss
packages/ng/department/select/input/department-select-input.component.scss
packages/ng/establishment/select/input/establishment-select-input.component.scss
packages/ng/simple-select/input/select-input.component.scss
packages/ng/styles/definitions/select/_select-input.scss
packages/ng/user/select/input/user-select-input.component.scss
packages/scss/src/components/button/mods.scss

Fixes
- Replace select & Button more arrows by carrets
- Improve selects right padding with clearer
- Fix clearer position on `mod-S`
-----

Select fixes

---

packages/ng/styles/definitions/select/_select-input.scss

Fix clearer position conditionned by mod-S
-----

Fix clearer position condition

---

packages/ng/styles/definitions/select/_select-input.scss
packages/scss/src/components/field/component.scss

Remove !important on textfield padding
-----

[Select] Remove !important on textfield padding

---

packages/scss/src/components/callout/component.scss

Fix clearer color in callout context
-----
-----

[Clear] Fix color in callout context

---

packages/scss/src/commons/core.scss
packages/scss/src/components/util/index.scss

Overflow:
I generate the most common utilities, but deliberately omit `overflow-x`, `overflow-y` and `clip`.
Border-radius:
`!important` is now present on the utility.
-----
-----

Utils for overflow + Border radius !important

---

packages/icons/src/icon/index.scss
packages/icons/src/icon/mods.scss
packages/scss/src/components/actionIcon/component.scss
packages/scss/src/components/actionIcon/mods.scss
packages/scss/src/components/button/component.scss
packages/scss/src/components/button/mods.scss
stories/documentation/texts/icons/icon-sizes.stories.ts
stories/qa/icon/icon.stories.html

- Fix icons sizes mod
- Make icons sizes mod accessible as mixin
- Link icons sizes mixins in buttons & action icons
- Fix button / action icons icon default size
-----

Icons & Button / Action icons

---

packages/ng/styles/components/_popup.scss

[Modal] Improve content padding

---

packages/scss/src/commons/config.scss
packages/scss/src/commons/vars.scss
stories/qa/colors/colors.stories.html
stories/qa/colors/colors.stories.ts

- Add alternative palettes
- Create a QA page to vizualise colors
-----

Add alternative palettes

---

stories/documentation/navigation/pagination/pagination-basic.stories.ts
stories/documentation/navigation/pagination/pagination-compact.stories.ts
stories/documentation/navigation/pagination/pagination-pages.stories.ts

Fix pagination icons
-----
-----

[Pagination] Fix icons

---

stories/documentation/structure/grids/grids-responsive.stories.ts

Edit stories classes to avoid our workaround need
-----

[Grid] Workaround classes

---

packages/scss/src/components/title/component.scss

If the browser supports it, we balance the line lengths on multiline titles.
-----
-----

Proposal to balance lines on titles

---

packages/scss/src/commons/config.scss
stories/qa/colors/colors.stories.html

Update decorative colors
-----
-----

[Colors] Update decorative colors

---

packages/scss/src/components/tableSorted/states.scss
stories/documentation/listings/table/table-sortable.stories.ts

[Sorting into tables was no longer working](https://github.com/LuccaSA/lucca-front/issues/2303), so I added a story to test and correct it.
-----
-----

Fix table sort + story

---

packages/scss/src/components/fieldset/component.scss
packages/scss/src/components/fieldset/exports.scss
packages/scss/src/components/fieldset/index.scss
packages/scss/src/components/fieldset/mods.scss
packages/scss/src/components/fieldset/vars.scss
packages/scss/src/components/grid/component.scss
packages/scss/src/components/index.scss
packages/scss/src/components/switch/index.scss
stories/documentation/forms/fieldset/fieldset-basic.stories.ts

New fieldset component for forms. It comes with three mod:
- alignment to the left of its title;
- toggle system with a button;
- ~~toggle system with a switch.~~
You can also pass in an optional helper.
-----
NB: I modified a few things in grid and switch components so that the whole thing could work together.
-----

Fieldset component

---

packages/scss/src/commons/config.scss
packages/scss/src/commons/vars.scss
stories/qa/colors/colors.stories.html

Add Lucca's palette to cover further needs
-----
-----

Add Lucca's palette

---

packages/scss/src/commons/core.scss

Generate new utilities with logical properties. For example:
- `u-marginInline0`
- `u-paddingBlockXL`
- `u-borderBlockS`
-----
-----

Add utilitities for *-block and *-inline properties

---

stories/documentation/texts/text/text.stories.ts
stories/qa/typography/typography.stories.html

remove refs to deleted text size classes.
-----

remove refs to deleted text size classes

---

.storybook/styles.scss

Icon-funnel is deprecated

---

packages/scss/src/commons/base.scss

Remove scrollbar-gutter to avoid background images issues
-----

remove scrollbar-gutter

---

packages/scss/src/commons/config.scss

Update grey 50/100/200 colors
-----
before 
after
-----

update grey 50/100/200

---

packages/ng/multi-select/panel/panel.component.scss

- Fix column height that didn't take in consideration if search was visible or not (leading to extra space on left column)
- Fix column left top spacing when search is not visible
-----

[Multiselect] Fix spacing and column height

---

packages/ng/multi-select/panel/panel.component.scss

fix left column spacing when search is not visible
-----

fix left column spacing when search is not visible

---

stories/documentation/loaders/skeleton/skeleton-circle.stories.ts
stories/documentation/loaders/skeleton/skeleton-dark.stories.ts
stories/documentation/loaders/skeleton/skeleton-square.stories.ts
stories/documentation/loaders/skeleton/skeleton-texts.stories.ts
stories/documentation/loaders/skeleton/skeleton-titles.stories.ts
stories/documentation/loaders/skeleton/skeleton-width.stories.ts

Skeleton stories folder in Loaders
-----

Skeleton in loaders folder

---

stories/documentation/loaders/skeleton/skeleton-circle.stories.ts
stories/documentation/loaders/skeleton/skeleton-dark.stories.ts

- Use global mod-dark by default
- Remove mod-dark from circles stories
-----

skeletons docs fixes

---

packages/ng/simple-select/api/api-v4.directive.ts

Default sort value for LuSimpleSelectApiV4Directive was invalid.
-----

fix(select): invalid initial v4 sort

---

.eslintrc
angular.json
packages/ng/button/button.component.scss
packages/ng/button/button.component.ts
packages/ng/button/ng-package.json
packages/ng/button/public-api.ts
stories/documentation/actions/button/button-wrapper.stories.ts

Add the new `luButton` directive.
The directive (while made with a `@Component` decorator is matching `button[luButton]` and `a[luButton]`, with the following usage:
```ts
<button luButton>Click me !</button>
```
Or with more options:
```ts
<button luButton="outlined" size="S" block palette="primary">Click me !</button>
```
-----
-----

feat(button): new button Angular directive

---

packages/scss/src/components/card/component.scss

Fix the proper usage of the following variables: 
- `--components-card-border-radius`
- `--components-card-border-color`
-----

[Card] Fix unused variables

---

stories/documentation/texts/icons/HTML&CSS/icon-sizes.stories.ts

Test new story format with HTML component
-----

Stories format & HTML components

---

packages/ng/core/date/native/native-date.adapter.ts

Fix date-select search with year granularity
-----
Bug : 
https://github.com/LuccaSA/lucca-front/assets/35571450/f054298f-4b58-40c0-9da0-58e53f006598
-----

Fix date-select search with year granularity

---

packages/scss/src/components/newBadge/component.scss

Apply Lucca's palette instead of primary
-----

[New badge] Lucca's palette instead of primary

---

stories/documentation/forms/inline-message/html&css/inline-message-basic.stories.ts
stories/documentation/forms/inline-message/html&css/inline-message-size.stories.ts
stories/documentation/forms/inline-message/html&css/inline-message-states.stories.ts

- Add states
- Flat stories
-----

[Inline message] Stories

---

packages/scss/src/components/button/mods.scss
packages/scss/src/components/button/states.scss
packages/scss/src/components/radioButtons/component.scss
packages/scss/src/components/radioButtons/states.scss

- Radio / Radiobutton box shadow inset -> outset
- Radiobutton box shadow color 200 -> 300
-----

[Radiobutton / Button] Box shadow

---

packages/scss/src/components/card/mods.scss
stories/qa/card/card.stories.html

Add focus style to card clickable
-----

[Card][Clickable] Add focus style

---

packages/ng/multi-select/displayer/default-displayer.component.scss
packages/ng/styles/definitions/select/_select-input.scss

Fix multi displayer, click zone and padding
-----

[Select] Fix multi displayer, click zone and padding

---

packages/icons/src/commons/base.scss

Remove svg and ttf files for icofonts

---

packages/scss/src/components/button/states.scss
packages/scss/src/components/menu/states.scss
packages/scss/src/components/numericBadge/mods.scss
packages/scss/src/components/numericBadge/states.scss
packages/scss/src/components/radioButtons/component.scss
packages/scss/src/components/radioButtons/states.scss
stories/documentation/texts/status/status-basic.stories.ts
stories/qa/button/button.stories.html
stories/qa/forms/radio-buttons.stories.html
stories/qa/menu/menu.stories.html

- Add numericBadge disabled compatibility with radiobutton 
- Improve nested code by applying numericBadge mods and states mixins
- Bonus : fix disabled button text color
-----

[numericBadge] Nested compatibility

---

stories/documentation/actions/button/angular/button-basic.stories.ts
stories/documentation/actions/button/angular/button-counter.stories.ts
stories/documentation/actions/button/angular/button-icon.stories.ts

Added two new button-related stories to show how to create a button with an icon and a button with a counter using the new `luButton` component.
-----
-----

docs(button): new stories for luButton with icon and with counter

---

packages/ng/user/picture/user-picture.component.html
packages/ng/user/picture/user-picture.component.ts
stories/documentation/users/picture/picture.stories.ts
stories/documentation/users/user.mocks.ts

- Updated luUserPicture template with img tag to check potential href errors.
- Add href error method to display initials image.
-----

[UserPicture] Use initials in case of pictureHref error

---

Jenkinsfile

chore: bump Jenkins Shared Lib

---

packages/ng/icon/icon.component.scss

Fix primary color / remove duplicated success color
-----

[Icon] Fix primary color

---

stories/documentation/actions/button/button-icon.stories.ts

Fix Icon story typo
-----
-----

[Button] Icon story typo

---

packages/ng/button/button.component.ts
stories/documentation/actions/button/angular/button-basic.stories.ts
stories/documentation/actions/button/angular/button-counter.stories.ts
stories/documentation/actions/button/angular/button-icon.stories.ts

Fix the issue with `<button luButton></button>` throwing a compilation error due to unsupported default value for the input.
-----
-----

fix(button): fix compilation error when using luButton without a value

---

packages/scss/src/components/verticalNavigation/states.scss

Fix active colors
-----
https://github.com/LuccaSA/lucca-front/assets/25581936/7bed7836-c60b-4803-981a-52302796e831
-----

[Vertical navigation] Fix active colors

---

packages/scss/src/commons/config.scss

Figma associé : https://www.figma.com/file/Z3U9qNU5cZxpWKfqoddKcQ/Decoratives-colors?type=design&node-id=8618-638&mode=design&t=5kTnQb1jxWmya3U1-0
-----
-----

Fix color for decorative glacier 200

---

stories/documentation/overlays/modal/modal.stories.ts

Remove XXL from documentation which is not covered by DS
-----

[Modal] Remove XXL from documentation

---

packages/scss/src/components/divider/component.scss
packages/scss/src/components/divider/index.scss
packages/scss/src/components/divider/mods.scss
packages/scss/src/components/divider/vars.scss
stories/documentation/structure/divider/divider-basic.stories.ts

New options for the divider component:
-----
-----

Divider with text or action

---

packages/scss/src/components/tableSorted/mods.scss
packages/scss/src/components/tableSorted/states.scss

Sticking to the guideline: the state displayed by the icons and the current state.
-----
-----

Fix table sort icon direction

---

packages/ng/styles/definitions/user/user-picture.scss

 FIX distorted avatars 

---

packages/ng/styles/definitions/user/user-picture.scss

When using a non square image the avatar image was distorted.
-----

FIX distorted avatars

---

packages/scss/src/components/textfields/mods.scss
stories/qa/forms/textfield-legacy.stories.html

Fix background color on legacy textfield clearer
-----
-----

[Legacy Textfield] Fix clearer background

---

packages/scss/src/commons/config.scss

Sorry, a little problem with the list merge that caused the color variables for states to disappear.
-----
-----

Fix all palettes

---

Jenkinsfile

Bump Jenkins Shared Lib
-----
-----

chore(ci): bump Jenkins Shared Lib

---

packages/scss/src/components/callout/component.scss
packages/scss/src/components/calloutDisclosure/component.scss
packages/scss/src/components/calloutPopover/component.scss

Fix components height (border > boxshadow)
-----

[Callouts] Fix components height

---

packages/ng/icon/icon.component.ts
stories/documentation/texts/icons/HTML&CSS/icon-sizes.stories.ts

Add XXS size to HTML & Angular documentation
-----

[Icons] Add XXS to documentation

---

packages/ng/callout/callout-disclosure/callout-disclosure.component.html
packages/ng/callout/callout-disclosure/callout-disclosure.component.ts
stories/documentation/feedback/callout-disclosure/angular/callout-disclosure.stories.ts

Add open control to component `lu-callout-disclosure`
-----
Add banana box `open` on `lu-callout-disclosure`
-----

[2457] Add open banana box on lu-callout-disclosure

---

stories/documentation/structure/grids-legacy/grids-auto-width.stories.ts
stories/documentation/structure/grids-legacy/grids-basic.stories.ts
stories/documentation/structure/grids-legacy/grids-horizontal-alignment.stories.ts
stories/documentation/structure/grids-legacy/grids-justify.stories.ts
stories/documentation/structure/grids-legacy/grids-offset.stories.ts
stories/documentation/structure/grids-legacy/grids-sort.stories.ts
stories/documentation/structure/grids-legacy/grids-vertical-alignment.stories.ts

Note: I've fixed the compilation here, but the stories still aren't correct, since `grid` and `gridLegacy` can't be loaded simultaneously.
-----
-----

Fix compilation for grid legacy stories

---

packages/scss/src/components/file/component.scss
packages/scss/src/components/file/states.scss

cf. https://github.com/LuccaSA/lucca-front/issues/2431
Fix cursor mode on file upload
-----
-----

[File upload] Fix cursor mode 

---

packages/scss/src/components/card/mods.scss

Set focus style on card instead of arrow if arrow is focused.
-----
https://github.com/LuccaSA/lucca-front/assets/25581936/23d1ecbd-ee4d-4e8d-98c2-34e640e0d4a7
-----

[Card] Component focus style 

---

packages/ng/callout/callout/callout.component.ts
packages/ng/new-badge/new-badge.component.ts
packages/ng/numeric-badge/numeric-badge.component.ts

Fix style import on a bunch of new components:
- numeric badge
- new badge
- callout (standard)
-----

[Wrapped components] Fix style import on a bunch of new components

---

packages/scss/src/components/grid/index.scss

Adds classes to manage mod-auto grids based on breakpoints.
fix #2478 
-----
-----

Grid mod auto + rwd

---

stories/documentation/structure/grids/grids-position-responsive.stories.ts
stories/documentation/structure/grids/grids-responsive.stories.ts
stories/documentation/structure/grids/grids-span-responsive.stories.ts

Demos for responsive grid (#2478)

---

packages/ng/styles/components/_popup.scss

Title size changes.
fix #2179 
-----
-----
Before: 
After:

Dialog title

---

packages/ng/styles/definitions/user/user-picture.scss
packages/scss/src/commons/config.scss
packages/scss/src/commons/utils/loading.scss
packages/scss/src/components/chip/component.scss
packages/scss/src/components/clear/component.scss
packages/scss/src/components/field/states.scss
packages/scss/src/components/label/component.scss
packages/scss/src/components/radio/component.scss
packages/scss/src/components/radioField/component.scss
packages/scss/src/components/radioField/vars.scss
packages/scss/src/components/skeleton/mods.scss
packages/scss/src/components/status/component.scss
packages/scss/src/components/statusBadge/component.scss
packages/scss/src/components/switch/component.scss
packages/scss/src/components/switchField/component.scss
packages/scss/src/components/textfields/mods.scss
packages/scss/src/components/timeline/component.scss
packages/scss/src/components/timeline/mods.scss
packages/scss/src/components/toast/mods.scss
stories/documentation/structure/grids-legacy/grids-auto-width.stories.ts
stories/documentation/structure/grids-legacy/grids-basic.stories.ts
stories/documentation/structure/grids-legacy/grids-horizontal-alignment.stories.ts
stories/documentation/structure/grids-legacy/grids-justify.stories.ts
stories/documentation/structure/grids-legacy/grids-offset.stories.ts
stories/documentation/structure/grids-legacy/grids-sort.stories.ts
stories/documentation/structure/grids-legacy/grids-vertical-alignment.stories.ts

Border-radius full

---

packages/scss/src/components/emptyState/component.scss

Increase empty state content width
360px > 400px
-----

[Empty State] Increase content width

---

packages/ng/empty-state/empty-state-page/empty-state-page.component.html
packages/ng/empty-state/empty-state-page/empty-state-page.component.scss
packages/ng/empty-state/empty-state-page/empty-state-page.component.ts
packages/ng/empty-state/empty-state-section/empty-state-section.component.ts
packages/scss/src/components/emptyState/component.scss
stories/documentation/feedback/empty-state/angular/empty-state-page.stories.ts
stories/documentation/feedback/empty-state/angular/empty-state-section.stories.ts

Empty state: fixes

---

packages/scss/src/components/grid/index.scss
packages/scss/src/components/grid/mods.scss
stories/documentation/structure/grids/grids-auto-responsive.stories.ts

Grid: fixes

---

packages/ng/multi-select/input/select-input.component.scss
packages/ng/styles/components/_popup.scss
packages/scss/src/components/button/index.scss
packages/scss/src/components/button/mods.scss
packages/scss/src/components/multiSelect/mods.scss
stories/qa/button/button.stories.html

- Button : Add mod-delete
- Multiselect : fix css import
- Multiselect : fix mod-S height
- Popup : Fix title font weight
-----

Fix RC 17.2

---

packages/ng/empty-state/empty-state-page/empty-state-page.component.ts
packages/scss/src/components/emptyState/vars.scss
stories/documentation/feedback/empty-state/html&css/empty-state-page.stories.scss
stories/qa/empty-state/empty-state-page.stories.scss

Fix background color default for empty states

---

.storybook/preview.mjs
stories/documentation/feedback/empty-state/angular/empty-state-page.stories.ts

Change backgrounds colors

---

stories/documentation/integration/utilities/borders-radius.stories.ts
stories/documentation/integration/utilities/borders.stories.ts
stories/documentation/integration/utilities/shadows.stories.ts
stories/documentation/structure/box/box-arrow.stories.ts
stories/documentation/structure/box/box-basic.stories.ts
stories/documentation/structure/box/box-killable.stories.ts
stories/documentation/structure/box/box-toggle.stories.ts
stories/documentation/structure/grids/grids-alignments.stories.ts
stories/documentation/structure/grids/grids-auto-responsive.stories.ts
stories/documentation/structure/grids/grids-auto.stories.ts
stories/documentation/structure/grids/grids-basic.stories.ts
stories/documentation/structure/grids/grids-form.stories.ts
stories/documentation/structure/grids/grids-gap.stories.ts
stories/documentation/structure/grids/grids-position-responsive.stories.ts
stories/documentation/structure/grids/grids-position.stories.ts
stories/documentation/structure/grids/grids-responsive.stories.ts
stories/documentation/structure/grids/grids-span-responsive.stories.ts
stories/documentation/structure/grids/grids-span.stories.ts
stories/documentation/toolbox/animations/animations.scss

Fixes related to grey 25 as default background color
-----
-----

[Storybook] Fixes related to grey 25 as default background color

---

packages/scss/src/components/emptyState/component.scss
packages/scss/src/components/emptyState/mods.scss

Content background / shadow only on page option
-----

[Empty State] Content background / shadow only on page option

---

stories/documentation/feedback/empty-state/html&css/empty-state-section-center.stories.ts
stories/documentation/feedback/empty-state/html&css/empty-state-section-palette.stories.ts
stories/documentation/feedback/empty-state/html&css/empty-state-section.stories.ts

Empty states stories format
-----

Empty states stories format

---

packages/scss/src/components/button/component.scss
packages/scss/src/components/button/index.scss
packages/scss/src/components/button/mods.scss
packages/scss/src/components/button/states.scss
packages/scss/src/components/button/vars.scss
packages/scss/src/components/buttonGroup/mods.scss
stories/documentation/actions/button/html&css/button-palette.stories.ts
stories/documentation/actions/button/html&css/button-size.stories.ts
stories/documentation/actions/button/html&css/button-states.stories.ts
stories/documentation/actions/button/html&css/button-style.stories.ts
stories/qa/button/button.stories.html

fix #1779 
fix #1880 
-----
-----

Button cleanup

---

packages/ng/date/calendar/calendar-input.component.html
packages/ng/forms/text-input/text-input.component.html
packages/ng/modal/modal-panel.component.html
packages/scss/src/components/calloutFeedbackList/component.scss
packages/scss/src/components/calloutFeedbackList/index.scss
packages/scss/src/components/calloutFeedbackList/mods.scss
packages/scss/src/components/divider/component.scss
packages/scss/src/components/divider/index.scss
packages/scss/src/components/divider/mods.scss
packages/scss/src/components/divider/vars.scss
stories/documentation/listings/table/table-actions.stories.ts
stories/documentation/navigation/pagination/pagination-basic.stories.ts
stories/documentation/navigation/pagination/pagination-compact.stories.ts
stories/documentation/navigation/pagination/pagination-pages.stories.ts
stories/documentation/navigation/skip-links/skip-links-basic.stories.ts
stories/documentation/structure/box/box-killable.stories.ts
stories/documentation/structure/cards/cards-action.stories.ts
stories/documentation/structure/divider/divider-basic.stories.ts
stories/documentation/structure/mobile-header/mobile-header-basic.stories.ts
stories/documentation/structure/page-header/page-header-basic.stories.ts
stories/documentation/structure/page-header/page-header-breadcrumb.stories.ts
stories/documentation/structure/page-header/page-header-menu.stories.ts
stories/qa/box/box.stories.html
stories/qa/card/card.stories.html
stories/qa/divider/divider.stories.html
stories/qa/icon/icon.stories.html
stories/qa/mobile-header/mobile-header.stories.html
stories/qa/page-header/page-header.stories.html
stories/qa/pagination/pagination.stories.html
stories/qa/table/table.stories.html

Replace components & documentation references by button
-----

[ActionIcon] Replace components & documentation references by button

---

packages/ng/icon/icon.component.scss
stories/documentation/feedback/callout-popover/html&css/basic.stories.ts
stories/documentation/feedback/callout-popover/html&css/size.stories.ts
stories/qa/callout/callout.stories.html

- Fix icons alignement with S size
- Add dropdown in HTML stories
-----
-----

[Callouts] Fix icons alignement with S size

---

stories/documentation/feedback/callout-disclosure/angular/callout-disclosure.stories.ts
stories/documentation/forms/fields/text/angular/textfield.stories.ts
stories/documentation/integration/utilities/borders-radius.stories.ts
stories/documentation/integration/utilities/borders.stories.ts
stories/documentation/integration/utilities/comma.stories.ts
stories/documentation/integration/utilities/ellipsis.stories.ts
stories/documentation/integration/utilities/float.stories.ts
stories/documentation/integration/utilities/help.stories.ts
stories/documentation/integration/utilities/reset.stories.ts
stories/documentation/integration/utilities/shadows.stories.ts
stories/documentation/integration/utilities/spin.stories.ts
stories/documentation/integration/utilities/text-color.stories.ts
stories/documentation/integration/utilities/text-size.stories.ts
stories/documentation/integration/utilities/text-style.stories.ts
stories/documentation/integration/utilities/units.stories.ts
stories/documentation/integration/utilities/vertical-align.stories.ts
stories/documentation/structure/grids/grids-auto-responsive.stories.ts
stories/documentation/texts/status-badge/status-badge-basic.stories.ts
stories/documentation/users/picture/picture.stories.ts

- Improve documentation versions info
- Improve documentation cope format
-----

[Documentation] Improve stories

---

stories/documentation/texts/text/text.stories.ts

[Titles & Texts] Add missing styles
-----
-----

[Titles & Texts] Add missing styles

---

packages/scss/src/components/callout/component.scss
packages/scss/src/components/link/mods.scss
stories/documentation/actions/links/link-basic.stories.ts
stories/documentation/actions/links/link-disabled.stories.ts
stories/documentation/actions/links/link-external.stories.ts
stories/documentation/actions/links/link-hover.stories.ts

Link icon with no wrap before icon

---

packages/ng/numeric-badge/numeric-badge.component.ts
stories/documentation/texts/numeric-badge/angular/numeric-badge.stories.ts

LuNumericBadge: Add `string` type
-----
-----

[2506] LuNumericBadge : Support string type

---

stories/documentation/structure/page-header/page-header-basic.stories.ts
stories/documentation/structure/page-header/page-header-breadcrumb.stories.ts
stories/documentation/structure/page-header/page-header-menu.stories.ts
stories/qa/page-header/page-header.stories.html

Remove section in header

---

packages/ng/option/item/tree-option-item.component.scss

Fix checkbox & sort icon position
-----
-----

[Departement] Fix checkbox & sort icon position

---

packages/scss/src/components/checkbox/component.scss

Fix #2560 
-----
-----
Before: 
After:

Fix gap for legacy mandatory checkbox

---

packages/scss/src/components/simpleSelect/component.scss

fix #2566 
-----
Thanks @BertrandPodevin for the solution.
-----
Before:
After:

Fix chevron for simple Select

---

packages/scss/src/commons/config.scss

H2 padding 8px > 6px
-----
-----

[Titles] Reduce H2 padding

---

packages/scss/src/components/dialog/component.scss

Following the dialog and palette merge, some classes still needed to be renamed.
-----
-----

grey -> neutral

---

packages/ng/multi-select/input/select-input.component.scss
packages/ng/simple-select/input/select-input.component.scss

fix #2544
-----
-----
Before:
After:

SimpleSelect/Multiselect – Add imports for clear and utilities 

---

packages/scss/src/components/checkbox/component.scss

Conflict between the PR that fixed the thickness of the border and the PR that replaced the gap with a margin. Fixed now!
-----
-----

Fix checkbox margin

---

packages/ng/qualification/select/input/qualification-select-input.component.html
stories/documentation/users/select/user-homonyms.stories.html
stories/documentation/users/select/user-homonyms.stories.ts

Fix options gap on deprecated user & qualification select
-----
-----

[User Select / Qualification][Deprecated] Fix options gap

---

packages/ng/core-select/input/select-input.component.ts
packages/ng/multi-select/panel/panel.component.ts

fix(select): strange option selection when clue change

---

packages/scss/src/components/navside/component.scss

- Fix children horizontal alignement
- Remove items gap
-----
-----

[Secondary navigation] Minor spacings fixes

---

packages/ng/dialog/dialog/dialog.component.scss
packages/ng/dialog/directives/dialog-open.directive.ts
stories/documentation/overlays/dialog/dialog-basic.stories.ts
stories/documentation/overlays/dialog/dialog.stories.ts

chore(rc): style and template-driven fixes

---

packages/scss/src/components/dialog/component.scss

[Dialog] Fix zindex header

---

packages/scss/src/components/navside/component.scss

- Fix icon size & spacings
-----

[Navside] fix icon size

---

packages/ng/dialog/dialog.service.ts
packages/ng/dialog/dialog/dialog.component.scss
packages/ng/dialog/directives/dialog-open.directive.ts
stories/documentation/overlays/dialog/dialog-basic.stories.ts
stories/documentation/overlays/dialog/dialog.stories.ts

chore: fix style for proper sizing in dialogs

---

packages/scss/src/commons/config.scss

Sorry for the omission!
-----
-----

Add neutral 400 for rgb colors

---

packages/ng/core-select/input/select-input.component.ts

fix select-input placeholder of core-select
-----

fix(core-select/select-input): placeholder

---

packages/scss/src/commons/config.scss
packages/scss/src/commons/utils/color.scss
packages/scss/src/commons/utils/index.scss
packages/scss/src/components/navside/component.scss
packages/scss/src/components/navside/vars.scss
packages/scss/src/components/numericBadge/index.scss
packages/scss/src/components/numericBadge/mods.scss
stories/documentation/navigation/menu-secondary/menu-secondary-basic.stories.ts
stories/qa/main-menu/main-menu.stories.html

Fixes #2604 
-----
-----
Before: 
After:

Navside: replace product by brand for numeric badges

---

packages/ng/option/item/tree-option-item.component.scss

Fix horizontal spacing on option item (not multiple)
-----
-----

[Departement] Fix hozitontal spacing

---

packages/ng/styles/components/_picker.scss

Add horizontal spacing on simple & multiple select empty state
-----

[New selects] Add horizontal padding on empty state

---

stories/documentation/actions/links/link-disabled.stories.ts
stories/documentation/actions/links/link-nowrap.stories.ts

Use `<span>` on link disabled stories
-----

[Documentation] Link disabled stories

---

docs/dialog.md
packages/ng/dialog/dialog.service.ts
packages/ng/dialog/dialog/dialog.component.scss
packages/ng/dialog/directives/dialog-open.directive.ts
stories/documentation/overlays/dialog/dialog-basic.stories.ts
stories/documentation/overlays/dialog/dialog.stories.ts

This PR adds the `docs/dialog.md` file to see how we can integrate markdown files from github to zeroheight for better technical documentation.
The next step for the integration test will be to follow these steps: https://zeroheight.com/help/article/sync-markdown-files-from-github/
-----
-----

docs: markdown integration tentative

---

packages/scss/src/components/util/index.scss

Unit & commas utilities deprecated
-----

[Utilities] Unit & commas deprecated

---

packages/scss/src/components/formLabel/component.scss

Fix component size with ? tooltip icon
-----

[FormField] Fix component size with ? tooltip icon

---

packages/ng/dialog/dialog-header/dialog-header.component.ts

fix(dialog): better id management for header title

---

packages/ng/core-select/user/users.directive.ts

Missing filters input / fields / exportAs on LuCoreSelectUsersDirective.
-----

fix(core-select): missing filters input / fields / exportAs on LuCoreSelectUsersDirective

---

packages/ng/form-field/form-field.component.ts

fix(form-field): ariaInvalid sometimes not applied properly and throwing error

---

packages/scss/src/components/button/index.scss
stories/qa/button/button.stories.html

Fix Succes/Error & Outlined/Text compatibility 
-----
-----

[Button] Succes & Error specificity

---

packages/scss/src/components/formLabel/component.scss

Fix * size
-----
https://github.com/LuccaSA/lucca-front/issues/2656
-----

[Form Label] Fix * size

---

packages/scss/src/components/breadcrumbs/component.scss
packages/scss/src/components/breadcrumbs/index.scss
packages/scss/src/components/callout/component.scss
packages/scss/src/components/callout/mods.scss
packages/scss/src/components/callout/vars.scss
stories/documentation/navigation/breadcrumbs/breadcrumbs-compact.stories.ts

Component callout refacto

---

packages/icons/src/commons/utils/icon.scss
packages/icons/src/icon/component.scss
packages/icons/src/icon/index.scss
packages/icons/src/icon/mods.scss
packages/icons/src/icon/vars.scss
packages/scss/src/components/breadcrumbs/component.scss

Css var for content icon.
-----
-----

Css var for content icon

---

packages/scss/src/components/textField/vars.scss

Fix palettes (`product` was applied instead of `neutral` while resolving conflicts)
-----

[Textfield] Fix palettes

---

packages/scss/src/components/divider/component.scss
packages/scss/src/components/filterBar/component.scss
packages/scss/src/components/filterBar/exports.scss
packages/scss/src/components/filterBar/index.scss
packages/scss/src/components/filterBar/mods.scss
packages/scss/src/components/filterBar/vars.scss
packages/scss/src/components/grid/component.scss
packages/scss/src/components/index.scss
stories/documentation/structure/filter-bar/filter-bar-basic.stories.ts
stories/qa/filterBar/filter-bar.stories.html
stories/qa/filterBar/filter-bar.stories.ts

Add filter bar component
-----
-----

Feat filter bar component

---

packages/scss/src/components/navside/vars.scss

Fix compact alert palette
-----

[Secondary nav] Compact alert palette

---

packages/ng/core-select/establishment/establishments.directive.ts

Use correct query param when filtering on specific operation
-----

fix(establishment): wrong operations query param

---

packages/scss/src/commons/config.scss

The palette for Cloud Control was missing! 😱
-----
https://lucca-hr.zoom.us/rec/share/hSG8brBs9YwjRnO4_Cow0LMWvUpTd5_0tzsSAFZDxkHF6H0vuILOPOypix-QdNa4.WVhjXVY7-2IbyKUm?startTime=1708530789000
-----

Cloud Control palette

---

stories/documentation/listings/table/table-basic.stories.ts
stories/documentation/listings/table/table-parent.stories.ts

Parent & Collasped story
-----
-----

[Table] Parent & Collasped story

---

packages/scss/src/components/chip/component.scss
packages/scss/src/components/chip/mods.scss

Click zone increased from 12x12px to 24x24px.
-----
-----
Bottom line = new behavior.

Expand clickable zone for chips button

---

packages/scss/src/components/_sample/component.scss
packages/scss/src/components/_sample/exports.scss
packages/scss/src/components/_sample/index.scss
packages/scss/src/components/_sample/mods.scss
packages/scss/src/components/_sample/states.scss
packages/scss/src/components/_sample/vars.scss

This component documents the architecture and can be copied and pasted to serve as a template for new components.
-----

Component sample

---

packages/scss/src/components/callout/mods.scss
packages/scss/src/components/callout/vars.scss

[Callout] Fix gap

---

packages/scss/src/components/skeleton/index.scss
packages/scss/src/components/skeleton/mods.scss
packages/scss/src/components/skeleton/states.scss
packages/scss/src/components/skeleton/vars.scss
stories/documentation/loaders/skeleton/skeleton-align.stories.ts

Skeletons : mod alignRight + mod alignCenter

---

packages/scss/src/components/indexTable/component.scss
packages/scss/src/components/indexTable/mods.scss

Fix indexTable padding
-----
-----

Fix.index table

---

packages/ng/styles/components/_picker.scss
packages/scss/src/components/callout/mods.scss
packages/scss/src/components/callout/vars.scss
packages/scss/src/components/filterBar/component.scss
packages/scss/src/components/formLabel/component.scss
packages/scss/src/components/indexTable/component.scss
packages/scss/src/components/indexTable/mods.scss
packages/scss/src/components/indexTable/vars.scss
packages/scss/src/components/tag/component.scss
stories/qa/tags/tags.stories.html

Apply schematics on last 17.4 PR
-----

Apply schematics on last 17.4 PR

---

packages/ng/styles/components/cdk/_textarea.scss

[CDK autoresize] Fix generated height

---

packages/scss/src/components/timeline/index.scss
packages/scss/src/components/timeline/mods.scss
packages/scss/src/components/timeline/states.scss
stories/documentation/listings/timelines/timelines-dashed.stories.ts
stories/qa/timelines/timelines.stories.html

- Allow vertical + checked + number
- Allow vertical + checked + L
- Allow palette usage
- Add dashed story
-----
-----

[Timeline] Misc mod combo fixes & stories

---

packages/ng/core-select/user/users.directive.ts

fix(core-select): do not make id overridable in getMe method
-----

fix(core-select): do not make id overridable in getMe method

---

stories/documentation/texts/numeric-badge/html&css/numeric-badge-basic.stories.ts

Test fix control type Select
-----

[ZH] Test fix control type Select

---

packages/ng/popup-employee/card/panel/user-popover-panel.component.ts

Fix detect changes in user popover

---

packages/scss/src/commons/config.scss
packages/scss/src/components/calloutPopover/mods.scss
packages/scss/src/components/checkboxField/vars.scss
packages/scss/src/components/formLabel/component.scss
packages/scss/src/components/radioField/vars.scss
packages/scss/src/components/switchField/component.scss
stories/qa/tokens/tokens.stories.html

Add token spacing 25 and apply it
-----
-----

[Tokens Spacings] Add 25

---

packages/ng/core/portal/portal.directive.spec.ts
packages/ng/core/portal/portal.directive.ts

Previous implementation was pushing each text instead of replacing with the latest one.
-----

fix(portal): handle string update

---

packages/ng/popup-employee/card/panel/user-popover-panel.component.ts
packages/ng/popup-employee/card/trigger/user-popover-trigger.directive.ts

Fix the initial position when opening user-popover for the first time
-----
-----

fix(user-popover): fix initial position after employee is loaded

---

packages/scss/src/components/calloutFeedbackList/component.scss
packages/scss/src/components/calloutFeedbackList/mods.scss
packages/scss/src/components/calloutFeedbackList/vars.scss

[Callout feedback] Decrease gap

---

packages/scss/src/components/formLabel/component.scss

Mandatory asterisk ui
-----
-----

[Form label] Mandatory asterisk ui

---

stories/documentation/actions/button/angular/button-basic.stories.ts
stories/documentation/actions/button/angular/button-counter.stories.ts
stories/documentation/actions/button/angular/button-icon.stories.ts
stories/documentation/forms/fields/radio/angular/radiofield.stories.ts
stories/documentation/forms/fields/text/angular/textfield.stories.ts
stories/documentation/forms/fields/textarea/angular/textarea.stories.ts
stories/documentation/forms/fields/textarea/html&css/textareafield.stories.ts
stories/documentation/forms/select/multi-select.stories.ts
stories/documentation/forms/select/simple-select.stories.ts

17.4 Format stories

---

packages/ng/core-select/user/users.directive.ts

fix(users.directive): formerEmployee query param & avoid infinite recursion

---

packages/ng/tooltip/trigger/tooltip-trigger.directive.ts

I think this will be safer to avoid any side effects during tests.
-----
-----

Add wrapper with .u-mask

---

.editorconfig
.storybook/msw/handlers.ts
.storybook/msw/helpers.ts
docs/core-select-api-directive.md
docs/core-select-users-directive.md
packages/ng/core-select/user/user-option.component.ts
packages/ng/core-select/user/user-option.model.ts
packages/ng/core-select/user/users.directive.ts
stories/documentation/forms/select/custom-api-example.component.ts
stories/documentation/forms/select/simple-select.stories.ts

Add example and documentation about customizing simple and multi-select directives
-----
-----

docs(core-select): API and Users guides

---

packages/scss/src/commons/config.scss

The colors had been incorrectly changed from 900 to 400 when switching to color-mix. This has now been corrected.
-----
-----

Color fix for elevations and box shadows

---

packages/ng/schematics/new-icons/mapping.ts

Remove chart levels from icons schematics
-----

[Schematics] Remove chart levels from icons schematics

---

packages/ng/forms/text-input/text-input.component.ts
stories/documentation/forms/fields/text/angular/textfield.stories.ts

Title says it all, we most likely overlooked this type when first implementing text input component.
-----
-----

feat(text-input): add url as valid type

---

stories/documentation/forms/fields/text/angular/textfield.stories.ts

Add version to Angular textfield url option
-----

[Documentation] Add version to Angular textfield url option

---

packages/ng/button/button.component.ts

Title says it all ^^
-----
closes #2737 
-----

feat(button): add `delete` input that adds `mod-delete` to button classes

---

docs/core-select-users-directive.md

Add `displayMeOption` documentation.
-----

[Core Select] displayMeOption documentation

---

packages/ng/forms/textarea-input/textarea-input.component.html
packages/ng/forms/textarea-input/textarea-input.component.ts
packages/scss/src/components/textField/component.scss
stories/documentation/forms/fields/textarea/angular/textarea.stories.ts
stories/documentation/forms/fields/textarea/html&css/textareafield.stories.ts

Add support for the `rows` attribute

---

packages/ng/user/picture/user-picture.component.ts

* `<lu-user-picture [displayFormat]="'lf'" [user]="user" />` was working but not `<lu-user-picture [user]="user" [displayFormat]="'lf'" />`
* In `LuUserTileComponent`, the `pictureDisplayFormat` was not working because of the point above
-----
-----

fix(user): do not depend on setter order in LuUserPictureComponent

---

packages/ng/core/type/enum.ts

Add missing `typeof`. Thx @g-drouard!
-----
-----

docs(core): fix EnumValue example

---

packages/ng/user/display/user-display.pipe.spec.ts
packages/ng/user/display/user-display.pipe.ts

Fix https://github.com/LuccaSA/lucca-front/issues/2787
-----

fix(userDisplay): handle user with empty firstName or lastName

---

packages/scss/src/commons/utils/index.scss

Remove invalid properties

---

stories/documentation/forms/fields/text/angular/textfield.stories.ts

Title says it all
closes #2716
-----
-----

docs(textfield): clearer set to `false` by default in story

---

packages/scss/src/commons/utils/media.scss
packages/scss/src/components/comment/component.scss
packages/scss/src/components/comment/exports.scss
packages/scss/src/components/comment/index.scss
packages/scss/src/components/comment/mods.scss
packages/scss/src/components/comment/vars.scss
packages/scss/src/components/form/mods.scss
stories/documentation/texts/comment/basic.stories.ts
stories/documentation/texts/comment/no-avatar.stories.ts
stories/documentation/texts/comment/richText.stories.ts
stories/documentation/texts/comment/small.stories.ts
stories/documentation/texts/comment/wrapper-compact.stories.ts
stories/documentation/texts/comment/wrapper.stories.ts
stories/qa/comment/comment.stories.html

Adjustements for comment component

---

README.md

Replace the quotes in the code blocks of README.md
-----
-----

docs(readme): replace quotes in code blocks

---

packages/ng/forms/text-input/text-input.component.html
packages/ng/forms/text-input/text-input.component.ts
packages/scss/src/components/textField/component.scss
packages/scss/src/components/textField/index.scss
packages/scss/src/components/textField/mods.scss
stories/documentation/forms/fields/text/angular/textfield.stories.ts
stories/documentation/forms/fields/text/html&css/textfield-alignRight.stories.ts
stories/documentation/forms/fields/text/html&css/textfield-valueAlignRight.stories.ts
stories/qa/forms/textfield.stories.html

Remove border for prefix and suffix and add mod-alignRight

---

packages/ng/popup-employee/card/panel/user-popover-panel.component.html
packages/scss/src/components/userPopover/component.scss
stories/documentation/users/popover/angular/popover.stories.ts
stories/documentation/users/popover/html&css/popover.stories.ts

Fix #2783 
⚠️ For the time being, the year remains in long format.
-----
-----

User Popover : adjustments + HTML story

---

packages/scss/src/components/dialog/component.scss
packages/scss/src/components/dialog/mods.scss
packages/scss/src/components/dialog/vars.scss
packages/scss/src/components/loading/component.scss
packages/scss/src/components/loading/index.scss
packages/scss/src/components/loading/mods.scss
packages/scss/src/components/loading/vars.scss
stories/documentation/loaders/loadings/loadings-basic.stories.ts

-----
`[class~='mod-fullPage' i]` means you don't have to worry about character case.
-----

Component loading refacto

---

packages/scss/src/commons/base.scss

Fix firefox default placeholder opacity
-----

[Base] Fix firefox default placeholder opacity

---

packages/scss/src/commons/utils/media.scss
packages/scss/src/components/comment/component.scss
packages/scss/src/components/comment/exports.scss
packages/scss/src/components/comment/index.scss
packages/scss/src/components/comment/mods.scss
packages/scss/src/components/comment/vars.scss
packages/scss/src/components/form/mods.scss
packages/scss/src/components/index.scss
stories/documentation/texts/comment/basic.stories.ts
stories/documentation/texts/comment/no-avatar.stories.ts
stories/documentation/texts/comment/richText.stories.ts
stories/documentation/texts/comment/small.stories.ts
stories/documentation/texts/comment/wrapper-compact.stories.ts
stories/documentation/texts/comment/wrapper.stories.ts
stories/qa/comment/comment.stories.html
stories/qa/comment/comment.stories.ts

Adding new component comment
-----
-----

[comment] New component

---

packages/scss/src/components/textfields/component.scss

Remove useless placeholder opacity
(Is now global https://github.com/LuccaSA/lucca-front/pull/2819)
-----

[Base] Remove useless placeholder opacity

---

packages/scss/src/components/tableSticked/mods.scss
packages/scss/src/components/tableSticked/vars.scss

Reduce sticky table shadow intensity
-----
-----

[Table] Reduce shadow intensity

---

packages/ng/empty-state/empty-state-page/empty-state-page.component.html
packages/ng/empty-state/empty-state-page/empty-state-page.component.ts
packages/ng/empty-state/empty-state-section/empty-state-section.component.html
packages/ng/empty-state/empty-state-section/empty-state-section.component.ts
packages/scss/src/components/emptyState/component.scss
stories/documentation/feedback/empty-state/html&css/empty-state-page.stories.ts
stories/documentation/feedback/empty-state/html&css/empty-state-section-center.stories.ts
stories/documentation/feedback/empty-state/html&css/empty-state-section-palette.stories.ts
stories/documentation/feedback/empty-state/html&css/empty-state-section.stories.ts
stories/documentation/listings/index-table/index-table-empty-state.stories.ts
stories/qa/empty-state/empty-state-page.stories.html
stories/qa/empty-state/empty-state-section.stories.html

Everything is explained in #2744 
-----
closes #2744 and #2622 
-----

refactor(empty-states): make title and description optional

---

packages/scss/src/commons/base.scss
packages/scss/src/commons/config.scss
packages/scss/src/commons/vars.scss

Add an option to test Source Sans 3.
-----
-----
Before: 
After:

Add an option to change font family

---

packages/ng/popup-employee/card/panel/user-popover-panel.component.html
packages/scss/src/components/userPopover/component.scss
stories/documentation/users/popover/html&css/popover.stories.ts

Edit date format (from `longDate` to `shortDate`)
-----

[User popover] longDate > shortDate

---

stories/documentation/forms/fields/switch/html&css/switchfield-invalid.stories.ts
stories/qa/forms/checkbox.stories.html
stories/qa/forms/framed.stories.html
stories/qa/forms/switch.stories.html
stories/qa/forms/textfield.stories.html
stories/qa/grid/grid.stories.html

Fix small typo

---

packages/scss/src/commons/base.scss
packages/scss/src/components/form/component.scss
packages/scss/src/components/form/index.scss
packages/scss/src/components/form/mods.scss
packages/scss/src/components/form/vars.scss
packages/scss/src/components/textfields/component.scss
stories/documentation/forms/examples/angular/form-basic.stories.ts
stories/documentation/forms/examples/html&css/form-basic.stories.ts

Full form example & header classes
-----
-----

[Form] Full form example & header classes

---

packages/scss/src/components/errorPage/component.scss
packages/scss/src/components/errorPage/vars.scss
stories/documentation/feedback/error-page/error-page-basic.stories.ts

Title color, font size & apostrophe
-----
-----

[Error page] Title color, font size & apostrophe

---

packages/scss/src/components/breadcrumbs/component.scss
packages/scss/src/components/breadcrumbs/mods.scss
packages/scss/src/components/breadcrumbs/states.scss

- Replace icon
- Neutral 600 > 700
-----
-----

[Breadcrumb] Icon & color

---

packages/ng/forms/radio-group-input/radio/radio.component.html

Add name attribute on radio input for keyboard navigation with Firefox

---

.storybook/msw/handlers.ts

Replace search by clue story user select
-----
-----

fix(select): replace search by clue story user select

---

packages/ng/package.json

chore: use correct peerDeps

---

packages/ng/core/translate/translation.model.ts
packages/ng/user/select/input/user-select-input.translate.ts
packages/ng/user/select/searcher/user-searcher.translate.ts

Set fr translation required.
Add some german translations.
-----
-----

feat: add german translations

---

packages/ng/toast/toasts.component.html
packages/ng/toast/toasts.component.ts
packages/ng/toast/toasts.model.ts
stories/documentation/overlays/toasts/toasts.stories.html
stories/documentation/overlays/toasts/toasts.stories.ts

Use PortalDirective with LuToastsComponent to allow use of TemplateRef
-----
https://github.com/LuccaSA/lucca-front/assets/2039493/6adbcc3f-ddae-473f-b275-210f9434c6f8

[Toasts] PortalContent as message

---

packages/scss/src/components/callout/component.scss
packages/scss/src/components/callout/mods.scss
stories/qa/callout/callout.stories.html

Cover actions container
-----
-----

[Callout] Cover actions container

---

packages/ng/styles/definitions/option/_option-item.scss

Align checkbox on top
-----
-----

[Select multi] Align checkbox on top

---

packages/ng/toast/toasts.component.html
packages/scss/src/components/button/mods.scss
packages/scss/src/components/index.scss
packages/scss/src/components/toast/component.scss
packages/scss/src/components/toast/index.scss
packages/scss/src/components/toast/mods.scss
packages/scss/src/components/toast/vars.scss

Toast UI refactor – Timer + Inverted button

---

packages/ng/toast/toasts.component.html
packages/scss/src/commons/config.scss
packages/scss/src/components/button/mods.scss
packages/scss/src/components/index.scss
packages/scss/src/components/toast/component.scss
packages/scss/src/components/toast/index.scss
packages/scss/src/components/toast/mods.scss
packages/scss/src/components/toast/vars.scss

Toast UI refactor
-----
ℹ️ Toast timer & removal is historically handled by CSS animation. It works well, but a timer refactor would be way cleaner. 
-----

[Toast] UI refactor

---

packages/ng/multi-select/displayer/default-displayer.component.ts

Fix +N chip S size
-----
-----

[Multiselect] Fix +N chip S size

---

stories/documentation/overlays/tooltip/tooltip.stories.ts

Improved tooltip story format and code example.
-----
-----

docs(tooltip): story refactor

---

stories/documentation/forms/examples/angular/form-basic.stories.ts
stories/documentation/forms/examples/html&css/form-basic.stories.ts
stories/documentation/navigation/breadcrumbs/breadcrumbs-basic.stories.ts
stories/documentation/navigation/breadcrumbs/breadcrumbs-compact.stories.ts
stories/documentation/overlays/popover2/popover2.stories.ts
stories/documentation/overlays/toasts/toasts.stories.html
stories/documentation/overlays/toasts/toasts.stories.ts
stories/documentation/overlays/tooltip/tooltip.stories.ts
stories/documentation/texts/comment/basic.stories.ts
stories/documentation/texts/comment/richText.stories.ts
stories/documentation/texts/comment/small.stories.ts
stories/documentation/texts/comment/wrapper-compact.stories.ts
stories/documentation/texts/comment/wrapper.stories.ts
stories/qa/comment/comment.stories.html

18.1 Doc format (round 2)
-----

18.1 Doc format (round 2)

---

stories/documentation/overlays/popover2/popover2.stories.ts

Keep space for popover positions in ZH
-----

[18.1] Stories format

---

packages/ng/button/button.component.ts
stories/documentation/actions/button/angular/button-basic.stories.ts

Rollback automatic type to prevent to break submit buttons in forms without type.
-----

[Button] Rollback automatic type

---

packages/scss/src/components/callout/component.scss
packages/scss/src/components/callout/mods.scss
packages/scss/src/components/callout/vars.scss

Fix Close icon size & position
-----

[Callout] Close icon size & position

---

packages/scss/src/components/checkboxField/component.scss

Apply root display to avoid position issues
-----

[Checkbox] Root display

---

packages/scss/src/components/pageHeader/vars.scss

Description max width 50 > 33.5rem
-----
-----

[Page header] Description max width 50 > 33.5rem

---

packages/scss/src/components/navside/component.scss
packages/scss/src/components/navside/mods.scss
stories/documentation/navigation/menu-secondary/menu-secondary-basic.stories.ts

New badge position
-----
-----

[Secondary nav] New badge position

---

packages/ng/button/button.component.ts
packages/ng/time/duration-picker/duration-picker.component.scss
packages/ng/time/duration-picker/duration-picker.component.ts
packages/ng/time/time-picker/time-picker.component.scss
packages/ng/time/time-picker/time-picker.component.ts
packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
packages/ng/user/picture/user-picture.component.ts
packages/ng/user/tile/user-tile.component.ts
packages/scss/src/components/callout/component.scss
packages/scss/src/components/callout/mods.scss
packages/scss/src/components/callout/vars.scss
packages/scss/src/components/checkboxField/component.scss
packages/scss/src/components/dialog/component.scss
packages/scss/src/components/footer/component.scss
packages/scss/src/components/footer/mods.scss
packages/scss/src/components/footer/vars.scss
packages/scss/src/components/grid/vars.scss
packages/scss/src/components/navside/component.scss
packages/scss/src/components/navside/mods.scss
packages/scss/src/components/notchBox/vars.scss
packages/scss/src/components/pageHeader/vars.scss
packages/scss/src/components/popover/component.scss
packages/scss/src/components/scrollBox/component.scss
packages/scss/src/components/scrollBox/vars.scss
stories/documentation/actions/button/angular/button-basic.stories.ts
stories/documentation/navigation/menu-secondary/menu-secondary-basic.stories.ts
stories/documentation/overlays/dialog/dialog-basic.stories.ts
stories/qa/dialog/dialog.stories.html
stories/qa/dialog/dialog.stories.ts
stories/qa/footer/footer.stories.html

[18.1.1] Update RC

---

packages/ng/dialog/dialog-footer/dialog-footer.component.ts
packages/ng/dialog/dialog-header/dialog-header.component.ts

I was tired that day... these roles don't exist.
-----
-----

Remove header and footer roles

---

packages/ng/popover2/popover.directive.ts

fix(popover2): add overlayref recycling to avoid multiplying bounding boxes

---

packages/ng/simple-select/input/select-input.component.html
stories/documentation/forms/fields/simple-select/angular/simple-select.stories.ts

Fix #2912 
-----
-----
Before: 
After:

Remove clear if select is disabled

---

packages/scss/src/components/loading/mods.scss

Revert translate for loading position

---

packages/scss/src/components/emptyState/component.scss

Change default icon color

---

packages/ng/core-select/option/default-option.component.ts
packages/scss/src/components/multiSelect/component.scss
packages/scss/src/components/multiSelect/mods.scss

Add ellipsis for multi displayer

---

packages/scss/src/commons/config.scss

[Colors] Add Core HR colors

---

packages/ng/new-badge/new-badge.component.scss
packages/ng/numeric-badge/numeric-badge.component.scss

Fix Angular components host selectors
-----

Fix Angular components host selectors

---

packages/ng/empty-state/empty-state-page/empty-state-page.component.html
packages/ng/empty-state/empty-state-page/empty-state-page.component.ts
packages/ng/empty-state/empty-state-section/empty-state-section.component.html
packages/ng/empty-state/empty-state-section/empty-state-section.component.ts
stories/documentation/feedback/empty-state/angular/empty-state-page.stories.ts
stories/documentation/feedback/empty-state/angular/empty-state-section.stories.ts

Revert heading > title
-----
Postponed to 18.2
-----

[Empty State] Revert heading > title (postponed to 18.2)

---

packages/ng/forms/radio-group-input/radio/radio.component.html

Fix multiple radio group
-----
Regression from https://github.com/LuccaSA/lucca-front/pull/2831
-----

Fix missing name radio input

---

stories/documentation/structure/cards/cards-arrow-action.stories.ts
stories/documentation/structure/cards/cards-basic.stories.ts
stories/documentation/structure/cards/cards-clickable.stories.ts
stories/qa/card/card.stories.html

Improve documentation stories
-----

[Cards] Improve documentation stories

---

packages/icons/src/icon/component.scss
packages/icons/src/icon/index.scss
packages/icons/src/icon/vars.scss

Add CSSvar to font family
-----
Related to Banner to let the possibility to override the icons ont name
-----

[Icons] Add CSSvar to font family

---

packages/scss/src/components/statusBadge/component.scss

Fix vertical alignement in tables
-----
Milestone `18.2` as it requires extra tests
-----

[Status badge] Fix vertical alignement in tables

---

packages/scss/src/commons/core.scss
stories/documentation/integration/utilities/display.stories.ts
stories/documentation/integration/utilities/print.stories.ts

-----
⚠️ Waiting for master rebase on rc.
-----

Add grid display into utilities

---

docs/radio-input.md

Add usage docs for the new radio input wrapper
-----
-----

docs(radio-input): add base usage docs

---

packages/ng/form-field/form-field.component.ts
stories/documentation/forms/fields/checkbox/angular/checkboxfield.stories.ts
stories/documentation/forms/fields/multi-select/angular/multi-select.stories.ts
stories/documentation/forms/fields/number/angular/numberfield.stories.ts
stories/documentation/forms/fields/radio/angular/radiofield.stories.ts
stories/documentation/forms/fields/simple-select/angular/simple-select.stories.ts
stories/documentation/forms/fields/switch/angular/switchfield.stories.ts
stories/documentation/forms/fields/text/angular/textfield.stories.ts
stories/documentation/forms/fields/textarea/angular/textarea.stories.ts
stories/documentation/forms/time/duration-picker-angular.stories.ts
stories/documentation/forms/time/time-picker-angular.stories.ts

Add HiddenLabel description
-----

[Documentation] Add HiddenLabel description

---

stories/documentation/feedback/callout-disclosure/angular/callout-disclosure.stories.ts
stories/documentation/feedback/callout/angular/callout-basic.stories.ts
stories/documentation/forms/fields/checkbox/angular/checkboxfield.stories.ts
stories/documentation/forms/fields/multi-select/angular/multi-select.stories.ts
stories/documentation/forms/fields/number/angular/numberfield.stories.ts
stories/documentation/forms/fields/simple-select/angular/simple-select.stories.ts
stories/documentation/forms/fields/switch/angular/switchfield.stories.ts
stories/documentation/forms/fields/text/angular/textfield.stories.ts
stories/documentation/forms/fields/textarea/angular/textarea.stories.ts
stories/documentation/forms/time/duration-picker-angular.stories.ts
stories/documentation/forms/time/time-picker-angular.stories.ts

Remove default size in code preview
-----

[Stories] Remove default size in code preview

---

packages/ng/popover2/content/popover-content/popover-content.component.html
packages/ng/popover2/content/popover-content/popover-content.component.ts
packages/ng/popover2/popover.directive.ts

Handled popover2 resize after content changed
-----
-----

feat(popover2): handled popover2 resize after content changed

---

packages/scss/src/components/menu/component.scss
stories/qa/menu/menu.stories.html

Fix mod-header with legacy
-----
-----

[Menu] Fix mod-header with legacy

---

packages/scss/src/components/pageHeader/component.scss
packages/scss/src/components/pageHeader/vars.scss

[Page header] Component padding

---

packages/scss/src/components/comment/component.scss
packages/scss/src/components/comment/mods.scss
packages/scss/src/components/comment/vars.scss

- Fix main gap
- Fix name / date size with S size
- Fix spacing between `info` and `content` when avatar is not displayed
-----

[Comment] Fix gap + S size

---

packages/ng/time/time-picker/time-picker.component.ts

Add a default value for max input in TimePickerComponent
closes #3009
-----
Empty
-----

fix: add default valeur for max input #3009

---

packages/ng/popover2/content/popover-content/popover-content.component.ts
packages/ng/popover2/popover.directive.ts

Fix focustrap (not cleared)
-----

[Popover2] Fix focustrap

---

packages/scss/src/components/divider/component.scss
packages/scss/src/components/divider/vars.scss

Fix margins & icon color
-----

[Divider] Fix margins & icon color

---

stories/documentation/feedback/callout/html&css/callout-actions.stories.ts
stories/documentation/feedback/callout/html&css/callout-basic.stories.ts
stories/documentation/feedback/callout/html&css/callout-icons.stories.ts
stories/documentation/feedback/callout/html&css/callout-killable.stories.ts
stories/documentation/feedback/callout/html&css/callout-title.stories.ts

[Callout] Add action story

---

packages/ng/form-field/form-field.component.ts

Reported by @klediouron on Slack.
-----
-----

fix(lu-form-field): aria-labelledby sometimes filling with label id again and again

---

packages/scss/src/components/checkboxField/component.scss
packages/scss/src/components/file/component.scss
packages/scss/src/components/indexTable/component.scss
packages/scss/src/components/indexTable/mods.scss
packages/scss/src/components/tableSortable/component.scss
packages/scss/src/components/tableSortable/index.scss
packages/scss/src/components/tableSortable/mods.scss
stories/documentation/listings/index-table/index-table-basic.stories.ts
stories/documentation/listings/index-table/index-table-sortable.stories.ts
stories/documentation/listings/table/table-sortable.stories.ts

Fix indexTable, checkbox-radio, tableSortable

---

packages/scss/src/components/tableSortable/index.scss
packages/scss/src/components/tableSortable/mods.scss
packages/scss/src/components/tableSortable/states.scss
stories/documentation/listings/index-table/index-table-sortable.stories.ts

[tableSortable] Fix + alignCenter + alignRight

---

packages/scss/src/components/emptyState/component.scss
packages/scss/src/components/emptyState/mods.scss

Fix page mod content padding
-----

[Emptystate] Fix page mod content padding

---

stories/documentation/navigation/viewTabs/viewTabs-basic.stories.ts

[viewTabs] Removing mod-vertical

---

packages/scss/src/components/avatar/mods.scss
stories/documentation/users/avatars/angular/basic.stories.ts
stories/documentation/users/avatars/angular/group.stories.ts
stories/documentation/users/avatars/html&css/basic.stories.ts
stories/documentation/users/avatars/html&css/display.stories.ts
stories/documentation/users/avatars/html&css/group/basic.stories.ts
stories/documentation/users/avatars/html&css/group/clickable.stories.ts
stories/documentation/users/avatars/html&css/group/more.stories.ts
stories/documentation/users/avatars/html&css/sizes.stories.ts

[Avatars] HTML stories + fix

---

stories/documentation/feedback/empty-state/angular/empty-state-page.stories.ts
stories/documentation/feedback/plg-push/angular/plg-push-basic.stories.ts
stories/documentation/forms/fields/number-format/angular/numberFormatfield.stories.ts
stories/documentation/forms/fields/phone-number-input/angular/phone-number-input.stories.ts
stories/documentation/forms/inline-message/angular/inline-message-basic.stories.ts
stories/documentation/forms/time/time-picker-angular.stories.ts
stories/documentation/listings/index-table/index-table-sortable.stories.ts
stories/documentation/listings/table/table-sortable.stories.ts
stories/documentation/navigation/viewTabs/viewTabs-basic.stories.ts
stories/documentation/overlays/popover2/popover2.stories.ts
stories/documentation/overlays/tooltip/tooltip.stories.ts
stories/documentation/structure/divider/divider-basic.stories.ts
stories/documentation/users/avatars/html&css/basic.stories.ts
stories/documentation/users/avatars/html&css/display.stories.ts
stories/documentation/users/avatars/html&css/group/basic.stories.ts
stories/documentation/users/avatars/html&css/group/clickable.stories.ts
stories/documentation/users/avatars/html&css/group/more.stories.ts
stories/documentation/users/avatars/html&css/sizes.stories.ts

Update stories documentation
-----

[18.2] Update stories documentation

---

Jenkinsfile
e2e/NuGet.Config

Use GitHub for NuGet packages
-----

chore(deps): use GitHub for NuGet packages

---

packages/ng/forms/phone-number-input/phone-number-input.component.ts

Catch exceptions thrown while parsing invalid inputs with `libphonenumber-js`
Before
After
-----
-----

fix(phone-number-input): catch libphonenumber-js exceptions

---

packages/ng/forms/phone-number-input/phone-number-input.component.html
packages/ng/forms/phone-number-input/phone-number-input.component.ts

Add name display using `Intl.DisplayNames` inside phone-number-input's select box.
Name of the country can be searched and is displayed in the current locale obtained from `LOCALE_ID`.
-----
-----

feat(phone-number-input): country name display & search

---

stories/documentation/listings/index-table/index-table-mass-selection-and-pagination.stories.ts
stories/documentation/navigation/pagination/pagination-basic.stories.ts

We update ourselves on Figma and what is decided by content design.
-----
-----

[Pagination] content adjustement

---

packages/scss/src/components/multiSelect/component.scss

#3046 
-----
-----
Before:
After:

[MultiSelect] Fix placeholder color for invalid state

---

packages/ng/forms/phone-number-input/phone-number-input.component.html
packages/ng/forms/phone-number-input/phone-number-input.component.ts
packages/ng/forms/phone-number-input/validators.ts
stories/documentation/forms/fields/phone-number-input/angular/phone-number-input.stories.ts

Default country can be set through input "country"
Incomplete number are formatted on blur
-----
-----

feat(phone-number-input): set country and format incomplete

---

packages/ng/dialog/dialog-routing/dialog-routing.models.ts
packages/ng/dialog/dialog-routing/dialog-routing.utils.spec.ts
packages/ng/dialog/dialog-routing/dialog-routing.utils.ts

Sometimes, we can to play with `canActivate` / `data` & co.
-----
-----

feat(dialog): handle all Route config options in dialogRouteFactory

---

packages/ng/department/department-select.spec.ts
packages/ng/department/select/feeder/department-feeder.component.ts
packages/ng/department/service/department-v3.service.ts
packages/ng/department/service/department-v4.service.ts
packages/ng/department/service/index.ts

Remplacement de l'api v3 des départements par son équivalent v4
-----

v4 departments api

---

packages/scss/src/components/gauge/component.scss
stories/documentation/listings/table/table-basic.stories.ts
stories/documentation/loaders/gauge/gauge-basic.stories.ts
stories/documentation/structure/cards/cards-basic.stories.ts
stories/qa/gauge/gauge.stories.html

Fix UI (radius on bar)
-----
-----

[Gauge] Radius on bar

---

packages/scss/src/components/plgPush/component.scss

Fix link color when PLG push style is included
-----

[Link] Fix color when PLG push is included

---

packages/scss/src/components/grid/component.scss
stories/qa/grid/grid.stories.html
stories/qa/grid/grid.stories.ts

[grid] Fix QA + max-width

---

packages/ng/forms/phone-number-input/phone-number-input.component.html
packages/ng/forms/phone-number-input/phone-number-input.component.scss
packages/ng/styles/definitions/option/_option-item.scss

Fix multi select group search UI broken by Phone number.
-----
-----

[Select multi] Group search UI

---

packages/scss/src/components/formLabel/component.scss
packages/scss/src/components/formLabel/mods.scss
packages/scss/src/components/formLabel/vars.scss

Fix for long formLabel

---

build.js
packages/ng/schematics/action-icon/index.ts
packages/ng/schematics/empty-state-title/index.ts
packages/ng/schematics/lib/local-deps/installer.ts
packages/ng/schematics/new-icons/index.ts
packages/ng/schematics/palettes/index.ts
packages/ng/schematics/tokens-spacing/index.ts

Fix the "famous" `Cannot find module 'postcss-scss'` when running LF's schematics.
Fix #3073 
-----
-----

fix(schematics): local deps package.json was excluded by Angular

---

packages/scss/src/components/file/states.scss
stories/documentation/forms/files/files-basic.stories.ts
stories/documentation/forms/files/files-droppable.stories.ts
stories/documentation/forms/files/files-error.stories.ts
stories/documentation/forms/files/files-success.stories.ts
stories/documentation/forms/files/files-uploading.stories.ts

Fix states contrasts
-----
-----

[File upload] Fix states contrasts

---

packages/scss/src/components/loading/component.scss
packages/scss/src/components/loading/mods.scss
packages/scss/src/components/loading/vars.scss
stories/documentation/loaders/loadings/loadings-basic.stories.ts
stories/qa/loadings/loadings.stories.html

This PR primarily corrects centering via a margin for flex contexts. #3086 
-----
-----

[loading] fix margins

---

packages/ng/multi-select/displayer/default-displayer.component.scss
packages/scss/src/components/multiSelect/component.scss
packages/scss/src/components/multiSelect/index.scss
packages/scss/src/components/multiSelect/states.scss
packages/scss/src/components/textField/component.scss
packages/scss/src/components/textField/states.scss

Fix:
- Multiselect & Textfield hover color  #3059
- Multiselect small width overflow : [Slack](https://lucca.slack.com/archives/GSCU69USV/p1726132506030369)
- Multiselect arrow rotation #3070 
-----

[Multiselect / Textfield] UI fixes

---

packages/ng/package.json

ajoute date-fns dans les peer deps
-----

fix: add date-fns on peer deps

---

packages/scss/src/components/tableSortable/component.scss

Possibility of multi-line sorting buttons.
-----
-----

[sortable] multilines

---

packages/ng/multi-select/panel/panel.component.html
packages/ng/simple-select/panel/panel.component.html
packages/scss/src/components/loading/component.scss
packages/scss/src/components/loading/mods.scss
packages/scss/src/components/loading/vars.scss

Remove default 100% width to avoid brekings
-----

[Loading] Remove default 100% width

---

stories/documentation/forms/fields/text/html&css/textfield-info.stories.ts

[Doc] Fix QA textfield DOM

---

stories/qa/forms/files.stories.html

[File upload] Update QA story

---

docs/popover2.md

[popover2] documentation for luPopoverTrigger

---

stories/documentation/forms/fieldset/fieldset-basic.stories.ts

[Fieldset] Add S control

---

packages/ng/forms/text-input/text-input.component.html
stories/documentation/forms/fields/number/angular/numberfield.stories.ts
stories/documentation/forms/fields/text/angular/textfield.stories.ts

Format Angular stories + fix password button size
---------

[Textfield] Format Angular stories + fix password button size

---

packages/scss/src/components/timeline/component.scss
packages/scss/src/components/timeline/mods.scss
packages/scss/src/components/timeline/vars.scss

Fix title size in S 
---------

[Timeline] Fix title size in S 

---

packages/scss/src/components/dialog/component.scss
stories/documentation/overlays/dialog/dialog-basic.stories.ts
stories/documentation/overlays/dialog/dialog-drawer.stories.ts
stories/documentation/overlays/dialog/dialog-drawerFromBottom.stories.ts
stories/qa/dialog/dialog.stories.html

Fixes #2977 
-----
-----
Before:
After:

[dialog] Internal scroll

---

packages/scss/src/components/indexTable/component.scss
stories/documentation/listings/index-table/index-table-basic.stories.ts

[indexTable] button option

---

packages/ng/forms/number-format-input/number-format-input.component.ts

Issue :
```html
<lu-number-format-input
required
placeholder="Placeholder"
formatStyle="currency"
[useAutoPrefixSuffix]="true"
[currency]="costsForm.controls.currency.value?.id"
currencyDisplay="name"
[formControl]="testFC"
>
</lu-number-format-input>
```
```
admin-training.store.ts:460 ERROR TypeError: Cannot read properties of null (reading 'pipe')
at new _NumberFormatInputComponent (lucca-front-ng-forms.mjs:618:68)
at NodeInjectorFactory.NumberFormatInputComponent_Factory [as factory] (lucca-front-ng-forms.mjs:668:14)
at getNodeInjectable (core.mjs:5872:38)
at instantiateAllDirectives (core.mjs:12400:23)
at createDirectivesInstances (core.mjs:11822:3)
at ɵɵelementStart (core.mjs:23526:5)
at ɵɵelement (core.mjs:23583:3)
at CostsFormComponent2_Template (template.html:53:9)
at …
```

fix(number-format-input): formControl incompatibility

---

packages/scss/src/components/pageHeader/vars.scss

[pageHeader] max-width: 50rem

---

packages/ng/tooltip/trigger/tooltip-trigger.directive.ts

Add export to luTooltip directive
-----
-----

feat(lu-tooltip): export as luTooltip

---

packages/ng/time/duration-picker/duration-picker.component.ts
packages/ng/time/public-api.ts

I added the export of the new `DurationPicker` component to `time/public-api.ts`, for other projects to import it properly.
-----

fix(duration-picker): Add DurationPicker component to public API

---

packages/ng/dialog/dialog.service.ts
packages/ng/dialog/model/dialog-config.ts
packages/scss/src/components/dialog/component.scss
packages/scss/src/components/dialog/index.scss
packages/scss/src/components/dialog/mods.scss
packages/scss/src/components/dialog/vars.scss
stories/documentation/overlays/dialog/dialog-basic.stories.ts
stories/documentation/overlays/dialog/dialog.stories.ts

[Dialog] Neutral background mod

---

packages/scss/src/components/avatar/component.scss
packages/scss/src/components/userTile/component.scss
stories/documentation/users/tile/angular/user-tile.stories.ts
stories/qa/user-tile/user-tile.stories.html
stories/qa/user-tile/user-tile.stories.scss

[User tile] Vertical alignement

---

packages/ng/skeleton/skeleton-button/skeleton-button.component.html
packages/ng/skeleton/skeleton-field/skeleton-field.component.html
packages/ng/skeleton/skeleton-header/skeleton-header.component.html
packages/scss/src/commons/core.scss
packages/scss/src/commons/vars.scss
packages/scss/src/components/container/component.scss
packages/scss/src/components/container/mods.scss
packages/scss/src/components/container/vars.scss
packages/scss/src/components/emptyState/component.scss
packages/scss/src/components/emptyState/mods.scss
packages/scss/src/components/emptyState/vars.scss
packages/scss/src/components/footer/component.scss
packages/scss/src/components/footer/index.scss
packages/scss/src/components/indexTable/component.scss
packages/scss/src/components/indexTable/index.scss
packages/scss/src/components/menu/component.scss
packages/scss/src/components/navside/mods.scss
packages/scss/src/components/navside/vars.scss
stories/documentation/listings/index-table/index-table-empty-state.stories.ts
stories/documentation/listings/table/table-empty.stories.ts
stories/documentation/navigation/menu/menu-container.stories.ts
stories/documentation/structure/containers/containers-basic.stories.ts
stories/documentation/structure/footer/footer-basic.stories.ts
stories/qa/footer/footer.stories.html

Container variables are set to global, which simplifies components that used the container.
This PR also includes the PR #3125 and fixes #3096.
-----
-----

[container] vars move to common

---

packages/ng/date2/date-input/date-input.component.html
packages/scss/src/components/calendar/component.scss

[date-input/calendar] aria + fix CSS

---

packages/ng/tag/tag.component.ts

[Tag] Fix size options

---

packages/ng/user/display/user-display.pipe.ts

Fix `Cannot read properties of undefined (reading 'length')` from datadog report.
-----
-----

fix(user-display): handle `null` string in isNotEmptyString

---

packages/ng/option/selector/all/select-all.component.ts
packages/ng/option/selector/all/tree-select-all.component.ts
packages/ng/user/display/user-display.pipe.ts

Two edge cases that sometime occur.
-----
-----

fix(user-display): handle `null` string in isNotEmptyString (#3136)

---

.github/c-3po.yml

chore: mandatory milestones

---

docs/dialog.md
packages/ng/dialog/dialog/dialog.component.scss
packages/scss/src/components/dialog/component.scss
stories/documentation/overlays/dialog/dialog-routing.stories.ts
stories/documentation/overlays/dialog/dialog.stories.ts

[dialog] fix grid

---

packages/ng/core/portal/portal.directive.ts
packages/ng/multi-select/panel/panel.component.html
packages/ng/simple-select/panel/panel.component.html

fix(portal): handle nullish values

---

stories/documentation/forms/date2/basic-html.stories.ts

HTML story for calendar.
-----
-----

[calendar] HTML story

---

stories/documentation/forms/date2/basic.stories.ts
stories/documentation/forms/date2/basicDecade.stories.ts
stories/documentation/forms/date2/basicYear.stories.ts
stories/documentation/forms/date2/date-input.stories.ts
stories/documentation/forms/date2/optionOverflowDisabled.stories.ts
stories/documentation/forms/date2/optionOverflowHidden.stories.ts
stories/documentation/forms/date2/optionTodayHidden.stories.ts
stories/documentation/forms/date2/optionWeekendHidden.stories.ts
stories/documentation/forms/date2/selectDay.stories.ts
stories/documentation/forms/date2/selectRange.stories.ts
stories/documentation/forms/select/multi-select.stories.ts
stories/documentation/texts/comment/angular.stories.ts
stories/documentation/texts/comment/chat.stories.ts

[18.3] Stories format

---

stories/documentation/texts/comment/angular/basic.stories.ts
stories/documentation/texts/comment/angular/chat.stories.ts

[18.3] Format comments stories
-----

[18.3] Format comments stories

---

packages/scss/src/components/form/component.scss

[divider] fix margin in forms

---

packages/ng/date2/date-input/date-input.component.html
packages/ng/date2/date-input/date-input.component.ts
stories/documentation/forms/date2/date-input.stories.ts
stories/documentation/listings/table/table-empty.stories.ts

Overflow input flags were forced to true for some testing and the change was somehow commited, this PR reverts them.
-----
-----

fix(date-input): overflow input flags

---

packages/ng/comment/comment/comment.component.html
packages/scss/src/components/comment/component.scss
stories/documentation/texts/comment/html&css/richText.stories.ts
stories/qa/comment/comment.stories.html

`comment-content-textContainerOptionnal` --> `comment-content-textContainerOptional`
-----

[Comment] Class typo

---

stories/documentation/forms/fields/date/date-input-field.stories.ts
stories/helpers/stories.ts

Add a story that showcases `lu-date-input` inside a `lu-form-field`
-----
-----

docs(date-input): new Documentation/Forms/Fields/DateInput/Angular story

---

packages/ng/multi-select/input/select-all/with-select-all.directive.ts
packages/ng/multi-select/input/select-input.component.spec.ts
packages/ng/multi-select/public-api.ts
packages/ng/multi-select/select.utils.ts
stories/qa/multi-select/multi-select-select-all.stories.ts

fix(multi-select): initial values were not taken into account
fix(multi-select): missing export of utils and models
feat(multi-select): add selectionToOptions util
-----
-----

fix(multi-select): initial values were not taken into account

---

packages/ng/department/select/feeder/department-feeder.component.ts
packages/ng/department/select/input/department-select-input.component.ts
packages/ng/department/service/department-v4.service.ts

Fix on department select : set filters with [] instead of undefined if no input 
-----

Fix(department select): set filters with [] instead of undefined if no input 

---

.storybook/msw/handlers.ts
packages/ng/multi-select/input/select-all/with-select-all.directive.ts
packages/ng/multi-select/input/select-input.component.spec.ts
packages/ng/multi-select/select.model.spec.ts
packages/ng/multi-select/select.model.ts
stories/documentation/forms/select/multi-select.stories.ts

* wrong selectAll/unselectAll text when not using withSelectAll
* select was emitting a value when parent calls `writeValue`
* various stories fixes 
-----
-----

fix(multi-select): multiple fixes

---

packages/scss/src/commons/core.scss

Apply token to border radius utilities
-----
-----

[Utilities] Apply token to border radius utilities

---

packages/scss/src/components/form/index.scss

Replace default label & inline message color by disabled (neutral 500)
-----
-----

[Switch] Disabled color

---

packages/scss/src/components/form/index.scss
packages/scss/src/components/form/states.scss

Fix legend invalid color
-----
-----

[Fieldset] Fix legend invalid color

---

packages/ng/tooltip/trigger/ellipsis.ruler.ts
packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
stories/qa/tooltip/tooltip.stories.ts

For 1 000 tooltips, this PR bring these numbers:
| Name        | Scripting | Rendering | Painting | Total |
| ----------- | --------- | --------- | -------- | ----- |
| Base        | 762       | 1103      | 19       | 1884  |
| SharedRuler | 473       | 727       | 17       | 1217  |
-----
-----

ref(tooltip): share clonedElement between luTooltip instance

---

docs/core-select-users-directive.md
packages/ng/core-select/user/user-option.component.ts
packages/ng/core-select/user/users.directive.ts

* fix(core-select): apps could not extend LuCoreSelectUsersDirective anymore
* fix(core-select): displayMeOption was not working anymore
-----
-----

fix(core-select): LuCoreSelectUsersDirective extension /  displayMeOption

---

packages/scss/src/components/indexTable/index.scss
stories/documentation/listings/index-table/index-table-footer.stories.ts
stories/documentation/listings/index-table/index-table-nested-sub-totals.stories.ts
stories/documentation/toolbox/numbers/numbers.stories.html
stories/documentation/toolbox/numbers/numbers.stories.ts

Replace utilities by component's mod.
-----

[Tables] Replace utility by component mod

---

packages/ng/core-select/user/users.directive.ts

Ease custom LuCoreSelectUsersDirective directives
-----
-----

fix(core-select): provide LuCoreSelectUsersDirective too

---

packages/scss/src/commons/base.scss
packages/scss/src/commons/utils/index.scss
packages/scss/src/commons/utils/reset.scss
stories/documentation/integration/utilities/reset.stories.ts

[details/summary] reset mixin + util

---

packages/ng/tooltip/trigger/ellipsis.ruler.ts
packages/ng/tooltip/trigger/tooltip-trigger.directive.ts

Each time a width is read after a class has been added or the dom has been updated, the browser recompute all layers (reflow). Before this PR, this occured **twice per tooltip**.
Now, this append twice, whatever number of tooltip is appended at the same time.
Before:
After:
-----
-----

fix(tooltip): too many reflows

---

packages/scss/src/components/form/index.scss
stories/qa/box/box.stories.html

- Allow arrows on form field
- Allow to use a block layout
- Fix arrows with checkbox / switch story
-----

[Box] Allow arrows on form field

---

packages/scss/src/components/table/mods.scss
stories/qa/table/table.stories.html

Fix card + actions padding
-----
-----

[Table] Card + actions padding

---

packages/scss/src/components/indexTable/component.scss
packages/scss/src/components/indexTable/mods.scss

Fix css triggered by pagga's linter
-----

[Index table] Fix css triggered by lint

---

packages/ng/styles/components/_popup.scss
packages/ng/styles/components/_sidepanel.scss
stories/documentation/navigation/sidepanel/sidepanel.stories.ts
stories/documentation/overlays/modal/modal.stories.ts
stories/documentation/overlays/sidepanel/sidepanel.stories.ts

Fix content height in legacy sidepanels
-----

[Sidepanel] Fix content height in legacy sidepanels

---

packages/scss/src/components/emptyState/component.scss
stories/documentation/feedback/empty-state/angular/empty-state-page.stories.ts
stories/documentation/feedback/empty-state/angular/empty-state-section.stories.ts

Fix actions padding & alignment
-----
-----

[Empty state] Actions padding & alignment

---

packages/scss/src/components/navside/component.scss

Fix loading colors (which were invisible) and replace it by palette navigation 700
-----

[Navside] Fix loading colors

---

packages/scss/src/commons/base.scss
stories/qa/menu/menu.stories.html

Apply focus style by default on buttons
-----

Apply focus style by default on buttons

---

packages/scss/src/commons/base.scss

Reset default focus style on buttons
-----

[Focus] Reset default focus style on buttons

---

packages/ng/core-select/panel/panel.utils.ts
packages/ng/multi-select/panel/panel.component.ts
packages/ng/simple-select/panel/panel.component.ts
stories/documentation/forms/fields/simple-select/angular/simple-select.stories.ts

fix(panel): fix searchable when using luOptionGroup on lu-simple-select or lu-multi-select

---

stories/documentation/_sample/angular/basic.stories.ts
stories/documentation/_sample/html&css/basic.stories.ts
stories/qa/_sample/sample.stories.html
stories/qa/_sample/sample.stories.ts

Add stories to copy and paste.
-----
-----

[sample] stories

---

packages/ng/numeric-badge/numeric-badge.component.ts
packages/scss/src/commons/config.scss
packages/scss/src/commons/utils/loading.scss
packages/scss/src/components/numericBadge/component.scss
packages/scss/src/components/numericBadge/index.scss
packages/scss/src/components/numericBadge/mods.scss
packages/scss/src/components/numericBadge/states.scss
packages/scss/src/components/numericBadge/vars.scss
stories/documentation/texts/numeric-badge/angular/numeric-badge.stories.ts
stories/documentation/texts/numeric-badge/html&css/numeric-badge-basic.stories.ts
stories/qa/numeric-badge/numeric-badge.stories.html

[numericBadge] loading

---

packages/ng/styles/components/_dropdown.scss
stories/documentation/overlays/dropdown/dropdown-basic.stories.html

[dropdown] divider

---

packages/scss/src/commons/base.scss
packages/scss/src/commons/config.scss

[fontFace] use mixin for Source Sans 3

---

packages/ng/forms/number-input/number-input.component.html
packages/ng/forms/number-input/number-input.component.ts
stories/documentation/forms/fields/number/angular/numberfield.stories.ts

I can't reproduce the bug properly so it's hard to say if the fix is really working :/
#3235
-----
-----

fix(number-input): fix tentative for min & max validators

---

packages/ng/toast/toasts.component.html
packages/scss/src/components/toast/component.scss

[Toast] Content as paragraph

---

packages/scss/src/components/textField/states.scss

Wrong token for placeholder / error
-----

[Textfield] Wrong token for placeholder / error

---

packages/scss/src/components/fieldset/component.scss
packages/scss/src/components/fieldset/index.scss
packages/scss/src/components/fieldset/states.scss
packages/scss/src/components/fieldset/vars.scss
stories/documentation/forms/fieldset/fieldset-basic.stories.ts
stories/qa/fieldset/fieldset.stories.html

The icon gets an animation in the process.
-----
-----
Before:
After:

[fieldset] expandable - change icon

---

packages/scss/src/commons/utils/reset.scss
packages/scss/src/components/divider/component.scss
packages/scss/src/components/divider/vars.scss

[divider] css var [utils] reset list

---

packages/ng/core-select/input/select-input.component.ts

fix(ng): fix the fixing fix

---

packages/scss/src/components/navside/mods.scss

Add support for ESR
-----
Duplicated from: https://github.com/LuccaSA/lucca-front/pull/3291
-----

[18.3][navside] Add support for ESR

---

packages/ng/skeleton/skeleton-data-table/skeleton-data-table.component.ts
packages/ng/skeleton/skeleton-index-table/skeleton-index-table.component.ts
packages/ng/skeleton/skeleton-table/skeleton-table.component.ts
stories/documentation/actions/links/angular.stories.ts
stories/documentation/actions/links/link-basic.stories.ts
stories/documentation/actions/links/link-disabled.stories.ts
stories/documentation/actions/links/link-hover.stories.ts
stories/documentation/actions/links/link-nowrap.stories.ts
stories/documentation/integration/utilities/reset.stories.ts
stories/documentation/loaders/skeleton-data-table/angular/skeleton-data-table.stories.ts
stories/documentation/loaders/skeleton-index-table/angular/skeleton-index-table.stories.ts
stories/documentation/loaders/skeleton-table/angular/skeleton-table.stories.ts
stories/documentation/structure/divider/angular/divider-basic.stories.ts
stories/documentation/structure/divider/html&css/divider-basic.stories.ts
stories/documentation/structure/fancy-box/angular/fancy-box-basic.stories.ts
stories/documentation/structure/fancy-box/html&css/fancy-box-basic.stories.ts
stories/documentation/texts/numeric-badge/angular/numeric-badge.stories.ts
stories/documentation/texts/numeric-badge/html&css/numeric-badge-basic.stories.ts
stories/documentation/texts/numeric-badge/html&css/numeric-badge-loading.stories.ts
stories/documentation/texts/numeric-badge/html&css/numeric-badge-palette.stories.ts
stories/documentation/texts/numeric-badge/html&css/numeric-badge-size.stories.ts
stories/documentation/texts/status-badge/html&css/status-badge-basic.stories.ts
stories/documentation/texts/status-badge/html&css/status-badge-palettes.stories.ts
stories/documentation/texts/status-badge/html&css/status-badge-size.stories.ts

[19.1] Format stories

---

packages/scss/src/commons/config.scss
packages/scss/src/commons/vars.scss

You can load the font with : 
```scss
@use '@lucca-front/scss/src/commons/config' with (
$fontFamilyCursive: 'Caveat',
);
```
-----
-----

[caveat] disabled by default

---

stories/documentation/forms/date2/date-input.stories.ts

[Date] Clean story's controls

---

docs/core-select-api-directive.md
docs/core-select-users-directive.md
docs/date-input.md
docs/multi-select-all.md
docs/popover2.md
docs/radio-input.md
docs/user-popover.md

Format markdown files for ZH integration
-----

Format markdown files for ZH integration

---

packages/ng/forms/multilanguage-input/multilanguage-input.component.html

[multilanguage] fix gap 

---

packages/ng/tooltip/trigger/ellipsis.ruler.ts
packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
stories/documentation/overlays/tooltip/tooltip-ellipsis.stories.ts
stories/qa/tooltip/tooltip.stories.ts

By running outside ZoneJS and by synchronizing read/Write phase, it fix freeze issues;
-----
-----

perf: tooltips freeze issue

---

packages/icons/src/commons/config.scss
packages/icons/update-icons.js
packages/scss/src/commons/core.scss

Update icons & font urls
-----

Update icons & font urls

---

packages/scss/src/components/menu/component.scss

While working on https://github.com/LuccaSA/lucca-front/pull/2745, I stumbled across this stray variable.
-----

Replace stray t-shirt-sized spacing.

---

stories/documentation/texts/status-badge/angular/status-badge-angular.stories.ts
stories/documentation/texts/status-badge/html&css/status-badge-palettes.stories.ts

[statusBadge] add neutral option

---

packages/ng/multi-select/input/select-all/multi-select-all-displayer.component.ts

Fix badge size on Multi select with S size
-----

[Multiselect] Establishment S numeric badge size

---

stories/documentation/feedback/callout/angular/callout-basic.stories.ts

Add required / optional info on Description / Heading
-----

[Callout] Required / optional doc

---

packages/scss/src/components/segmentedControl/component.scss
packages/scss/src/components/timepicker/component.scss

Fixes for https://github.com/LuccaSA/lucca-front/issues/3350
-----

fix(front) : 3350 : replace use of deprecated colors

---

packages/ng/time/time-picker/time-picker.component.html
packages/ng/time/time-picker/time-picker.component.ts
packages/scss/src/components/timepicker/component.scss

The generated ID did not allow multiple components to be used on the same page... fixed.
-----
-----

[timePicker] fix id

---

packages/ng/time/core/time-picker-part.component.html
packages/ng/time/time-picker/time-picker.component.html
stories/documentation/forms/time/time-picker-angular.stories.ts

[timePicker] fix name

---

packages/ng/date2/public-api.ts
stories/documentation/forms/date2/selectDay.stories.ts
stories/documentation/forms/date2/selectInProgress.stories.ts
stories/documentation/forms/date2/selectRange.stories.ts
stories/documentation/forms/fields/form-field-nested-controls.stories.ts
stories/documentation/forms/select/multi-select.stories.ts
stories/documentation/forms/select/simple-select.stories.ts
stories/documentation/forms/time/duration-picker-angular.stories.ts
stories/documentation/structure/box/box-arrow-ng.stories.ts
stories/documentation/texts/comment/angular/chat.stories.ts
stories/documentation/texts/tags/angular/tag.stories.ts
stories/documentation/users/popover/angular/popover.stories.ts
stories/qa/filterBar/filter-bar.stories.ts

docs: fix import path in multiple stories

---

packages/ng/core-select/establishment/establishments.directive.ts
packages/ng/core-select/user/users.directive.ts

Add unique operation ids input for establishments and users select directives.
-----

feat(core-select): add unique operations input for establishments and users directive

---

package.json
packages/ng/chip/chip.component.html
packages/ng/chip/chip.component.scss
packages/ng/chip/chip.component.ts
packages/ng/chip/chip.translate.ts
packages/ng/chip/ng-package.json
packages/ng/chip/public-api.ts
packages/ng/chip/translations.ts
packages/ng/link/link.component.ts
packages/ng/link/link.translate.ts
stories/documentation/listings/chip/angular/basic.stories.ts
stories/documentation/listings/chip/html&css/basic.stories.ts

[chip] angular wrapper

---

README.md

Readme translation

---

stories/qa/button/button.stories.ts
stories/qa/loadings/loadings.stories.ts
stories/qa/numeric-badge/numeric-badge.stories.ts
stories/qa/progress/progress.stories.ts

[QA] disable animations

---

packages/ng/department/service/department-v4.service.ts

Remplacement de l'api v3 des départements `/scopedtree` par son équivalent v4
-----

v4 departments : scopedtree

---

packages/ng/numeric-badge/numeric-badge.component.html
packages/ng/numeric-badge/numeric-badge.component.ts
packages/scss/src/components/numericBadge/component.scss
packages/scss/src/components/numericBadge/index.scss
packages/scss/src/components/numericBadge/states.scss
stories/documentation/texts/numeric-badge/angular/numeric-badge.stories.ts

[numericBadge] maxValue

---

stories/documentation/navigation/breadcrumbs/breadcrumbs-compact.stories.ts
stories/documentation/structure/page-header/page-header-back.stories.ts

Remove breadcrumb semantic for compact mode

---

packages/scss/src/components/emptyState/component.scss

[emptyState] no action

---

packages/ng/styles/components/cdk/_global.scss
packages/scss/src/commons/utils/overflow.scss
packages/scss/src/components/layout/states.scss
packages/scss/src/components/navside/states.scss

A utility to block scrolling, and its overload for Angular, which does things differently.
-----
-----

[utils] overflow block

---

.storybook/styles.scss
stories/qa/_sample/sample.stories.html
stories/qa/avatar/avatar.stories.html
stories/qa/box/box.stories.html
stories/qa/breadcrumb/breadcrumb.stories.html
stories/qa/callout/callout.stories.html
stories/qa/card/card.stories.html
stories/qa/chip/chip.stories.html

Compact QA stories to improve UI diff (first batch)
-----
-----

[QA] Compact stories - first batch

---

packages/scss/src/commons/config.scss
packages/scss/src/components/form/index.scss
packages/scss/src/components/form/mods.scss

[formFields] width mixin

---

packages/ng/core-select/api/api.directive.spec.ts
packages/ng/core-select/input/select-input.component.ts
packages/ng/multi-select/input/select-input.component.spec.ts
packages/scss/src/components/multiSelect/component.scss
packages/scss/src/components/multiSelect/index.scss
packages/scss/src/components/multiSelect/states.scss

-----
-----
025-01-28 16.14.40.gif…]()

[multiSelect] remove placeholder when input is not used

---

packages/scss/src/components/filterPill/index.scss

[filterPills] fix focus visible for checkboxes

---

packages/scss/src/components/pageHeader/component.scss

[Page header] Actions gap

---

stories/documentation/overlays/dropdown/dropdown-basic.stories.ts

[Dropdown] Storybook DOM typo

---

stories/documentation/forms/fields/phone-number-input/angular/phone-number-input.stories.ts
stories/documentation/forms/fields/text/angular/textfield.stories.ts
stories/documentation/forms/filterPills/angular/filter-bar.stories.ts
stories/documentation/texts/numeric-badge/angular/numeric-badge.stories.ts
stories/documentation/texts/status-badge/angular/status-badge-angular.stories.ts
stories/documentation/texts/text-flow/html&css/basic.stories.ts

[19.2] Format stories

---

stories/documentation/forms/fields/text/html&css/textfield-width.stories.ts
stories/documentation/forms/filterPills/angular/filter-bar.stories.ts
stories/documentation/forms/filterPills/angular/filter-pills.stories.ts
stories/documentation/listings/chip/angular/basic.stories.ts

[19.2] Format doc 2

---

packages/ng/styles/components/_popup.scss

[19.2] Fix modal title padding

---

packages/ng/empty-state/empty-state-section/empty-state-section.component.scss

Fix width width on Angular component
-----
https://github.com/LuccaSA/lucca-front/issues/2815
-----

[Empty states section] Fix width width on Angular component

---

packages/scss/src/components/textFlow/component.scss

Fix some margins

---

packages/ng/popup-employee/card/trigger/user-popover-trigger.directive.ts
stories/documentation/users/avatars/angular/basic.stories.ts
stories/documentation/users/display/with-popover.stories.ts
stories/documentation/users/tile/angular/user-tile.stories.ts

docs: add new display name user popover story and improve existing user-related stories with popover

---

packages/ng/styles/definitions/select/_select-input.scss

Fix multiple chip overflow
-----
-----

[Select] Fix multiple chip overflow

---

packages/ng/multi-select/input/select-input.component.html
packages/ng/simple-select/input/select-input.component.html
packages/scss/src/components/multiSelect/component.scss
packages/scss/src/components/multiSelect/index.scss
packages/scss/src/components/multiSelect/states.scss
packages/scss/src/components/simpleSelect/component.scss
packages/scss/src/components/simpleSelect/index.scss
packages/scss/src/components/simpleSelect/states.scss

-----
Display search icon when component has search
-----
https://github.com/user-attachments/assets/23218884-7992-4a75-8286-13f78cf2c578
https://github.com/user-attachments/assets/3eda79a9-7399-46d1-b46b-aaf25637b0b8
-----

[Simple & Multi select] Display search icon when component has search

---

packages/ng/modal/dialog-adapter/dialog-content-adapter/dialog-content-adapter.component.html
packages/ng/multi-select/input/select-all/multi-select-all-displayer.component.ts
packages/ng/numeric-badge/numeric-badge.component.html
packages/ng/numeric-badge/numeric-badge.component.ts
stories/documentation/actions/button/angular/button-counter.stories.ts
stories/documentation/texts/numeric-badge/angular/numeric-badge.stories.ts

[numericBadge] disable tooltip option

---

packages/scss/src/components/numericBadge/mods.scss

[Numeric badge] Fix inherited color

---

stories/documentation/navigation/menu/menu-scrollbox.stories.ts

[scrollBox] fix menu

---

packages/scss/src/components/dataTableSticked/mods.scss

Fix combination of sticky columns / row & sort
-----
Before: 
https://github.com/user-attachments/assets/2c78da25-5fd7-4043-8139-8f09c1684279
After: 
https://github.com/user-attachments/assets/49f8ccfd-340b-4fd7-bb1e-09ab7b71c80c
@vvalentin-lucca Let's discuss the implementation, there might be a better approach. 
-----

fix sticky with sort

---

packages/ng/form-field/form-field.component.ts

Fix invalid status when invalid input is provided
-----
Wrong boolean returned
-----

fix(form-filed): invalid status when invalid input is provided

---

packages/ng/api/select/input/api-select-input.component.html
packages/ng/formly/types/select.html
packages/ng/styles/definitions/select/_select-input.scss

Fix line break when chip has button
-----
-----

[Select (deprecated)] Fix line break

---

packages/ng/user/tile/user-tile.component.html

Fix height calculation when role is empty
-----

[User Tile] Fix height calculation when role is empty

---

packages/scss/src/components/table/component.scss

[table] Fix text align inheritance

---

packages/ng/core-select/input/select-input.component.ts
packages/ng/forms/phone-number-input/phone-number-input.component.html
packages/scss/src/components/multiSelect/index.scss
packages/scss/src/components/simpleSelect/index.scss

Prevent search icon
-----
-----

[Phone number] Prevent search icon

---

packages/ng/forms/phone-number-input/phone-number-input.component.scss
packages/ng/multi-select/input/select-input.component.html
packages/scss/src/components/filterPill/component.scss
packages/scss/src/components/multiSelect/component.scss
packages/scss/src/components/multiSelect/index.scss
packages/scss/src/components/multiSelect/mods.scss
packages/scss/src/components/simpleSelect/mods.scss
packages/scss/src/components/simpleSelect/states.scss

[phoneNumber – simpleSelect – filterPills] fix ellipsis

---

stories/documentation/forms/fields/multi-select/angular/multi-select.stories.ts
stories/documentation/forms/fields/multilanguage/angular/multilanguagefield.stories.ts
stories/documentation/forms/fields/simple-select/angular/simple-select.stories.ts

Add width input to a bunch of stories
-----

[Form field] Add width input to a bunch of stories

---

packages/ng/core-select/user/former-employees.component.ts
packages/ng/date/picker/date-picker.component.html
packages/ng/forms/multilanguage-input/multilanguage-input.component.html
packages/ng/forms/phone-number-input/phone-number-input.component.html
packages/ng/multi-select/input/select-all/multi-select-all-header.component.ts
packages/ng/simple-select/input/select-input.component.html

fix: add missing standalone on ngModels without name

---

packages/ng/form-field/form-field.component.spec.ts
packages/ng/form-field/form-field.component.ts

When hot-swapping the control of a `formControl` directive, required/invalid statuses were not updated correctly.
-----
-----

fix(form-field): better required and invalid detection

---

packages/scss/src/components/textFlow/component.scss

[Text flow] ol support

---

packages/scss/src/components/textFlow/component.scss
stories/documentation/_sample/angular/basic.stories.ts
stories/documentation/_sample/html&css/basic.stories.ts
stories/qa/_sample/sample.stories.ts
stories/qa/select/select.stories.html
stories/qa/select/select.stories.ts

Update sample stories + add Selects QA
-----

Update sample stories + add Selects QA

---

packages/scss/src/components/tag/component.scss
packages/scss/src/components/tag/mods.scss

[Tag] Increase icon size

---

.storybook/styles.scss
packages/scss/src/commons/config.scss
packages/scss/src/commons/core.scss
packages/scss/src/commons/function.scss
packages/scss/src/commons/vars.scss

[palettes] option for all products

---

packages/scss/src/components/navside/states.scss
packages/scss/src/components/newBadge/component.scss
packages/scss/src/components/newBadge/index.scss
packages/scss/src/components/newBadge/mods.scss
packages/scss/src/components/newBadge/vars.scss
stories/documentation/navigation/menu-secondary/menu-secondary-basic.stories.ts

[newBadge] inverted mod for navSide

---

packages/ng/core-select/input/select-input.component.ts
packages/ng/core-select/option/option.component.html
packages/ng/core-select/option/option.component.ts
packages/ng/date2/date-input/date-input.component.ts
packages/ng/filter-pills/core/filter-pill-input-component.ts
packages/ng/filter-pills/filter-pill/filter-pill.component.html
packages/ng/filter-pills/filter-pill/filter-pill.component.ts
packages/ng/popover2/popover.directive.ts
packages/ng/simple-select/panel/panel.component.html
packages/scss/src/components/tag/component.scss
packages/scss/src/components/tag/mods.scss
packages/scss/src/components/textFlow/component.scss
stories/documentation/_sample/angular/basic.stories.ts
stories/documentation/_sample/html&css/basic.stories.ts
stories/documentation/forms/filterPills/angular/filter-bar.stories.ts
stories/qa/_sample/sample.stories.ts
stories/qa/select/select.stories.html
stories/qa/select/select.stories.ts

[19.2.4] Update RC

---

packages/scss/src/components/button/index.scss
packages/scss/src/components/button/mods.scss
packages/scss/src/components/button/vars.scss
stories/documentation/actions/button/html&css/button-with-arrow.stories.ts

[button] with arrow

---

packages/ng/styles/definitions/select/_select-input.scss

Fix clear button spacings
-----

[Department] Fix clear button spacings

---

packages/scss/src/components/dataTable/component.scss
packages/scss/src/components/indexTable/component.scss
stories/qa/data-table/data-table.stories.html
stories/qa/data-table/data-table.stories.ts
stories/qa/index-table/index-table.stories.html
stories/qa/index-table/index-table.stories.ts

[indexTable - dataTable] fix alignement for tags, status and avatars

---

packages/scss/src/components/tag/vars.scss

[Tag] Default cursor 

---

packages/ng/tag/tag.component.html

So UI devs can more easily target the text part and apply an ellipsis.
-----
-----

[tag] tag-content always present

---

stories/documentation/overlays/dropdown/dropdown-basic.stories.ts

[Dropdown] Update doc

---

packages/ng/empty-state/empty-state-page/empty-state-page.component.html
packages/ng/empty-state/empty-state-page/empty-state-page.component.ts
stories/documentation/feedback/empty-state/angular/empty-state-page.stories.ts
stories/qa/empty-state/empty-state-page.stories.html

Add `slotTop` that give the possibility to add content over the title
-----

[Empty state] Top slot

---

package.json

See https://lucca.slack.com/archives/C0BASUM42/p1739868182547989
-----
-----

[devtools] fix i18n

---

packages/ng/horizontal-navigation/horizontal-navigation.component.ts
stories/documentation/navigation/horizontalNavigation/horizontalNavigation-basic.stories.ts
stories/documentation/navigation/horizontalNavigation/horizontalNavigation-container.stories.ts
stories/documentation/navigation/horizontalNavigation/horizontalNavigation-count.stories.ts
stories/documentation/navigation/horizontalNavigation/horizontalNavigation-scrollbox.stories.ts
stories/documentation/navigation/vertical-navigation/vertical-navigation-basic.stories.ts
stories/documentation/navigation/vertical-navigation/vertical-navigation-disabled.stories.ts
stories/documentation/navigation/vertical-navigation/vertical-navigation-iconless.stories.ts
stories/documentation/structure/page-header/html&css/page-header-menu.stories.ts
stories/qa/horizontalNavigation/horizontalNavigation.stories.html
stories/qa/vertical-navigation/vertical-navigation.stories.html

Navigation roles are reserved for the main navigation of the site (not the product).
-----
-----

[*navigation] remove nav

---

packages/scss/src/components/checkbox/states.scss
packages/scss/src/components/checkboxField/states.scss
packages/scss/src/components/formLabel/states.scss
packages/scss/src/components/inlineMessage/states.scss
packages/scss/src/components/radio/states.scss
packages/scss/src/components/switch/states.scss
packages/scss/src/components/switchField/states.scss

Label, inline message & icons : 500 > 600
-----

[Checkbox/Radio/Switch] Edit disabled colors

---

packages/ng/highlight-data/highlight-data.component.ts

By detecting the `/` only we should be able to add local urls.
-----
-----

[highlightData] illustration source

---

packages/ng/button/button.component.ts

An input to automatically set the class.
-----
-----

[button] disclosure input

---

packages/scss/src/commons/config.scss
packages/scss/src/components/button/component.scss
packages/scss/src/components/callout/component.scss
packages/scss/src/components/calloutAccordion/component.scss
packages/scss/src/components/calloutDisclosure/component.scss
packages/scss/src/components/highlightData/component.scss
packages/scss/src/components/link/mods.scss
stories/qa/button/button.stories.html

The contrast of hovered links is enhanced to meet accessibility needs and also to make them more prominent.
-----
-----

[link] contrasted hover

---

packages/scss/src/components/indexTable/mods.scss

Fixe : https://github.com/LuccaSA/lucca-front/issues/3226
-----

fix(front) : fix - no forced layoutFixed for responsive

---

packages/ng/forms/multilanguage-input/multilanguage-input.component.html
packages/ng/forms/multilanguage-input/multilanguage-input.component.ts

[multilanguage] inherit size 

---

packages/scss/src/components/multiSelect/mods.scss

Fix search icon with S size
-----
-----

[Multi select] Search icon size with S size

---

packages/ng/schematics/.eslintrc
packages/ng/schematics/lib/angular-component-ast.ts
packages/ng/schematics/lu-select/migration.ts
packages/ng/schematics/lu-select/tests/input/api-selects.component.ts
packages/ng/schematics/lu-select/tests/input/simple-case.component.ts
packages/ng/schematics/lu-select/tests/output/api-selects.component.ts
packages/ng/schematics/lu-select/tests/output/rejected.component.ts
packages/ng/schematics/lu-select/tests/output/simple-case.component.ts
packages/ng/schematics/lu-select/util.ts
stories/qa/index-table/index-table.stories.ts

Better logic for removing imports in multi-line contexte, which are quite common but surprisingly were not tested.
#3460
-----
-----

fix(select-schematic): better deletion and detection logic

---

stories/documentation/overlays/dropdown/dropdown-component.stories.ts

[Dropdown] Fix description typo

---

packages/scss/src/components/navside/states.scss

Remove New Badge automatic invert
-----

[Navside] Remove New Badge automatic invert

---

docs/rich-text-input.md
packages/ng/button/button.component.ts
stories/documentation/actions/button/angular/button-basic.stories.ts
stories/documentation/actions/button/angular/button-icon.stories.ts
stories/documentation/actions/button/html&css/button-disclosure.stories.ts
stories/documentation/forms/fileUpload/angular/basic.stories.ts
stories/documentation/forms/select/simple-select.stories.ts
stories/documentation/navigation/breadcrumbs/angular/breadcrumbs-basic.stories.ts
stories/documentation/navigation/horizontalNavigation/angular/horizontalNavigation-basic.stories.ts
stories/documentation/navigation/horizontalNavigation/horizontalNavigation-basic.stories.ts
stories/documentation/navigation/horizontalNavigation/horizontalNavigation-container.stories.ts
stories/documentation/navigation/horizontalNavigation/horizontalNavigation-count.stories.ts
stories/documentation/navigation/horizontalNavigation/horizontalNavigation-scrollbox.stories.ts
stories/documentation/structure/footer/angular/footer-basic.stories.ts
stories/documentation/structure/footer/html&css/footer-basic.stories.ts
stories/documentation/structure/highlight-data/angular/basic.stories.ts
stories/documentation/texts/read-more/angular/read-more.stories.ts

[19.3] Format stories

---

stories/documentation/forms/fileUpload/angular/basic.stories.ts

The French language was only there for a test.
-----
-----

[fileUpload] remove lang fr

---

packages/ng/date2/date-range-input/date-range-input.component.html
packages/ng/date2/date-range-input/date-range-input.component.ts
packages/ng/multi-select/displayer/default-displayer.component.ts
packages/ng/simple-select/input/select-input.component.html
packages/ng/simple-select/input/select-input.component.ts

[select] autocomplete off by default

---

packages/ng/date2/date-range-input/date-range-input.component.html

Fix disabled state by default
-----

[Date range] Fix disabled state by default

---

stories/qa/date-input/date-input.stories.html
stories/qa/date-input/date-input.stories.ts
stories/qa/date-range-input/date-range-input.stories.html
stories/qa/date-range-input/date-range-input.stories.ts

[QA] Add Date input & Date range input basic pages
-----

[QA] Add Date input & Date range input basic pages

---

packages/ng/forms/textarea-input/textarea-input.component.ts

Set default rows value to avoid scroll break
-----

[Textarea] Set default rows value

---

packages/scss/src/components/indexTable/index.scss
packages/scss/src/components/indexTable/mods.scss
stories/qa/index-table/index-table.stories.html
stories/qa/index-table/index-table.stories.ts

Fix specificity issues on Index Table actions when luButton is imported.
-----

[Index table] Fix button style with Angular import

---

packages/ng/option/item/tree-option-item.component.scss

[option] increase depth for nesting + reduce code

---

packages/scss/src/components/filterBar/component.scss

Don’t remove divider if form field is present

---

stories/documentation/forms/date2/date-input.stories.ts

Fix null exception on the date-input story.
-----
-----

fix(date-input): fix null exception in story

---

packages/scss/src/commons/config.scss
packages/scss/src/commons/vars.scss

Several mechanisms for activating high contrast: 
- a utility class that can be placed wherever you like
- media queries that respond to system user preferences
- an LF parameter in the configuration
Once high contrast is activated, it corrects here:
- form text field borders
- placeholders
- error states
-----
-----

[forms] contrasted

---

packages/scss/src/components/breadcrumbs/index.scss
stories/documentation/navigation/breadcrumbs/angular/breadcrumbs-basic.stories.ts
stories/qa/breadcrumb/breadcrumb.stories.html
stories/qa/breadcrumb/breadcrumb.stories.ts

Deprecate compact mode & update stories
-----

[Breadcrumbs] Deprecate compact mode

---

packages/scss/src/components/userTile/component.scss
packages/scss/src/components/userTile/mods.scss
packages/scss/src/components/userTile/vars.scss

Fix gap for S / XS sizes
-----

[User Tile] Fix gap for S / XS sizes

---

stories/documentation/forms/filterPills/angular/filter-pills.stories.ts

[Filter pills] Improve clearable documentation
-----

[Filter pills] Improve clearable documentation

---

packages/ng/core-select/input/select-input.component.ts
packages/ng/filter-pills/core/tokens.ts
packages/ng/filter-pills/filter-pill/filter-pill.component.ts
packages/ng/simple-select/input/panel-ref.factory.ts
packages/ng/title/README.md
packages/scss/src/components/breadcrumbs/index.scss
packages/scss/src/components/userTile/component.scss
packages/scss/src/components/userTile/mods.scss
packages/scss/src/components/userTile/vars.scss
stories/documentation/forms/date2/date-input.stories.ts
stories/documentation/forms/filterPills/angular/filter-pill-child-component.stories.ts
stories/documentation/forms/filterPills/angular/filter-pills.stories.ts
stories/documentation/navigation/breadcrumbs/angular/breadcrumbs-basic.stories.ts
stories/qa/breadcrumb/breadcrumb.stories.html
stories/qa/breadcrumb/breadcrumb.stories.ts

[19.3.2] Update RC

---

packages/ng/filter-pills/filter-pill/filter-pill.component.html
packages/scss/src/components/filterPill/component.scss
packages/scss/src/components/filterPill/mods.scss
packages/scss/src/components/filterPill/vars.scss

[filterPills] adjust max width

---

packages/ng/forms/radio-group-input/radio/radio.component.html
packages/ng/forms/radio-group-input/radio/radio.component.ts
stories/documentation/forms/fields/radio/angular/radiofield.stories.ts

[radio] portalContent type for inlineMessage

---

packages/ng/date2/date-input/date-input.component.ts
packages/ng/date2/date-range-input/date-range-input.component.ts
stories/documentation/forms/date2/date-input.stories.ts
stories/documentation/forms/date2/date-range-input.stories.ts

Added an input to control an existing class that allowed a fluid width.
-----
-----

[date/rangeInput] Add input for width auto

---

packages/scss/src/components/navside/component.scss
packages/scss/src/components/navside/mods.scss
packages/scss/src/components/navside/vars.scss

- Display option label in compact mode
- Supports alerts in compact mode
- Fix hover color in compact mode
- Fix misc spacing issues on bottom section
-----
-----

[Sidenav] Compact fixes

---

packages/ng/forms/fieldset/fieldset.component.html
packages/ng/forms/fieldset/fieldset.component.scss
packages/ng/forms/fieldset/fieldset.component.ts
packages/ng/forms/number-input/number-input.component.ts
packages/ng/forms/public-api.ts
packages/scss/src/components/fieldset/component.scss
stories/documentation/forms/fieldset/angular/fieldset-basic.stories.ts
stories/documentation/forms/fieldset/html&css/fieldset-basic.stories.ts

[fieldset] wrapper

---

packages/scss/src/components/navside/mods.scss
packages/scss/src/components/navside/states.scss

Remove unwanted padding on mobile view
-----

[Sidenav] Remove unwanted padding

---

packages/ng/page-header/page-header.component.html
packages/scss/src/components/pageHeader/component.scss
stories/documentation/structure/page-header/angular/page-header-basic.stories.ts
stories/documentation/structure/page-header/html&css/page-header-leading-trailing.stories.ts

Add slots around the title.
-----
-----

[pageHeader] add leading and trailing slots

---

packages/scss/src/components/filterBar/component.scss

[filterBar] fix display

---

packages/ng/box/box.component.html
packages/ng/box/box.component.scss
packages/ng/box/box.component.ts
packages/ng/box/ng-package.json
packages/ng/box/public-api.ts
packages/scss/src/components/filterBar/component.scss
stories/documentation/structure/box/angular/basic.stories.ts
stories/documentation/structure/box/html&css/box-arrow-ng.stories.ts
stories/documentation/structure/box/html&css/box-arrow.stories.ts
stories/documentation/structure/box/html&css/box-basic.stories.ts
stories/documentation/structure/box/html&css/box-killable.stories.ts
stories/documentation/structure/box/html&css/box-toggle.stories.ts

[box] wrapper

---

packages/scss/src/components/tableSticked/mods.scss

Fix table shadow position
-----

[Table] Fix table shadow position

---

packages/ng/footer/footer.component.scss

Required for sticky positions.
-----
-----

[footer] display contents for wrapper

---

packages/ng/scrollBox/scroll-box.component.ts

[scrollBox] fix init

---

packages/ng/page-header/page-header.component.html
packages/ng/page-header/page-header.component.ts
packages/scss/src/commons/vars.scss
packages/scss/src/components/container/index.scss
packages/scss/src/components/container/mods.scss
packages/scss/src/components/footer/component.scss
packages/scss/src/components/footer/index.scss
packages/scss/src/components/footer/mods.scss
packages/scss/src/components/footer/vars.scss
packages/scss/src/components/pageHeader/component.scss
packages/scss/src/components/pageHeader/index.scss
packages/scss/src/components/pageHeader/mods.scss
packages/scss/src/components/pageHeader/vars.scss
stories/documentation/structure/page-header/angular/page-header-basic.stories.ts
stories/documentation/structure/page-header/html&css/page-header-container.stories.ts

- Adjust padding for header and footer component to align it with container padding.
- Add option for inject container container inside these components.
-----
-----

[pageHeader/pageFooter] container

---

packages/ng/modal/modal-panel.component.html

[modal] fix class + [class]

---

packages/ng/form-field/form-field.component.html
packages/ng/form-field/form-field.component.ts
packages/ng/forms/radio-group-input/radio-group-input.component.ts
stories/documentation/structure/box/html&css/box-arrow-ng.stories.ts

Remove automatic inline mode when using `arrow` option
-----

[Form field] Remove automatic inline with arrow

---

package-lock.json
package.json
packages/ng/package.json

Forgot to update angular versions in ng's package.json... I also updated the nx deps versions.
-----
-----

fix(deps): update angular in ng package deps

---

packages/ng/schematics/lu-button/migration.ts
packages/ng/schematics/lu-button/tests/input/simple-cases.component.ts
packages/ng/schematics/lu-button/tests/output/simple-cases.component.ts
packages/ng/schematics/lu-icon/migration.ts
packages/ng/schematics/lu-icon/tests/input/external-template.component.html
packages/ng/schematics/lu-icon/tests/output/external-template.component.html

fix: various schematic fixes before release

---

docs/user-popover.md
packages/ng/popover2/popover.directive.ts
packages/ng/user-popover/card/trigger/lu-user-popover.directive.ts
packages/scss/src/components/userPopover/component.scss
stories/documentation/listings/index-table/index-table-actions-userPopover.stories.ts
stories/documentation/users/avatars/angular/basic.stories.ts
stories/documentation/users/display/with-popover.stories.ts
stories/documentation/users/popover/angular/popover.stories.ts
stories/documentation/users/tile/angular/user-tile.stories.ts

[userPopover] keyboard navigation

---

packages/ng/package.json

Add missing optional peer dependencies for formly
-----
-----

chore: add missing optional peer dependencies to ng package

---

packages/ng/filter-pills/filter-pill/filter-pill.component.ts
packages/ng/multi-select/input/select-input.component.ts
stories/documentation/forms/filterPills/angular/filter-bar.stories.ts

When an optional filter pill has a value, it must be displayed.
When an optional filter pill is hidden, its value must be cleared.
-----
Co-authored-by: Flavien Normand <contact@flavien-normand.fr>

fix(filter-pills): value = displayed

---

packages/ng/comment/comment/comment.component.ts

Add missing style import
-----

[Callout] Add missing style import

---

packages/ng/popover2/content/popover-content/popover-content.component.ts
packages/ng/popover2/popover-tokens.ts
packages/ng/popover2/popover.directive.ts

fix: focus is now brought back to trigger on popover close on focus mode

---

packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
stories/documentation/overlays/tooltip/tooltip.stories.ts

[tooltip] add role button when needed

---

packages/ng/mobile-push/mobile-push.component.html
packages/ng/mobile-push/mobile-push.component.ts

I suggest to provide output events on link usage each app can consume according to their own needs. Could be especially useful to track use of links.
-----
-----

Mobile push.enh

---

packages/scss/src/commons/config.scss

Color input disabled 600 > 500
-----

[Tokens] Color input disabled 600 > 500

---

packages/ng/forms/number-format-input/number-format-input.component.html
packages/ng/forms/number-format-input/number-format-input.component.ts
packages/ng/forms/number-input/number-input.component.html
packages/ng/forms/number-input/number-input.component.ts
stories/documentation/forms/fields/number-format/angular/numberFormatfield.stories.ts
stories/documentation/forms/fields/number/angular/numberfield.stories.ts

Add `valueAlignRight` option
-----
-----

[Number / Number format] Add valueAlignRight option

---

packages/scss/src/components/numericBadge/states.scss
packages/scss/src/components/segmentedControl/index.scss
packages/scss/src/components/segmentedControl/states.scss
stories/qa/segmented-control/segmented-control.stories.html
stories/qa/segmented-control/segmented-control.stories.ts

Fix select numeric badge disappearing value
-----
-----

[Segmented control] Fix select numeric badge disappearing value + add disabled

---

packages/scss/src/commons/utils/index.scss

Fix u-hX token

---

packages/scss/src/components/pageHeader/mods.scss

Fixed inverted mobile condition
-----

[Page header] Fixed inverted mobile condition

---

stories/documentation/listings/index-table/index-table-interactive-nested-selectable.stories.html
stories/documentation/listings/index-table/index-table-nested-selectable.stories.ts
stories/documentation/listings/index-table/index-table-nested-sub-totals.stories.ts
stories/documentation/listings/index-table/index-table-nested.stories.ts
stories/documentation/listings/index-table/index-table-responsive-card-list-nested.stories.ts

`header` on `th` or `td` do not exist. Use `headers` instead.
-----

fix(front) : typo header -> headers

---

packages/ng/date2/date-input/date-input.component.html
packages/ng/date2/date-range-input/date-range-input.component.html
stories/documentation/listings/data-table/html&css/sort.stories.ts
stories/documentation/listings/index-table/index-table-sortable.stories.ts
stories/documentation/listings/table/table-sortable.stories.ts
stories/qa/data-table/data-table.stories.html

[Icons] Update deprecated names
-----

[Icons] Update deprecated names

---

packages/ng/dialog/dialog-header/dialog-header.component.html
packages/ng/dialog/dialog-header/dialog-header.component.ts
packages/scss/src/components/dialog/component.scss
packages/scss/src/components/dialog/vars.scss
stories/documentation/overlays/dialog/dialog.stories.ts

[dialog] add a slot for action

---

packages/ng/api/api.spec.ts
packages/ng/date2/calendar2/calendar2.component.html
packages/ng/department/department-select.spec.ts
packages/ng/establishment/establishment-select.spec.ts
packages/ng/forms/text-input/text-input.component.html
packages/ng/multi-select/panel/panel.component.html
packages/ng/option/picker/option-picker-advanced.component.html
packages/ng/option/picker/option-picker.component.html
packages/ng/option/picker/tree-option-picker-advanced.component.html
packages/ng/option/picker/tree-option-picker.component.html
stories/documentation/forms/date2/basic-html.stories.ts
stories/documentation/forms/fields/checkbox/angular/checkboxfield.stories.ts
stories/documentation/forms/fields/multi-select/angular/multi-select.stories.ts
stories/documentation/forms/fields/number/angular/numberfield.stories.ts
stories/documentation/forms/fields/radio/angular/radiofield.stories.ts
stories/documentation/forms/fields/simple-select/angular/simple-select.stories.ts
stories/documentation/forms/fields/switch/angular/switchfield.stories.ts
stories/documentation/forms/fields/text/html&css/textfield-prefix-suffix.stories.ts
stories/documentation/forms/fields/textarea/angular/textareafield.stories.ts
stories/documentation/forms/time/duration-picker-angular.stories.ts
stories/documentation/forms/time/time-picker-angular.stories.ts
stories/documentation/listings/data-table/html&css/basic.stories.ts
stories/documentation/listings/data-table/html&css/editable.stories.ts
stories/documentation/listings/index-table/index-table-actions-subAction.stories.ts
stories/documentation/listings/index-table/index-table-interactive-nested-selectable.stories.html
stories/documentation/listings/index-table/index-table-nested.stories.ts
stories/qa/data-table/data-table.stories.html
stories/qa/forms/textfield.stories.html

Various feedback from the DS audit:
- calendar day titles
- suffix positioning for inputs
- deleting the dialog role for comboboxes
- improved form field stories
- table semantics
- alternative button texts
- details on numerical values
-----
-----

[a11y] audit feedbacks

---

packages/ng/core-select/user/translations.ts
packages/ng/user/select/searcher/translations.ts

[former user] update translation

---

packages/ng/user/tile/user-tile.component.ts
stories/documentation/users/tile/angular/user-tile.stories.ts

[User tile] Add size input

---

packages/scss/src/components/emptyState/component.scss
stories/documentation/feedback/empty-state/angular/empty-state-page.stories.ts

Add plug & error visuals + fix icon spacing
-----

[Empty states] Add visuals + fix icon spacing

---

stories/documentation/actions/button/angular/button-basic.stories.ts
stories/documentation/actions/button/angular/button-counter.stories.ts
stories/documentation/actions/button/angular/button-icon.stories.ts
stories/documentation/feedback/callout-disclosure/angular/callout-disclosure.stories.ts
stories/documentation/forms/fields/checkbox/angular/checkboxfield.stories.ts
stories/documentation/forms/fields/text/angular/textfield.stories.ts
stories/documentation/forms/fields/textarea/angular/textareafield.stories.ts
stories/documentation/texts/status-badge/angular/status-badge-angular.stories.ts
stories/documentation/users/avatars/angular/basic.stories.ts

Clean ref to v16/17 + add missing v20.2 info
-----

Clean ref to v16/17 + add missing v20.2 info

---

docs/rich-text-input.md

Update rich-text-input documentation with new toolbar structure
-----
Fixes #3855
-----

docs(rich-text-input): update rich text custom toolbar documentation

---

packages/ng/button/button.component.ts

Trigger error animation on state change.
-----
-----

chore(button): trigger error animation on state change

---

packages/ng/forms/rich-text-input/rich-text-input.component.ts

Remove console error
-----
-----

fix(rich-text): add optional parameter when tabindex is set

---

docs/pagination.md

`prevPage` ➡️ `previousPage`
-----
-----

[pagination] fix documentation

---

stories/documentation/forms/fieldset/angular/fieldset-basic.stories.ts
stories/documentation/forms/fieldset/html&css/fieldset-basic.stories.ts

- Add grid & fields examples
- Remove content controls as it would generate a very large row in controls documentation
-----
-----

[Fieldset] Improve stories

---

packages/ng/multi-select/panel/panel.component.scss
packages/ng/simple-select/panel/panel.component.scss
packages/scss/src/commons/vars.scss
packages/scss/src/components/button/states.scss

[scss] linter

---

stories/documentation/forms/fieldset/angular/fieldset-basic.stories.ts

[Fieldset] fix story

---

packages/scss/src/components/button/states.scss
packages/scss/src/components/numericBadge/states.scss

[button] fix states with counter

---

packages/ng/user-popover/card/trigger/user-popover.component.html
packages/ng/user-popover/card/trigger/user-popover.component.ts
packages/scss/src/components/userPopover/component.scss
stories/documentation/users/popover/html&css/skeleton.stories.ts

-----
Fixes #3873 
Thx @Supamiu for the help.
-----

[userPopover] skeleton

---

packages/ng/segmentedControl/filter/filter.component.html
packages/ng/segmentedControl/filter/filter.component.ts
packages/ng/segmentedControl/ng-package.json
packages/ng/segmentedControl/public-api.ts
packages/ng/segmentedControl/segmented-control.component.scss
packages/ng/segmentedControl/segmented-control.component.ts
packages/ng/segmentedControl/segmented-control.token.ts
packages/ng/segmentedControlTabs/ng-package.json
packages/ng/segmentedControlTabs/panel/panel.component.ts
packages/ng/segmentedControlTabs/public-api.ts
packages/ng/segmentedControlTabs/segmented-control-tabs.component.html
packages/ng/segmentedControlTabs/segmented-control-tabs.component.scss
packages/ng/segmentedControlTabs/segmented-control-tabs.component.ts
packages/ng/segmentedControlTabs/segmented-control-tabs.token.ts
packages/scss/src/components/segmentedControl/component.scss
stories/documentation/navigation/segmentedControl/angular/segmentedControl.stories.ts
stories/documentation/navigation/segmentedControl/angular/segmentedControlTabs.stories.ts
stories/documentation/navigation/segmentedControl/html&css/segmentedControl-filter.stories.ts
stories/documentation/navigation/segmentedControl/html&css/segmentedControl-tabs.stories.ts

-----
Working together with @Supamiu!
-----
Tabs:
Filters:

[segmentedControl] wrappers angular for filters and tabs

---

packages/ng/form-field/framed-input/framed-input.component.html
packages/ng/form-field/framed-input/framed-input.component.ts
packages/ng/forms/radio-group-input/radio-group-input.component.ts
packages/ng/forms/radio-group-input/radio/radio.component.html
packages/ng/forms/radio-group-input/radio/radio.component.ts
packages/scss/src/components/inputFramed/component.scss
packages/scss/src/components/inputFramed/index.scss
packages/scss/src/components/inputFramed/mods.scss
packages/scss/src/components/inputFramed/vars.scss
stories/documentation/forms/input-framed/angular/basic.stories.ts
stories/documentation/forms/input-framed/html&css/alignCenter.stories.ts

[inputFramed] mod-alignCenter

---

packages/ng/core-select/input/select-input.component.ts
packages/ng/date2/abstract-date-component.ts
packages/ng/date2/date-input/date-input.component.html
packages/ng/date2/date-range-input/date-range-input.component.html
packages/ng/date2/date-range-input/date-range-input.component.ts

feat(date): add panelOpen and panelClose events to date inputs

---

packages/ng/core-select/department/departments.directive.ts

fix(tree): total count on departments

---

packages/scss/src/commons/core.scss
stories/documentation/listings/index-table/index-table-actions-tooltipsCell.stories.ts
stories/documentation/listings/index-table/index-table-actions-tooltipsRow.stories.ts

-----
`(click)` moved to `tr`
-----

[indexTable] update stories for tooltips

---

.prettierrc
packages/ng/formly/types/checkbox.html
packages/ng/formly/types/radios.html
packages/ng/formly/wrappers/helper.html
packages/ng/formly/wrappers/icon.html
packages/ng/formly/wrappers/suffix.html
stories/documentation/listings/index-table/index-table-interactive-nested-selectable.stories.html
stories/documentation/texts/icons/icon-basic.stories.html
stories/documentation/users/display/display.stories.html
stories/qa/empty-state/empty-state-page.stories.html
stories/qa/icon/icon.stories.html

The prettier config was not correctly set for some files using angular. This fixes that.
-----

refactor(prettier): use angular parser for more files

---

docs/user-popover.md

Remove Featflag documentation
-----

[User popover] Remove Featflag documentation
