LuccaSA/lucca-front

- tools/link.js
[npm link](https://docs.npmjs.com/cli/link) is the way to wwork on several interdependnat npm packages.
here we will have several packages with dependencies between them, `ng` is dependant on `scss`. but in the future we'll have
`scss depends on `icons`
`webcomponents` depends on `icons` and `scss`
`ng` depends on `icons`, `scss`, `webcomponents`
this script does all the necessary linking
> add link script

- packages/scss/src/components/_radio.scss
Height was duplicated. CombCSS inverted the two values.
> [fix] round radio

- packages/scss/demo/components/lists.html
- packages/scss/src/components/_list.scss
About that : 
As I want to allow to have a link on list-item-content, padding are now on list-item-content and list-item-actions. So the default padding is applied on both, except list-item-actions left padding. 
Using a link on list also become only a suggestion.
> [ref] action buttons must be outside the list element link

- packages/scss/demo/components/utilities.html
- packages/scss/src/utilities/_misc.scss
Force a one line string. Useful for tables cells, especially for numerical values and names.
> [add] nowrap utility

- packages/ng/package.json
we'll use `@angular/common/http` if we need to use a http service
> ng-dep [rem] dep to @angular/http

- packages/ng/src/app/date-range-picker/date-range-modal/date-range-modal.scss
The `~` isn't supported by the gulp build command
> [FIX] change import path to work with gulp build

- packages/icons/src/_font.scss
Safari Mac wasn't supporting the "format" in the src font definition
> [FIX] Safari **** bug

- packages/scss/src/components/inputs/input/_input.compact.scss
- packages/scss/src/components/inputs/input/_input.framed.scss
- packages/scss/src/components/inputs/input/_input.scss
Patch fixing issues that appeared while styling formly forms :
- label should never change (nor position nor font-size) in compact mode
- `.input-messages` now have a `.mod-helper`, positionning helper messages below the input in compact mode
- `.input-messages` has a smaller line-height
- `.input.mod-framed` now supports `.mod-autocomplete`
Thoses additions/changes are necessary for the integration of formly forms
> [SCSS] Input fixes

- packages/scss/src/components/inputs/input/_input.compact.scss
To avoid border render issue, compact input now uses box-shadow instead of border
> [FIX] input compact border was being left out by chrome

- packages/ng/src/plugins/ngMaterial/_dialog.scss
Adds `mod-sidePanel` to the mdDialog component. 
It is yet impossible to override its animations.
> [NG] Add mdDialog override mod-sidePanel 

- packages/scss/src/components/inputs/textfield/_textfield.compact.scss
- packages/scss/src/components/inputs/textfield/_textfield.framed.scss
- packages/scss/src/components/inputs/textfield/_textfield.scss
Adds the `is-focused` state on `textfield` to handle cases where the sibling selector ~ cannot be used.
> [SCSS] is-focused state for textfield

- packages/scss/src/components/_nav-side.scss
navSide wasn't using the selected-text variable even though it was available. Now it does.
> [SCSS] Unused theme variable is now used

- packages/ng/src/app/date-range-picker/date-range-picker.module.ts
i commented too much last time, the daterangepicker module still needs to be a ngmodule cuz its impotrted somewhere
> ng [fix] date rage picker moduel

- packages/ng/demo/app/api/api.component.html
- packages/ng/demo/app/api/api.component.ts
- packages/ng/demo/app/api/api.module.ts
- packages/ng/demo/app/api/api.router.ts
- packages/ng/demo/app/app.module.ts
- packages/ng/demo/app/app.router.ts
- packages/ng/demo/app/navigation/navigation.component.html
- packages/ng/demo/app/shared/index.ts
- packages/ng/demo/app/shared/redirect/redirect.component.html
- packages/ng/demo/app/shared/redirect/redirect.component.ts
- packages/ng/demo/app/shared/redirect/redirect.interceptor.ts
- packages/ng/demo/app/shared/redirect/redirect.module.ts
- packages/ng/demo/app/shared/redirect/redirect.service.ts
for the directives api-picker and user-picker, the demo needs to be able to redirect xhr requests to a lucca website. so this pr adds the redirectModule in the demo shared module to allow users to connect to one of their local website or a prod website (#totesSafe)
the component looks like this
> Ng.demo.redirect

- packages/scss/src/components/inputs/textfield/_textfield.framed.scss
- packages/scss/src/components/inputs/textfield/_textfield.material.scss
- packages/scss/src/components/inputs/textfield/_textfield.scss
- packages/scss/src/mixins/_forms.scss
Fixes `textfield.is-focused` behaviour, moving material specific part to its rightful place.
Adds textfieldFramedError() mixin to handle this mod error state in the `ng` package
> [SCSS][FIX] Fix textfield.is-focused behaviour

- packages/ng/src/app/formly/types/formly-field.common.scss
- packages/ng/src/app/formly/wrappers/button.ts
- packages/ng/src/app/formly/wrappers/flex-layout.scss
- packages/ng/src/style/components/_formly.scss
- packages/ng/src/style/components/_input.scss
Merge #176 first
Fixes layout issues due to formly wrappers after the rollout of textfield refactoring.
Adds better ng-invalid support.
> [NG][FIX] Fixes issues post textfield classic update

- packages/ng/demo/app/formly/basic/basic.ts
- packages/ng/demo/app/formly/formly.component.html
- packages/ng/demo/app/formly/formly.module.ts
- packages/ng/src/app/api/picker/api-picker.component.ts
- packages/ng/src/app/api/picker/api-picker.directive.ts
- packages/ng/src/app/api/picker/api-picker.template.ts
- packages/ng/src/app/formly/formly.config.ts
- packages/ng/src/app/formly/formly.module.ts
- packages/ng/src/app/formly/types/api.html
- packages/ng/src/app/formly/types/api.ts
- packages/ng/src/app/formly/wrappers/icon.ts
- fixes #186 - adds formly wrapper, 
- fixes #183 - adds `v` `^` keydown to navigate options in dropdown and `enter` to select it
> Ng.apipicker.formly

- packages/scss/CHANGELOG.md
- packages/scss/demo/templates/fullmenu.html
- packages/scss/demo/templates/side.html
- packages/scss/src/components/_nav-side.scss
- packages/scss/src/theming/components/_nav-side.theme.scss
Adds a `.navSide-bottomSection` to handle navSide-item that needs to be stuck to the bottom of the screen.
It has its own palette to ease its customisation. If you need more than one button stucked to the bottom, you'll have to adjust the bottom-section-height variable in the theme.
> [SCSS] navSide bottom section

- packages/ng/.angular-cli.json
- packages/ng/CHANGELOG.md
- packages/ng/demo/app/user/picture/basic/basic.html
- packages/ng/demo/app/user/tile/basic/basic.component.html
- packages/ng/demo/styles.scss
- packages/ng/src/app/user/picture/user-picture.component.scss
- packages/ng/src/app/user/picture/user-picture.component.ts
- packages/ng/src/app/user/tile/user-tile.component.html
- packages/ng/src/app/user/tile/user-tile.component.scss
- packages/ng/src/app/user/tile/user-tile.component.ts
- packages/ng/src/style/_theming.overridable.scss
- packages/ng/src/style/theme/_user-picture.theme.scss
Adds new attributes to lu-user-tile and lu-user-picture:
- `lu-user-picture` has a new attribute `size` to set it size in px
- `lu-user-tile` has a new attribute `imageSize` to set its user-picture size in px
> [NG] lu-user-tile & lu-user-picture new size attribute

- packages/ng/package.json
i have some transpilation problems cuz different libs want different versions of rxjs, by doing that i can tweak my lock file to stop having these issues
> ng-build [mod] dont fix rxjs version

- packages/scss/src/components/inputs/textfield/_textfield.scss
Remove relicat from lu-select development that broke the textfield style.
> [SCSS][fix] Remove relicat

- packages/scss/src/components/_container.scss
With margin collapse, the bottom margin was collapsed with the container margin, leading to wrongful sizing
> [SCSS][fix] bottom margin was collapsing

- packages/scss/src/components/_nav-side.scss
- packages/scss/src/theming/components/_nav-side.theme.scss
Style changes after testing it in prod. It now uses margin-bottom rather than padding and adds a z-index. It is necessary to do so to work on both FF and IE.
> [SCSS][ENH] navSide - Better style after integration

- packages/ng/docs/demo/src/styles.scss
- packages/ng/libraries/core/src/lib/user/picture/user-picture.component.scss
- packages/ng/libraries/core/src/style/_theming.scss
- packages/ng/libraries/formly/package.json
- packages/ng/libraries/material/package.json
- packages/ng/libraries/material/src/style/_theming.scss
- packages/ng/package.json
- packages/ng/tsconfig.json
- packages/ng/yarn.lock
follow up of PR #308 and #310 
-------------
- updated formly version
- updated package.json for entry points /formly and /material
> :warning: some shenanigans with scss build 
> for some reason that i dont wanna look for, when building with ng-packagr, it seems node-sass cant resolve `@import '~@lucca-front/scss/src/theming';`
> cuz `theming` can be the flder `/theming` or the file `_theming`
> so i have to specify `@import '~@lucca-front/scss/src/theming.scss';` (n /libs/xxx/src/style/_theming.scss) or the libs tont build
> **BUT**
> when i build the demo and import `/libs/xxx/src/style/main` via the /demo/style.scss, it does'nt build if i specify the .scss
> as a result me and sandy we gonna rename the folder `/theming` -> `/theme` and hope it fixes …
> Formly.version

- packages/scss/CHANGELOG.md
- packages/scss/src/components/_nav-side.scss
- packages/scss/src/components/_table.scss
- packages/scss/src/components/inputs/textfield/_textfield.scss
- packages/scss/src/mixins/_forms.scss
@sanlucca Textfields looked better for me with a height of 2px less, so I did not edited component's padding.
> [fix] still has all border with browser zoom

- packages/scss/CHANGELOG.md
- packages/scss/src/components/_table.scss
Table sortable arrow always stay on the last label line
+ fix its vertical alignment for mod-small tables
> [enh] arrow position improved for large table heads

- packages/ng/docs/demo/src/app/select/basic/basic.html
- packages/ng/docs/demo/src/app/select/basic/basic.ts
- packages/ng/libraries/core/src/lib/option/index.ts
- packages/ng/libraries/core/src/lib/option/item/option-item.component.scss
- packages/ng/libraries/core/src/lib/option/item/option-item.component.ts
- packages/ng/libraries/core/src/lib/option/item/option-item.model.ts
- packages/ng/libraries/core/src/lib/option/operator/feeder/index.ts
- packages/ng/libraries/core/src/lib/option/operator/feeder/option-feeder.component.ts
- packages/ng/libraries/core/src/lib/option/operator/feeder/option-feeder.module.ts
- packages/ng/libraries/core/src/lib/option/operator/index.ts
- packages/ng/libraries/core/src/lib/option/operator/option-operator.model.ts
- packages/ng/libraries/core/src/lib/option/operator/option-operator.module.ts
- packages/ng/libraries/core/src/lib/option/operator/pager/index.ts
- packages/ng/libraries/core/src/lib/option/operator/pager/option-pager.component.ts
- packages/ng/libraries/core/src/lib/option/operator/pager/option-pager.module.ts
- packages/ng/libraries/core/src/lib/option/operator/searcher/index.ts
- packages/ng/libraries/core/src/lib/option/operator/searcher/option-searcher.component.ts
- packages/ng/libraries/core/src/lib/option/operator/searcher/option-searcher.module.ts
- packages/ng/libraries/core/src/lib/option/operator/template/index.ts
- packages/ng/libraries/core/src/lib/option/operator/template/option-template.component.html
- packages/ng/libraries/core/src/lib/option/operator/template/option-template.component.ts
- packages/ng/libraries/core/src/lib/option/operator/template/option-template.module.ts
- packages/ng/libraries/core/src/lib/option/option.module.ts
- packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts
- packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
adds the notion of _option operator_, being stuff that take `Obs<T[]>` in and return `Obs<T[]>` out
then the option picker chains them together. it allows writting this kind of html
```html
<lu-select [(ngModel)]="withOperators" class="textfield-input">
<lu-option-picker>
<lu-option-feeder [options]="options$ | async"></lu-option-feeder>
<lu-option-searcher [searchFn]="searchFn"></lu-option-searcher>
<lu-option-pager></lu-option-pager>
<lu-option-template>
<ng-template let-option>{{option.name}}</ng-template>
</lu-option-template>
</lu-option-picker>
</lu-select>
```
to have a searchable paged select
> Select.operators

- packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.ts
- packages/ng/libraries/core/src/lib/input/index.ts
- packages/ng/libraries/core/src/lib/input/input.directive.ts
- packages/ng/libraries/core/src/lib/input/input.model.ts
- packages/ng/libraries/core/src/lib/input/input.module.ts
- packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
- packages/ng/libraries/core/src/lib/select/input/select-input.model.ts
- packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.ts
add 
- ILuInput<T> - pretty empty interface that extends `ControlValueAccessor`
- ALuInput<T> - adds class `is-filled` when value is not empty
- LuInputDirective<T> - extends ALuInput
- ALuSelect - implements ILuInput<T> and add `is-filled` class to host element - affects all selects (normal, api, user, ...)
> Input.directive

- packages/ng/libraries/core/src/lib/option/item/option-item.component.scss
- packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts
- packages/ng/libraries/core/src/lib/option/picker/option-picker.model.ts
- packages/ng/libraries/core/src/lib/select/input/select-input.common.scss
- :bug: fix bug with keyboard events being stopped so searchers just dont work no more
- :sparkles: add `overlap-trigger` input on option-picker
- :bug: minor display bug
> Select.fix.keyboardevents

- packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts
- packages/ng/libraries/core/src/lib/option/picker/option-picker.model.ts
- packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
- packages/ng/libraries/core/src/lib/select/input/select-input.model.ts
when the value chages for the select-input (control value accerssor) it passes the info to its picker so the picker adds the class `is-selected` to current value
> option-picker - add class `is-selected` to current value

- packages/ng/docs/demo/src/app/app.module.ts
- packages/ng/docs/demo/src/app/navigation/navigation.router.ts
- packages/ng/docs/demo/src/app/number/basic/basic.html
- packages/ng/docs/demo/src/app/number/basic/basic.ts
- packages/ng/docs/demo/src/app/number/number.component.html
- packages/ng/docs/demo/src/app/number/number.component.ts
- packages/ng/docs/demo/src/app/number/number.module.ts
- packages/ng/docs/demo/src/app/number/number.router.ts
- packages/ng/docs/demo/src/app/number/parameters/parameters.html
- packages/ng/docs/demo/src/app/number/parameters/parameters.ts
- packages/ng/libraries/core/src/lib/index.ts
- packages/ng/libraries/core/src/lib/module.ts
- packages/ng/libraries/core/src/lib/number/index.ts
- packages/ng/libraries/core/src/lib/number/number.module.ts
- packages/ng/libraries/core/src/lib/number/number.pipe.ts
- packages/scss/src/_utilities.scss
- packages/scss/src/utilities/_visibility.scss
- adds `u-hidden` utility class
- adds the `luNumber` pipe to allow you to display some numbers, some with decimal parts, some sithout, but aligned on the separator
> Pipe.number

- packages/ng/docs/demo/src/app/select/foundations/basic/basic.html
- packages/ng/docs/demo/src/app/select/foundations/multiple/multiple.html
- packages/ng/docs/demo/src/app/select/multiple/basic/basic.html
- packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.html
- packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts
- packages/ng/libraries/core/src/lib/select/input/select-input.component.html
- packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.html
- packages/ng/libraries/core/src/style/definitions/option/_option-item.scss
- packages/ng/libraries/core/src/style/definitions/select/_select-input.scss
- packages/ng/libraries/core/src/style/theme/_options.theme.scss
- packages/scss/src/components/inputs/field/_field.framed.scss
- packages/scss/src/components/inputs/field/_field.scss
- packages/scss/src/components/inputs/textfield/_textfield.material.scss
Fix select & forms style.
Adds `mod-overflow` if you want to go over the input size.
`lu-select-display-wrapper` is now properly wrapping the display content
`.is-loading` attributes are all using !important as they must override any ::after/::before positionning
> [FIX] Select & forms style

- packages/scss/src/components/inputs/checkbox/_checkboxesfield.scss
- packages/scss/src/components/inputs/field/_field.scss
- packages/scss/src/components/inputs/radio/_radiosfield.scss
- packages/scss/src/components/inputs/textfield/_textfield.scss
Refactoring `field` mixin to unnest `fieldname-messages`.
Fixes #434
> [SCSS][FIX] Unnesting fieldname-messages

- packages/ng/libraries/core/src/lib/select/clearer/select-clearer.component.html
fixes #461 
lu-select clearer was causing unexpected form submit, because button default type is submit.
> [fix] lu-select clearer causing unexpected form submit

- packages/ng/docs/demo/src/app/app.module.ts
- packages/ng/docs/demo/src/app/shared/redirect/redirect.component.ts
some quick wins for the demo
- use `#` for navigation so we have shareable url with surge deployment
- before https://latest-lucca-front-luccasa.surge.sh/ng/user/picture
- after https://456-pr-lucca-front-luccasa.surge.sh/ng/#/user/picture
- do not auto try to redirect to lucca.local.dev cuz most people dont have this env, also when it crashed, it kept the `is-laoding` class forever
- some more better stuff with the redirect are integrated in PR #450
> Demo quick wins

- packages/ng/docs/demo/src/app/shared/redirect/redirect.component.ts
- packages/ng/libraries/core/src/lib/api/select/searcher/api-searcher.component.ts
- packages/ng/libraries/core/src/lib/option/operator/searcher/option-searcher.component.ts
- packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts
- packages/ng/libraries/core/src/lib/option/picker/option-picker.model.ts
- packages/ng/libraries/core/src/lib/popover/panel/popover-panel.model.ts
- packages/ng/libraries/core/src/lib/user/select/searcher/user-searcher.component.ts
fixes #401 
when changing the highlighted option via `^` `v`, we ensure that the highlighted option is fully visible by scrolling to it if its not
as a result the `scrollBottom` event is triggered when we get to the last option, allowing for full navigation of a select with a pager just with the keyboard
> [feat] select - keep highlighted option visible

- packages/scss/CHANGELOG.md
- packages/scss/demo/templates/compact-withBanner.html
- packages/scss/demo/templates/full-withBanner.html
- packages/scss/demo/templates/fullmenu.html
- packages/scss/demo/templates/side-cards.html
- packages/scss/demo/templates/side-filters.html
- packages/scss/demo/templates/side-header.html
- packages/scss/demo/templates/side-sections-header.html
- packages/scss/demo/templates/side-sections.html
- packages/scss/demo/templates/side.html
- packages/scss/src/components/_main.scss
- packages/scss/src/components/_nav-side.scss
- packages/scss/src/theming/components/_nav-side.theme.scss
Fixes the issue where the navSide with a `navSide-bottomSection` was jumping when scrolling on IE.
We introduce a `navSide-mainSection` that wraps around the `navSide-scrollWrapper`.
> [fix][SCSS] NavSide moving when scrolling on IE11

- packages/scss/src/components/_nav-side.scss
Padding-top on mobile menu must be toggle size and not banner size.
> [FIX][SCSS] Mobile menu height should be toggle size.

- packages/ng/libraries/formly/src/lib/types/api.ts
[ng-formly] fix nullrefex on apiselect when templateoptions.filters wasnt specified
fixes #529
> [fix] ng-formly api without filters

- packages/scss/src/components/inputs/checkbox/_checkboxesfield.scss
- packages/scss/src/components/inputs/radio/_radiosfield.scss
- packages/scss/src/theming/components/_field.theme.scss
Checkboxesfield mod-row used `.radio` instead of `.checkbox`
Both checkboxesfield & radiosfield now uses a common variable for horizontal-spacing
> [fix] [SCSS] Checkboxesfield mod-row was not properly defined

- packages/scss/CHANGELOG.md
- packages/scss/src/components/_callout.scss
- packages/scss/src/mixins/_forms.scss
- packages/scss/src/theming/components/_callout.theme.scss
- textfield is-required character is visible again
- callout background is editable in theme
--------
fixes #533 
fixes #535
> [fix] minor - textfield* and callout bg

- packages/ng/docs/demo/src/app/tooltip/basic/basic.html
- packages/ng/libraries/core/src/lib/popover/trigger/popover-trigger.model.ts
- packages/ng/libraries/core/src/lib/tooltip/panel/tooltip-panel.component.ts
- packages/ng/libraries/core/src/lib/tooltip/trigger/tooltip-trigger.directive.ts
- packages/ng/libraries/core/src/style/definitions/tooltip/_tooltip.scss
added input on tooltip trigger directive to allow custom positionning
@sanlucca right now it has no impact, cuz tooltip doesn't support classes `lu-popover-below`, so i think you need to patch [this file](https://github.com/LuccaSA/lucca-front/blob/feat.tooltip.position/packages/ng/libraries/core/src/style/definitions/tooltip/_tooltip.scss) with [this](https://github.com/LuccaSA/lucca-front/blob/feat.tooltip.position/packages/ng/libraries/core/src/style/components/_popover.scss#L17)
-----
fixes #432
> [feat] tooltip positioning

- packages/ng/libraries/core/src/lib/scroll/scroll.directive.ts
`$event.srcElement` is undefined on Firefox
> [fix] Firefox compatibility issue

- packages/ng/libraries/core/src/lib/api/select/pager/api-pager.component.ts
- packages/ng/libraries/core/src/lib/api/select/pager/api-pager.model.ts
- packages/ng/libraries/core/src/lib/api/select/searcher/api-searcher.model.ts
- packages/ng/libraries/core/src/lib/option/operator/for-options/for-options.directive.ts
fixes #572 
maybe fixes #541 
--------
- added a markforcheck in foroptions directive that seemed to not update since the optimizations from PR #550 
- also rewrote api pager and api paged searcher to use `Subject` instead of `BehaviorSubject` that seemed to emit twice when .next was called once, resulting in multiple http.get
> [fix] some bugs with api pager and paged searcher

- packages/ng/libraries/core/src/lib/api/select/pager/api-pager.model.ts
- packages/ng/libraries/core/src/lib/api/select/searcher/api-searcher.model.ts
fixes #577 
-----
after some debug it seemed that the rescroll was triggered by the fact that at the time of the opening of the picker, old options were still there, so it could find the highlighted option and it tried to scroll to it. it was due to option list reinitialization was made on the onOpen event, add some debouncetime and you have this
- i have 80 options and select the 77th
- i close the picker
- i reopen the picker, all 80 options are available
- it highlights the 77th, and try to scroll to it
- at the same time onOpen is called in the api-pager
- it reinits with just 20 options
- it tries to scroll to the 77th of the 20 options
- all hell breaks loose
so the fix was to reinit the option list on close
> picker rescroll shenanigans

- packages/scss/src/components/_container.scss
- packages/scss/src/components/_main.scss
Adds `mod-withMenu` and `mod-withMenuCompact` to handle layout without using proxy selectors.
Might be a patch or a feature in 2.5
> [ENH] Add mod-withMenu and mod-withMenuCompact

- packages/ng/libraries/core/src/lib/option/operator/for-options/for-options.directive.ts
- packages/ng/libraries/core/src/lib/option/picker/option-picker.component.html
- packages/ng/libraries/core/src/lib/option/picker/option-picker.model.ts
- packages/ng/libraries/core/src/style/definitions/option/_option-picker.scss
Fixes #609 
It adds a loader when opening an option-picker that takes 100% of the picker max-height. Therefor, the initial height of the select is more accurate and the dropdown is correctly placed by the overlay service.
> [bug][ng] Adds a loader when opening an option-picker

- packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.scss
- packages/ng/libraries/core/src/lib/select/input/select-input.model.ts
- packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.scss
- packages/ng/libraries/core/src/style/components/_overlay.scss
Fixes #610
`api-select` and `user-select` are always clearable. Therefor, we are adding a similar padding as on the `is-clearable` state .
#601 broke the fact that the picker should at least be as wide as its input. It is now the case, yet we force it to be at least 185px wide.
> [bug][ng] Select padding and picker minwidth

- packages/scss/src/components/inputs/textfield/_textfield.scss
- packages/scss/src/theming/components/_button.theme.scss
- packages/scss/src/theming/components/_textfield.theme.scss
Improve buttons & textfield height/alignment to be perfectly aligned together by default.
> [628] improve button / textfield alignment & height

- packages/ng/libraries/core/src/lib/option/picker/option-picker.model.ts
with the addition of the loader in patch 2.5.1, when the loading was done the search field of an option picker with a search operator wasnt focused
to fix it we replay the onOpen event at the end of loading
> [fix] option-picker async wasnt focusing search input on open

- packages/ng/docs/demo/src/app/formly/fieldgroup/fieldgroup.ts
- packages/ng/libraries/formly/src/lib/wrappers/textfield-layout.html
- packages/ng/libraries/formly/src/lib/wrappers/textfield-layout.ts
- packages/scss/src/components/inputs/field/_field.framed.scss
- packages/scss/src/components/inputs/textfield/_textfield.framed.scss
- packages/scss/src/components/inputs/textfield/_textfield.scss
Textarea disabled wasn't working on mod-framed because in this mod, the `textfield` needs to be the one disabled, not the input. 
Therefore, I adapted the style in the `scss` package and added a `is-disabled` on the `textfield-layout` for formly
> [NG][SCSS] Fix textarea disabled on mod-framed

- packages/ng/applications/sandbox/src/app/issues/poc-tree-picker/index.ts
- packages/ng/applications/sandbox/src/app/issues/poc-tree/poc-tree.component.html
- packages/ng/applications/sandbox/src/app/issues/poc-tree/poc-tree.module.ts
- packages/ng/libraries/core/src/lib/option/item/option-item.component.ts
- packages/ng/libraries/core/src/lib/option/item/option-item.model.ts
- packages/ng/libraries/core/src/lib/option/picker/option-picker-advanced.component.ts
- packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts
- packages/ng/libraries/core/src/lib/option/picker/option-picker.model.ts
- packages/ng/libraries/core/src/lib/tree/option/index.ts
- packages/ng/libraries/core/src/lib/tree/option/item/tree-option-item.component.html
- packages/ng/libraries/core/src/lib/tree/option/item/tree-option-item.component.ts
- packages/ng/libraries/core/src/lib/tree/option/item/tree-option-item.model.ts
- packages/ng/libraries/core/src/lib/tree/option/picker/index.ts
- packages/ng/libraries/core/src/lib/tree/option/picker/tree-option-picker.component.html
- packages/ng/libraries/core/src/lib/tree/option/picker/tree-option-picker.component.scss
- packages/ng/libraries/core/src/lib/tree/option/picker/tree-option-picker.component.ts
- packages/ng/libraries/core/src/lib/tree/option/picker/tree-option-picker.model.ts
- packages/ng/libraries/core/src/lib/tree/option/picker/tree-option-picker.module.ts
- packages/ng/libraries/core/src/lib/tree/option/tree-option.module.ts
- added tree-picker component to handle all the different methods of selection on a tree
- tree-option-item does not preovide a `ALuOptionItem`, so you cant use it in an option picker - i did that so that you dont have a different comportment when you embedded tree options in option picker and in tree picker (in an option picker, selecting a node would only select the node, not all the children too)
> Poc.tree.picker

- packages/ng/applications/sandbox/src/app/issues/poc-modal/poc-modal.component.ts
- packages/ng/libraries/core/src/lib/overlay/modal/modal-panel.component.html
- packages/ng/libraries/core/src/lib/overlay/modal/modal-panel.component.ts
- packages/ng/libraries/core/src/lib/overlay/modal/modal.model.ts
- packages/ng/libraries/core/src/lib/overlay/modal/modal.translate.ts
- packages/ng/tsconfig.json
@GuillaumeNury - i did what you said about the labels for the buttons in the modal footer
- there's a default for each one, linked to a trad key so you can override it by providing your own trad
- or you can specify a `submitLabel` and `cancelLabel` for the component you want to inject in the modal
> Modal.some.enhancements

- packages/ng/libraries/core/src/style/components/_popup.scss
- packages/ng/libraries/core/src/style/components/_sidepanel.scss
- packages/ng/libraries/core/src/style/theme/_popup.theme.scss
Adds sizing for modals/popup
Adds scrollblock from cdk
Changes scroll strategy in the sidepanel where the header scrolls with the content. It avoids craming the scroll between to heavy blocks.
> [add] Scroll block and scroll in sidepanel

- package-lock.json
- packages/ng/applications/sandbox/src/app/issues/issues.router.ts
- packages/ng/applications/sandbox/src/app/issues/node-sass-end/index.ts
- packages/ng/applications/sandbox/src/app/issues/node-sass-end/node-sass-end.component.html
- packages/ng/applications/sandbox/src/app/issues/node-sass-end/node-sass-end.component.ts
- packages/ng/applications/sandbox/src/app/issues/node-sass-end/node-sass-end.module.ts
- packages/ng/libraries/core/package.json
- packages/ng/libraries/material/src/style/components/_datepicker.scss
- packages/ng/libraries/material/src/style/components/_menu.scss
- packages/ng/libraries/material/src/style/components/_options.scss
- packages/ng/package-lock.json
- packages/ng/package.json
- packages/scss/.browserslistrc
- packages/scss/gulpfile.js
- packages/scss/package-lock.json
- packages/scss/package.json
- packages/scss/src/components/_grid.scss
- packages/scss/src/theming/components/_main.theme.scss
i did this branch where i removed everything related to node-sass
- package scss now builds with `gulp-dart-sass` that uses the npm package `sass`
- package ng - removed dependency and peer dep to node-sass
so now when you use `npm start` in packasge `scss`, it works the same but uses `sass` and not `node-sass`
also when you use `npm start` in package `ng`, it builds with `sass`. as a result it doesn't build cuz of some `Compound selector` in `@lucca-front/ng/material` stylesheet. but once all bugs are ironed out it will build
@sanlucca i let you finish this while i'm on vacation
------
fixes #652
> Rem node sass

- packages/ng/applications/sandbox/src/app/issues/fix-modal/fix-modal.component.html
- packages/ng/applications/sandbox/src/app/issues/fix-modal/fix-modal.component.ts
- packages/ng/applications/sandbox/src/app/issues/fix-modal/fix-modal.module.ts
- packages/ng/applications/sandbox/src/app/issues/fix-modal/index.ts
- packages/ng/applications/sandbox/src/app/issues/issues.router.ts
- packages/ng/libraries/core/src/lib/overlay/modal/modal.module.ts
- packages/ng/libraries/core/src/lib/overlay/modal/modal.service.ts
- packages/ng/libraries/core/src/lib/overlay/modal/modal.token.ts
- packages/ng/libraries/core/src/lib/overlay/sidepanel/sidepanel.module.ts
- packages/ng/libraries/core/src/lib/overlay/sidepanel/sidepanel.service.ts
- packages/ng/libraries/core/src/lib/overlay/sidepanel/sidepanel.token.ts
the way the injection was handled, the factory creating modalRef depended on what module you imported
- if you imported `LuModalModule` then `LuModal.open(...)` opened modals :+1:
- if you imported `LuOverlayModule` then `LuModal.open(...)` opened sidepanels :-1:
> Fix modal/sidepanel

- packages/ng/applications/sandbox/src/app/issues/issues.router.ts
- packages/ng/applications/sandbox/src/app/issues/modals-no-submit/index.ts
- packages/ng/applications/sandbox/src/app/issues/modals-no-submit/modals-no-submit.component.html
- packages/ng/applications/sandbox/src/app/issues/modals-no-submit/modals-no-submit.component.ts
- packages/ng/applications/sandbox/src/app/issues/modals-no-submit/modals-no-submit.module.ts
- packages/ng/libraries/core/src/lib/overlay/modal/modal-panel.component.html
- packages/ng/libraries/core/src/lib/overlay/modal/modal-panel.component.ts
- packages/ng/libraries/core/src/lib/overlay/sidepanel/sidepanel-panel.component.html
hides the submit button in modal/sp footer if the user hasnt provided a submit action
https://687-pr-lucca-front-luccasa.surge.sh/ng/#/modals-no-submit - modal/sp opens with no `ok` button
https://687-pr-lucca-front-luccasa.surge.sh/ng/#/fix-modal - modal/sp has a open button
> modal-sidepanel - hide submit button

- packages/ng/applications/sandbox/src/app/issues/issues.router.ts
- packages/ng/applications/sandbox/src/app/issues/select-overlap/index.ts
- packages/ng/applications/sandbox/src/app/issues/select-overlap/select-overlap.component.html
- packages/ng/applications/sandbox/src/app/issues/select-overlap/select-overlap.component.ts
- packages/ng/applications/sandbox/src/app/issues/select-overlap/select-overlap.module.ts
- packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
with the refactor of the popovers, it was not possible anymore to make  the picker of a select overlap its input. now its possible again
was used in [prisme](http://prisme.lucca.io/home) for the search bar
> [fix] Select picker overlap

- .travis.yml
- packages/ng/applications/sandbox/src/app/issues/fix-705-select-enter/fix-705-select-enter.component.html
- packages/ng/applications/sandbox/src/app/issues/fix-705-select-enter/fix-705-select-enter.component.ts
- packages/ng/applications/sandbox/src/app/issues/fix-705-select-enter/fix-705-select-enter.module.ts
- packages/ng/applications/sandbox/src/app/issues/fix-705-select-enter/index.ts
- packages/ng/applications/sandbox/src/app/issues/issues.router.ts
- packages/ng/libraries/core/src/lib/option/picker/option-picker-advanced.component.html
- packages/ng/libraries/core/src/lib/option/picker/option-picker.component.html
- packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
- packages/ng/libraries/core/src/lib/tree/option/picker/tree-option-picker-advanced.component.html
- packages/ng/libraries/core/src/lib/tree/option/picker/tree-option-picker.component.html
as stated in the issue, the problem was that the select-input stopped propagation of event `keydown.enter`.
solution was to stop propagation only when the picker wasnt already opened
> due to the fact that the select-input opens on `enter` and stops propagation - [see code](https://github.com/LuccaSA/lucca-front/blob/master/packages/ng/libraries/core/src/lib/select/input/select-input.component.ts#L109)
>
> and when a basic option picker is opened, the select-input stays focuesd, so the `keydown.enter` event is stopped.
>
> but when you open an advanced option picker with a searcher, the focus is passed to the search input, so the `keydown.enter` is caught by the overlay
----
fixes #705
> Fix/705.option picker.keyboard.selection

- packages/ng/libraries/core/src/lib/api/select/feeder/api-feeder.component.ts
api-feeder didnt provide itself as onopen subscriber, so nothing happened when picker opened
------
fixes #729
> [fix] api-feeder 

- packages/ng/libraries/core/src/lib/tree/option/picker/index.ts
add missing export for a clean override of tree picker
> tree-picker add missing exports for override

- packages/ng/applications/sandbox/src/app/issues/issues.router.ts
- packages/ng/applications/sandbox/src/app/issues/user-select-homonyms/index.ts
- packages/ng/applications/sandbox/src/app/issues/user-select-homonyms/user-select-homonyms.component.html
- packages/ng/applications/sandbox/src/app/issues/user-select-homonyms/user-select-homonyms.component.ts
- packages/ng/applications/sandbox/src/app/issues/user-select-homonyms/user-select-homonyms.module.ts
- packages/ng/libraries/core/src/lib/user/select/homonyms/index.ts
- packages/ng/libraries/core/src/lib/user/select/homonyms/user-homonyms.component.ts
- packages/ng/libraries/core/src/lib/user/select/homonyms/user-homonyms.module.ts
- packages/ng/libraries/core/src/lib/user/select/homonyms/user-homonyms.service.ts
- packages/ng/libraries/core/src/lib/user/select/index.ts
- packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.html
- packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.scss
- packages/ng/libraries/core/src/lib/user/select/input/user-select-input.module.ts
- packages/ng/libraries/core/src/lib/user/select/user-select.module.ts
- packages/ng/libraries/core/src/lib/user/user.model.ts
fixes #413 
when the user-select must displays 2 homonyms, it'll display an additional information to differentiate them
@sanlucca i need some polish on it
before merging, must replace this dev lines
https://github.com/LuccaSA/lucca-front/compare/rc...feat/homonyms?expand=1#diff-28d9955c4f0b225b531ef382c7a83f84R21
```ts
//  temp - match homonyms on initials to get more homonyms match in dev mode
// private _format = LuDisplayFullname.lastfirst;
private _format = LuDisplayInitials.lastfirst;
```
> Feat - homonyms

- packages/ng/libraries/formly/src/lib/types/radios.html
i'll add an input type `button group` or something, but when the user want radio buttons, we should display radio buttons
alos what it did is display radios if less than 3 options, and display a button group for 3 or more option and i kinda feel it should be the orther way around
> formly-radio - always use radio fields

- packages/ng/libraries/core/src/lib/tree/option/item/tree-option-item.translate.ts
Fixes a small typo in the default translations for `LU_TREE_OPTION_ITEM_TRANSLATIONS`
> [fix] typo in luTreeOptionItemTranslations

- packages/scss/src/components/inputs/textfield/_textfield.scss
> fix textfield mod white focus style

- packages/scss/src/components/_table.scss
fix #850 
A vertical align middle should be defined (for a div / a structure)
> [table] table-body-row-cell alignment

- packages/ng/applications/sandbox/src/app/issues/split-select/split-select.component.html
- packages/ng/applications/sandbox/src/app/issues/split-select/split-select.component.ts
- packages/ng/applications/sandbox/src/app/issues/split-select/split-select.module.ts
- packages/ng/libraries/select/src/lib/input/select-input.component.ts
- packages/ng/libraries/select/src/lib/input/select-input.model.ts
- select wasnt flagged as touched when closing the picker via click outside
- changed contentquery to find the clearer to static false to allow for adding a ngif on it
> [fix] select touched

- packages/ng/applications/sandbox/src/app/issues/issues.router.ts
- packages/ng/applications/sandbox/src/app/issues/option-comparer/index.ts
- packages/ng/applications/sandbox/src/app/issues/option-comparer/option-comparer.component.html
- packages/ng/applications/sandbox/src/app/issues/option-comparer/option-comparer.component.ts
- packages/ng/applications/sandbox/src/app/issues/option-comparer/option-comparer.module.ts
- packages/ng/libraries/api/src/lib/select/input/api-select-input.component.html
- packages/ng/libraries/api/src/lib/select/input/api-select-input.component.ts
- packages/ng/libraries/department/src/lib/select/input/department-select-input.component.html
- packages/ng/libraries/department/src/lib/select/input/department-select-input.component.ts
- packages/ng/libraries/option/src/lib/picker/option-picker.component.ts
- packages/ng/libraries/option/src/lib/picker/option-picker.model.ts
- packages/ng/libraries/option/src/lib/picker/tree-option-picker.component.ts
- packages/ng/libraries/user/src/lib/select/input/user-select-input.component.html
- packages/ng/libraries/user/src/lib/select/input/user-select-input.component.ts
To detect which option are selected, there is a comparison of JSON values. When using API/User Select, it is more safe to compare options by id.
This PR add a new input to pass something like `(o1, o2) => o1.id === o2.id`.
If we want to go further, feeders could provide a comparer that would be used by picker.
API/Users feeder could provide a ByIdOptionComparer. When no comparer are provided, we can stick to the JSON comparer.
> [add] optionComparer input on option-pickers

- packages/ng/applications/sandbox/src/app/issues/ivy-option-picker/ivy-option-picker.module.ts
- packages/ng/libraries/api/src/lib/select/input/api-select-input.component.ts
- packages/ng/libraries/date/src/lib/select/date-select-input.component.ts
- packages/ng/libraries/department/src/lib/select/input/department-select-input.component.ts
- packages/ng/libraries/select/src/lib/input/select-input.component.ts
- packages/ng/libraries/user/src/lib/select/input/user-select-input.component.ts
depending on if ivy is enabled or not, the order in which `@contenChild` and `@ViewChild` query are executed changes and it is source of bug because i over relied on `get/set` (fyi - it was the source of the bugs that caused me to panicked when i tried to migrate to ng 9 + ivy)
now i rely on _official_ life-cycle hooks to initialise my components
----
[ici](http://lucca-front.lucca.local/rc/ng/#/split-select) on peut voir que le custom displayer est ignore alors que [la](http://lucca-front.lucca.local/PR-966/ng/#/split-select) il remarche
> [fix] select - custom displayer

- packages/ng/.angular.json
- packages/ng/applications/sandbox/tsconfig.es5.json
- packages/ng/libraries/date/src/lib/calendar/calendar-input.component.scss
- packages/ng/libraries/root/src/style/_theming.overridable.scss
- packages/ng/libraries/root/src/style/_theming.scss
- packages/ng/libraries/root/src/style/theme/_calendar.theme.scss
- packages/ng/package.json
Leaves out grid for a flex display to make it usable on IE11.
Fixes #995
> [Fix] Calendar style on IE11

- packages/ng/applications/sandbox/src/app/issues/dropdown/dropdown.component.html
- packages/ng/libraries/dropdown/src/lib/item/dropdown-item.directive.ts
- packages/ng/libraries/dropdown/src/lib/item/dropdown-item.model.ts
- packages/ng/libraries/dropdown/src/lib/panel/dropdown-panel.component.ts
- focus first dropdown item at dropdown opening to allow the user to navigate it via `tab` without having to go through the rest of the page
- refocus trigger button on dropdown close
> [fix] dropdown focus comportment

- packages/ng/applications/sandbox/src/app/issues/issues.router.ts
- packages/ng/applications/sandbox/src/app/issues/overlays-events/index.ts
- packages/ng/applications/sandbox/src/app/issues/overlays-events/overlays-events.component.html
- packages/ng/applications/sandbox/src/app/issues/overlays-events/overlays-events.component.ts
- packages/ng/applications/sandbox/src/app/issues/overlays-events/overlays-events.module.ts
- packages/ng/applications/sandbox/src/app/issues/refacto-overlay-advanced/refacto-overlay-advanced.component.html
- packages/ng/applications/sandbox/src/app/issues/refacto-overlay-advanced/refacto-overlay-advanced.component.ts
- packages/ng/libraries/dropdown/src/lib/trigger/dropdown-trigger.directive.ts
- packages/ng/libraries/popover/src/lib/trigger/popover-trigger.directive.ts
- packages/ng/libraries/popover/src/lib/trigger/popover-trigger.model.ts
- packages/ng/libraries/select/src/lib/input/select-input.component.ts
- packages/ng/libraries/tooltip/src/lib/trigger/tooltip-trigger.directive.ts
added outputs on popover _triggers_ that emits when the panel opens or closes
popover trigger
```ts
@Directive({
selector: '[luPopover]',
})
export class LuPopoverTriggerDirective {
@Output('luPopoverOnOpen') onOpen = new EventEmitter<void>();
@Output('luPopoverOnClose') onClose = new EventEmitter<void>();
```
```html
<button [luPopover]="asdas" (luPopoverOnOpen)="onOpen()" (luPopoverOnClose)="onClose()">click me</button>
```
dropdown trigger
```ts
@Directive({
selector: '[luDropdown]',
})
export class LuDropdownTriggerDirective {
@Output('luDropdownOnOpen') onOpen = new EventEmitter<void>();
@Output('luDropdownOnClose') onClose = new EventEmitter<void>();
```
tooltip-trigger
```ts
@Directive({
selector: '[luTooltip]',
})
export class LuTooltipTriggerDirective {
@Output('luTooltipOnOpen') …
```
> [Fix] ng popover events

- packages/ng/applications/sandbox/src/app/issues/date-granularity/date-granularity.component.html
- packages/ng/applications/sandbox/src/app/issues/date-granularity/date-granularity.component.ts
- packages/ng/applications/sandbox/src/app/issues/date-granularity/date-granularity.module.ts
- packages/ng/applications/sandbox/src/app/issues/date-granularity/index.ts
- packages/ng/applications/sandbox/src/app/issues/date-input/date-input.component.html
- packages/ng/applications/sandbox/src/app/issues/date-input/date-input.module.ts
- packages/ng/applications/sandbox/src/app/issues/issues.router.ts
- packages/ng/libraries/core/src/lib/date/date-adapter.class.ts
- packages/ng/libraries/core/src/lib/date/date-adapter.interface.ts
- packages/ng/libraries/core/src/lib/date/native/native-date.adapter.ts
- packages/ng/libraries/date/src/lib/calendar/calendar-input.component.ts
- packages/ng/libraries/date/src/lib/input/date-input.directive.ts
- packages/ng/libraries/date/src/lib/input/date-input.translate.ts
- packages/ng/libraries/date/src/lib/picker/date-picker.component.html
- packages/ng/libraries/date/src/lib/picker/date-picker.component.ts
- packages/ng/libraries/date/src/lib/select/date-select-input.component.html
- packages/ng/libraries/date/src/lib/select/date-select-input.component.ts
- packages/ng/libraries/date/src/lib/select/date-select-input.intl.ts
- packages/ng/libraries/date/src/lib/select/date-select-input.module.ts
- packages/ng/libraries/date/src/lib/select/date-select-input.token.ts
- packages/ng/libraries/date/src/lib/select/date-select-input.translate.ts
add `@Input() granularity` to 
- lu-date-select component
- lu-date-picker component
- lu-calendar component
- [luDateInput] directive
to allow the end user to only select a month or a year, not necessarily a date
fixes #1026
-----
left to do
_should just display "2021", not "Jan 1, 2021"_
> [ng] date inputs - add granularity option

- packages/ng/libraries/api/src/lib/select/searcher/api-searcher.component.ts
- packages/ng/libraries/api/src/lib/select/searcher/api-searcher.model.ts
- packages/ng/libraries/option/src/lib/picker/option-picker-advanced.component.html
- packages/ng/libraries/option/src/lib/picker/option-picker-advanced.component.ts
- packages/ng/libraries/option/src/lib/picker/tree-option-picker-advanced.component.html
- packages/ng/libraries/option/src/lib/picker/tree-option-picker-advanced.component.ts
- packages/ng/libraries/root/src/style/components/_picker.scss
- packages/ng/libraries/user/src/lib/select/searcher/user-searcher.component.ts
fixes #1040 
@vvalentin-lucca i need some stylin done because i had to change the way the loading placeholder is handled in option-picker advanced
_before_
```html
<ng-content *ngIf="!(loading$ | async); else loading"></ng-content>
<ng-template #loading>	
<div class="lu-picker-loading loading mod-block"></div>	
</ng-template>
```
_after_
```html
<ng-content [class.is-loading]="loading$ | async"></ng-content>
```
> [ng] api-select - rework to force refresh on open

- packages/scss/src/utilities/_spacing.scss
The variable was not restored to its original state and that was causing problems.
Before:
```
.u-marginLeftSmall {
marginleft: 1rem !important;
}
```
After:
```
.u-marginLeftSmall {
margin-left: 1rem !important;
}
```
All the code generated is here (and is passed to the CSS validator): https://codepen.io/vincent-valentin/pen/BajxNzx?editors=0100
> Fix hyphen

- packages/scss/src/components/_chips.scss
- packages/scss/src/theming/_components.scss
- packages/scss/src/theming/components/_chips.theme.scss
> [FIX] Hover State for chip kill

- packages/scss/demo/demo.css
- packages/scss/src/components/_action-icon.scss
- packages/scss/src/components/_button.scss
- packages/scss/src/components/inputs/radio-buttons/_radio-buttons.scss
`actionIcon`:
- better centering
- margin only if sibling 
- focus state
- focus state for palettes
- `mod-invert` fixed
- focus state for `mod-invert`
`button`:
- focus for `button-group`
- focus for `is-success` and `is-error`
- `mod-invert` fixed
- focus state for `mod-invert`
-----
-----
> Focus for actionIcon, button-group and button states

- packages/scss/src/theming/_palettes.scss
White and black "colors" wasn't used so we couldn't see it crashing.
> [SCSS][fix] white and black colors needs to be a map with color

- packages/ng/libraries/api/src/lib/select/searcher/api-searcher.component.html
- packages/ng/libraries/api/src/lib/select/searcher/api-searcher.component.ts
- packages/ng/libraries/api/src/lib/select/searcher/api-searcher.model.ts
- packages/ng/libraries/option/src/lib/picker/option-picker-advanced.component.html
- packages/ng/libraries/option/src/lib/picker/option-picker-advanced.component.ts
- packages/ng/libraries/root/src/style/components/_picker.scss
- packages/ng/libraries/user/src/lib/select/searcher/user-searcher.component.html
- packages/ng/libraries/user/src/lib/select/searcher/user-searcher.component.ts
after #1063, when an api-select opened we forced refresh but kept the old results (or the placeholder) visible.
with this fix we force a recompute of the loading state and hide current results behind teh loader
> [fix] api-select on open loading placeholder

- packages/ng/libraries/date/src/lib/input/date-input.translate.ts
The date input should now display the date in the right format in British English despite the injected `en-GB` `localeId`.
> Add en-GB date format

- packages/scss/demo/components/mixins.html
- packages/scss/demo/demo.css
- packages/scss/src/_typo.scss
- packages/scss/src/components/_container.scss
- packages/scss/src/components/_section.scss
- packages/scss/src/mixins/_responsiveness.scss
- packages/scss/src/utilities/_misc.scss
- At a given breakpoint, `media_smaller_than` and `media_larger_than` were triggered at the same time.
- Add font-weight for `strong` and `u-wrap` class.
-----
Before: 
https://codepen.io/vincent-valentin/pen/PoZRKwG
-----
After:
https://codepen.io/vincent-valentin/pen/PoZRKNb
> Fix overlapping breakpoints + u-wrap

- packages/scss/demo/components/cards.html
- packages/scss/src/components/_card.scss
- packages/scss/src/theming/components/_card.theme.scss
Cards now have a border and no elevation. Previous style is available with a .mod-elevated
> [add] Border card and mod elevate

- packages/scss/src/components/inputs/field/_field.scss
The native error handling in HTML 5 does not have the desired behaviour with custom styles, so we remove it.
> fix(scss) field invalid state

- packages/scss/.browserslistrc
This pull request set scss package autoprefixer browserlist option to defaults. The objective is to reduce dist size.
fixes #1188
> feat(scss) optimize SCSS dist size by using autoprefixer options

- packages/ng/applications/sandbox/src/app/issues/date-select-enh/date-select-enh.component.html
- packages/ng/applications/sandbox/src/app/issues/date-select-enh/date-select-enh.component.ts
- packages/ng/applications/sandbox/src/app/issues/date-select-enh/date-select-enh.module.ts
- packages/ng/applications/sandbox/src/app/issues/date-select-enh/index.ts
- packages/ng/applications/sandbox/src/app/issues/issues.router.ts
- packages/ng/applications/sandbox/src/app/issues/select-option-placeholder/select-option-placeholder.component.ts
- packages/ng/libraries/date/src/lib/calendar/calendar-input.component.html
- packages/ng/libraries/date/src/lib/calendar/calendar-input.component.ts
- packages/ng/libraries/date/src/lib/calendar/calendar-item.class.ts
- packages/ng/libraries/date/src/lib/calendar/calendar-item.interface.ts
- packages/ng/libraries/date/src/lib/picker/date-picker.component.html
- packages/ng/libraries/date/src/lib/picker/date-picker.component.ts
- packages/ng/libraries/date/src/lib/select/date-select-input.component.html
- packages/ng/libraries/date/src/lib/select/date-select-input.component.ts
partially fixes #1184 
fixes #1027
- use `disabled` instead of `class.is-disabled` to disable days in the calendar input when they are outside the min-max period
- add `startOn` input on calndar zand date-select comps to open the calendar on a specific date
> feat(ng-date) date-inputs - better disabling - startOn

- packages/scss/src/components/_callout.scss
Instead of redefining the colors from the palettes, one inherits directly from the current color.
> fix(scss) callout icon color

- packages/ng/libraries/root/src/style/components/_popup.scss
fixes #1047 
Modals are now fullscreen on mobile.
> fix(ng-popup) max-size responsiveness

- packages/ng/libraries/modal/src/lib/modal-panel.component.html
- packages/ng/libraries/sidepanel/src/lib/sidepanel-panel.component.html
nobody uses it, and its ugly anyway
> ref(ng-modal|sp) hide the error thingy in the modal|sidepanel footer

- packages/icons/src/_font.scss
Apply the property to the document, not to the font.
> fix(icons) font smoothing

- packages/scss/src/components/inputs/textfield/_textfield.scss
Fix, remove box-shadow none from textfield.mod-filter, for accessibility
> fix(scss) remove box-shadow none from textfield mod-filter

- packages/ng/libraries/date/src/lib/calendar/calendar-input.component.html
- packages/ng/libraries/date/src/lib/calendar/calendar-input.component.ts
- packages/ng/libraries/establishment/src/lib/select/select-all/establishment-select-all.translate.ts
- packages/ng/libraries/option/src/lib/selector/all/select-all.translate.ts
- packages/ng/libraries/root/src/style/components/_popup.scss
- add es, de, pt translations for `select all / deselect all`
- prevent the calendar-input from going to unsupported granularity
- scss autoprefixer warning due to `fill-available` used in class .lu-modal-panel
fix #1249 
fix #1250
fix #1235
> fix(ng) quick fixes

- packages/ng/applications/sandbox/src/app/issues/user-select-homonyms/user-select-homonyms.component.html
- packages/ng/applications/sandbox/src/app/issues/user-select-homonyms/user-select-homonyms.component.ts
- packages/ng/libraries/user/src/lib/picture/user-picture.component.ts
- packages/ng/libraries/user/src/lib/user.model.ts
allows the `lu-user-picture` to fallback from user.picture.href to user.pictureHref because _some_ user apis give this info like that
> fix(ng) user picture fallback

- packages/ng/applications/sandbox/src/app/issues/refacto-tooltip/refacto-tooltip.component.html
- packages/ng/applications/sandbox/src/app/issues/refacto-tooltip/refacto-tooltip.component.ts
- packages/ng/applications/sandbox/src/app/issues/refacto-tooltip/refacto-tooltip.module.ts
- packages/ng/applications/sandbox/src/app/issues/refactor-select/refactor-select.component.html
- packages/ng/applications/sandbox/src/app/issues/refactor-select/refactor-select.component.ts
- packages/ng/applications/sandbox/src/app/issues/refactor-select/refactor-select.module.ts
- packages/ng/libraries/dropdown/src/lib/trigger/dropdown-trigger.directive.ts
- packages/ng/libraries/popover/src/lib/trigger/popover-trigger.directive.ts
- packages/ng/libraries/select/src/lib/input/select-input.component.ts
- packages/ng/libraries/select/src/lib/input/select-input.model.ts
- packages/ng/libraries/tooltip/src/lib/trigger/tooltip-trigger.directive.ts
destroying a select was calling `closePopover` (even if popover wasnt opened and closePopover was marking the control as `touched`. now we close the popover if it was opened - very big brain solution
fix #1255 
all popover-triggers and extensions (tooltip, dropdown, select) were not properly cleaning their subscription, as a result a popover or tooltip could be triggered to appear _after_ its trigger had been destroyed
fix #1259
> fix(ng) tooltip and select shenanigans

- packages/ng/libraries/establishment/src/lib/select/input/establishment-select-input.component.ts
- packages/ng/libraries/establishment/src/lib/select/legal-unit-selector/legal-unit-selector.directive.ts
Fixes a bug where the same value was selected more than once by the establishment picker
[HUB-3287]
[HUB-3287]: https://luccasoftware.atlassian.net/browse/HUB-3287
> fix(ng) establishment-picker selects the same value more than once

- packages/ng/libraries/tooltip/src/lib/panel/tooltip-panel.component.html
- packages/ng/libraries/tooltip/src/lib/trigger/tooltip-trigger.directive.ts
During a guild workshop, we dived into how to make our tooltip accessible (following this French doc on the subject https://www.accede-web.com/notices/interface-riche/infobulles-personnalisees/):
> feat(ng-tooltip) Accessible tooltip

- packages/scss/src/components/inputs/checkbox/_checkbox.scss
- stories/scss/form/checkbox/checkbox.stories.html
- stories/scss/form/checkbox/checkbox.stories.ts
closes #1290
Added a line for better feedback to assistive technologies (avoiding [a bug with Safari](https://bugs.webkit.org/show_bug.cgi?id=203138) that can't do it on the input).
fix #1285
see ?path=/story/scss-form-checkboxes--basic for reference html dom to have for mixed cb
> feat(scss-a11y) better a11y for checkbox mixed

- packages/ng/tooltip/src/lib/trigger/tooltip-trigger.directive.ts
- stories/ng/popover/popover.stories.ts
- stories/ng/tooltip/tooltip.stories.html
- stories/ng/tooltip/tooltip.stories.ts
better handling of the focus by the tooltip trigger
- if it's on an element natively focusable (button, a, ...) or already with a tabindex, the tooltip trigger doesn't try to touch the focusability of the tag
- if it's on a non focusable dom element, it adds a tabindex=0 _only when not disabled_
fixes #1294 (i hope)
> fix(ng-tooltip) tooltip focus handling

- packages/scss/src/components/_box.scss
The arrow was sometimes badly positioned with the calculation on its size.
> fix(scss) Box - better positioning of the arrow

- README.md
- demo/index.html
- packages/ng/material/src/style/components/_dialog.scss
- packages/ng/root/src/style/components/_popup.scss
- packages/scss/src/components/_container.scss
- packages/scss/src/components/_error-page.scss
- packages/scss/src/components/_grid.scss
- packages/scss/src/components/_header.scss
- packages/scss/src/components/_layout.scss
- packages/scss/src/components/_nav-side.scss
- packages/scss/src/components/_section.scss
- packages/scss/src/theming/_breakpoints.scss
- packages/scss/src/theming/_commons.scss
- packages/scss/src/theming/components/_container.theme.scss
- stories/qa/container/container.stories.html
- stories/qa/grid/grid.stories.html
- to-migrate/ng/drag-drop/drag-drop.component.html
- to-migrate/scss/components/containers.html
- to-migrate/scss/components/forms/forms-checkboxes.html
- to-migrate/scss/components/forms/forms-files.html
- to-migrate/scss/components/forms/forms-framed.html
- to-migrate/scss/components/forms/forms-radios.html
- to-migrate/scss/components/forms/forms-switches.html
- to-migrate/scss/components/forms/forms-textfields.html
- to-migrate/scss/components/grids.html
- to-migrate/scss/components/templates.html
- to-migrate/scss/demo.css
- to-migrate/scss/lucca-front.css
- to-migrate/scss/templates/form.html
- Container's refactoring;
- modification and addition of breakpoints.
For the record:
- new `xxxs` breakpoint at **320px**;
- new `xxs` breakpoint at **480px**;
- renaming of breapoint `sm` (576px) to `xs` now at **640px**;
- renaming of breapoint `md` (768px) to `s` now at **800px**;
- renaming of breapoint `lg` (992px) to `m` now at **1024px**;
- renaming of breapoint `xl` (1200px) to `l` now at **1280px**;
- renaming of breapoint `xxl` (1250px) to `xl` now at **1366px** (the old `xl` was 1200px);
- renaming of breapoint `xxxl` (1500px) to `xxl` now at **1600px** (the old `xxl` was 1250px);
- new `xxxl` breakpoint at **1920px** (the old `xxxl` was 1500px).
Old: https://codepen.io/vincent-valentin/full/vYLaJNv
New: https://codepen.io/vincent-valentin/full/abdKBLz
[Migration guidelines …
> refactor(scss) responsive container and breakpoints

- packages/scss/src/components/_callout.scss
- packages/scss/src/theming/components/_callout.theme.scss
- stories/qa/callout/callout.stories.html
- stories/qa/callout/callout.stories.ts
> feat(scss) Callout

- packages/ng/popover/src/lib/trigger/popover-trigger.model.ts
- packages/ng/tooltip/src/lib/trigger/tooltip-trigger.directive.ts
- stories/ng/popover/popover.stories.ts
fixes #1393 
popover triggers `hover` and `focus` now act the same because js events focus and hover should be understood as 2 ways to represent the same end user interaction with the element
so a popover with trigger `hover` will open when the trigger is focused, and a popover with the `focus` trigger will appear when hovered
> feat(ng-a11y) popover triggers

- packages/ng/api/src/lib/service/api-v4.service.ts
- packages/ng/establishment/src/lib/select/input/establishment-select-input.component.html
- packages/ng/establishment/src/lib/select/input/establishment-select-input.component.ts
- packages/ng/establishment/src/lib/service/index.ts
- packages/ng/establishment/src/lib/service/legal-unit-service.model.ts
- packages/ng/establishment/src/lib/service/legal-unit.service.ts
- packages/ng/select/src/lib/input/select-input.model.ts
- stories/ng/establishment-select/establishment-select.stories.ts
Establishment picker: do not display nor group by legal units when they are not used by the tenant.
A tenant is considered not using the legal units when there is either only one LU, only one establishment, or the same number of LUs and establishments.
- [issue #1318](https://github.com/LuccaSA/lucca-front/issues/1318) - ets-select - better display for small tenants
[HUB-3353]
[HUB-3353]: https://luccasoftware.atlassian.net/browse/HUB-3353
> feat(ng-ets) Do not group by legal unit if not usefull

- packages/ng/user/src/lib/select/input/user-select-input.component.html
- packages/ng/user/src/lib/select/me/me-option.directive.ts
- stories/ng/user/select/user-select.stories.ts
it wont work when one of the filter applied is `id=notequal,1,2,3`, that just breaks the user-select
> fix(ng-user) me-first directive wasnt applying the filters of the user-select

- package-lock.json
- package.json
- packages/scss/src/_typo.scss
The top margins of titles were no longer redefined and inherited normalize.
> Fix margins for titles

- packages/ng/material/src/style/main-v11.overridable.scss
- packages/ng/material/src/style/main-v11.scss
- packages/ng/material/src/style/main.overridable.scss
- packages/ng/material/src/style/main.scss
LF overrides @angular/material typography using [v11 syntax](https://v11.material.angular.io/guide/typography).
This PR uses [v12+ syntax](https://material.angular.io/guide/typography).
As LF has to be compatible with Angular v11 and v12, two new SCSS entry point have been added. When using Angular 11 with LF 7 : 
```scss
/* Before */
@import "~@lucca-front/ng/material/style/main.overridable.scss";
/* After*/
@import "~@lucca-front/ng/material/style/main-v11.overridable.scss";
```
> fix(ng/material) use v12 syntax for @angular/material theming

- gulpfile.js
- packages/ng/root/package.json
- packages/ng/schematics/collection.json
- packages/ng/schematics/ng-add/file-content.ts
- packages/ng/schematics/ng-add/index.ts
- packages/ng/schematics/ng-add/tasks.ts
- packages/ng/schematics/tsconfig.json
Add support for `ng add @lucca-front/ng` in order to quickly install LF using @angular/cli.
This command :
- Adds `@lucca-front/ng`
- Adds `@lucca-front/icons`
- Adds `@lucca-front/scss`
- Updates `styles.scss` with
```scss
$noCssVar: true;
@import '~@lucca-front/scss/src/main.overridable'
, '~@lucca-front/ng/style/main.overridable.scss'
, 'scss/shame';
:root {
@include generateCSSVarsFromTheme($theme);
}
```
- Adds empty `scss/_shame.scss`
- Adds `stylePreprocessorOptions` in `angular.json`
- Adds `src/scss/overrides/_palettes.override.scss` with default palette
> feat(root): add ng-add schematic

- packages/scss/src/_typo.scss
Custom styles should be able to override the library's original values.
> fix(scss) remove !important on margin-bottom and color values

- packages/ng/material/src/style/main.overridable.scss
- packages/ng/material/src/style/main.scss
PR #1428 used `mat.core` mixin, importing all the style from material. We replace it with the mixin `mat.all-component-typographies()` which is the correct update of the deprecated code.
> [NG][FIX] Stop importing all of material CSS

- packages/scss/src/components/_action-icon.scss
- stories/qa/icon/icon.stories.html
Uses `grey 500` as color for icons on `.actionIcon[disabled]` instead of lowering the button's opacity:
- fixes display issues for `.actionIcon` in tables
- sets icon color to `grey 500` even when `.palette-*` has been added
> fix(scss) switch to grey palette for disabled state

- packages/scss/src/components/_table.scss
Fixes display issues on `.table.mod-card`:
- broken border radius
- double bottom border
-----
> Fix(scss) table mod card double border and radius

- packages/scss/src/components/_main.scss
Include banner height on margin-top
-----
Before
After
> [FIX] Navside margin top with banner

- packages/scss/src/components/_form.scss
- packages/scss/src/components/inputs/field/_field.framed.scss
- packages/scss/src/components/inputs/textfield/_textfield.framed.scss
The grid background on the hover was not in accordance with the design system.
It is replaced by a more pronounced border color. 
A white background is also added to override the inherited background color of the fields outside the mod-framed.
-----
> FIX(scss) Hover states for fields in mod-framed

- packages/scss/src/components/_button.scss
- stories/scss/button/button-basic.stories.html
Fixes display for the `arrowSouth` icon in the `.button.mod-more` button.
-----
> fix(scss) .button.mod-more

- packages/scss/src/components/_nav-side.scss
The text is hidden so that it is not removed from the assistance tools.
> Mask the help text

- packages/ng/user/src/lib/select/input/user-select-input.component.html
- packages/ng/user/src/lib/select/input/user-select-input.component.ts
- packages/ng/user/src/lib/select/me/me-option.directive.ts
- packages/ng/user/src/lib/select/searcher/user-searcher.component.ts
* Stop displaying "me" option when clue is not empty (fix #1447)
* Do not display user twice (when current user is in options)
Before :
After :
-----
> feat(ng/user) MeOption improvements

- packages/scss/src/components/_breadcrumbs.scss
Sets correct `font-size` and `line-height` values for breadcrumbs links and removes `margin-bottom`.
-----
> fix(scss) breadcrumbs sizing and spacing

- packages/scss/src/components/inputs/checkbox/_checkboxesfield.scss
- packages/scss/src/components/inputs/radio/_radiosfield.scss
- stories/scss/form/framed/framed.stories.html
Adds support for the `fieldset` element in containers with the `.radiosfield` or `.checkboxesfield` classes.
-----
> fix(scss) display for fieldset in framed forms

- packages/scss/src/components/_form.scss
- packages/scss/src/components/inputs/checkbox/_checkbox.scss
- packages/scss/src/components/inputs/field/_field.scss
- packages/scss/src/components/inputs/radio/_radio.scss
- packages/scss/src/mixins/_forms.scss
- stories/scss/form/checkbox/checkbox.stories.html
- stories/scss/form/checkbox/checkbox.stories.ts
- stories/scss/form/framed/framed.stories.html
- stories/scss/form/framed/framed.stories.ts
- stories/scss/form/radio/radio.stories.html
- stories/scss/form/radio/radio.stories.ts
- stories/scss/form/textfields/textfield.stories.html
- stories/scss/form/textfields/textfield.stories.ts
Added support for the aria-required attribute in addition to the is-required class.
⚠️ No breaking change but it is still necessary to add the `is-required` class for the radio buttons.
Close #1540
> Aria-required support

- packages/scss/src/theming/_sizes.scss
Standard size is used as H4 and Body 1 (which lately diverged in Figma). 
Reducing the standard line height on LF impacted the height of multiple components (buttons, selects...)
For now we are reverting the standard line height but we should have 2 specifics values in the future.
> [Font size] fix standard

- packages/ng/api/src/lib/service/api-v4.service.ts
- packages/ng/formly/src/lib/types/api.html
- packages/ng/formly/src/lib/types/api.ts
Since the PR : https://github.com/LuccaSA/lucca-front/pull/1512, it is impossible to add api v4 sorting on formly api select because it is not using the `sort` property.
- Add the sort property in the formly api select component,
- Add a protection in api v4 select for nul sorting params
-----
> fix(ng) sorting in formly api select

- packages/scss/src/components/_action-icon.scss
- packages/scss/src/theming/components/_action-icon.theme.scss
- stories/documentation/actions/action-icon/action-icon-basic.stories.ts
https://user-images.githubusercontent.com/25581936/163575863-c3bbb183-deda-4290-85d8-f489e4e34931.mov
- Harmonize states with Figma
- Remove global palettes
- Use 1 overridable palette
- Add .mod-small
- Add .mod-delete 
Breaking : 
- Current default version is now .mod-small
- Palette should be replaced by a theme override if necessary
> [DS to LF] Action icon

- packages/ng/toast/ng-package.json
- packages/ng/toast/src/public-api.ts
- packages/ng/toast/src/toasts.component.html
- packages/ng/toast/src/toasts.component.ts
- packages/ng/toast/src/toasts.intl.ts
- packages/ng/toast/src/toasts.model.ts
- packages/ng/toast/src/toasts.module.ts
- packages/ng/toast/src/toasts.service.ts
- packages/ng/toast/src/toasts.token.ts
- packages/ng/toast/src/toasts.translate.ts
- packages/scss/src/components/_toasts.scss
- stories/documentation/overlays/toasts/toasts.stories.html
- stories/documentation/overlays/toasts/toasts.stories.ts
Generate toasts (with different types info, error, success, warning) thank to a service or input observables directly on the `lu-toast` . You can also switch the toast position (bottom, or top by default).
-----
https://user-images.githubusercontent.com/35571450/158795727-1215113b-ca2b-432d-b5a2-4c7681094305.mp4
-----
> feat(ng-toast) add toast generation

- packages/scss/src/components/_callout.scss
Supports `<button class="link">` in callouts.
> [callout] button.link support

- .eslintrc
- package-lock.json
- package.json
- packages/ng/title/README.md
- packages/ng/title/ng-package.json
- packages/ng/title/src/index.ts
- packages/ng/title/src/lib/index.ts
- packages/ng/title/src/lib/title-translate.service.ts
- packages/ng/title/src/lib/title.module.ts
- packages/ng/title/src/lib/title.service.spec.ts
- packages/ng/title/src/lib/title.service.ts
- packages/ng/title/src/public-api.ts
Adds utility service that sets the page title according to routing rules. It respects Lucca's rules for page titles ("Current page title - Current app - Lucca" i.e. "Purchases - Cleemy Procurement - Lucca")
Inspired from https://github.com/LuccaSA/Cleemy.Front/blob/master/projects/cleemy/page-title/src/page-title.service.ts#L11
Thanks to @belabb-z @jbosi @mathieu-bellange @JeSuisCharlie1 @LucasPerrault @albangranger 
fixes https://github.com/LuccaSA/Guildes/issues/48
> feat(ng) ADD Title service

- packages/ng/department/src/lib/service/department-v3.service.ts
Fixes a typo in `LuDepartmentV3Service` : a non existing getter was referenced by mistake and was always resolved as `undefined`
> Fix department select with appInstanceId + operations attributes

- packages/scss/src/commons/base.scss
- packages/scss/src/commons/config.scss
We can now use font variable with this syntax: 
```
@forward '@lucca-front/scss/src/commons/config' with (
$fontVariable: true
);
```
> fontVariable option

- stories/documentation/forms/api/select/api-select.stories.ts
- stories/documentation/forms/date/calendar/calendar.stories.ts
- stories/documentation/forms/date/select/date-select.stories.ts
- stories/documentation/forms/department/department-select.stories.ts
- stories/documentation/forms/establishment-select/establishment-select.stories.ts
- stories/documentation/forms/qualification/qualification-select.stories.ts
- stories/documentation/forms/select/select.stories.ts
- stories/documentation/overlays/dropdown/dropdown-basic.stories.ts
- stories/documentation/overlays/dropdown/dropdown-component.stories.ts
- stories/documentation/overlays/dropdown/dropdown-directive.stories.ts
- stories/documentation/overlays/modal/modal.stories.ts
- stories/documentation/overlays/popover/popover.stories.ts
- stories/documentation/overlays/toasts/toasts.stories.ts
- stories/documentation/users/select/user-homonyms.stories.ts
- stories/documentation/users/select/user-select.stories.ts
- stories/documentation/users/tile/user-tile-format.stories.ts
- stories/documentation/users/tile/user-tile.stories.ts
After Angular 14 migration, Storybook forced "Angular" type in prettier. "Angular" type is only for HTML files. Our "Typescript" had broken format.
-----
> fix(storybook): use type code to avoid using "angular" language in prettier

- packages/scss/src/components/timeline/mods.scss
A pseudo element was forgotten during the transition to LF 10.
> Fix timeline

- packages/ng/schematics/lib/scss-ast.ts
- packages/ng/schematics/migrations/css-vars/css-class-registry.ts
- packages/ng/schematics/migrations/css-vars/migration.spec.ts
- packages/ng/schematics/migrations/css-vars/migration.ts
- stories/documentation/integration/utilities/float.stories.ts
Corrige:
- Quand on importe textfield, checkbox ou radio, il faut aussi importer field
- Divider est aussi un composant (à importer si utilisé, donc)
- La source src/ng doit être appelé après la liste des composants SCSS sinon il y a des soucis de spécification
- u-right / u-left deviennent u-floatRight / u-floatLeft
-----
> [FIX] Fix LF9 -> LF10 migration script

- packages/ng/schematics/migrations/css-vars/tests/colors-white.input.scss
- packages/ng/schematics/migrations/css-vars/tests/colors-white.output.scss
- packages/ng/schematics/migrations/css-vars/updaters/color.ts
* Automatic migration of `_color(text)`
> feat(schematics): handle _color(text)

- packages/scss/src/components/field/vars.scss
- packages/scss/src/components/textfield/mods.scss
Textfield width variables refered to _fields_ instead of _textfield_ leading to an unwanted breaking change.
> [textfield] width variables

- packages/scss/src/components/table/mods.scss
`[class*='-row-cell']` was also targeting `.table-body-row-cell-handler `
> [Table] Fix handlers position

- e2e/LuccaFront.Tests.e2e/Features/DepartmentSelect.feature
- e2e/LuccaFront.Tests.e2e/Features/EstablishmentSelect.feature
- e2e/LuccaFront.Tests.e2e/Features/QualificationSelect.feature
- e2e/LuccaFront.Tests.e2e/Features/Switches.feature
- e2e/LuccaFront.Tests.e2e/Steps/ModSteps.cs
Ajout de tests e2e basiques pour les stories suivantes : 
+ EstablishmentSelect https://lucca-front.lucca.io/storybook/?path=/story/documentation-forms-establishmentselect--basic
+ QualificationSelect https://lucca-front.lucca.io/storybook/?path=/story/documentation-forms-qualification--select
+ DepartmentSelect https://lucca-front.lucca.io/storybook/?path=/story/documentation-forms-departmentselect--select
+ Switches https://lucca-front.lucca.io/storybook/?path=/story/documentation-forms-switches-basic--basic
Les tests sur les select sont très basiques et ne font que prendre une screenshot sans faire aucune action : il faudrait revoir les stories pour respecter le même formalisme que les autres stories en proposant des switches pour modifier les options des composants
> Add UI diff hub stuff

- packages/ng/title/README.md
- packages/ng/title/src/lib/title.service.spec.ts
- packages/ng/title/src/lib/title.service.ts
* Inject `ResolvedData` in title parts translations params
* Support `Observable<string> | string` in `LuTitleService` methods
> [Title] New features

- .eslintrc
- packages/ng/tsconfig.json
- packages/ng/tsconfig.lib.json
Eslint for VSCode was broken due to a tsconfig targeting only one file.
-----
> fix: eslint on VSCode was broken

- stories/documentation/actions/button/button-basic.stories.ts
Besoin: Quand on copie le bouton avec les options nécessaire depuis la documentation, il nous manque tout le temps le type de bouton.
> Add type button on basicButton stories

- packages/ng/styles/components/_dropdown.scss
- stories/documentation/overlays/dropdown/dropdown-basic.stories.html
- stories/documentation/overlays/dropdown/dropdown-basic.stories.ts
Cover icons for dropdown options
-----
- Option's display switched to a display flex to handle (or not) icons
- Bonus: add a mod-delete to options
-----
> [Dropdown] Cover icons on options

- packages/scss/src/components/list/component.scss
- packages/scss/src/components/list/index.scss
- packages/scss/src/components/list/mods.scss
- packages/scss/src/components/table/index.scss
- packages/scss/src/components/table/mods.scss
- stories/documentation/listings/lists/lists-basic.stories.ts
- stories/qa/list/list.stories.html
Actions icons should be visible by default
-----
Add a `mod-actionsHidden` to cover legacy behavior just in case
-----
> [Table/List] Action icons should be visible by default

- packages/ng/simple-select/src/lib/index.ts
- packages/ng/simple-select/src/lib/input/select-input.component.ts
- packages/ng/simple-select/src/lib/option/displayer.directive.ts
- packages/ng/simple-select/src/lib/option/option.directive.ts
- packages/ng/simple-select/src/lib/panel/panel.component.ts
- packages/ng/simple-select/src/lib/select.model.ts
- stories/documentation/forms/select/simple-select.stories.ts
* Removed `LU_SIMPLE_SELECT_COMPONENTS` as it does not work with AOT
* Fixed inference issue in template
* Improved typing in template
-----
It is a little breaking change for simple-select users but it is in beta state anyway
-----
> Fix simple select typing

- packages/scss/src/commons/config.scss
By adding the keyword "default", we allow overloads on the colours in the products.
It will be useful to apply the new colour charts progressively in the products before doing it again here in a global way.
-----
-----
> Update config with default parameters

- packages/scss/src/components/textfield/states.scss
Fix of the label color when the input is invalid.
Color : changed from primary to error.
-----
> Fix invalid label color

- packages/icons/src/icon/component.scss
- packages/icons/src/icon/index.scss
- packages/icons/src/icon/mods.scss
- packages/scss/src/components/button/component.scss
- packages/scss/src/components/button/mods.scss
- stories/documentation/actions/button/button-icon.stories.ts
Rewrite icons size to allow overrides in components
-----
Exemples bellow show buttons with size mods (line 1) and size mods on both buttons and icons (line 2)
-----
> allow to override button's icons

- packages/ng/user/src/lib/display/user-display.module.ts
De façon à corriger un problème de Null provider pour le LuUserDisplayPipe on provide dans le module "LuUserDisplayModule" le pipe 
-----
> Fix pipe providing for Lu User Display Module

- .storybook/msw/handlers.ts
- .storybook/msw/mocks.ts
- packages/ng/option/src/lib/picker/option-picker-advanced.component.ts
Fix for https://github.com/LuccaSA/lucca-front/issues/1938
-----
Selected items where lost if user :
1. check some items in the picker
2. scroll to the bottom of the picker -> new query triggered -> new selectors created without existing values (checked items)
3. one selector (who has an empty value) is clicked
-----
> Fix selection lost in picker advanced

- packages/ng/modal/src/lib/modal.token.ts
🐛 Sidepanel where broken because of the new inject syntax: we need to provide all inherited services (even if not necessary...)
-----
> fix(sidepanel): Sidepanel where broken because of the new inject syntax

- packages/scss/src/commons/base.scss
For browsers that support it, it avoids triggering a page repaint when a scrollbar is added.
-----
-----
> Scrollbar stable

- packages/ng/user/src/lib/display/display-format.model.ts
- packages/ng/user/src/lib/display/user-display.pipe.spec.ts
- packages/ng/user/src/lib/display/user-display.pipe.ts
Allow the override of default user display policy
-----
-----
> Enh allow default user display format override

- stories/documentation/overlays/popover/popover.stories.ts
Fix error `PopoverMockDirectiveStory does not have a module def (ɵmod property)`
In Popover Stories.
We only pass the component in standalone to fix the issue.
-----
https://lucca-front.lucca.io/storybook/?path=/story/documentation-overlays-popover--basic
-----
> Fix Error In PopoverMockDirectiveStory (emod property)

- packages/ng/schematics/lib/angular-template.ts
When a file use CRLF line endings (hey Windows !), the replaced content is broken because typescript normalize line endings with only LF.
-----
> fix(schematic): CRLF/LF issue on some projects

- packages/scss/src/components/form/index.scss
Fix variables on `.form` scope
-----
Not a perfect solution as we duplicated variables, but it avoids breakings before the form/field refactor. 
-----
> [Forms] Fix variables

- packages/ng/establishment/src/lib/select/input/establishment-select-input.component.scss
Fix establishment categories alignement
-----
As we set button as `inline-flex`, `text-align: left` was not working anymore
-----
> [Establishment] Fix categories alignment

- packages/ng/popup/src/lib/popup-ref.model.ts
`modal.open(A, {}, { size: 'L' })` was broken
-----
> fix(popup): size class

- packages/ng/modal/src/lib/modal-config.default.ts
- packages/ng/modal/src/lib/modal-config.model.ts
- packages/ng/modal/src/lib/modal-ref.model.ts
- packages/ng/sidepanel/src/lib/sidepanel.model.ts
* 🔨 ref(modal): mode is optional (default to modal)
* ✨ feat(modal): expose luDefaultSidepanelConfig
* 🐛 fix(modal): bring back config interface to avoid breaking change and deprecate them
-----
> Better.modal.typings

- packages/ng/modal/src/lib/modal-ref.model.ts
- packages/ng/modal/src/lib/modal.service.spec.ts
- packages/ng/modal/src/lib/modal.service.ts
- packages/ng/modal/src/lib/modal.token.ts
- packages/ng/popup/src/lib/popup.service.ts
- packages/ng/popup/src/lib/popup.token.ts
- packages/ng/sidepanel/src/lib/sidepanel.service.ts
* 🔨 no more popup inheritance
* 🔨 Popup/Modal/Sidepanel can no longer have a custom config type.
* 🐛 `modal.open` returns a `ILuModalRef` and not a `ILuPopupRef`
-----
#1918 introduced a richer `ILuModalRef`. `ILuModalRef` and `ILuPopupRef` can no longer be used interchangeably.
I removed CustomConfigType as it is not used across Lucca repositories. `inject` typings does not take default config type : 
```typescript
class AComponent {
// modal1 has LuModal<any> type
public modal1 = inject(LuModal);
// modal2 has LuModal<LuModalConfig> type
public constructor(public modal2: LuModal) {}
}
```
-----
> ref(modal): no more popup inheritance + "open" correct return type

- packages/ng/modal/src/lib/modal-ref.factory.ts
- packages/ng/modal/src/lib/modal-ref.model.ts
- packages/ng/modal/src/lib/modal.model.ts
- packages/ng/modal/src/lib/modal.service.ts
- packages/ng/popup/src/lib/popup-ref.model.ts
- packages/ng/popup/src/lib/popup.service.ts
- packages/ng/sidepanel/src/lib/sidepanel.model.ts
- packages/ng/sidepanel/src/lib/sidepanel.service.ts
- 🔨 All Modals and Sidepanels has only two generics instead of three. The result is inferred from component type.
-----
```typescript
class TestModalComponent implements ILuModalContent {
title: 'Test';
submitAction() {
return 42;
}
}
class BeforeThisPrOpenerComponent {
modal = inject(LuModal);
open() {
const ref = this.modal.open(TestModalComponent);
const result$ = ref.onClose;
//    ^^^^^^^ inferred as a `Observable<unknown>` 😭
}
manualOpen() {
const ref = this.modal.open<TestModalComponent, void, number>(TestModalComponent);
const result$ = ref.onClose;
//    ^^^^^^^ typed manually as a `Observable<number>`  🙁
}
}
class AfterThisPrOpenerComponent {
modal = inject(LuModal);
open() {
const ref = this.modal.open(TestModalComponent);
const result$ = ref.onClose;
//    ^^^^^^^ …
```
> [BREAKING] Ref modal typings

- packages/ng/modal/src/lib/modal.model.ts
- packages/ng/modal/src/lib/modal.service.spec.ts
* 🐛 fix(modal): better return type when ModalComponent has no submitAction method
-----
> fix(modal): better return type when ModalComponent has no submitAction method

- Jenkinsfile
Update Jenkins shared library version to v0.58.3 allowing us to publish pre-releases to npm using the specified channel in git tags i.e.
`v16.0.0-rc.1` -> release channel `rc` instead of `next`
-----
> Update Jenkins shared library version

- packages/scss/src/commons/config.scss
- packages/scss/src/components/breadcrumbs/mods.scss
- packages/scss/src/components/buttonGroup/component.scss
- packages/scss/src/components/field/component.scss
- packages/scss/src/components/field/mods.scss
- packages/scss/src/components/link/index.scss
- packages/scss/src/components/link/mods.scss
- packages/scss/src/components/radio/component.scss
- packages/scss/src/components/switch/component.scss
- packages/scss/src/components/title/component.scss
- stories/documentation/actions/button/button-group.stories.ts
- stories/documentation/actions/links/link-basic.stories.ts
- stories/documentation/forms/checkbox/checkbox-basic.stories.ts
- stories/qa/button/button.stories.html
- stories/qa/links/links.stories.html
- Apply primary on secondary palette
- Add radio/checkbox gap on fields
- Fix button group (previously applied en deprecated code)
- Remove link decorationNone (keep only decorationHover) 
- Remove translation animation on switch icon
- Fix hover on breadcrumb compact
- Set radio as flex (instead of block) to fix `.textfield.mod-radio`
- Delay new title weights on next release
-----
> 16.1 Fixes

- packages/scss/src/components/pagination/component.scss
Fix build warning generated by use of `end` instead of `flex-end`
-----
> Fix warning

- Jenkinsfile
`lucca.local` is deprecated, we update the reference to `lucca.tech` urls in PR comments pointing us to storybook
-----
> chore(tech): use lucca.tech url in PRs

- packages/ng/new-badge/new-badge.component.scss
- packages/ng/numeric-badge/numeric-badge/numeric-badge.component.scss
- packages/scss/src/components/callout/component.scss
- packages/scss/src/components/field/vars.scss
- packages/scss/src/components/textfield/component.scss
- packages/scss/src/components/textfields/mods.scss
- packages/scss/src/components/textfields/states.scss
- packages/scss/src/components/timeline/mods.scss
- stories/documentation/forms/textfield/textfield-basic.stories.ts
- stories/qa/forms/textfield-legacy.stories.html
- stories/qa/forms/textfield.stories.html
- Fix vertical timeline dot position
- Fix new textfield prefix ID
- Replace textfield borders by boxshadow to fit with DS & legacy components & fix focus offset
- `.textfield-label-input` as `span` 
- Fix legacy textfield messages margin
- Wrap _formLabel_ & _inlineMessage_ override inside `.textfield`
- Fix callout clear focus style
- Revert deprecated classes for legacy textfields with clearer
- Fix wrapped _newBadge_ & _numericBadge_ height
-----
> 16.3 fixes

- packages/ng/date/select/date-select-input.component.ts
- stories/documentation/forms/date/select/date-select.stories.ts
Replace null/undefined startOn input by today date
-----
Before fix, with `startOn: null`
🐛  `ERROR Error: Unable to convert "Invalid Date" into a date` 🐛
-----
> Fix date select with undefined/handle startOn

- packages/ng/callout/callout.component.html
- packages/ng/callout/callout.component.ts
- stories/documentation/feedback/callout/callout-basic.stories.ts
- stories/documentation/feedback/callout/callout-icons.stories.ts
- stories/documentation/feedback/callout/callout-killable.stories.ts
- stories/documentation/feedback/callout/callout-tiny.stories.ts
`title` input has been renamed to `heading` to avoid DX issues with title also being an html attribute (even tho it'd be bound using `attr.title`, it can easily create confusion among devs).
This PR also changes `hidden` for a two-way binding, meaning that clicking the hide icon now closes the callout, and then sends the updated value on a `hiddenChange` event emitter, making it possible to bind hidden using `[(hidden)]="mybool"`.
-----
> fix(callout): title => heading renaming, hidden now a two way binding

- packages/ng/callout/callout.component.html
- packages/ng/callout/callout.component.ts
Everything is in the title, pretty much, this is a small one.
-----
> fix(callout): rename `hidden` input to `removed` to avoid HTML attribute conflicts

- packages/scss/src/components/button/states.scss
Fix disabled + outlined + palette style
-----
Before
After
-----
> [Button] Fix disabled + outlined + palette style

- packages/scss/src/commons/base.scss
- packages/scss/src/commons/config.scss
- packages/scss/src/commons/core.scss
Why remove the variable font? 
It's heavier than the 4 files needed to manage the different weights.
(💥 `$fontVariable: true` must be removed if you use it.)
Why delete utilities?
These weights are not present in the DS.
-----
-----
> Remove font variable option and remove utilities not present in DS

- packages/scss/src/components/statusBadge/component.scss
We set the font to normal to avoid inheriting any bolding.
-----
-----
> Status badge font weight

- packages/scss/src/components/tag/component.scss
We set the font to normal to avoid inheriting any bolding.
-----
-----
> Tag font weight

- build.js
- packages/icons/package.json
This is a hotfix for the missing type export in `@lucca-front/icons` that was causing multiple components failing
-----
-----
> fix(icons): fix missing type export in built bundle

- Jenkinsfile
- packages/ng/establishment/establishment-select.spec.ts
- packages/ng/form-field/form-field.component.scss
Use linux nodes on CI
-----
- Fixed case of `textField` (was `textfield`, UNIX systems are case sensitive)
- Fixed establishment select tests where some providers were missing (weird that we see it with this change 🤔)
This PR was initially merged via https://github.com/LuccaSA/lucca-front/pull/2335 but it was removed in https://github.com/LuccaSA/lucca-front/pull/2346 when we had an issue with merges from rc to master
> chore(ci): use linux node

- packages/ng/core-select/input/select-input.component.ts
Mark lu-simple-select/lu-multi-select as touched when panel is closed.
-----
> Fix select touched

- packages/scss/src/components/navside/component.scss
A margin auto was applied to every instances of `.numericBadge` instead of `.navSide .numericBadge`
-----
> [Numeric Badge] Fix navside scope

- packages/scss/src/components/textfields/mods.scss
Fix `textfield mod-search` + `mod-S/XS` padding issue
-----
- CSSvar was removed as this case didn't refer to a standard spacing but an arbitrary value depending on icon width
- Removing cancel button only on `hover`/`active` stated for` type="search"` leaded to extra right margin (or gap?) on defaut state. 
-----
> [Textfield] mod-search + size incompatibility 

- packages/ng/icon/icon.component.scss
Fix luIcon root size
-----
before
after
-----
> [luIcon] Fix component root size

- packages/ng/simple-select/api/api-v3.directive.ts
- packages/ng/simple-select/api/api-v4.directive.ts
This PR fixes a double encoding issue with apiVX directives for select components that turned `Lucca ` into `Lucca%25%20` due to it encoding once by hand (resulting in `Lucca%20`) and then having Angular encode params once again when assigned to HttpParams (resulting in `%` being encoded as `%25`).
Removing the manual encoding resulved the issue.
-----
-----
> fix(simple-select): URI encoding done twice instead of just once

- packages/ng/button/button.component.ts
- packages/ng/callout/callout.component.ts
- packages/ng/form-field/form-field.component.ts
- packages/ng/forms/checkboxfield/checkboxfield.component.ts
- packages/ng/forms/switchfield/switchfield.component.ts
- packages/ng/forms/textfield/textfield.component.ts
- packages/ng/icon/icon.component.ts
- packages/ng/inline-message/inline-message.component.ts
- packages/ng/numeric-badge/numeric-badge.component.ts
We noticed an issue with icons, buttons and some other components that, when nested in wrappers, weren't behaving as they should. The issue being that since `size` defaulted to `M`, if the parent was using `mod-S` for its own size, the child component would not automatically be switched to `S` size as it already had a `mod-M` applied to it.
This created situations where icons are too large in a small component, for instance.
I fixed it by setting the default value for size to `undefined` (by just not defining it, not setting it explicitly) which won't apply any mod unless the size is explicitly passed as input value.
-----
-----
> refactor(wrappers): size now defaults to inherit rather than M

- packages/ng/styles/definitions/select/_select-input.scss
- packages/scss/src/components/button/component.scss
- packages/scss/src/components/button/mods.scss
- packages/scss/src/components/clear/component.scss
- packages/scss/src/components/clear/mods.scss
- packages/scss/src/components/clear/vars.scss
- packages/scss/src/components/numericBadge/index.scss
- packages/scss/src/components/numericBadge/mods.scss
- packages/scss/src/components/textfields/mods.scss
- stories/documentation/actions/button/angular/button-counter.stories.ts
- stories/qa/button/button.stories.html
- [Button] Use icon size mixins
- [Button] Apply numericBadge sizes in size/palettes mixins
- [Clear] Use icon size mixins
- [Numeric badge] Harmonize size mixin names (`s`/`xs` > `S`/`XS`)
-----
Note: This PR is not specified as breaking as `numericBadge.s` / `numericBadge.xs` are not used yet outside of LF
-----
> Fix NG wrap specificity 

- packages/icons/src/icon/component.scss
- packages/scss/src/components/actionIcon/component.scss
- packages/scss/src/components/calloutAccordion/component.scss
- packages/scss/src/components/calloutDisclosure/component.scss
- packages/scss/src/components/calloutPopover/component.scss
Increase icon default size from `1.25rem (20px)` to `1.5rem (24px)` to fit with Figma
-----
Defaut values were: 
Figma : `24px`
Default HTML icon : `20px` 
Default Angular icon : `24px`
Nested in buttons, callout, etc : `24px`
Are now `24px` everywere
It's still possible to override `--icon-size` to keep our current default value (1.25rem) on HTML component
-----
> [Icons] Fix icon default size

- packages/ng/inline-message/inline-message.component.ts
- packages/scss/src/components/inlineMessage/component.scss
- packages/scss/src/components/inlineMessage/mods.scss
- packages/scss/src/components/inlineMessage/vars.scss
- Fix icon size
- Remove style encapsulation in Angular component as discussed to avoid nested components imports issues 
-----
-----
> fix inline message icon size + remove style encapsulation

- packages/ng/core/tools/ng-clazz.directive.ts
- packages/ng/icon/icon.component.ts
- packages/ng/inline-message/inline-message.component.ts
Add `markForCheck` call to `NgClazz` so we can make sure class changes are going to be applied properly. This fixes an issue found in various BUs.
-----
This PR also includes changes to `lu-inline-message` because we were troubleshooting with it and I took this opportunity to fix some class management in it.
-----
> fix(ngClazz): change detection not applied properly on ngClass value change

- packages/ng/option/selector/all/select-all.translate.ts
On remplace le D majuscule de la traduction  deselect pour un d minuscule.
-----
-----
> [FIX] - translation deselect

- packages/ng/callout/callout-popover/callout-popover.component.html
Closes #2464 : a callout popover now correctly doesn't include `lucca-icon` tag when no icon is provided
-----
Add `*ngIf` directives to display `lucca-icon` tags only when icon is provided
-----
> fix(callout): issue #2464 icon not displayed when iconless

- packages/ng/a11y/skip-links/skip-links.component.ts
- tsconfig.json
No need for constructors with `inject()`.
-----
We could do that on the whole codebase.
> chore(skip-links): use inject syntax

- packages/scss/src/components/calloutPopover/mods.scss
Fix icon size and border radius for XS size
-----
-----
> [Callout Popover] Fix XS icon size & radius

- packages/scss/src/commons/utils/media.scss
```
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($value, 16px) or calc($value / 16px)
More info and automated migrator: https://sass-lang.com/d/slash-div
╷
8 │     @return $value / 16px * 1em;
│             ^^^^^^^^^^^^^
╵
```
-----
> fix(commons): deprecated / as a division operator

- packages/ng/user/select/input/user-select-input.component.html
- packages/ng/user/select/input/user-select-input.component.ts
- stories/documentation/users/select/user-select.stories.html
- stories/documentation/users/select/user-select.stories.ts
Closes #2422 
Add a parameter `enablePrincipal` within `user-select` to control principal display : 
Boolean set to `true`
Boolean set to `false`
-----
Surround  `luUserMeOption` with `ng-container` conditionnaly displayed depending on `enabledPrincipal` parameter value. 
Default value is set to `true` to avoid regress on existing uses.
-----
> enh(userSelect): issue #2422 allow to disable principal

- packages/scss/src/components/gauge/component.scss
- packages/scss/src/components/gauge/vars.scss
- packages/scss/src/components/progress/component.scss
- packages/scss/src/components/progress/vars.scss
- Height : 10px > 8px
- Background color : Replace transparent black by grey 100 (Keep a variable open in case it's needed on darker backgrounds) 
- Background color : Replace Base by grey 100  (Keep a variable open in case it's needed on darker backgrounds) 
- Add border radius
-----
-----
> [Gauge / Progress] Fix height & background color

- stories/documentation/feedback/callout-popover/angular/callout-popover.stories.ts
- stories/documentation/forms/fields/checkbox/angular/checkboxfield.stories.ts
- stories/documentation/forms/fields/multi-select/angular/multi-select.stories.ts
- stories/documentation/forms/fields/simple-select/angular/simple-select.stories.ts
- stories/documentation/forms/fields/switch/angular/switchfield.stories.ts
- stories/documentation/forms/fields/text/angular/textfield.stories.ts
- stories/documentation/forms/select/multi-select.stories.ts
- stories/documentation/forms/select/simple-select.stories.ts
- stories/documentation/users/select/user-select.stories.ts
Various stories imrovements:
- Simple select Input doc cleanup
- Multi select input doc cleanup
- Textfield now has 3 stories: basic, with prefix/suffix, password visibility
- callout popover now has base values for `closeDelay` and `openDelay`
- luUserSelect now has a base value for `disablePrincipal`
- Better code formatting for ZeroHeight renderer using `generateInputs`
-----
-----
> docs(stories): stories and code display improvements

- packages/ng/callout/callout-disclosure/callout-disclosure.component.scss
- packages/ng/callout/callout-popover/callout-popover.component.scss
- packages/ng/callout/callout/callout.component.scss
- packages/ng/icon/icon.component.scss
Default display of wrapped component in `:host` selector stopped to work when we switched components to `encapsulation: ViewEncapsulation.None`
-----
> Wrapped components fix default display 

- packages/scss/src/components/button/component.scss
- packages/scss/src/components/button/index.scss
- packages/scss/src/components/button/mods.scss
- packages/scss/src/components/button/states.scss
- packages/scss/src/components/divider/index.scss
The aim of this project is always to have an important component properly architected for the management of nested components (molecules).
We now distinguish between native states (pseudo-selectors) and forced states (classes).
This makes it easier to import a component without having to redefine its native behaviors each time.
Pseudo-selectors are now in the component or its modifiers. And non-native states remain called from the index (with the prefix `.is-`).
-----
-----
> Clean states for buttons

- packages/scss/src/commons/utils/reset.scss
Actuellement on ne peut pas faire de reset en précisant `ol` comme paramètre dans l'appel de la mixin.
```
ol {
@include reset.list($list: 'ol');
}
```
C'est parce que dans la mixin il ne faut pas les parenthèses dans la condition.
La solution de repli c'est de ne rien préciser en paramètre car c'est les mêmes styles que le `ul` qui est le choix par défaut.
```
ol {
@include reset.list;
}
```
-----
> fix(commons): delete wrong parentheses usage in condition

- packages/scss/src/components/checkbox/mods.scss
- packages/scss/src/components/table/index.scss
- packages/scss/src/components/table/mods.scss
- packages/scss/src/components/table/vars.scss
- stories/documentation/listings/table/table-selectable.stories.ts
- stories/qa/table/table.stories.html
- Hover : grey 25 > grey 50
- Selected line : product 50
- Selected line hovered in a clickable table : product 100
- Fix checkbox alignement
- Replace old checkbox by the new one
-----
https://github.com/LuccaSA/lucca-front/assets/25581936/95ac6353-d90f-4d64-8ff1-9f0f814b046c
https://github.com/LuccaSA/lucca-front/assets/25581936/f899966d-1693-41eb-a723-6e0a24128bbd
-----
> [Table] States colors & checkbox alignement fixes

- packages/ng/establishment/select/establishment-select.token.ts
- packages/ng/establishment/select/input/establishment-select-input.component.ts
- packages/ng/establishment/select/legal-unit-selector/legal-unit-selector.directive.ts
- packages/ng/establishment/select/searcher/establishment-searcher.component.ts
- packages/ng/establishment/select/select-all/establishment-select-all.component.ts
LuEstablishmentService was not overridable because of to many providers for `ALuEstablishmentService`.
-----
-----
> fix(establishment): LuEstablishmentService is now overridable

- packages/scss/src/components/checkbox/component.scss
- packages/scss/src/components/checkbox/states.scss
We switch from a shadow to a real border to avoid calculation errors in Windows.
As the icon has insufficient space, it is moved to a `::after`.
-----
-----
> Fix checkbox border

- packages/ng/button/button.component.ts
- stories/documentation/actions/button/angular/button-icon.stories.ts
Closes #2499 : `mod-onlyIcon` when child `IconComponent` exists. `withIcon` class when the button is empty (text / span)
-----
> enh(button): dynamically add mod-onlyIcon & withIcon classes

- packages/scss/src/components/title/component.scss
Sometimes the balanced formatting on titles looks strange, so we prefer a prettier management of line breaks.
-----
-----
> text-wrap: balance -> pretty

- packages/ng/form-field/form-field.component.scss
- packages/ng/form-field/form-field.component.ts
- packages/ng/forms/checkbox-input/checkbox-input.component.ts
- packages/ng/forms/switch-input/switch-input.component.ts
- packages/ng/forms/text-input/text-input.component.scss
- packages/ng/forms/text-input/text-input.component.ts
- stories/documentation/forms/fields/form-field.stories.ts
Modified the `lu-form-field` stories to show an example of a custom component inside `lu-form-field` instead of the non-functionnal demos we previously had.
This PR also bring a fix to the `Expression has changed after it was checked` error showing when the `input` was created during a detection cycle, which means anytime but at page init.
-----
-----
> chore(form-field): stories improvement and change detection fixes

- packages/ng/core-select/input/select-input.component.ts
- packages/ng/dialog/dialog.provider.ts
- packages/ng/dialog/dialog.providers.ts
- packages/ng/dialog/dialog.service.ts
- packages/ng/dialog/dialog/dialog.component.scss
- packages/ng/dialog/public-api.ts
- packages/ng/form-field/form-field.component.scss
- packages/ng/modal/modal.module.ts
- packages/ng/modal/modal.service.ts
- packages/ng/multi-select/displayer/default-displayer.component.ts
- stories/documentation/overlays/dialog/dialog.stories.ts
- stories/documentation/overlays/modal/modal.stories.ts
This PR fixes:
- Missing scss import in `lu-form-field` resulting in size not being applied properly
- Wrong injector used in `LuDialogService`, resulting in issues in any dialog component that needs injection (hello transloco)
- Wrong injector used for `LuModal` adapter, resulting in the same as above for `LuModal` boxes
- Placeholder label updates not being applied properly in `lu-multi-select`, breaking transloco usages for placeholders
-----
-----
> chore(rc): fixes for issues noticed with rc.2 tests

- packages/scss/src/components/tag/mods.scss
> Transparent background for outlined tags

- packages/scss/src/components/navside/component.scss
- stories/documentation/navigation/menu-secondary/menu-secondary-basic.stories.ts
Reinstates an animation for the appearance of sub-menus that had disappeared by mistake a long time ago.
Fixes #2603 
-----
-----
> Add animation for submenus

- packages/ng/callout/callout-feedback-item/callout-feedback-item.component.ts
- packages/ng/dialog/dialog.service.ts
- packages/ng/dialog/model/dialog-config.ts
- packages/ng/establishment/establishment.module.ts
- packages/ng/establishment/select/establishment-select.module.ts
- packages/ng/establishment/select/input/establishment-select-input.component.ts
- packages/ng/modal/modal.service.ts
- packages/ng/qualification/qualification.module.ts
- packages/ng/qualification/select/input/qualification-select-input.component.ts
- packages/ng/qualification/select/input/qualification-select-input.module.ts
- packages/ng/qualification/select/qualification-select.module.ts
- packages/ng/select/input/select-input.component.ts
- packages/ng/select/input/select-input.module.ts
- packages/ng/select/select.module.ts
- packages/ng/user/select/input/user-select-input.component.ts
- packages/ng/user/select/input/user-select-input.module.ts
- packages/ng/user/select/user-select.module.ts
Add deprecated with alternative to:
- establishment-select
- qualification-select
- user-select
- lu-select
Fix panelClass and size not applied to `LuModal` dialogs.
-----
-----
> fix(lu-modal): panelClass settings + old select deprecation

- packages/ng/core-select/input/select-input.component.ts
Disabling a `FormControl` applied to a `lu-simple-select` wasn't being applied visually until a new change detector cycle was started, this PR fixes the behavior by adding a `markForCheck` call when disabled is applied.
-----
-----
> fix(simple-select): disabled state not applied visually until new cd cycle

- .storybook/preview-head.html
- packages/ng/styles/components/cdk/_overlay.scss
- packages/scss/src/commons/config.scss
- packages/scss/src/commons/utils/color.scss
- packages/scss/src/commons/utils/index.scss
- packages/scss/src/commons/utils/loading.scss
- packages/scss/src/components/actionIcon/mods.scss
- packages/scss/src/components/checkbox/component.scss
- packages/scss/src/components/file/states.scss
- packages/scss/src/components/header/component.scss
- packages/scss/src/components/loading/mods.scss
- packages/scss/src/components/navside/component.scss
- packages/scss/src/components/progress/vars.scss
- packages/scss/src/components/textfields/states.scss
- stories/documentation/feedback/empty-state/html&css/empty-state-page.stories.ts
- stories/documentation/integration/utilities/borders-radius.stories.ts
- stories/documentation/integration/utilities/borders.stories.ts
- stories/documentation/toolbox/animations/animations.scss
- stories/qa/tokens/tokens.stories.html
> Remove rgba colors – Add transparentize function

- packages/ng/core-select/input/select-input.component.ts
- packages/ng/core-select/panel/panel.models.ts
- packages/ng/multi-select/input/panel.model.ts
- packages/ng/simple-select/input/panel-ref.factory.ts
Fixed a bug that happened with options were set after the panel is opened, which happens quite often with `*apiV4`.
When options are set, if the panel is too far on the right hand side of the screen and the data requires the panel to be larger than the select input's width, then it would expand to the right no matter what, at least when opening it for the first time.
This was due to the panel's position not being updated after new options are set, which is what this PR fixes.
-----
-----
> fix(select): position not updating when new options are set

- packages/ng/dialog/dialog-header/dialog-header.component.html
- packages/ng/dialog/dialog-header/dialog-header.component.ts
- packages/ng/modal/dialog-adapter/dialog-content-adapter/dialog-content-adapter.component.html
- packages/scss/src/components/dialog/component.scss
- packages/scss/src/components/dialog/vars.scss
- stories/documentation/overlays/dialog/dialog-basic.stories.ts
- stories/documentation/overlays/dialog/dialog-drawer.stories.ts
- stories/documentation/overlays/dialog/dialog-drawerFromBottom.stories.ts
- stories/documentation/overlays/dialog/dialog.stories.ts
Allow customisation of the new dialog's header slot to allow more content than just everything wrapped in `h1`.
⚠️ This means that you have to put a `h1` inside `lu-dialog-header` for it to render as a title.
-----
-----
> fix(dialog): header missing customisation possibilities

- packages/scss/src/components/dialog/component.scss
Addition of a relative position and z-index on dialog content, so that any positioning within this container does not override the header.
I'm also taking this opportunity to rename the optional form in line with the latest guidelines.
-----
> Stronger sticky header for dialogs

- packages/scss/src/components/navside/mods.scss
Reset numericBadge position in Compact mod
-----
-----
> [Navside] Reset numericBadge position in Compact mod

- packages/ng/forms/checkbox-input/checkbox-input.component.scss
- packages/ng/forms/checkbox-input/checkbox-input.component.ts
Automatic loading of styles when using the angular component for checkbox.
Fixes #2635 
-----
Before: 
After: 
-----
> Fix styles for checkbox component

- packages/ng/core-select/establishment/establishment-grouping.service.ts
Requests where using `&limit=0=0` 🙈 
-----
> fix(core-select): wrong HttpParams when calling establishmentsCount and legalUnitsCount

- packages/ng/core-select/establishment/establishments.directive.ts
- packages/ng/core-select/job-qualification/job-qualifications.directive.ts
These APIs use `search` and not `clue` .
-----
> fix(establishment): wrong query filter (use search instead of clue)

- packages/ng/dialog/model/dialog-config.ts
- stories/documentation/overlays/dialog/dialog-service.stories.ts
In dialogs, the `LuDialogRef.result$` property was typed as `Observable<T | void>`, while `void` isn't possible in the event of `ref` being present and typed.
This was due to a hiccup in typescript, caused by inference in a wrong spot and logic not being split enough, which is what this PR fixes.
-----
-----
> fix(dialog): fix result$ type being `T | void` while it shouldn't

- packages/ng/forms/text-input/text-input.component.html
- packages/ng/forms/text-input/text-input.component.ts
- stories/documentation/forms/fields/text/angular/textfield.stories.ts
When setting a `lu-text-input` `type` to `number`, we had no ways to provide a value for `step` in order to customize it, this PR adds a `step` button for this.
Additionally, it's also adding a `noSpingButtons` boolean input that can be used to put the `u-noSpinButtons` class on the native input to hide native number input spin buttons.
-----
-----
> feat(text-field): add `step` input and `noSpinButtons` flag to remove spin buttons

- .storybook/msw/handlers.ts
- .storybook/msw/helpers.ts
- packages/ng/core-select/establishment/establishments.directive.ts
- packages/ng/core-select/input/select-input.component.ts
- packages/ng/core-select/job-qualification/job-qualifications.directive.ts
- packages/ng/core-select/option/group.pipe.ts
- packages/ng/core-select/option/index.ts
- packages/ng/core-select/option/option.component.html
- packages/ng/core-select/option/option.component.scss
- packages/ng/core-select/option/option.component.ts
- packages/ng/core-select/panel/index.ts
- packages/ng/core-select/panel/panel.utils.ts
- packages/ng/multi-select/panel/panel.component.html
- packages/ng/multi-select/panel/panel.component.ts
- packages/ng/simple-select/input/select-input.component.html
- packages/ng/simple-select/panel/panel.component.html
- packages/ng/simple-select/panel/panel.component.ts
- packages/ng/styles/components/_picker.scss
- packages/ng/styles/definitions/option/_option-item.scss
- stories/documentation/forms/select/multi-select.stories.ts
- stories/documentation/forms/select/select.utils.ts
- stories/documentation/forms/select/simple-select.stories.ts
Grouped options, with empty clue:
Grouped options, wit clue:
-----
-----
> feat: Better sorting and display for grouped select

- packages/ng/core-select/api/api.directive.ts
- stories/documentation/overlays/dialog/dialog-service.stories.ts
This was caused by the fact that we directly connected data source to `options$` instead of using the setter, which is also updating panel position.
-----
-----
> fix(select): panel position not updating on api data changes 

- packages/ng/multi-select/displayer/displayer-input.directive.ts
- stories/documentation/forms/select/multi-select.stories.ts
Placeholder wan't updated properly because it was returning... a setter reference.
This PR fixes that so everytime someone uses the `luMultiSelectDisplayerInput` directive, aria-* attributes and placeholder are properly connected.
It also fixes a CD issue with activedescendant update.
-----
-----
> fix(multi-select): placeholder not showing on custom displayers

- packages/ng/form-field/form-field.component.html
- packages/ng/form-field/form-field.component.ts
This PR changes the input type of `label` to `PortalContent` so it can be a `string | TemplateRef`, allowing `ng-template` inputs.
-----
-----
> feat(form-field): label can now be a ng-template or a string

- packages/ng/form-field/form-field.component.ts
- packages/ng/forms/public-api.ts
- packages/ng/forms/textarea-input/textarea-input.component.html
- packages/ng/forms/textarea-input/textarea-input.component.ts
- packages/scss/src/components/textField/component.scss
- stories/documentation/forms/fields/textarea/angular/textarea.stories.ts
New `lu-textarea-input` component that makes it easy to create form fields with a text area.
Example:
```html
<lu-form-field
label="Label"
tooltip="Je suis un message d'aide"
inlineMessage="Helper Text"
inlineMessageState="default"
size="M"
>
<lu-textarea-input
cols="50"
rows="3"
required
placeholder="Placeholder"
[(ngModel)]="example"
></lu-textarea-input>
</lu-form-field>
```
-----
-----
> feat(form-fields): new textarea-input wrapper

- packages/ng/form-field/form-field.component.html
- packages/ng/form-field/form-field.component.ts
- packages/ng/form-field/input.directive.ts
- packages/ng/forms/public-api.ts
- packages/ng/forms/radio-group-input/radio-group-input.component.ts
- packages/ng/forms/radio-group-input/radio-group-token.ts
- packages/ng/forms/radio-group-input/radio/radio.component.html
- packages/ng/forms/radio-group-input/radio/radio.component.scss
- packages/ng/forms/radio-group-input/radio/radio.component.ts
- packages/scss/src/components/form/index.scss
- stories/documentation/forms/fields/radio/angular/radiofield.stories.ts
- stories/documentation/forms/fields/radio/html&css/radiofield-size.stories.ts
New `lu-radio-group` and `lu-radio` components to create `fieldset` structures that will hold `input[type=radio]` components, managing UX, a11y and control linking as with every input component.
Example use:
```html
<lu-form-field label="Option example">
<lu-radio-group-input [(ngModel)]="example">
<lu-radio [value]="1" inlineMessage="I am option 1">Option 1</lu-radio>
<lu-radio [value]="2" inlineMessage="I am option 2">Option 2</lu-radio>
<lu-radio [value]="3" inlineMessage="I am option 3 and I'm disabled" disabled>Option 3</lu-radio>
</lu-radio-group-input>
</lu-form-field>
```
In order to make this work as a template, I had to add a `fieldset` structure for `lu-form-field`, which is filled by the `lu-radio-group` itself so you don't have to do anything manually (like with checkbox for …
> feat(fields): new radio wrapper components

- packages/ng/forms/checkbox-input/checkbox-input.component.html
- packages/ng/forms/checkbox-input/checkbox-input.component.ts
- stories/documentation/forms/fields/checkbox/angular/checkboxfield.stories.ts
Closes #2677 : add a `mixed` boolean input for checkbox-field component. 
When the input is `true`, the attribute `aria-check` is set to `mixed`.
-----
-----
> feat(checkbox): mixed input

- packages/ng/dialog/dialog.service.ts
- packages/ng/forms/text-input/text-input.component.ts
- `placeholder` now defaults to `''` in `lu-text-input`
- `dialog` instances are now properly marked as `aria-modal`
-----
-----
> fix(input + dialog): undefined placeholder and modal flag

- packages/ng/core-select/input/select-input.component.ts
- packages/ng/multi-select/input/select-input.component.ts
This was caused by removing chip updating clue, which triggered panel open. Added a flag to allow clue change without panel open logic being triggered.
-----
-----
> fix(multi-select): chip click opening panel

- packages/ng/user/display/user-display.pipe.ts
- packages/ng/user/picture/index.ts
- packages/ng/user/picture/user-picture.component.ts
- packages/ng/user/tile/user-tile.component.ts
Use a narrower type of user in `luUserDisplay`, `LuUserDisplayPipe`, `LuUserPictureComponent` and `LuUserTileComponent`.
Support both `null` and `undefined` for optional properties.
-----
> ref(user): use a more specific type for user related components

- packages/scss/src/components/card/component.scss
- packages/scss/src/components/table/mods.scss
- stories/documentation/listings/table/table-card.stories.ts
-----
Other options considered but abandoned:
- `overflow: hidden` on `.card` (too risky);
- selectors `> *` (too risky on arrays are poorly constructed and contrary to our guidelines);
- don't use `:where` (too verbose when compiling CSS).
-----
Before: 
After:
> Fix overflow for table card with clickable lines

- packages/ng/core-select/input/select-input.component.ts
When closing the panel with escape, do not close the englobing dialog.
-----
> fix(core-select): stop escape propagation

- packages/ng/core-select/user/users.directive.ts
`operationIds` does not exist on users API. Use `operations` instead.
-----
> fix(core-select): fix operations query filter on users API

- packages/icons/src/icon/component.scss
- packages/icons/src/icon/vars.scss
The `--icon-size` variable remains undefined so that it can be overloaded, so we use another variable name for the fallback.
-----
-----
> Fix icon size fallback

- build.js
Exports the `schema.json` required by `nx` during the build process.
-----
> fix(schematics): export schema.json during build

- .storybook/msw/mocks.ts
- packages/ng/core-select/input/select-input.component.ts
- packages/ng/core-select/user/user-homonym.service.ts
- packages/ng/core-select/user/users.directive.ts
- clue was sometimes missing in `users` directive
- nextPage was emitting to often (two by two)
- cache homonyms information 
-----
> fix(core-select): wrong users loading params and too much nextPage events

- packages/ng/core-select/input/select-input.component.ts
Do not submit englobing form when selecting an option using enter key.
-----
> fix(core-select): do not submit englobing form when hitting enter

- .eslintrc
- packages/ng/forms/text-input/text-input.component.html
- packages/ng/multi-select/input/select-input.component.html
Using clearable `lu-text-input` or `lu-multi-select` inside a `form` leads to clearing value instead of submitting the form.
This PR also add an Eslint rule to avoid this problem in the future.
-----
> chore: add mandatory button type eslint rule

- packages/ng/schematics/lib/html-ast.ts
- packages/ng/schematics/tokens-spacing/tests/template.input.html
- packages/ng/schematics/tokens-spacing/tests/template.output.html
With new control flow syntax, Angular added new nodes to the `AngularCompilerLib`, which aren't `TmplAstTemplate`, meaning that the visit methods were just skipping them.
This PR adds proper handling of these node types in the `HtmlAst.visit` method so every `visitXXX` method will now just see their content.
Parsing the `BlockNode`s themselves can be added, not sure it's relevant since it'd mean that we're making a schematic that has something to do in these blocks, but adding a method to visit them is quite trivial.
-----
-----
> fix(schematics): template schematics skipping control flow blocks

- packages/ng/dialog/testing/ng-package.json
- packages/ng/dialog/testing/providers.ts
- packages/ng/dialog/testing/public-api.ts
Add `provideLuDialogDataTesting` to provide `DIALOG_DATA` for testing context in order to be able to test components that are meant to be used as dialog content.
It's added in a new entrypoint called `@lucca-front/ng/dialog/testing` in order to not include it in the main dialog bundle used for production.
-----
-----
> test(dialog): new testing entrypoint for data testing provider

- packages/ng/empty-state/empty-state-page/empty-state-page.component.html
- packages/ng/empty-state/empty-state-page/empty-state-page.component.ts
- packages/ng/empty-state/empty-state-section/empty-state-section.component.html
- packages/ng/empty-state/empty-state-section/empty-state-section.component.ts
- packages/ng/safe-content/safe-external-svg.pipe.ts
Empty state components have an optional icon but when it's not provided, the request is still fired, creating an error.
This is fixed by only showing icon when it's here and handling null gracefully in safe svg pipe to handle possible async pipe use cases.
-----
-----
> fix(empty-state): http request for icon still fired even when it's null

- packages/scss/src/components/indexTable/mods.scss
Prevent rows to go over sticky header while hovering it
-----
https://github.com/LuccaSA/lucca-front/assets/25581936/fba87cdb-11dc-4ad8-8ae6-c0b9d1b31b73
-----
> [Index Table] Prevent row to go over sticky header

- packages/scss/src/components/emptyState/component.scss
- packages/scss/src/components/emptyState/mods.scss
* Reduce heading to match `h2` styles.
* Address buttons based on the mockups provided.
Closes #2520.
-----
https://github.com/LuccaSA/lucca-front/assets/144820795/d93e5326-50ec-4a9b-9ee7-311cb79b5aba
-----
> [EmptyState] Tweaks for narrow views

- packages/ng/popup-employee/card/panel/user-popover-panel.component.ts
Color in user picture embed inside the user-popover panel was missmatching the one from "real" `lu-user-picture` due to a missing space in the string used to feed the base value for HSL. This PR just fixes that by adding a space (big PR yeah).
-----
-----
> fix(user-popover): background color not matching user-picture

- docs/core-select-users-directive.md
- packages/ng/core-select/api/api-v3.directive.spec.ts
- packages/ng/core-select/api/api.directive.ts
- packages/ng/core-select/api/public-api.ts
Doc on how to override the user directive has been written in https://github.com/LuccaSA/lucca-front/pull/2748.
However, some explanation was missing, especially regarding the limit parameter which must be provided in the request, in order to trigger the page change on scroll.
This PR is meant to update the doc, as well as exposing the `MAGIC_PAGE_SIZE` const (and renaming it), which is a good default value if you don't want to provide a custom limit.
-----
-----
> [Simple & Multi Select] Expose MAGIC_PAGE_SIZE and update doc.

- packages/scss/src/components/navside/states.scss
Fix inverted deprecated  alert color when item is active
-----
> [Secondary nav] Fix inverted deprecated  alert color when item is active

- packages/scss/src/components/checkbox/component.scss
- packages/scss/src/components/checkbox/states.scss
- stories/qa/forms/checkbox-legacy.stories.html
The border on checkboxes was not correctly displayed on Windows with zoom enabled.
We tried a fix, but it ended up causing too many border effects. So we're going back to the previous version and fix it differently.
(Note we are on the depreciated version of the component checkbox.)
-----
A little background:
- [The bug reported by @MarcFairbrother](https://lucca.slack.com/archives/GSCU69USV/p1707486422351609)
- [The fix](https://codepen.io/vincent-valentin/pen/MWxqLNb/3ea9c87f0ee7c0de19cb8c2509b94742?editors=1100)
- [Installing the patch](https://github.com/LuccaSA/lucca-front/pull/2559)
- [The rest of the patch](https://github.com/LuccaSA/lucca-front/pull/2575)
-----
> Fix for border on checkbox and revert with only one pseudo-element

- packages/ng/styles/definitions/select/_select-input.scss
Fix placeholder color with `.ng-invalid.ng-touched` classes (previously only `.is-error`)
Date icon should stay grey in error/invalid state to fit with our Design System
-----
-----
> [Datepicker] Invalid cover

- packages/ng/option/picker/option-picker.component.ts
- packages/ng/option/picker/tree-option-picker.component.ts
- packages/ng/popover/panel/popover-panel.model.ts
- packages/ng/popover/trigger/popover-trigger.model.ts
- packages/ng/popup-employee/card/panel/user-popover-panel.component.ts
- packages/ng/popup-employee/card/trigger/user-popover-trigger.directive.ts
`lu-select` wasn't updating when options arrived after the panel has been opened, this PR fixes that issue.
It's also affecting (and fixing) custom selects like `lu-establishment-picker` etc.
-----
-----
> fix(lu-select): panel position not updating when options change

- packages/ng/forms/number-input/number-input.component.ts
Placeholder was `undefined` by default, showing it as string in inputs, which isn't ideal.
This PR fixes that by making it an empty string by default instead.
-----
-----
> fix(number-input): default placeholder should be '' not `undefined`

- packages/scss/src/components/indexTable/component.scss
Fix `indexTable` inconsistent cells padding
-----
-----
> fix(front): indexTable inconsistent cell padding

- packages/ng/form-field/form-field.component.ts
Because we were only querying the first layer of content children, we were only fetching controls from it and not descendants, meaning that in cases like this:
```html
<lu-form-field>
<div class="inputWrapper">
<lu-text-input type="text"></lu-text-input>
<button luButton="text" type="button"></button>
</div>
</lu-form-field>
```
The `lu-text-input` component wasn't behaving properly with `aria-*` flags and the field wasn't detected as required.
-----
-----
> fix(form-field): get validators from descendants to handle deep inputs

- packages/ng/forms/radio-group-input/radio-group-input.component.ts
- packages/ng/forms/radio-group-input/radio/radio.component.html
- packages/ng/forms/radio-group-input/radio/radio.component.ts
- `<lu-radio disabled="false">...` is now properly enabled, as we're using the native `disabled` attribute, which evaluates `false` as `true` because it's non-null.
- `name` attribute is now set by the parent group to allow multiple `lu-radio-roup-input` to behave properly in the same page.
-----
-----
> fix(radio): disabled attribute and autogenerated name

- packages/ng/core/type/enum.ts
- packages/ng/core/type/index.ts
- packages/ng/user/display/display-format.model.ts
It is annoying to expose enum in templates, in addition to pass an enum value, we can now pass a string:
```html
{{ user | luUserDisplay:'fl' }}
{{ user | luUserDisplay:LuDisplayFullname.firstlast }}
```
-----
> feat(user): allow string union type for luUserInput format

- packages/ng/core-select/option/option-outlet.directive.ts
Handle option value falsy not displaying (false boolean or 0 number)
-----
> fix(core-select): handle option value falsy not displaying

- packages/ng/dialog/dialog.service.ts
- packages/ng/dialog/model/dialog-config.ts
Handled `cdkConfigOverride.canClose` option in `LuDialogService`
-----
Fixed JsDoc for `alert` property.
-----
> fixed(lu-dialog): handled canClose option in LuDialogService

- packages/ng/core-select/input/select-input.component.ts
- packages/ng/core-select/select.model.ts
- stories/documentation/forms/select/multi-select.stories.ts
- stories/documentation/forms/select/simple-select.stories.ts
* The condition was the opposite of what the old naming said
* Added a new strategy with the previous behavior
-----
Even if it is a breaking change, nobody uses it at the moment.
-----
> fix(core-select): wrong naming for if-clue-empty startegy

- README.md
- packages/scss/src/components/toast/component.scss
Toast kill button was misaligned only in iOS browsers
-----
iOS sets a default padding on this button, which is not there in other browsers ; unsetting it fixes the issue
Before:
After:
-----
> [Toast] Fix misaligned kill button in Safari iOS

- packages/ng/forms/radio-group-input/radio/radio.component.html
The `id` attribute of the radio input now corresponds to the `for` attribute of its label so that clicking on the label correctly triggers the selection of the attached option.
-----
-----
> fix(radio): add missing radio input id suffix

- packages/ng/multi-select/input/panel-ref.factory.ts
- packages/ng/multi-select/panel/panel.component.ts
- packages/ng/simple-select/input/panel-ref.factory.ts
- packages/ng/simple-select/panel/panel.component.ts
Pressing "Enter" when making a search without result was selecting either `null` or the last active item. This PR resets the active item when no options are displayed and stop sending `null` as a value.
-----
> fix(select): strange selection behavior on empty search result

- packages/scss/src/components/index.scss
- packages/scss/src/components/tableFixed/mods.scss
- packages/scss/src/components/tableSticked/mods.scss
- stories/documentation/listings/table/table-sticky-columns-breakpoints.stories.ts
- stories/documentation/listings/table/table-sticky-header.stories.ts
- stories/documentation/structure/grids/grids-auto-responsive-container.stories.ts
- stories/documentation/structure/grids/grids-auto-responsive.stories.ts
- stories/qa/table/table.stories.html
> Small adjustments for table sticky

- packages/ng/button/button.component.ts
- stories/documentation/actions/button/angular/button-basic.stories.ts
As described in #2739, this won't override already present type (like `submit` for instance) and won't be applied to `<a luButton>` tags, only `<button luButton>` ones.
-----
closes #2739
-----
> feat(button): apply default type set to `button` when not present on the button

- packages/ng/form-field/form-field.component.html
- packages/scss/src/components/formLabel/component.scss
- stories/documentation/forms/checkbox/checkbox-basic.stories.ts
- stories/documentation/forms/fields/number/angular/numberfield.stories.ts
- stories/documentation/forms/fields/text/angular/textfield.stories.ts
- stories/documentation/forms/fields/text/html&css/textfield-info.stories.ts
- stories/documentation/forms/fields/textarea/angular/textarea.stories.ts
- stories/documentation/forms/form-label/form-label-basic.stories.ts
- stories/documentation/forms/form-label/form-label-counter.stories.ts
- stories/documentation/forms/form-label/form-label-error.stories.ts
- stories/documentation/forms/form-label/form-label-size.stories.ts
- stories/documentation/forms/switch/switch-basic.stories.ts
- stories/documentation/integration/utilities/help.stories.ts
- stories/qa/form-label/form-label.stories.html
- stories/qa/forms/checkbox.stories.html
- stories/qa/forms/switch.stories.html
- stories/qa/forms/textfield.stories.html
Before:
After: 
-----
I'm also adding an alternative text to the icon, but until I can add a translation mechanism, I'm sticking with a very generic text « ? » for « help ».
-----
> Focus visible for tooltip informations in labels

- packages/ng/core-select/api/api-v3.directive.ts
- packages/ng/core-select/user/users.directive.ts
* do not send empty fields
* wrong operation parameter name
-----
> fix(core-select): do not send empty fields / wrong operation parameter name

- packages/ng/empty-state/empty-state-page/empty-state-page.component.html
- packages/ng/empty-state/empty-state-page/empty-state-page.component.ts
- packages/ng/empty-state/empty-state-section/empty-state-section.component.html
- packages/ng/empty-state/empty-state-section/empty-state-section.component.ts
- packages/scss/src/components/emptyState/component.scss
- packages/scss/src/components/emptyState/mods.scss
- stories/documentation/feedback/empty-state/angular/empty-state-page.stories.ts
- stories/documentation/feedback/empty-state/angular/empty-state-section.stories.ts
- stories/documentation/feedback/empty-state/html&css/empty-state-section.stories.ts
> Empty state titles

- packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
We cannot disable the new tooltip because of the wrong input transformer.
-----
-----
> fix(tooltip): wrong disable transform

- packages/ng/multi-select/displayer/counter-displayer/counter-displayer.component.scss
- packages/ng/multi-select/displayer/counter-displayer/counter-displayer.component.ts
- packages/ng/multi-select/displayer/index.ts
- stories/documentation/forms/select/multi-select.stories.ts
Reusable counter displayer for multi-select in order to show either the name when a single item is selected or `X selected` when multiple items are selected.
Usage example:
```html
<lu-multi-select
#selectRef
class="multiSelect"
[clearable]="clearable"
[loading]="loading"
[(ngModel)]="selectedLegumes"
placeholder="Placeholder..."
[options]="legumes | filterLegumes:clue"
(clueChange)="clue = $event"
[maxValuesShown]="maxValuesShown"
>
<ng-container *luMultiDisplayer="let values; select: selectRef">
<lu-multi-select-counter-displayer [selected]="values" label="things selected"></lu-multi-select-counter-displayer>
</ng-container>
</lu-multi-select>
```
@jeremie-lucca I think the docs part should be made inside ZH directly as it's where most of it already is, we really just need the above …
> feat(multi-select): new counter displayer

- packages/ng/core/date/date-adapter.class.ts
- packages/ng/core/date/date-adapter.interface.ts
- packages/ng/core/date/date-granularity.enum.ts
- packages/ng/core/date/native/native-date.adapter.ts
- packages/ng/core/date/string/string-date.adapter.ts
- packages/ng/date/calendar/calendar-input.component.ts
- packages/ng/date/calendar/calendar-item.class.ts
- packages/ng/date/calendar/calendar-item.interface.ts
- packages/ng/date/input/date-input.directive.ts
- packages/ng/date/picker/date-picker.component.ts
- packages/ng/date/select/date-select-input.component.ts
It is annoying to expose enum in templates, in addition to pass an enum value, we can now pass a string:
```html
<lu-date-select [granularity]="'month'" />
<lu-date-select [granularity]="ELuDateGranularity.month" />
```
-----
> feat(date): allow string union type for `lu-date-select`,`lu-date-picker`,`luDateInput` and `lu-calendar`

- packages/ng/dialog/dialog/dialog.component.ts
Correction de l'option `autofocus: 'first-input'` du `LuDialogService`
-----
-----
> fix(dialog): autofocus first-input

- packages/scss/src/commons/core.scss
A mixin for transposing CSS vars from one syntax to another.
-----
Possible examples of use after importing `@use '@lucca-front/scss/src/commons/core';`.
Generate a fallback for the legacy primary palette:
```sass
@include core.rosetta('--palettes-primary', '--palettes-product', ('text', '50', '100', '200', '300', '400', '500', '600', '700', '800', '900'));
```
Generate a fallback for the product palette:
```sass
@include core.rosetta('--palettes-product', '--palettes-primary', ('text', '50', '100', '200', '300', '400', '500', '600', '700', '800', '900'));
```
Generate a fallback for legacy spacings:
```sass
@include core.rosetta('--spacings', '--pr-t-spacings', ('0': '0', 'XXS': '50', 'XS': '100', 'S': '200', 'M': '300', 'L': '400', 'XL': '600', 'XXL': '800', 'auto': 'auto'));
``` …
> Rosetta mixin

- packages/ng/user/display/user-display.pipe.spec.ts
- packages/ng/user/display/user-display.pipe.ts
- stories/documentation/users/display/display.stories.html
- stories/documentation/users/display/display.stories.ts
Add multiple users param on LuUserDisplayPipe
N.B. Usage with single user param remains the same
-----
Examples : 
- In template: `{{ users | luUserDisplay: { format: 'LF', separator: '; '  } }}`
- With transform: `luUserDisplayPipe.transform(users, { format: 'LF', separator: '; ' });`
Defaut values:
- Format (same as single user): InjectionToken `LU_DEFAULT_DISPLAY_POLICY`
- Separator: `, `
Breaking changes :
- Before: Passing a null user displays an empty string
- After: Passing a null user throws an error
-----
> [2078] Add multiple users param on LuUserDisplayPipe

- packages/scss/src/components/scrollBox/component.scss
- packages/scss/src/components/scrollBox/vars.scss
Although it's not perfect, reducing shadows reduces the distance at which moving the scrollbar causes no shadows to appear.
-----
-----
> Scrollbox : shadow width reduction

- packages/scss/src/components/popover/component.scss
To avoid overlapping with the scrollbar.
-----
> Popover : close button on left

- packages/scss/src/components/notchBox/vars.scss
Improve box shadow
-----
We can't apply `--pr-t-elevation-shadow-raised` token as we use a filter `drop-shadow` on this component.
It would be possible to make a combination of 3 different `drop-shadow` but that would lead to a breaking change as some BU override `--component-notchbox-box-shadow` to remove or set a 1px border style shadow on Notch Box, so we decided to apply a single shadow quite close to orginal mockups.
-----
> [Notch box] Improve box shadow

- packages/ng/core-select/establishment/establishments.directive.ts
- packages/ng/core-select/job-qualification/job-qualifications.directive.ts
- packages/ng/core-select/user/users.directive.ts
We were encoding clue for search query twice in the APi directives, I removed that and the `split(' ').join(',')` behavior.
-----
closes #2903
-----
> fix(core-select): remove double URI encoding in API directives

- packages/ng/dialog/dialog.service.ts
- packages/ng/dialog/model/dialog-config.ts
- stories/documentation/overlays/dialog/dialog-canClose.stories.ts
Dialog close should not be handled by default by angular/cdk
Close can be disabled for click on backdrop
-----
-----
> fix(dialog): close can be disabled specifically for click on backdrop

- packages/ng/option/picker/option-picker.component.ts
The `overlayRef` may be null before changes appear. If so, just ignore the `updatePosition()` because there is no position to update.
-----
Currently throws an error in the console but does not impact the navigation flow.
-----
Please backport this fix on a 18.0 lts release so that Cleemy Expenses may be updated!
> fix(option-picker): overlayRef may be null

- packages/scss/src/components/dialog/component.scss
> Break word for dialog titles

- packages/scss/src/components/pageHeader/component.scss
- stories/documentation/structure/page-header/page-header-back.stories.ts
Add a link in front of the header title to go back to the parent section.
-----
-----
> Back button for page header

- packages/ng/core-select/api/api-v3.directive.ts
- packages/ng/core-select/api/api-v4.directive.ts
- packages/ng/core-select/api/api.directive.ts
- packages/ng/core-select/establishment/establishments.directive.ts
- packages/ng/core-select/input/select-input.component.ts
- packages/ng/core-select/job-qualification/job-qualifications.directive.ts
- packages/ng/core-select/user/user-homonym.service.ts
- packages/ng/core-select/user/users.directive.ts
- packages/ng/multi-select/panel/panel.component.html
- packages/ng/multi-select/panel/panel.component.ts
- packages/ng/simple-select/panel/panel.component.html
- packages/ng/simple-select/panel/panel.component.ts
- Avoid highlight issue by limiting the number of time usersDirective emits options. 
- Avoid blinking by adding a trackBy function on select panels (in a non-breaking way).
-----
Fix #2936
I will add a PR on RC to force user to add a `optionKey` on `ALuCoreSelectApiDirective` children.
-----
> fix(users): no highlighted item after clue change

- packages/ng/popover2/popover.directive.ts
Blocking the background scroll causes the scrollbar to disappear and triggers an unwanted shift + reflow.
-----
-----
Before: 
After:
> Remove scroll block for popover2

- packages/ng/empty-state/empty-state-page/empty-state-page.component.html
- packages/ng/empty-state/empty-state-page/empty-state-page.component.ts
- packages/ng/empty-state/empty-state-section/empty-state-section.component.html
- packages/ng/empty-state/empty-state-section/empty-state-section.component.ts
- stories/documentation/feedback/empty-state/angular/empty-state-page.stories.ts
- stories/documentation/feedback/empty-state/angular/empty-state-section.stories.ts
- stories/qa/forms/textfield.stories.html
The `title` attribute of the Angular component generates an HTML tooltip, so we change it to `heading`.
-----
-----
Before:
> Replace title with heading

- packages/ng/core-select/api/api.directive.spec.ts
- packages/ng/core-select/api/api.directive.ts
- packages/ng/core-select/panel/index.ts
- packages/ng/core-select/panel/key-manager.spec.ts
- packages/ng/core-select/panel/key-manager.ts
- packages/ng/core-select/user/user-homonym.service.ts
- packages/ng/core-select/user/users.directive.spec.ts
- packages/ng/core-select/user/users.directive.ts
- packages/ng/multi-select/input/panel-ref.factory.ts
- packages/ng/multi-select/panel/panel.component.ts
- packages/ng/simple-select/panel/panel.component.ts
- Extracted `CoreSelectKeyManager` to avoid duplication is simple/multi select panels. It makes Highlight logic more testable
- Fix issue in homonyms cache
- Fix highlight issue when using `LuCoreSelectUsersDirective`
- Fix missing clue when typing the first search when using `LuCoreSelectUsersDirective`
-----
-----
> fix(core-select): missing clue filter in users directive under some conditions

- packages/ng/core/translate/intl.model.ts
For teams who create/copy components relying on `getIntl`, the update from `ILuTranslation` to `LuTranslation` was breaking.
-----
-----
> fix(intl): remove breaking change by accepting legacy type in getIntl

- packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
- stories/documentation/overlays/tooltip/tooltip.stories.ts
We'd like to be able to deactivate the accessibility of tooltips when they only serve to repeat text that's already there (masked).
-----
This option disables `aria-describedby`.
-----
> Add option luTooltipOnlyForDisplay for tooltips

- packages/ng/popover2/content/popover-content/popover-content.component.ts
- packages/ng/popover2/popover.directive.ts
- packages/ng/popover2/popover2.translate.ts
- stories/documentation/overlays/popover2/popover2.stories.ts
On Focus, opens popover after the debounce specified by `luPopoverOpenDelay`.
On `Tab` with popover opened, focus on close button then popover's content, then trigger button again.
-----
-----
> feat(popover2): hover+focus trigger mode

- packages/scss/src/components/tableStickedDeprecated/mods.scss
- stories/documentation/listings/table-legacy/table-sticky-columns-breakpoints.stories.ts
`columnSticky` and `stickyColumn` existed. Only `stickyColumn` is retained.
Fix #1974 
-----
-----
> columnSticky is deprecated

- packages/ng/schematics/empty-state-title/index.ts
- packages/ng/schematics/empty-state-title/migration.spec.ts
- packages/ng/schematics/empty-state-title/schema.json
- packages/ng/schematics/empty-state-title/tests/template.input.html
- packages/ng/schematics/empty-state-title/tests/template.output.html
- packages/ng/schematics/lib/angular-template.ts
- packages/ng/schematics/migrations.json
- packages/ng/schematics/new-icons/index.ts
- packages/ng/schematics/new-icons/migration.ts
Automatically replace all `title` inputs of empty-states to `heading` input.
-----
Migration has been tested on PEO ([commit](https://github.com/LuccaSA/Poplee.Talent/commit/a873b56bd486bb6756b8b54df03bae1ab9c77a55))
-----
> feat(schematics): add empty-state-heading migration

- packages/scss/src/components/dialog/component.scss
The positioning of a sticky element seems to take place in Safari at the end of the animation.
So that the footer doesn't interfere with the display during loading, I suggest displaying it later on this browser.
Fix #2599 
-----
-----
Before: 
After:
> Fix footer on dialogs with Safari

- packages/scss/src/components/tooltip/component.scss
Disables the tooltip automatically generated by Safari when it detects truncated text.
-----
-----
Before:
> Remove tooltip generated by Safari desktop

- packages/scss/src/components/indexTable/component.scss
- packages/scss/src/components/indexTable/states.scss
- stories/documentation/listings/index-table/index-table-actions-touch-detection.stories.ts
- stories/documentation/listings/index-table/index-table-actions.stories.ts
- stories/documentation/listings/index-table/index-table-basic.stories.ts
- stories/documentation/listings/index-table/index-table-footer.stories.ts
- stories/documentation/listings/index-table/index-table-interactive-nested-selectable.stories.html
- stories/documentation/listings/index-table/index-table-layout-fixed-responsive.stories.ts
- stories/documentation/listings/index-table/index-table-layout-fixed.stories.ts
- stories/documentation/listings/index-table/index-table-mass-selection-and-pagination.stories.ts
- stories/documentation/listings/index-table/index-table-nested-selectable.stories.ts
- stories/documentation/listings/index-table/index-table-nested-sub-totals.stories.ts
- stories/documentation/listings/index-table/index-table-nested.stories.ts
- stories/documentation/listings/index-table/index-table-responsive-card-list-custom.stories.ts
- stories/documentation/listings/index-table/index-table-responsive-card-list-label.stories.ts
- stories/documentation/listings/index-table/index-table-responsive-card-list-nested.stories.ts
- stories/documentation/listings/index-table/index-table-responsive-card-list.stories.ts
- stories/documentation/listings/index-table/index-table-selectable.stories.ts
- stories/documentation/listings/index-table/index-table-sorted.stories.ts
- stories/documentation/listings/index-table/index-table-stackable.stories.ts
- stories/documentation/listings/index-table/index-table-sticky-header.stories.ts
Users have expressed the need to be able to open links in tables to new tabs  (via the right-click menu, for example).
To do this, these links must not be hidden and must be visible in the interface.
`.indexTable-body-row-cell-action` is therefore deprecated and replaced by `.indexTable-body-row-cell-link`, which is its unmasked equivalent, and following @BertrandPodevin's idea, we extend this link so that it can be operated on the whole line, without requiring an `overflow: hidden`, `z-index`, or superimposing itself on other interactive elements.
-----
-----
> Show index table link

- packages/scss/src/components/toast/component.scss
- packages/scss/src/components/toast/vars.scss
#2131 
⚠️ This shift in the footer when a footer is detected is a test. The size of the footer may be wrong, as may its position.
-----
-----
> Toast position when footer is present

- packages/ng/core-select/user/users.directive.ts
- On users core-select directive, former employees query param was not the one expected by `api/v3/users/search` (`formerEmployee != formerEmployees`)
-----
> fix(core-select): fix former employees param for users core select

- packages/icons/src/commons/core.scss
In the `icons` package, there is an import from the `scss` package, which is an error and is also unused. The `icons` package must be independent and this bug prevents LF/icons to be used alone.
The import being unnecessary as no `config` sass variables are used in this file, we simply remove it.
-----
I noticed it while upgrading LF on a project which uses only the `icons` package.
> fix(icons): config path

- packages/ng/dialog/directives/dialog-open.directive.ts
This was due to config being applied after content, overriding its value.
-----
closes #2999
-----
> fix(dialog): content is `null` when using `[luDialogConfig]` in a template-driven approach

- stories/documentation/overlays/dialog/dialog.stories.ts
Story was using a `formControl` instead of a `formGroup`, stupid mistake from my past self
-----
-----
> fix(story): dialog story not opening with focus set to first-input

- packages/ng/forms/multilanguage-input/multilanguage-input.component.html
- packages/ng/popover2/content/popover-content/popover-content.component.html
- packages/ng/popover2/content/popover-content/popover-content.component.ts
- packages/ng/popover2/popover-tokens.ts
- packages/ng/popover2/popover.directive.ts
- stories/documentation/overlays/popover2/popover2.stories.ts
Add option to remove keyboard close button + apply it to multilanguage
-----
> [Popover2] Add option to remove keyboard close button

- stories/documentation/forms/time/duration-picker-angular.stories.ts
The masked fieldset legend was empty.
-----
-----
> [DurationPicker] Fix legend

- packages/scss/src/components/checkboxField/component.scss
- packages/scss/src/components/radioField/component.scss
Based on an idea by @BertrandPodevin, simplified positioning of radio buttons and checkboxes.
Hopefully, this will also correct the sometimes slightly off-centering under Windows when zoom is applied.
-----
-----
> Replace absolute position with grid

- packages/ng/core-select/api/api.directive.spec.ts
- packages/ng/core-select/api/api.directive.ts
*  optionKey is mandatory on ApiDirectives
-----
This will need to be rebased on RC once #2949 is merged and rc is up-to-date with master. Only [this commit](https://github.com/LuccaSA/lucca-front/pull/2950/commits/d961ce992234366c917d7550e14e1e3ca13d118c) is relevant.
This is a breaking change. On all classes that extend `ALuCoreSelectApiDirective`, apps have to:
```diff
class MyDirective extends ALuCoreSelectApiDirective {
+	protected override optionKey = (option: T) => option.id;
}
```
-----
> ref(core-select)!: optionKey is mandatory on ApiDirectives

- packages/ng/schematics/action-icon/index.ts
- packages/ng/schematics/empty-state-title/index.ts
- packages/ng/schematics/new-icons/index.ts
- packages/ng/schematics/palettes/index.ts
- packages/ng/schematics/tokens-spacing/index.ts
Because of a strange logic in Nx migration system, LF's scripts were not called as they would be with `@angular/cli`.
The issue seems tracked in https://github.com/nrwl/nx/issues/20282
-----
-----
> fix(schematics): support nx migration logic

- Jenkinsfile
When `package.json` are published, there is a `v` in `peerDependencies` which can lead to peer deps issues.
-----
-----
> ci: strip "v" from env.BRANCH_NAME if it's a release or pre-release

- packages/ng/date/input/date-input.directive.ts
- packages/ng/date/select/date-select-input.component.ts
Fix date picker "month" granularity mode.
-----
Change date format to match `datePipe` [custom format option](https://angular.dev/api/common/DatePipe?tab=usage-notes) (use in [formatDate](https://angular.dev/api/common/formatDate))
-----
> date pipe custom format options

- packages/ng/popover2/popover.directive.ts
- Add an `exportAs: "luPopover2` to `luPopover2` directive
- Provide a `close()` method to allow closing from the outside
-----
-----
> feat(popover): add exportAs and provide close method

- packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
Focus on popover closure triggers tooltips when buttons combine both behaviors. This has now been corrected.
-----
-----
Before: 
After:
> Fix tooltip + popover

- packages/scss/src/components/tag/component.scss
- packages/scss/src/components/tag/mods.scss
- packages/scss/src/components/tag/vars.scss
Color is now always in 800.
-----
-----
Before: 
After:
> Fix tag outlined color

- packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
- stories/documentation/overlays/tooltip/tooltip-ellipsis.stories.ts
Calculation with a clone posed problems because the clone was injected into a `div`, itself injected into the current context, which posed structural problems.
Moving the clone into the body, on the other hand, posed inheritance problems.
So we've changed our approach: we now duplicate the properties rather than the element.
-----
-----
> Fix ellipsis calculation

- packages/ng/dialog/dialog-header/dialog-header.component.html
- packages/ng/popover2/content/popover-content/popover-content.component.html
- packages/ng/toast/toasts.component.html
- packages/scss/src/components/calloutAccordion/mods.scss
- packages/scss/src/components/calloutDisclosure/mods.scss
- packages/scss/src/components/calloutPopover/mods.scss
- packages/scss/src/components/dialog/component.scss
- packages/scss/src/components/footer/component.scss
- packages/scss/src/components/indexTable/component.scss
- packages/scss/src/components/multiSelect/mods.scss
- packages/scss/src/components/plgPush/component.scss
- packages/scss/src/components/popover/component.scss
- packages/scss/src/components/simpleSelect/mods.scss
- packages/scss/src/components/switchField/component.scss
- packages/scss/src/components/tableSortable/index.scss
- packages/scss/src/components/textField/mods.scss
- packages/scss/src/components/textfields/mods.scss
- packages/scss/src/components/toast/component.scss
- packages/scss/src/components/userPopover/component.scss
- stories/documentation/listings/index-table/index-table-sortable.stories.ts
SCSS components can be loaded via an explicit CSS call, but also via NG components.
As the order in which NG components were called could not be controlled, we ended up with style overloads when components were nested and overloaded within other components.
In this PR, I increase the specificity of selectors when this happens, to ensure that the order in which CSS components are called up no longer interferes. 
-----
-----
> Fix selector specificity for nested components

- packages/scss/src/components/footer/component.scss
- packages/scss/src/components/footer/vars.scss
The alignment of the various .containers did not take into account the footer padding.
-----
-----
Before:
After:
> [Footer] Fix container width

- packages/ng/forms/phone-number-input/validators.ts
`countryCode` was missing while using `isValidPhoneNumber` in `PhoneNumberValidators`
So control values like below were incorrectly invalid :
- value : 07 56 45 68 98 -> invalid if no country provided, valid with 'FR'
- countryCode: FR -> wasn't used
-----
-----
> fix(phone-number-input): validator wasn't using missing the country code

- packages/scss/src/components/checkboxField/index.scss
- stories/qa/forms/checkbox.stories.html
Unchecked indeterminate checkboxes were not indicated as indeterminate, wrongly. This has now been corrected.
-----
-----
Before:
After:
> Checkbox unchecked mixed

- packages/scss/src/components/form/component.scss
> Fix form field margins

- packages/ng/callout/callout-disclosure/callout-disclosure.component.html
- packages/ng/callout/callout-disclosure/callout-disclosure.component.ts
- packages/ng/callout/callout-icon.pipe.ts
- packages/ng/callout/callout-popover/callout-popover.component.html
- packages/ng/callout/callout-popover/callout-popover.component.ts
- packages/ng/callout/callout-state.ts
- packages/ng/callout/callout.utils.spec.ts
- packages/ng/callout/callout.utils.ts
- packages/ng/callout/callout/callout.component.html
- packages/ng/callout/callout/callout.component.ts
When callout state input was updated multiple times without icon and palette inputs then the palette and icon doesn't refresh with state value.
-----
The callout state input setter was modifying other palette and icon inputs instead of just rendering.
This problem would have been detected using signal inputs because it's not writable signals.
-----
> [Callout] Set callout state input multiple times doesn't work

- packages/scss/src/components/button/component.scss
- packages/scss/src/components/menu/states.scss
- packages/scss/src/components/numericBadge/mods.scss
- packages/scss/src/components/radioButtons/component.scss
- packages/scss/src/components/segmentedControl/states.scss
- stories/documentation/actions/button/html&css/button-counter.stories.ts
Mixin `product` becomes `inherit` and applies not just a product palette but an inherited palette.
-----
-----
Before:
After:
> [numericBadge] inherit mixin

- packages/scss/src/components/radioField/component.scss
- packages/scss/src/components/switchField/component.scss
For reasons I couldn't explain, the radio input doesn't take up the whole space of the `radio` grid area in Safari, making it hard to click.
This PR fixes it by forcing the width and height attributes of the input to 100% of the container.
-----
> [Radio] Fix input size in Safari

- packages/ng/forms/textarea-input/textarea-input.component.html
- packages/ng/forms/textarea-input/textarea-input.component.ts
- packages/scss/src/components/textField/component.scss
- packages/scss/src/components/textField/index.scss
- packages/scss/src/components/textField/mods.scss
- packages/scss/src/components/textField/vars.scss
- stories/documentation/forms/fields/textarea/angular/textareafield.stories.ts
- stories/documentation/forms/fields/textarea/html&css/textareafield.stories.ts
New options for textareas:
- autoResize: disables browser resize and calculates the appropriate height for the current textarea value.
- scrollIntoView: ensures that a textarea that changes size is always fully visible in the interface.
- A maximum height of 80% of the viewport height has also been added.
- The options are added to the Angular component and also to the HTML component via a JS one-liner.
-----
Thanks @Supamiu for the helping hand!
-----
> [Textarea] Add autoResize and scrollIntoView options

- packages/ng/form-field/form-field.component.ts
- packages/ng/inline-message/inline-message.component.ts
- Fix support of `PortalContent` in `lu-inline-message`
- Add support for `PortalContent` as input in `lu-form-field`'s `inlineMessage` and `errorInlineMessage` inputs.
-----
-----
> fix(inline-message): properly handle PortalContent

- packages/scss/src/components/filters/index.scss
- packages/scss/src/components/filters/mods.scss
- packages/scss/src/components/header/index.scss
- packages/scss/src/components/header/mods.scss
- packages/scss/src/components/layout/component.scss
- packages/scss/src/components/layout/mods.scss
- packages/scss/src/components/main/component.scss
- packages/scss/src/components/main/index.scss
- packages/scss/src/components/main/mods.scss
- packages/scss/src/components/navside/mods.scss
- packages/scss/src/components/navside/vars.scss
- stories/qa/secondary-nav/secondary-nav-compact.stories.html
- stories/qa/secondary-nav/secondary-nav-compact.stories.ts
- stories/qa/secondary-nav/secondary-nav.stories.html
Switch to a single CSS var to manage the `.navSide.mod-compact`.
This will greatly simplify the use of the variable, which ends up being :
- for screen widths below `S` to `0`;
- for screen widths above `S` :
- to `15rem` if navSide has no mod-compact;
- to `7.5rem` if navSide has mod-compact.
`--commons-navSide-compact-width` is deprecated, but a fallback is provided.
-----
Thanks to @nsarradin  and the other workshop members for their joint reflections.
-----
> [navSide] css vars for width

- packages/ng/core/type/style.ts
- packages/ng/tag/tag.component.ts
Add a new type for decorative palette so the components that should handle them can, such as tag.
-----
-----
> feat: new DecorativePalette type for when they can be used as palette

- packages/ng/dialog/dialog/dialog.component.scss
- packages/scss/src/components/dialog/component.scss
- change of flex for grid requires revision of `cdk-dialog-container` code
- as the footer of the dialog may overflow, a hidden is also added to it
-----
-----
> [dialogs] subgrid + overflow

- packages/scss/src/components/grid/component.scss
We need to revert grid width management as it breaks UI on some grid/flex contexts (like horizontal fieldset).
-----
@fbasmaison-lucca We could reconsider this fix after the release
-----
> [Grid] Revert grid width management

- packages/ng/date2/calendar2/calendar2.component.html
- packages/scss/src/components/textField/component.scss
- packages/scss/src/components/textField/vars.scss
1. aria-selected was miscalculated in case of null.
2. max height is reserved for textarea and calculated differently
3. typo on textfield vars
-----
-----
> Fixes : textarea + typo + calendar

- packages/ng/core-select/api/api-v4.directive.ts
- packages/ng/core-select/establishment/establishments.directive.ts
- packages/ng/core-select/job-qualification/job-qualifications.directive.ts
- packages/ng/core-select/public-api.ts
- packages/ng/core-select/select.utils.ts
- packages/ng/core-select/user/users.directive.ts
- stories/documentation/forms/select/custom-api-example.component.ts
Allow to use searchDelimiter input for apiV4 select to search with comma delimiter for example.
By default it's space delimiter
-----
-----
> feat(core-select): Add custom search delimiter for apiV4

- packages/scss/src/components/dialog/component.scss
A `grid-area` was missing for cases where all 3 children (header/overflow/footer) in a dialog are not present.
-----
-----
Before:
After:
> [dialog] fix grid without header

- packages/scss/src/components/calloutDisclosure/component.scss
- The arrow now correctly rotates around its own axis,
- Safari's custom summary marker has been removed.
https://github.com/user-attachments/assets/90858c6e-ddaa-41ae-9894-db5eb0858980
-----
> fix(callout): #3170 Callout disclosure fixes

- packages/scss/src/components/loading/mods.scss
Mod-page centering did not cancel out vertical centering in flex containers.
-----
-----
> [loading] mod-page centering

- packages/ng/core/portal/portal.directive.ts
When `luPortal` is called with a non-component object as parameter, such as the output of a `| translate` when `count` parameter is `null`, making the pipe lie to us as it no longer returns a `string` but will instead return an `object`, the following error message appears (courtesy of @ArthurVinbeau for the screenshot):
It's really not meaningful and it takes quite some time to dig through the code and realize that Angular detects a random object as `ComponentFactory` and thus thinks we're calling it with the wrong parameters for the signature we're supposed to be using.
But in reality, the issue is just that we're passing it an object.
This PR adds a better error message for this case because it's impossible to use `luPortal` with a `ComponentFactory` anyways.
-----
-----
> chore(lu-portal): add error message for when Angular fails to create component

- packages/ng/multi-select/input/select-all/with-select-all.directive.ts
- packages/ng/multi-select/input/select-input.component.spec.ts
Before this fix, mode "all" was emitted.
See https://github.com/LuccaSA/Lucca.Analytics/pull/570#issuecomment-2464221121
-----
-----
> fix(multi-select): emit mode none when select all then unselect each

- packages/ng/multi-select/displayer/displayer-input.directive.ts
We were using the wrong Input directive, resulting in `luInput` missing from the native input, thus breaking links with error manegement and label aria.
Reported by @dclary-lucca 
-----
-----
> fix(multi-select): fix errors display and aria stuff on displayer

- packages/scss/src/components/form/mods.scss
Fix spacing gap jump when box appear/disappear
-----
Fixed by keeping the default top margin (even when there is a box)
-----
> [Form field with arrow] Fix spacing gap jump when box appear/disappear

- packages/ng/multi-select/input/select-all/with-select-all.directive.ts
- packages/ng/multi-select/input/select-input.component.spec.ts
The error thrown when an array value is passed to a `<lu-multi-select withSelectAll />` is imprecise. It refers to a non-exported type which is misleading.
This PR fixes that and refers to the exported type used by this directive.
-----
> fix(withSelectAll): exported type in error

- packages/scss/src/components/userTile/component.scss
- stories/documentation/users/tile/html&css/basic.stories.ts
- stories/documentation/users/tile/html&css/sizes.stories.ts
- stories/qa/user-tile/user-tile.stories.html
Apply avatar height calculation only if it has user info (to avoid component extra height)
-----
-----
> [User tile] Fix component height without user info

- packages/ng/callout/callout-disclosure/callout-disclosure.component.html
Better icon positioning for callout disclosure.
-----
-----
Before:
After:
> [callout] fix disclosure icon

- packages/ng/core-select/input/select-input.component.ts
- packages/ng/multi-select/input/select-input.component.ts
- stories/documentation/forms/select/multi-select.stories.ts
> feat(multi-select): new keepSearchAfterSelection option to skip clear on value update

- packages/scss/src/components/checkboxField/index.scss
States combined with mixed + !checked were missing (hover, active, disabled, invalid).
-----
-----
> [checkbox] mixed states

- packages/ng/date2/date-input/date-input.component.ts
We used to compare month value, which was bad because months are the same accross years, obviously...
-----
-----
> fix(date-input): properly handle min/max in a month picker configuration

- packages/ng/core-select/api/api-v4.directive.ts
- packages/ng/core-select/establishment/establishments.directive.ts
- packages/ng/core-select/job-qualification/job-qualifications.directive.ts
- packages/ng/core-select/select.utils.ts
- packages/ng/core-select/user/users.directive.ts
We used to encode search clue but now that we're using `HttpClient`'s `params`, Angular already takes care of the encoding for us.
-----
-----
> fix(users-select): remove extra encoding

- packages/ng/dialog/dialog-header/dialog-header.component.ts
> fix(dialog-header): _addAriaLabelledBy call is now null-safe

- packages/scss/src/components/textField/component.scss
Fix wrapping prefix 
-----
Before 
After
-----
> [Textfield] Fix wrapping prefix 

- packages/ng/multi-select/public-api.ts
- packages/ng/multi-select/select.validators.ts
Implemented the `required` validator for `LuMultiSelection` controls, which checks if the selection mode is set to 'none' and returns a validation error if true.
-----
> feat(select): add required validator for multiselection control

- packages/scss/src/components/indexTable/component.scss
- packages/scss/src/components/indexTable/mods.scss
- packages/scss/src/components/indexTable/vars.scss
Fixes #3241 
-----
The [padding had been modified on the cells to allow the focus-visible to overflow](https://lucca.slack.com/archives/C03GH0104NB/p1712147102570079), but now that it's increased, there's no need to worry about this.
NB: the width of the cells changes slightly, which can cause changes in the BUs.
-----
Before:
After:
> [indexTable] adjust paddings

- packages/ng/date2/date-input/date-input.component.html
- packages/ng/date2/date-input/date-input.component.ts
- packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
- Date input no longer considers `null` as invalid as far as Validation goes
- Date input now handles validation errors for `min` and `max` too
-----
-----
> fix(date-input): validators logic fixes

- packages/ng/core-select/input/select-input.models.ts
- packages/ng/multi-select/input/panel-ref.factory.ts
- packages/ng/multi-select/input/select-input.component.ts
- packages/ng/simple-select/input/panel-ref.factory.ts
- packages/ng/simple-select/input/select-input.component.ts
WebComponents cannot used selects due to the overlay container override. 
We use the child to update overlay container properties and not the override.
Delete provideLuSelectOverlayContainer() and add attributes aria-labelledby & lu-select-overlay-container in the panel factory
-----
> refactor(select): do not override overlay container

- packages/scss/src/commons/utils/reset.scss
- stories/documentation/integration/utilities/reset.stories.ts
The disc/circle/square styles were not reset.
-----
-----
Before:
After:
> [utils] reset list

- packages/scss/src/commons/base.scss
- packages/scss/src/commons/config.scss
- packages/scss/src/commons/core.scss
- packages/scss/src/commons/utils/index.scss
- packages/scss/src/commons/vars.scss
- stories/documentation/texts/text/text.stories.ts
Disable cursive font support:
```scss
@use '@lucca-front/scss/src/commons/config' with (
$fontFamilyCursive: false,
);
```
Load another font cursive (or rename it to sandbox) + define define its weights:
```scss
@use '@lucca-front/scss/src/commons/config' with (
$fontFamilyCursive: 'Lorem',
$fontWeightsCursive: (
'ultra-light': 100,
'light': 200,
'book': 300,
'regular': 400,
'medium': 500,
'semibold': 600,
'bold': 700,
'black': 800,
'extra-black': 900,
),
);
```
-----
-----
> Font face cursive (for caveat)

- stories/documentation/overlays/dialog/dialog-basic.stories.ts
- stories/documentation/overlays/dialog/dialog.stories.ts
Size as select control & show mod-neutralBackground version
-----
-----
> [Dialog] Size as select control & show mod-neutralBackground version

- packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
Signal-based logic made tabindex logic go boom.
-----
-----
> fix(tooltip): missing tabindex when using without ellipsis logic

- packages/ng/popup-employee/card/panel/user-popover-panel.component.html
- packages/ng/popup-employee/card/panel/user-popover-panel.component.ts
- packages/ng/popup-employee/popup-employee.translate.ts
- packages/ng/popup-employee/translations.ts
> fix(user-popover): remove useless alt and add alts on icons

- packages/scss/src/commons/base.scss
- packages/scss/src/commons/config.scss
- packages/scss/src/commons/utils/color.scss
- packages/scss/src/components/callout/component.scss
- packages/scss/src/components/calloutFeedbackList/component.scss
Now we can simply make a call to `@include color.palette('neutral');` to generate a palette via mixin.
-----
-----
> Remove circular dependency

- packages/scss/src/components/navside/mods.scss
Older versions of Firefox ESR do not support `:has`. A fallback is provided for this major component.
-----
-----
> [navside] Add support for ESR

- packages/ng/skeleton/skeleton-data-table/skeleton-data-table.component.html
- packages/ng/skeleton/skeleton-index-table/skeleton-index-table.component.html
- packages/ng/skeleton/skeleton-table/skeleton-table.component.html
- stories/documentation/actions/links/angular.stories.ts
- stories/documentation/listings/data-table/html&css/alignement-horizontal.stories.ts
- stories/documentation/listings/data-table/html&css/alignement-vertical.stories.ts
- stories/documentation/listings/data-table/html&css/basic.stories.ts
- stories/documentation/listings/data-table/html&css/cell-border.stories.ts
- stories/documentation/listings/data-table/html&css/draggable.stories.ts
- stories/documentation/listings/data-table/html&css/editable.stories.ts
- stories/documentation/listings/data-table/html&css/filter.stories.ts
- stories/documentation/listings/data-table/html&css/fixed-columns-responsive.stories.ts
- stories/documentation/listings/data-table/html&css/fixed-columns.stories.ts
- stories/documentation/listings/data-table/html&css/group.stories.ts
- stories/documentation/listings/data-table/html&css/overflow-both.stories.ts
- stories/documentation/listings/data-table/html&css/overflow-horizontal.stories.ts
- stories/documentation/listings/data-table/html&css/overflow-vertical.stories.ts
- stories/documentation/listings/data-table/html&css/quick-actions.stories.ts
- stories/documentation/listings/data-table/html&css/selectable.stories.ts
- stories/documentation/listings/data-table/html&css/sticky-columns-multiple.stories.ts
- stories/documentation/listings/data-table/html&css/sticky-columns.stories.ts
- stories/documentation/listings/data-table/html&css/sticky-header-columns.stories.ts
- stories/documentation/listings/data-table/html&css/sticky-header.stories.ts
- stories/documentation/listings/data-table/html&css/tree.stories.ts
- stories/documentation/loaders/skeleton-data-table/angular/skeleton-data-table-body.stories.ts
> [19.1] Stories

- stories/documentation/integration/utilities/reset.stories.ts
- stories/documentation/structure/divider/angular/divider-basic.stories.ts
- stories/documentation/structure/divider/html&css/divider-basic.stories.ts
- stories/documentation/structure/fancy-box/html&css/fancy-box-basic.stories.ts
- stories/documentation/texts/numeric-badge/html&css/numeric-badge-size.stories.ts
- stories/documentation/texts/status-badge/html&css/status-badge-palettes.stories.ts
> [19.1] Format stories (2)

- packages/ng/dialog/dialog-header/dialog-header.component.html
When opening a popover, the `mod-onlyIcon` loaded in the popover CSS would overwrite the mixin `onlyIconS`. By deleting the `luButton`, the class is no longer generated and the bug no longer occurs.
-----
https://lucca.slack.com/archives/C3W78FWUU/p1733828859780829
-----
Before:
After:
> [dialog] close + popover

- docs/core-select-users-directive.md
- docs/multi-select-all.md
MD heading levels for ZH integration
-----
> MD heading levels for ZH integration

- packages/ng/popup-employee/card/panel/user-popover-panel.component.html
- stories/documentation/forms/select/multi-select.stories.ts
- stories/documentation/forms/select/simple-select.stories.ts
- stories/documentation/listings/index-table/index-table-layout-fixed-responsive.stories.ts
- stories/documentation/listings/index-table/index-table-responsive-card-list-custom.stories.ts
Remove deprecated spacings
-----
> Remove deprecated spacings

- packages/ng/form-field/form-field.component.ts
- stories/documentation/forms/fields/form-field-async-loading.stories.ts
Because we were refreshing controls based on the new `events` observable, it's not emitting anything until an actual event is pushed in the Observable.
I solved this by just adding an initial start value so we can have the control's initial state.
Also added a story for testing purpose.
-----
-----
> fix(form-field): async loading for controls detection + test story

- .storybook/msw/handlers.ts
- packages/ng/core-select/user/users.directive.ts
- stories/documentation/forms/select/multi-select.stories.ts
`users` directive was overriding `panelHeaderTpl` with `undefined` instead of letting the template added by `withSelectAll`.
Bonus, `totalCount$` was wrong because a V3 API was called using a V4 fields 🙈 
-----
-----
> fix(multi-select): wrong API for users count and wrong override of panelHeaderTpl

- stories/documentation/forms/date2/date-range-input.stories.ts
> docs(date-range): add premade shortcuts story

- packages/ng/department/select/feeder/department-feeder.component.ts
- packages/ng/department/select/input/department-select-input.component.html
- packages/ng/department/select/input/department-select-input.component.ts
- packages/ng/department/service/department-v4.service.ts
- stories/documentation/forms/department/department-select.stories.ts
Add missing uniqueOperation for new api departments
https://github.com/LuccaSA/Organization.Structure/blob/81b1399a45228ba73d6eecd6177268065792bc16/back/src/Organization.Structure.Web/Controllers/Departments/TreeController.cs#L33
-----
-----
> fix: add uniqueOperation params for new departments api

- packages/ng/tag/tag.component.ts
In order to avoid using `@if` / `@else` to manage cases where we don't want icons, I propose to accept `undefined` as value for the icon input.
Simplify this...
```typescript
@if (isExpired()) {
<lu-tag
[label]="textKey() | transloco: textParams"
icon="error"
palette="error"
/>
} @else {
<lu-tag
[label]="textKey() | transloco: textParams"
palette="product"
outlined
/>
}
``` 
...with that
```typescript
<lu-tag
[label]="textKey() | transloco: textParams"
[icon]="isExpired() ? 'error' : undefined"
[palette]="isExpired() ? 'error' : 'product'"
[outlined]="!isExpired()"
/>
``` 
-----
-----
> feat(tag): Authorize undefined value for icon

- packages/ng/forms/multilanguage-input/multilanguage-input.component.html
- packages/scss/src/commons/base.scss
- packages/scss/src/commons/config.scss
- packages/scss/src/commons/vars.scss
- packages/scss/src/components/emptyState/component.scss
- packages/scss/src/components/errorPage/component.scss
- packages/scss/src/components/index.scss
- packages/scss/src/components/textFlow/component.scss
- packages/scss/src/components/textFlow/exports.scss
- packages/scss/src/components/textFlow/index.scss
- packages/scss/src/components/textFlow/vars.scss
- packages/scss/src/components/title/component.scss
- stories/documentation/texts/text-flow/html&css/basic.stories.ts
- stories/qa/text-flow/text-flow.stories.html
- stories/qa/text-flow/text-flow.stories.ts
- Remove titles spacings by default (margin + padding)
- Provide a deprecated flag `$deprecatedTitleSpacings` on `config.scss`
- Override a bunch of component to be iso with or without flag activated
-----
> Remove titles spacing

- packages/ng/core-select/input/select-input.component.spec.ts
- packages/ng/core-select/input/select-input.component.ts
- packages/ng/core-select/no-clue/index.ts
- packages/ng/core-select/no-clue/no-clue.directive.spec.ts
- packages/ng/core-select/no-clue/no-clue.directive.ts
- packages/ng/core-select/public-api.ts
- stories/documentation/forms/select/simple-select.stories.ts
In some niche cases, we cannot implement a search feature on an API. The `noClue` allows apiV4/apiV3 usage on these APIs.
When testing on a story, I found a bug: when typings a character to open a select, it would update the clue even if the select is not searchable.
-----
-----
> feat(core-select): add a noClue directive to disable apiV3/V4 search

- stories/documentation/listings/index-table/index-table-mass-selection-and-pagination.stories.ts
- stories/documentation/navigation/pagination/pagination-basic.stories.ts
- stories/documentation/navigation/pagination/pagination-compact.stories.ts
- stories/documentation/navigation/pagination/pagination-pages.stories.ts
- stories/qa/pagination/pagination.stories.html
Following the accessibility audit, we were asked to replace the `aria-labelledby` attribute on the `<nav>` element with an `aria-label` attribute. ([See criteria 9.2](https://docs.google.com/spreadsheets/d/1T7LIRH6YSZINQwhJ_tl2pcm0jIRrro98UkLF9xCgjpQ/edit?gid=644615132#gid=644615132))
-----
> docs(pagination): replace "aria-labelledby" with "aria-label"

- packages/ng/link/link.component.ts
Allows the directive to be placed on a button. And removes the mandatory label that was not used.
-----
-----
> [link] fix label

- packages/ng/number-format/number-format.directive.ts
The following condition has been removed :
- if value has not been changed, `blur` event will no trigger `onTouched`
-----
Before fix
https://github.com/user-attachments/assets/64416a2a-532a-407d-8efa-ac835c67fe52
After fix
https://github.com/user-attachments/assets/d1566abf-c00c-438d-b2a3-40f567657257
-----
> fix(number-format): touched should be triggered even if value has not been changed

- packages/ng/date2/calendar2/calendar2.component.ts
- packages/ng/date2/date-input/date-input.component.ts
- packages/ng/date2/date-range-input/date-range-input.component.ts
Remove deprecated allowSignalWrites options
Prevent a warning message in console 
`The 'allowSignalWrites' flag is deprecated and no longer impacts effect() (writes are always allowed)`
-----
-----
> chore: remove allowSignalWrites options in effect

- packages/ng/form-field/form-field.component.ts
When using `[invalid]="condition"`, the form field was always in error, as `invalidStatus` computed signal was always returning `true` whatever the `invalid` input boolean value passed.
-----
> fix(form-field): Use invalid input value

- packages/scss/src/components/dataTable/component.scss
An overflow occurs with webkit in certain (unidentified) contexts, and is fixed with a contain.
-----
-----
> [dataTable] fix overflow with WebKit

- packages/ng/form-field/form-field.component.ts
Allow using `string` instead of `number` for the input `width` of `lu-form-field`.
Works :
```html
<lu-form-field width="20">...</lu-form-field>
```
Does'nt works (because `width` must be in range of `20 | 30 | 40 | 50 | 60`) :
```html
<lu-form-field width="42">...<lu-form-field>
```
-----
-----
> feat(lu-form-field): allow string to width input

- packages/ng/dialog/dialog-routing/dialog-routing.utils.ts
Dialog routing was not taking providers into account.
-----
-----
> fix(dialog): wrong spread operator

- packages/ng/core-select/user/users.directive.ts
A generic was missing so it was not possible to override CoreSelectUserDirective with a custom User type.
-----
-----
> fix(core-select): custom core-select user directive typing

- packages/scss/src/components/tableSortable/component.scss
Fix padding with `luButton` & `luIcon`
-----
... by overriding `.withIcon` padding generated by `luButton`
https://github.com/LuccaSA/lucca-front/issues/3453
-----
> [Table sortable] Fix padding with luButton & luIcon

- packages/scss/src/components/dataTable/index.scss
- packages/scss/src/components/indexTable/index.scss
it's not clear at glance why it's an attribute selector that is used here with the `*=` option, so i just add an explanation of what this selector can achieve.
-----
> feat(tables): attribute selector target explanation

- packages/scss/src/components/textFlow/component.scss
To avoid extra margins, we can remove first-child’s start margin and last-child’s end margin.
This is especially useful in isolated context (eg: modals’ content), which seems to be the use-case for `.textFlow`.
Their container can be added extra margins if need be.
-----
-----
> [textFlow] Remove margins on both ends of `.textFlow`

- packages/ng/simple-select/panel/panel.component.html
This was due to cdk trap configured to grab focus on init, which made it focus the first input available.
-----
-----
> fix(former-employees): don't focus checkbox when panel is opened

- packages/ng/core-select/option/option.component.html
- packages/ng/core-select/option/option.component.ts
- packages/ng/simple-select/panel/panel.component.html
Identical ids were generated in lists with groups, which had an impact on screen readers. This has now been corrected.
-----
Thanks to @Supamiu!
-----
> [select] fix id when group by

- packages/ng/dialog/dialog-header/dialog-header.component.scss
Prevent dialogs from overriding titles spacings 
-----
CSS is compiled by LF on Angular components. It results to ignore `$deprecatedSpacings` when dialog is opened / override titles spacings.
-----
> [Titles] Prevent dialogs from overriding titles spacings 

- packages/ng/core-select/user/user-option.component.ts
- packages/ng/core-select/user/users.directive.ts
- stories/documentation/forms/select/simple-select.stories.ts
It is not possible to override user template without having to handle homonyms and current user logic.
-----
```html
<lu-simple-select
placeholder="Placeholder…"
users
#usersRef="luUsers"
[(ngModel)]="selectedUser"
>
<span *luUserOption="let user; usersRef: usersRef">👉👉👉 {{ user | luUserDisplay }} 👈👈👈</span>
</lu-simple-select>
```
-----
> feat(core-select): handle custom user option template

- packages/ng/dialog/dialog-routing/dialog-routing.component.ts
- packages/ng/dialog/dialog-routing/dialog-routing.models.ts
- packages/ng/dialog/dialog-routing/dialog-routing.utils.ts
- packages/ng/dialog/dialog-routing/outlet-component-instance.directive.ts
- stories/documentation/overlays/dialog/dialog-routing.stories.ts
In order to allow developper to open a confirm dialog like "You have unsaved data, are you sure you want to close this dialog?", we can now add `canDeactivate` guards in dialogRoutingConfig
-----
https://github.com/user-attachments/assets/182da645-3d2c-4e82-90e3-7346710a218a
-----
> feat(dialog): allow canDeactivate guards in dialogRoutingConfig

- packages/ng/simple-select/input/select-input.component.ts
Filter Pills implementation made it skip space event and thus closing panel right after it was opened, selecting the very first element in the list that was available.
-----
-----
> fix(simple-select): space not opening panel properly

- packages/scss/src/components/loading/mods.scss
The `L` mixin already includes the `block` mixin, but both are called in other mixins, in the same order.
-----
> [loading] Remove redundant code:

- packages/ng/empty-state/empty-state-page/empty-state-page.component.ts
- packages/ng/empty-state/empty-state-section/empty-state-section.component.ts
- packages/ng/empty-state/empty-state.model.ts
Allow using string instead of number for `hx` input
-----
Add `transform` with `numberAttribute`
-----
> feat(empty-state): Allow using string instead of number for `hx` input

- packages/ng/multi-select/panel/panel.component.html
Group template was not displayed when a clue was used
-----
-----
> fix(multi-select): group template was not displayed when a clue was used

- packages/ng/core-select/user/users.directive.ts
We need to use defaultScopedSearchUrl when `appInstanceId` && `operationIds` or `uniqueOperationIds`
-----
> fix(user-directive): Use defaultScopedSearchUrl when uniqueOperationIds

- packages/scss/src/components/footer/component.scss
Now that text in buttons can be returned to the line, we need to correct some behavior in the footer.
-----
-----
Before:
After:
> [footer] buttons with wrap

- packages/ng/form-field/form-field.component.ts
- stories/documentation/forms/fields/form-field.stories.ts
- stories/qa/index-table/index-table.stories.ts
Pour les profils de lieux de travail sur Office, nous avons besoin de relier plusieurs champs à un seul message d'erreur. 
-----
-----
> feat(form-field): add extra describedBy input

- packages/ng/date2/abstract-date-component.ts
- packages/ng/date2/date-input/date-input.component.ts
When in month mode, the min and max are now only applied to the corresponding year, and not all years.
-----
Note that the use of `startOfMonth` is to prevent that no month is selectable if min and max are in the same month. 
Before: 
After: 
-----
> [DateInputComponent] fix: the min/max in month mode

- packages/scss/src/components/indexTable/index.scss
- packages/scss/src/components/indexTable/mods.scss
- stories/documentation/listings/index-table/index-table-actions.stories.ts
Reduce specificity of actions buttons to allow override from mods, like mod-delete
Fixe https://github.com/LuccaSA/lucca-front/issues/3474
-----
> fix(front) : [indexTable] reduce specificity of actions buttons to allow override from mods, like mod-delete

- packages/ng/core-select/input/select-input.component.ts
- packages/ng/date2/abstract-date-component.ts
- packages/ng/date2/date-input/date-input.component.ts
- packages/ng/date2/date-range-input/date-range-input.component.html
- packages/ng/date2/date-range-input/date-range-input.component.ts
- packages/ng/filter-pills/core/filter-pill-input-component.ts
- packages/ng/filter-pills/filter-pill/filter-pill.component.html
- packages/ng/filter-pills/filter-pill/filter-pill.component.ts
- packages/ng/forms/checkbox-input/checkbox-input.component.ts
- packages/ng/multi-select/input/select-input.component.html
- packages/ng/simple-select/input/select-input.component.html
- stories/documentation/forms/filterPills/angular/date-filter-pill.stories.ts
- stories/documentation/forms/filterPills/angular/filter-pills.stories.ts
This pull request is a fix that allows enabling or disabling the clear button on a 'filter-pills' (date-range, select-input etc.) like 'lu-form-field'.
-----
In our case, we use filter-pills on a date-range input that must be filled in. So we don't want a clear button.
-----
> Fix(filter pills): clearable

- packages/ng/forms/textarea-input/textarea-input.component.ts
Textarea input with default value and autoresize doesn't apply autoresize on init.
-----
Add `startWith` on `valueChanges`.
-----
> fix(lu-textarea-input): apply autoresize with initial value

- package-lock.json
- packages/ng/schematics/lu-select/tests/input/simple-case.component.ts
- packages/ng/schematics/lu-select/tests/output/simple-case.component.ts
- packages/scss/src/components/indexTable/mods.scss
- stories/documentation/forms/fileToolbar/html&css/basic.stories.ts
- stories/documentation/forms/fileUpload/angular/basic.stories.ts
New lint update broke due to eslint thinking unused imports are unused vars, meaning that we can only ignore them in the test.
-----
-----
> fix(lint): force ignore unused vars in schematic test cases

- packages/ng/title/README.md
- packages/ng/title/title-translate.service.ts
- packages/ng/title/title.strategy.spec.ts
- packages/ng/title/title.strategy.ts
💥 Breaking when using `APP_TITLE` (but no usages on Lucca's side)
Some improvement on DX:
- Translate service is optional if you want to handle translations on your side
- deprecate APP_TITLE and add a `provideAppTitle(() => 'title')`
- add a `provideLuTitleTranslateService(() => inject(TranslocoService))`
-----
-----
> ref(title): better DX

- packages/ng/user/display/user-display.pipe.ts
This is mostly to prevent potential crashes and remove some meaningless nullish user errors from our Datadog reporting 🐶 
-----
-----
> fix(user-display): handle nullish values for user display tooling

- packages/ng/date2/date-range-input/date-range-input.component.html
Because of a signal used as value instead of being read in template and it being non-`null`, it was always considered as true, hence input being disabled.
We might need a linter rule or something to prevent this in the future.
-----
-----
> fix(date-range-input): input always disabled

- packages/scss/src/components/richText/vars.scss
This PR replaces the deprecated "grey" palette used on the toolbar's background with the "neutral" palette.
-----
-----
> fix(rich-textfield): #3583 replace grey with neutral

- packages/ng/date2/date-input/date-input.component.ts
- stories/documentation/forms/fields/date/date-input-field.stories.ts
Because of how we used to compare date with previous write value, resetting the input to its original value from write wasn't resulting in a change event being sent to the control. This has been fixed by resetting value from write call when selected date is being applied.
Also, this PR adds an e2e test to make sure it doesn't come back in the future (and I was able to TDD the fix ✨)
-----
-----
> fix(date-input): selecting initial value after a change doesn't reflect on model

- packages/ng/forms/rich-text-input/rich-text-input.component.html
- packages/ng/forms/rich-text-input/rich-text-input.component.ts
Fixed RTE autofocus when value is set programmatically (#3587)
-----
* Disabled autofocus when updating rich text input value automatically
* Removed useless field validity handling since it's already handled by `form-field` and `luInput`
-----
> fix(rich-text-input): fixed RTE autofocus when value is set programmatically

- packages/ng/forms/rich-text-input/rich-text-input.component.ts
Fixed RTE being marked as touched & dirty when initial value is set
-----
* Added custom lexical update tag, marking `writeValue` udpates to not fire changed/touched events
-----
> fix(rich-text-input): fixed RTE being marked as touched & dirty when initial value is set

- packages/scss/src/commons/utils/overflow.scss
A bit of tidying up in this mixin, which until now has been a piece of misunderstood magic code.
-----
- `overflow hidden` must only be applied to html, otherwise the sticky anchor changes
- `overscroll-behavior` should only be applied to dialog scrollbars (but is useless as we have a scrollblock)
- `overflow-scrolling` has no noticeable impact according to my tests
- `touch-action: none` remains in place only to ensure stronger support for older iOS devices
-----
> [utils] scrollblock update

- packages/scss/src/commons/core.scss
- packages/scss/src/commons/utils/index.scss
- packages/scss/src/components/indexTable/mods.scss
- packages/scss/src/components/tableSticked/mods.scss
- stories/documentation/listings/index-table/index-table-actions-dropdown.stories.ts
- stories/documentation/listings/index-table/index-table-actions-selectable.stories.ts
- stories/documentation/listings/index-table/index-table-actions-subAction.stories.ts
- stories/documentation/listings/index-table/index-table-actions-tooltipsCell.stories.ts
- stories/documentation/listings/index-table/index-table-actions-tooltipsRow.stories.ts
- stories/documentation/listings/index-table/index-table-actions-userPopover.stories.ts
- stories/documentation/listings/index-table/index-table-basic.stories.ts
- stories/documentation/listings/index-table/index-table-deprecated.stories.ts
- stories/documentation/listings/index-table/index-table-input.stories.ts
Stories for index table with:
- tooltips
- user popover
- text selectionable or actionable
- dropdown or sub actions
-----
`[class*='row-cell']` has been replaced by `.indexTable-head-row-cell, .indexTable-body-row-cell, .indexTable-foot-row-cell` so that it no longer applies to `indexTable-body-row-cell-link`.
-----
> [indexTable] stories

- packages/ng/simple-select/input/panel-ref.factory.ts
Simply adding a focus call did the trick, but I couldn't add a test for it yet as there's a lot of select-related tests in rc and I'd like to avoid having to reimplement them in this PR.
I tested manually tho.
-----
-----
> fix(simple-select): focus input after panel is closed

- packages/ng/core-select/input/select-input.component.ts
- packages/ng/filter-pills/core/tokens.ts
- packages/ng/filter-pills/filter-pill/filter-pill.component.ts
- stories/documentation/forms/filterPills/angular/filter-pill-child-component.stories.ts
When used deep inside the component tree, filter pill inputs might not register properly. This fixes the issue for the one input we've add issues with regarding this: select.
@GuillaumeNury Looks like the inject + register pattern is the solution once more.
-----
We might want to do this for all pills but this is more of a hotfix for now and we'll see how it goes in the future, it wouldn't be breaking for anyone anyways so it can wait a bit.
-----
> fix(filter-pills): better handling of nested select inputs

- packages/ng/file-upload/base-file-upload/base-file-upload.component.ts
- packages/ng/file-upload/single/single-file-upload.component.html
- packages/ng/form-field/form-field.component.ts
- stories/documentation/forms/fileUpload/angular/basic.stories.ts
As the `fileUpload` has a special handling, we need to manage its required differently from other inputs. We add an option for this in the `formField`.
-----
Bonus: the `luInputStandalone` didn't seem necessary and correct the `for`/`id` binding.
-----
> [FileUpload] Fix required

- packages/ng/highlight-data/highlight-data.component.html
- packages/ng/highlight-data/highlight-data.component.ts
> feat(highlight-data): allow for portalContent in heading, value and subText inputs

- packages/ng/page-header/page-header.component.html
- packages/scss/src/components/pageHeader/component.scss
- packages/scss/src/components/pageHeader/mods.scss
- packages/scss/src/components/pageHeader/vars.scss
Margin above navigation not aligned with figma: reduced from `100` to `50`.
-----
-----
> [pageHeader] fix margin

- packages/ng/title/README.md
- packages/ng/title/title.strategy.spec.ts
- packages/ng/title/title.strategy.ts
The title strategy guideline has been updated.
Product must display `Lucca ProductName` while other software may keep the current suffix strategy (`AppName – Lucca`)
-----
This PR will be backported to all v19 releases
> feat(title): new product guideline

- docs/core-select-api-directive.md
- packages/ng/core-select/api/api-v3.directive.ts
- packages/ng/core-select/api/api.directive.spec.ts
- packages/ng/core-select/api/api.directive.ts
- packages/ng/core-select/establishment/establishments.directive.ts
- packages/ng/core-select/input/select-input.component.ts
- packages/ng/core-select/job-qualification/job-qualifications.directive.ts
- packages/ng/core-select/user/users.directive.ts
- Allow API selects to override the `optionComparer` and `optionKey` inputs. Very useful when using an API without ids (weird but yes, that exists)
- Refactors the default `optionComparer` for API selects, it is now based on the comparison result of the `optionKey`. It's still overridable.
-----
> fix(core-select): option comparer overridable

- packages/ng/date2/abstract-date-component.ts
- packages/ng/date2/date-input/date-input.component.ts
There was a breaking change with the modification of the 2 validators of date input component (`min` and `max` became `minMax`)
-----
Avoid code duplication by splitting isInMinMax methods in 2 separated methods
Code is easier to read by not mutating result and directly return it
There is a better typing for error code in validation function, to avoid breaking the contract in the future
-----
> fix(date-input): revert change of minMax validation, avoid code duplication

- packages/ng/breadcrumbs/public-api.ts
- stories/documentation/navigation/breadcrumbs/angular/breadcrumbs-basic.stories.ts
- stories/documentation/navigation/horizontalNavigation/angular/horizontalNavigation-basic.stories.ts
- stories/documentation/structure/page-header/angular/page-header-basic.stories.ts
- stories/qa/breadcrumb/breadcrumb.stories.ts
Add missing `BreadcrumbsLinkDirective` import in `public-api.ts`
-----
-----
> fix(breadcrumbs): add missing import of `BreadcrumbsLinkDirective`

- packages/ng/core-select/user/former-employees.component.scss
- packages/ng/core-select/user/former-employees.component.ts
- packages/ng/styles/definitions/option/_option-item.scss
- stories/documentation/forms/filterPills/angular/select-filter-pill.stories.ts
Using a select with `enableFormerEmployees` previously added a checkbox layout to the filter pill, resulting on a broken layout.
This PR switches the checkbox for a fake one using CSS? just like we're doing in other options.
-----
-----
> fix(filter-pills): former employees adding checkbox layout to filter-pills

- packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
- stories/documentation/overlays/tooltip/tooltip.stories.ts
This only works properly on non-component elements, just like for popover2, we might want to do it using a directive if any issue appears with that. Reason is that when using `#ref` on a component, it gives us a ref to the component, not the host's `elementRef` that we want.
-----
closes #3541
-----
> feat(tooltip): allow for external host

- packages/ng/dialog/dialog.service.ts
- packages/ng/dialog/model/dialog-config.ts
- packages/ng/dialog/model/dialog-ref.ts
You can now pass data type as second argument, allowing for custom types especially for when stores are being used for data.
⚠️ Using this will disable auto check that ensures consistency between opener and dialog, this shouldn't be the default usage ⚠️ 
-----
closes #2963
-----
> feat(dialog): allow for type overriding in data config

- packages/ng/skeleton/skeleton-field/skeleton-field.component.html
- packages/ng/skeleton/skeleton-field/skeleton-field.component.ts
- stories/documentation/loaders/skeleton-field/angular/skeleton-field.stories.ts
Add `hiddenLabel` input on `lu-skeleton-field` to better match the display once the data is loaded when using `hiddenLabel` on `lu-form-field`.
-----
-----
> feat(lu-skeleton-field): add hiddenLabel input

- packages/ng/core-select/api/api-v4.directive.ts
This `optionComparer` forced override was forgotten in https://github.com/LuccaSA/lucca-front/pull/3641
Removing it simplifies the api v4 select with custom key by only specifying the `optionKey` attribute. Right now, we have to specify both `optionKey` and `optionComparer`
-----
> refactor(core-select): allow optionComparer override for api-v4

- packages/ng/schematics/lu-select/util.ts
`name` property was considered as unhandled, same for any template references (`#something` on the select tag), now they are !
-----
-----
> chore(select-schematic): support `name` attribute as well as template references

- .storybook/public/mockServiceWorker.js
- packages/ng/number-format/number-format.spec.ts
- packages/ng/number-format/number-format.ts
Add the possibility to keep 2 digits after the comma even if these digits are 0s.
This request is for Angular lu-number-format-input with formatStyle="currency"
-----
We let `Intl` deal with max and min digits number.
-----
> feat(number-format): currency style -> display a trailing 0 on fraction part if only 1 non-zero digit set

- packages/ng/forms/rich-text-input/rich-text-input.component.ts
- stories/documentation/forms/fields/rich-text/angular/rich-text-input.stories.ts
The richtext placeholder was not shown at init if the content is empty.
It appeared only at first click or after content edition
-----
A new story has been added to highlight the problem
-----
> fix: richtext placeholder was not shown at init when no content

- packages/ng/forms/rich-text-input/plugins/list-format/list-format.command.ts
Switching between the two list modes was updating correctly the content but not the buttons activation.
insertList or removeList are not concerned by the bug has they trigger a selection change, hence buttons update.
https://github.com/user-attachments/assets/be13a67a-0022-4f81-8343-f071921deaab
-----
choosed solution: manually trigger a selection update to ensure all buttons are updated.
-----
> fix(richtext): update lists buttons when switching list mode

- packages/ng/link/link.component.ts
- packages/ng/link/lu-router-link.ts
- packages/ng/link/public-api.ts
- stories/documentation/actions/links/angular-testing.stories.ts
- stories/documentation/actions/links/angular.stories.ts
Due to changes on RouterLink, Angular 20 broke our luLink component.
The fix was to expose their new internal signal and manipulate it directly from our own component, it's hacky but they didn't give us other choices.
Kudos to @LucasPerrault for the final fix!
-----
-----
> fix: lulink broken with Angular 20

- packages/ng/numeric-badge/numeric-badge.component.ts
- packages/scss/src/components/segmentedControl/states.scss
- Fix loading input that wasn't applying `mod-loading` class
- Fix numeric badge specificity with temporary code for loading when nested in Segmented Control
-----
> [Numeric badge] Loading + specificity

- packages/ng/dialog/dialog-routing/dialog-routing.component.ts
- packages/ng/dialog/dialog-routing/dialog-routing.utils.ts
Fix typing import issue with dialogs
-----
Before the fix, `dialog.d.ts` would contain the following
Which breaks target app build when importing `@lucca-front/ng/dialog`
Also there was unnecessary duplication of `ComponentType` type because it was imported from both `@angular/cdk/overlay` and `@angular/cdk/portal`
-----
> fix(dialog): fix typing import issue with dialogs

- packages/ng/core-select/api/api.directive.ts
- packages/ng/core-select/user/users.directive.spec.ts
Option was completed too soon. When `getOptionsPage` needs to emit multiple times, it would stop after the first emission when `isLastPage === true` (it is the case with our homonyms management).
-----
-----
> fix(core-select): homonyms additionnal data was not added when using search

- packages/stylelint-config/LFDeprecatedProperties.mjs
- packages/stylelint-config/LFDeprecatedSelectors.mjs
Deprecations for some selectors or properties were updated in Prisme, but not updated on the stylelint package.
That would trigger linting errors for people using the linter on the 20.1 version of lucca-front.
This fix should solve the problem.
-----
> chore(stylelint): Update deprecated versions, changed on last release

- packages/ng/callout/callout-popover/callout-popover.component.ts
When the callout is in mod-XS, its popover is in S (and not XS – which does not exist).
Fixes #3809 
-----
-----
> [callout] fix popover size with XS

- packages/scss/src/components/divider/component.scss
- packages/scss/src/components/divider/mods.scss
- packages/scss/src/components/divider/vars.scss
fix: #3741
Both `--components-divider-marginBlock` and `--components-divider-marginInline` rely on the new `--components-divider-margin-value` var which can be easily overridden.
> [!NOTE]
> I'm just not sure about the new variable name, if you have a better idea… 💡 
-----
> fix(divider) mod vertical margins

- packages/scss/src/components/tooltip/component.scss
[Tooltip] Fix overflow
-----
`hyphen: auto` cannot deal with all breaks (but still has priority on `word-break`)
-----
> [Tooltip] Fix overflow

- packages/ng/dialog/dialog.service.ts
Since 20.1.X (I'm not sure which one), we've lost the `data` type check based on `injectDialogData` when opening a dialog.
We now have the option to specify the data type as generic when calling `dialog.open`. This allows us to avoid having to specify an unnecessary injectDialogData in the component when injecting `data` only into the dialog's store, for example.
The problem is that Typescript automatically infers the `data` type and therefore no longer checks that `data` is typed the same as `injectDialogData`.
We're missing a [NoInfer](https://www.typescriptlang.org/docs/handbook/utility-types.html#noinfertype) to tell Typescript not to infer the type, so it only works when the generic is specified manually.
-----
Keep an …
> fix(dialog): Fix dialog data check type

- packages/scss/src/components/readMore/states.scss
> [readMore] fix line break for disabled state

- packages/scss/src/components/readMore/component.scss
- packages/scss/src/components/textFlow/component.scss
The component needs to know where to insert the placeholder text “Read less” that reserves the necessary space for the collapse button. To do this, it used to detect the presence of paragraphs (`p`).
It now detects the presence of lists (`ol`, `ul`) and titles (`hx`), and inserts the placeholder text in the right place.
-----
-----
> [readMore] fix detection for contents with lists or headings

- packages/ng/forms/rich-text-input/plugins/tag/tag-node.ts
- packages/ng/forms/rich-text-input/plugins/tag/tag.component.html
- packages/scss/src/components/richText/component.scss
- Remove @include reset.button; because scss already on `chip` class. So add missing border attribute.
- Remove `richTextField-content-chip` on tags list and use it in editor
-----
-----
> fix(richtext): Resolve some scss on tag chips

- packages/scss/src/components/skeleton/mods.scss
> [skeleton] fix square default radius

- packages/scss/src/components/button/states.scss
> fix(button): keep original palette while loading/success

- packages/scss/src/components/dataTable/mods.scss
-----
fixes #3854 
-----
Before:
After:
> [dataTable] fix background for groups

- packages/ng/date2/abstract-date-component.ts
- packages/ng/date2/date-format.ts
- packages/ng/date2/date-input/date-input.component.html
- packages/ng/date2/date-input/date-input.component.ts
> fix(date): better handling of single-digit input on month and day

- packages/ng/forms/multilanguage-input/multilanguage-input.component.html
- packages/ng/forms/multilanguage-input/multilanguage-input.component.ts
- stories/documentation/forms/fields/multilanguage/angular/multilanguagefield.stories.ts
Add a new `openOnFocus` input to `lu-multilanguage-input` to open the panel on focus, without pushing focus inside the first input.
closes #3718
-----
-----
> feat(multilanguage-input): new openOnFocus input to open panel on focus
