.gitignore
build/publish.js
package.json
packages/icons/CHANGELOG.md
packages/ng/CHANGELOG.md
packages/ng/package.json
packages/scss/.gitignore
packages/scss/CHANGELOG.md
packages/scss/demo/demo.html
packages/scss/dist/lucca-front.css
packages/scss/package.json
tools/lib/parse-package-json.js
tools/lib/patch-version-placeholder.js
tools/lib/publish-packages.js
tools/lib/update-master-version.js
tools/publish.js

* Update main package.json using `npm version`
* Patch all `package.json` and `CHANGELOG.md` with new version
* Publish all subpackage (it only call a fake script ATM)
Pour @jeremie-lucca : tu peux faire un `npm build` dans le sous dossier `scss`. De plus, ta démo pointe vers le CSS du dossier dist (généré avec `npm build`)

Package version handler

---

packages/ng/demo/app/app.component.html
packages/ng/demo/styles.scss
packages/ng/package.json
packages/ng/src/main.scss
packages/ng/src/style/_components.scss
packages/ng/src/style/_mixins.scss
packages/ng/src/style/components/_input.scss
packages/ng/src/styles.scss
packages/scss/src/components/_input.scss

import /scss styles in the /ng
add /ng specific classes - just ng-invalid for input - using /scss mixins

Package interdependencies

---

packages/scss/demo/components/buttons.html
packages/scss/demo/components/callouts.html
packages/scss/demo/components/cards.html
packages/scss/demo/components/chips.html
packages/scss/demo/components/forms.html
packages/scss/demo/components/forms/forms-checkboxes.html
packages/scss/demo/components/forms/forms-inputs.html
packages/scss/demo/components/forms/forms-radios.html
packages/scss/demo/components/forms/forms-switches.html
packages/scss/demo/components/forms/forms-textareas.html
packages/scss/demo/components/grids.html
packages/scss/demo/components/menus.html
packages/scss/demo/components/tables.html

Will be improved later with a plugin.

[FIX] Code indentation

---

packages/scss/src/_mixins.scss
packages/scss/src/mixins/_responsiveness.scss

Created three media query mixins : 
1) media_smaller_than(breakpoint)
2) media_larger_than(breakpoint)
3) media_between(breakpoint1, breakpoint2)
They throw warnings if the breakpoint used isn't defined

Created media query mixins

---

packages/scss/demo/components/cards.html
packages/scss/demo/components/lists.html
packages/scss/demo/includes/demo-main-content.html
packages/scss/demo/includes/demo-menu.html
packages/scss/src/_components.scss
packages/scss/src/components/_callout.scss
packages/scss/src/components/_card.scss
packages/scss/src/components/_list.scss
packages/scss/src/theming/_commons.scss
packages/scss/src/theming/_components.scss
packages/scss/src/theming/components/_list.theme.scss

Scss.cards improvements

---

packages/icons/src/_font.scss

- Scss : possibility to override icons font url
- Icons : ensure @font-face is generated at root of css

Scss font-face imports

---

packages/scss/src/components/_button.scss
packages/scss/src/theming/components/_button.theme.scss

[enh] improve buttons alignment

---

packages/icons/src/_partials.scss
packages/scss/demo/components/icons.html
packages/scss/demo/components/lists.html
packages/scss/demo/demo.css
packages/scss/src/_components.scss
packages/scss/src/_icons.scss
packages/scss/src/components/_actionIcon.scss
packages/scss/src/components/_list.scss
packages/scss/src/theming/_components.scss
packages/scss/src/theming/_icons.scss
packages/scss/src/theming/components/_action-icon.theme.scss
packages/scss/src/theming/components/_list.theme.scss

- Action icon button as component (previously in list component)
- Fix icons sizes 
- Fix default icons size
- lucca-icon as default class
Breaking changes in for figgo's lists. Will be fixed after the release.

[enh] action icon button as component

---

packages/scss/demo/components/icons.html
packages/scss/src/components/_actionIcon.scss
packages/scss/src/theming/components/_action-icon.theme.scss

Alpha on hover to be more efficient on all backgrounds (especially on background's light grey)

Scss.icon actions disabled state

---

packages/scss/src/components/_container.scss

100% width for xs container did not work.

[fix] xs 100% width

---

packages/scss/demo/components/forms/forms-checkboxes.html
packages/scss/demo/components/forms/forms-inputs.html
packages/scss/demo/components/forms/forms-radios.html
packages/scss/demo/components/forms/forms-switches.html
packages/scss/demo/components/forms/forms-textareas.html
packages/scss/demo/demo.css
packages/scss/demo/includes/demo-menu.html
packages/scss/src/components/_checkbox.scss
packages/scss/src/components/_input.scss
packages/scss/src/components/_radio.scss
packages/scss/src/components/_switch.scss
packages/scss/src/components/_textarea.scss
packages/scss/src/theming/_components.scss
packages/scss/src/theming/components/_checkbox.theme.scss
packages/scss/src/theming/components/_input.theme.scss
packages/scss/src/theming/components/_radio.theme.scss
packages/scss/src/theming/components/_switch.theme.scss
packages/scss/src/theming/components/_textarea.theme.scss

- Form elements  (input, textarea, radio, checkbox, switch) colors in theming
- Default secondary color
- Adding palettes for each form element

Scss.forms palettes

---

packages/scss/demo/components/cards.html
packages/scss/demo/components/tables.html
packages/scss/demo/includes/demo-main-content.html
packages/scss/demo/includes/demo-menu.html
packages/scss/src/_typo.scss
packages/scss/src/components/_actionIcon.scss
packages/scss/src/components/_card.scss
packages/scss/src/components/_table.scss
packages/scss/src/theming/_components.scss
packages/scss/src/theming/_sizes.scss
packages/scss/src/theming/components/_card.theme.scss
packages/scss/src/theming/components/_table.theme.scss
packages/scss/src/utilities/_text.scss

- Add a .card-content inside the card which get padding
- Add a .mod-card to table which allow to set first and last tr cell padding for card card alignment 
- Card padding in theming
- Improve small fonts line height
Breaking changes on 'card-content'. Only Figgo's cards are impacted. Easy to fix.

Scss.tables cards and headers

---

packages/scss/demo/components/main_menu.html
packages/scss/demo/components/templates.html
packages/scss/demo/details/full-menu.html
packages/scss/demo/includes/demo-main-content.html
packages/scss/demo/includes/demo-menu.html
packages/scss/demo/templates/fullmenu.html
packages/scss/demo/templates/side-cards.html
packages/scss/demo/templates/side-filters.html
packages/scss/demo/templates/side-sections-filters.html
packages/scss/demo/templates/side-sections.html
packages/scss/demo/templates/side.html
packages/scss/demo/templates/sidemenu-sections.html
packages/scss/src/components/_container.scss
packages/scss/src/components/_main.scss
packages/scss/src/components/_nav-side.scss
packages/scss/src/theming/components/_nav-side.theme.scss

The new menu and its documentation

New menu as navSide

---

packages/scss/demo/components/callouts.html
packages/scss/demo/components/forms/forms-inputs.html
packages/scss/src/components/_callout.scss
packages/scss/src/components/inputs/input/_input.scss
packages/scss/src/theming/_components.scss
packages/scss/src/theming/components/_callout.theme.scss
packages/scss/src/theming/components/_input.theme.scss

I created the branch on scss.input-fixes by mistake. 
--> just ignore inputs changes

Scss.callout margins

---

packages/scss/src/components/_nav-side.scss

Change variable use for navSide text color

Scss.nav side.themingfix

---

packages/scss/demo/components/buttons.html
packages/scss/demo/components/menus.html
packages/scss/src/components/_menu.scss
packages/scss/src/components/inputs/switch/_switch.scss
packages/scss/src/theming/_components.scss
packages/scss/src/theming/components/_menu.theme.scss

Scss.menu.theming

---

packages/scss/demo/components/lists.html
packages/scss/src/components/_list.scss
packages/scss/src/theming/components/_action-icon.theme.scss
packages/scss/src/theming/components/_list.theme.scss

Small breaking on mod / link position

[scss][enh] list item hovering

---

packages/scss/src/theming/_get-set.scss

Enhanced the _color function, adding a $type parameter to choose another entry than ".color".

[enh] add type to color function

---

packages/ng/demo/app/app.component.html
packages/ng/demo/app/app.module.ts
packages/ng/demo/app/user-tile/basic/basic.component.html
packages/ng/demo/app/user-tile/basic/basic.component.ts
packages/ng/demo/app/user-tile/user-tile.component.html
packages/ng/demo/app/user-tile/user-tile.component.ts
packages/ng/demo/app/user-tile/user-tile.module.ts
packages/ng/src/app/lu-root.module.ts
packages/ng/src/app/user-tile/user-tile.component.html
packages/ng/src/app/user-tile/user-tile.component.scss
packages/ng/src/app/user-tile/user-tile.component.spec.ts
packages/ng/src/app/user-tile/user-tile.component.ts
packages/ng/src/app/user-tile/user-tile.models.ts
packages/ng/src/app/user-tile/user-tile.module.ts
packages/ng/src/index.ts

Tile for user display. By default, the header displays the user's `jobTitle` but is customizable. A footer can be added via `ng-content`.

Ng.user tile

---

packages/ng/demo/app/app.component.html
packages/ng/demo/app/app.module.ts
packages/ng/demo/app/app.router.ts
packages/ng/demo/app/date-range-picker/date-range-picker.router.ts
packages/ng/demo/app/navigation/navigation.component.html
packages/ng/demo/app/navigation/navigation.component.ts
packages/ng/demo/app/user-tile/user-tile.router.ts
packages/ng/demo/index.html
packages/ng/package.json

ng-demo [add] basic router and navigation layout

---

packages/ng/src/plugins/ngMaterial/_general.scss
packages/ng/src/plugins/ngMaterial/_tooltip.scss

mdTooltip style override

---

packages/ng/demo/app/date-range-picker/basic/basic.component.html
packages/ng/demo/app/formly/fieldgroup/fieldgroup.html
packages/ng/demo/app/formly/fieldgroup/fieldgroup.ts
packages/ng/demo/app/formly/validation/validation.ts
packages/ng/src/app/formly/wrappers/helper.html
packages/ng/src/plugins/ngMaterial/_autocomplete.scss
packages/ng/src/plugins/ngMaterial/_general.scss
packages/ng/src/plugins/ngMaterial/_options.scss
packages/ng/src/plugins/ngMaterial/_select.scss
packages/ng/src/style/_components.scss
packages/ng/src/style/components/_formly.scss

Adds style support for formly :
- Supports the 3 mods (normal, compact, framed)
- Adds 2 global overrides for formly-group and formly-form
It also adds material overrides for :
- md-autocomplete
- md-select

[NG] Style for formly & forms

---

packages/ng/demo/app/shared/api-docs/api-docs.component.html
packages/ng/misc/api-doc.js

api-doc [enh] support pipe

---

packages/ng/demo/app/formly/debug/debug.html
packages/ng/demo/app/formly/debug/debug.ts
packages/ng/demo/app/formly/option/option.ts
packages/ng/src/app/formly/formly.config.ts
packages/ng/src/app/formly/types/autocomplete.ts
packages/ng/src/app/formly/types/select.ts
packages/ng/src/app/formly/wrappers/icon.html
packages/ng/src/app/formly/wrappers/icon.ts
packages/ng/src/app/formly/wrappers/suffix.html
packages/ng/src/app/formly/wrappers/suffix.ts
packages/ng/src/app/formly/wrappers/suffixes.common.scss

Adds wrapper for icons & suffixes

[Formly] Icon/Suffix wrapper

---

packages/ng/demo/app/date-range-picker/basic/basic.component.html
packages/ng/demo/app/empty/basic/basic.html
packages/ng/demo/app/empty/custom-fn/custom-fn.html
packages/ng/demo/app/formly/debug/debug.html
packages/ng/demo/app/formly/fieldgroup/fieldgroup.ts
packages/ng/demo/app/formly/option/option.ts
packages/ng/demo/app/user-display/basic/basic.component.html
packages/ng/src/app/date-range-picker/date-range-modal/date-range-modal.component.html
packages/ng/src/app/date-range-picker/date-range-modal/date-range-modal.scss
packages/ng/src/app/date-range-picker/date-range-picker.component.html
packages/ng/src/app/date-range-picker/date-range-picker.component.scss
packages/ng/src/app/formly/types/autocomplete.html
packages/ng/src/app/formly/types/date.html
packages/ng/src/app/formly/types/input.html
packages/ng/src/app/formly/types/select.html
packages/ng/src/app/formly/types/textarea.html
packages/ng/src/app/formly/wrappers/error.html
packages/ng/src/app/formly/wrappers/helper.html
packages/ng/src/app/formly/wrappers/label.html
packages/ng/src/app/formly/wrappers/layout.html
packages/ng/src/app/formly/wrappers/layout.ts
packages/ng/src/app/formly/wrappers/suffix.html
packages/ng/src/plugins/ngMaterial/_autocomplete.scss
packages/ng/src/plugins/ngMaterial/_datepicker.scss
packages/ng/src/plugins/ngMaterial/_dialog.scss
packages/ng/src/plugins/ngMaterial/_options.scss
packages/ng/src/plugins/ngMaterial/_overlay.scss
packages/ng/src/plugins/ngMaterial/_select.scss

Simple fix to deal with the fusion of input & textarea into a single component called textfield.

[NG] Fix post merge between input and textarea

---

packages/ng/src/plugins/ngMaterial/_autocomplete.scss
packages/ng/src/plugins/ngMaterial/_general.scss
packages/ng/src/plugins/ngMaterial/_menu.scss
packages/ng/src/plugins/ngMaterial/_options.scss

Fixes style issues and adds basic support for mat-menu

[fix] missing styles for ngMaterial

---

packages/ng/src/app/formly/types/autocomplete.html
packages/ng/src/app/formly/types/autocomplete.ts
packages/ng/src/app/formly/types/date.html
packages/ng/src/app/formly/types/date.ts
packages/ng/src/app/formly/types/input.html
packages/ng/src/app/formly/types/input.ts
packages/ng/src/app/formly/types/select.html
packages/ng/src/app/formly/types/select.ts
packages/ng/src/app/formly/types/textarea.html
packages/ng/src/app/formly/types/textarea.ts
packages/ng/src/app/formly/wrappers/error.ts
packages/ng/src/app/formly/wrappers/layout.html
packages/ng/src/app/formly/wrappers/layout.ts

adds classes `is-focused` and `is-error` to layout

formly [add] class is-focued and is-error on the layout

---

packages/ng/CHANGELOG.md

First draft for the changelog for @lucca-front/ng

[NG] Changelog

---

packages/scss/demo/templates/fullmenu.html
packages/scss/demo/templates/side.html
packages/scss/src/components/_header.scss
packages/scss/src/components/_nav-side.scss
packages/scss/src/mixins/_loading.scss
packages/scss/src/theming/components/_nav-side.theme.scss

Adds a new mixin to handle gradient animation.
Adds placeholder loaders for navSide and Header

[SCSS] Placeholder loaders for navSide and header

---

packages/ng/demo/app/app.component.html
packages/ng/demo/app/app.component.scss
packages/ng/demo/app/empty/empty.component.html
packages/ng/demo/app/formly/formly.component.html
packages/ng/demo/app/lu-popover/lu-popover.component.html
packages/ng/demo/app/shared/api-docs/api-docs-class.component.html
packages/ng/demo/app/shared/api-docs/api-docs-config.component.html
packages/ng/demo/app/shared/api-docs/api-docs.component.html
packages/ng/demo/app/shared/api-docs/api-docs.component.ts
packages/ng/demo/app/shared/api-docs/api-docs.style.scss
packages/ng/demo/app/shared/example-box/example-box.component.html
packages/ng/demo/app/shared/example-box/example-box.component.scss
packages/ng/demo/app/shared/example-box/example-box.component.ts
packages/ng/demo/app/user-display/user-display.component.html
packages/ng/demo/app/user-tile/user-tile.component.html
packages/ng/demo/styles.scss
packages/ng/demo/theming/_components.override.scss
packages/ng/demo/theming/_overrides.scss
packages/ng/demo/theming/_palettes.override.scss
packages/ng/demo/theming/components/_box.override.scss
packages/ng/demo/theming/components/_nav-side.override.scss
packages/ng/demo/theming/components/_table.override.scss

The demo has now a more beareable/readable style.

[NG] Make the demo bearable

---

packages/ng/CHANGELOG.md
packages/ng/demo/app/animations/animations.component.html
packages/ng/demo/app/animations/animations.component.ts
packages/ng/demo/app/animations/animations.module.ts
packages/ng/demo/app/animations/animations.router.ts
packages/ng/demo/app/animations/animations.scss
packages/ng/demo/app/animations/basic/basic.component.html
packages/ng/demo/app/animations/basic/basic.component.ts
packages/ng/demo/app/animations/scaling/scaling.component.html
packages/ng/demo/app/animations/scaling/scaling.component.ts
packages/ng/demo/app/animations/sliding/sliding.component.html
packages/ng/demo/app/animations/sliding/sliding.component.ts
packages/ng/demo/app/app.module.ts
packages/ng/demo/app/app.router.ts
packages/ng/demo/app/navigation/navigation.component.html
packages/ng/src/app/animations/basicAnimations.ts
packages/ng/src/app/animations/index.ts
packages/ng/src/app/animations/scalingAnimations.ts
packages/ng/src/app/animations/slidingAnimations.ts
packages/ng/src/index.ts

Adds `LFAnimationFactory` and basic animations (fade, scale, slide)

[NG] Angular Animations

---

packages/ng/src/app/formly/formly.config.ts
packages/ng/src/app/formly/types/autocomplete.html
packages/ng/src/app/formly/types/autocomplete.ts

merge #174, #175, #178 and #180 first. also merging #176 and #177 before should be beneficial
--------------
fixed the autocomplete formly type that was unusable. 
temp - desabled type select temporarily - uses type autocomplete instead

Ng.formly.autocomplete

---

packages/scss/CHANGELOG.md
packages/scss/demo/templates/fullmenu.html
packages/scss/demo/templates/side-cards.html
packages/scss/demo/templates/side-header.html
packages/scss/demo/templates/side-sections-header.html
packages/scss/demo/templates/side-sections.html
packages/scss/demo/templates/side.html
packages/scss/src/components/_main.scss
packages/scss/src/components/_nav-side.scss

Adds mobile support for navSide

[SCSS] Mobile support for navSide

---

lerna.json
packages/icons/package.json
packages/ng/demo/app/api/picker/basic/basic.html
packages/ng/demo/app/api/picker/nopicker/nopicker.html
packages/ng/package.json
packages/ng/src/app/api/index.ts
packages/ng/src/app/api/picker/api-picker.component.ts
packages/ng/src/app/api/picker/api-picker.directive.ts
packages/ng/src/app/api/picker/index.ts
packages/ng/src/app/formly/types/api.html
packages/ng/src/app/popover/index.ts
packages/ng/src/index.ts
packages/scss/package.json

- move `@Input` api from picker directive to compionenet
- add input filter - fixes #179 
- some stuff to make picker compoennet extension more easier ™️

api picker, some enhancements

---

packages/ng/src/app/formly/types/autocomplete.html
packages/ng/src/app/formly/types/autocomplete.ts

as i forgot the setvalue, the input does nothing

ng-formly [fix] forgot setvalue in formly autocomplete

---

packages/scss/src/components/_main.scss
packages/scss/src/components/_nav-side.scss
packages/scss/src/theming/components/_nav-side.theme.scss

Adds the right behaviour for main-content with the media query

[SCSS][fix] handle main-content display

---

packages/scss/demo/details/full-menu.html
packages/scss/demo/templates/fullmenu.html
packages/scss/demo/templates/noside-header.html
packages/scss/demo/templates/noside-sections-header.html
packages/scss/demo/templates/side-cards.html
packages/scss/demo/templates/side-header.html
packages/scss/demo/templates/side-sections-header.html
packages/scss/demo/templates/side-sections.html
packages/scss/demo/templates/side.html

+ Edit outdated code to copy in templates
+ Add compact menu interactions in demo

[scss] add icons to demo navside compact

---

packages/scss/src/components/_button.scss

Adds a slight lighten on background color for button hover/focus

[SCSS][enh] adds a slight color change on button hover/focus

---

packages/scss/CHANGELOG.md
packages/scss/demo/components/forms/forms-textfields.html
packages/scss/demo/demo.js
packages/scss/src/components/inputs/textfield/_textfield.framed.scss
packages/scss/src/components/inputs/textfield/_textfield.material.scss
packages/scss/src/components/inputs/textfield/_textfield.scss
packages/scss/src/mixins/_forms.scss

Valid & Invalid icons don't match. It will need an update after next icons update.

[enh] inline validation

---

packages/scss/src/components/inputs/textfield/_textfield.framed.scss
packages/scss/src/theming/components/_textfield.theme.scss

Fixes issues post classic where mod-framed was breaking its alignment and its suffixes were not properly placed

[SCSS][fix] Alignment issues on mod-framed

---

lerna.json
packages/icons/package.json
packages/ng/CHANGELOG.md
packages/ng/demo/app/select/simple-select/simple-select.component.ts
packages/ng/package.json
packages/ng/src/app/select/picker/select-picker.component.ts
packages/scss/package.json

Fix issue where options are not updated

Ng fix non selectable items 

---

packages/ng/CHANGELOG.md
packages/ng/demo/app/user/tile/basic/basic.component.html
packages/ng/demo/app/user/tile/displayFormat/display-format.component.html
packages/ng/demo/app/user/tile/displayFormat/display-format.component.ts
packages/ng/demo/app/user/tile/sizes/sizes.component.html
packages/ng/demo/app/user/tile/sizes/sizes.component.ts
packages/ng/demo/app/user/tile/user-tile.component.html
packages/ng/demo/app/user/tile/user-tile.component.ts
packages/ng/demo/app/user/tile/user-tile.module.ts
packages/ng/src/app/user/tile/user-tile.component.html
packages/ng/src/app/user/tile/user-tile.component.ts

Adds a displayFormat attribute to `lu-user-tile`

[NG] Adds displayFormat attribute to LuUserTile

---

.travis.yml
package.json
packages/ng/demo/app/animations/fading/fading.component.ts
packages/ng/demo/app/animations/scaling/scaling.component.ts
packages/ng/demo/app/animations/sliding/sliding.component.ts
packages/ng/package.json
packages/ng/src/app/animations/animation.factory.ts
packages/ng/src/app/user/tile/user-tile.component.html
packages/ng/src/app/user/tile/user-tile.component.ts

this pr contains :
- :hammer: travis calls script `travis` from root package, it is then dispatched to lf packages via lerna (for now only ng package is tested)
- :hammer: ng - travis script does this
- builds the demo in aot
- run tests for /src
- builds the demo in JIT, no minification/cachebusting for easier reverse engineering
- :boom: renammed `LfAnimationFactory` to `LuAnimationFactory` for consistency
- :bug: user-tile - use the display pipe the right way, is compatible aot

CI stuff (AOT, travis)

---

packages/scss/CHANGELOG.md
packages/scss/demo/components/forms.html
packages/scss/demo/components/forms/forms-textfields.html
packages/scss/demo/templates/form.html
packages/scss/src/components/_form.scss
packages/scss/src/components/inputs/textfield/_textfield.scss
packages/scss/src/mixins/_forms.scss

Supports is-required on textfield-label + demo

[scss] textfield supports is-required on textfield-label

---

packages/ng/CHANGELOG.md
packages/ng/demo/app/popover/popover.component.html
packages/ng/demo/app/popover/popover.component.ts
packages/ng/demo/app/popover/popover.module.ts
packages/ng/demo/app/popover/scroll/scroll.html
packages/ng/demo/app/popover/scroll/scroll.ts
packages/ng/src/app/popover/index.ts
packages/ng/src/app/popover/popover.animations.ts
packages/ng/src/app/popover/popover.component.ts
packages/ng/src/app/popover/popover.model.ts
packages/ng/src/app/popover/popover.triggers.ts

Adds scrollStrategy attribute to LuPopover. Default strategy is still repositioning.

[NG] Adds scrollStrategy attribute to LuPopover

---

packages/ng/CHANGELOG.md
packages/ng/demo/app/user/display/basic/basic.component.ts
packages/ng/demo/app/user/tile/displayFormat/display-format.component.html
packages/ng/demo/app/user/tile/displayFormat/display-format.component.ts
packages/ng/src/app/user/display/display-format.model.ts
packages/ng/src/app/user/display/index.ts
packages/ng/src/app/user/display/user-display.pipe.spec.ts
packages/ng/src/app/user/display/user-display.pipe.ts
packages/ng/src/app/user/picture/user-picture.component.ts
packages/ng/src/app/user/tile/user-tile.component.html
packages/ng/src/app/user/tile/user-tile.component.ts

Adds displayFormat on user-picture to handle how initials are displayed when there is no picture. Default value is FL

[NG] DisplayFormat on user-picture

---

packages/scss/src/components/_button.scss
packages/scss/src/theming/_sizes.scss
packages/scss/src/theming/components/_button.theme.scss

[enh] button sizing

---

packages/scss/CHANGELOG.md
packages/scss/demo/components/forms.html
packages/scss/demo/components/forms/forms-files.html
packages/scss/demo/includes/demo-menu.html
packages/scss/src/_components.scss
packages/scss/src/components/inputs/file/_file.scss

Scss.ux 699 input file

---

packages/ng/src/app/api/select/picker/api-select-picker.component.scss
packages/ng/src/app/select/directive/select.directive.ts
packages/ng/src/app/select/picker/select-picker.component.ts
packages/ng/src/app/select/scroll/picker/select-scroll-picker.component.ts
packages/ng/src/app/select/select.component.scss

Fix mutliples problems of select

Ng fixes select

---

packages/icons/CHANGELOG.md
packages/icons/src/_classes.scss

Icons.ux 746.icon.alignment

---

packages/scss/CHANGELOG.md
packages/scss/src/components/_table.scss

[fix] line borders gap

---

README.md
packages/scss/demo/components/mixins.html
packages/scss/demo/includes/demo-main-content.html

Adds a more detailed readme and more details on mixins & helper functions in the SCSS demo

[Doc] Documentation improvement

---

packages/ng/CHANGELOG.md
packages/ng/src/app/animations/animation.factory.ts
packages/ng/src/app/animations/fade.animation.ts
packages/ng/src/app/animations/scale.animation.ts
packages/ng/src/app/animations/slide.animation.ts

Allows the customization of animations with distinct in/out timing and trigger naming.
Removes generic LuAnimationFactory.

[NG] Adds Enter and leave animation timing and trigger naming

---

packages/ng/libraries/core/package.json

fixes #293 
meaning i didn't test nothin'

fix dependencies in ng sub package

---

packages/scss/gulpfile.js
packages/scss/package.json
packages/scss/src/_icons.scss
packages/scss/src/_theming.overridable.scss
packages/scss/src/_theming.scss
packages/scss/src/components/_actionIcon.scss
packages/scss/src/components/_container.scss
packages/scss/src/main.cssvar.scss
packages/scss/src/main.dist.scss
packages/scss/src/main.scss
packages/scss/src/mixins/_responsiveness.scss
packages/scss/src/theming/_cssvars.scss
packages/scss/src/theming/_get-set.scss

Refacto to make CSSVars activated by default

[1.0][SCSS] CSS Vars are now activated by default

---

packages/scss/CHANGELOG.md
packages/scss/demo/components/loading.html
packages/scss/demo/demo.css
packages/scss/src/components/_breadcrumb.scss
packages/scss/src/components/_card.scss
packages/scss/src/components/_form.scss
packages/scss/src/components/_loading.scss

Scss.loading.invert

---

packages/scss/CHANGELOG.md

The almighty changelog for 1.0.0 in SCSS package

[SCSS] Changelog SCSS Package

---

packages/scss/CHANGELOG.md
packages/scss/src/_icons.scss
packages/scss/src/_typo.scss
packages/scss/src/theming/_commons.scss

Fixes icon sizing & link hover state

[SCSS] Icon size & Link hover state

---

packages/ng/libraries/core/src/lib/select/index.ts
packages/ng/libraries/core/src/lib/select/input/select-input.component.html
packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
packages/ng/libraries/core/src/lib/select/input/select-input.module.ts
packages/ng/libraries/core/src/lib/select/picker/index.ts
packages/ng/libraries/core/src/lib/select/picker/select-picker.component.html
packages/ng/libraries/core/src/lib/select/picker/select-picker.component.scss
packages/ng/libraries/core/src/lib/select/picker/select-picker.component.ts
packages/ng/libraries/core/src/lib/select/picker/select-picker.model.ts
packages/ng/libraries/core/src/lib/select/picker/select-picker.module.ts

adds a picker to the new select, popover opens on click

Select.picker

---

packages/ng/docs/demo/src/app/select/basic/basic.html
packages/ng/docs/demo/src/app/select/basic/basic.ts
packages/ng/docs/demo/src/app/select/select.module.ts
packages/ng/libraries/core/src/lib/index.ts
packages/ng/libraries/core/src/lib/option/index.ts
packages/ng/libraries/core/src/lib/option/option.component.html
packages/ng/libraries/core/src/lib/option/option.component.ts
packages/ng/libraries/core/src/lib/option/option.model.ts
packages/ng/libraries/core/src/lib/option/option.module.ts
packages/ng/libraries/core/src/lib/popover/popover.component.ts
packages/ng/libraries/core/src/lib/popover/popover.model.ts
packages/ng/libraries/core/src/lib/popover/popover.triggers.ts
packages/ng/libraries/core/src/lib/select/input/select-input.component.html
packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
packages/ng/libraries/core/src/lib/select/picker/select-picker.component.html
packages/ng/libraries/core/src/lib/select/picker/select-picker.component.ts
packages/ng/libraries/core/src/lib/select/picker/select-picker.model.ts
packages/ng/libraries/core/src/lib/select/picker/select-picker.module.ts
packages/ng/libraries/core/src/lib/select/select.module.ts

the picker sees the options and on one option selections, gives it to the input and the input sets it as controlvalueaccessor

Select.option

---

packages/ng/docs/demo/src/app/select/basic/basic.html
packages/ng/libraries/core/src/lib/index.ts
packages/ng/libraries/core/src/lib/input/index.ts
packages/ng/libraries/core/src/lib/input/input.model.ts
packages/ng/libraries/core/src/lib/input/picker/index.ts
packages/ng/libraries/core/src/lib/module.ts
packages/ng/libraries/core/src/lib/option/item/option-item.component.scss
packages/ng/libraries/core/src/lib/option/item/option-item.component.ts
packages/ng/libraries/core/src/lib/popover/popover.module.ts
packages/ng/libraries/core/src/lib/select/input/select-input.component.html
packages/ng/libraries/core/src/lib/select/input/select-input.component.ts

temp - use templateref to display the current value

Poc.select.display

---

packages/ng/libraries/core/src/lib/option/item/option-item.model.ts
packages/ng/libraries/core/src/lib/option/operator/option-operator.model.ts
packages/ng/libraries/core/src/lib/option/operator/searcher/option-searcher.component.html
packages/ng/libraries/core/src/lib/option/operator/searcher/option-searcher.component.ts
packages/ng/libraries/core/src/lib/option/operator/template/option-template.component.html
packages/ng/libraries/core/src/lib/option/operator/template/option-template.component.ts
packages/ng/libraries/core/src/lib/option/picker/option-picker.model.ts
packages/ng/libraries/core/src/lib/popover/panel/popover-panel.model.ts
packages/ng/libraries/core/src/lib/popover/trigger/popover-trigger.model.ts

adds way for the picker to tell the operators some events are occuring
like keyboard evvents, picker opening/closing

Picker.events

---

packages/ng/docs/demo/src/app/select/basic/basic.html
packages/ng/libraries/core/src/lib/input/displayer/index.ts
packages/ng/libraries/core/src/lib/input/displayer/input-displayer.model.ts
packages/ng/libraries/core/src/lib/input/index.ts
packages/ng/libraries/core/src/lib/option/displayer/index.ts
packages/ng/libraries/core/src/lib/option/displayer/option-displayer.component.ts
packages/ng/libraries/core/src/lib/option/displayer/option-displayer.module.ts
packages/ng/libraries/core/src/lib/option/index.ts
packages/ng/libraries/core/src/lib/option/item/option-item.component.ts
packages/ng/libraries/core/src/lib/option/item/option-item.model.ts
packages/ng/libraries/core/src/lib/option/option.module.ts
packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts
packages/ng/libraries/core/src/lib/popover/trigger/popover-trigger.model.ts
packages/ng/libraries/core/src/lib/select/clearer/select-clearer.component.html
packages/ng/libraries/core/src/lib/select/clearer/select-clearer.component.ts
packages/ng/libraries/core/src/lib/select/input/select-input.component.html
packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
packages/ng/libraries/core/src/lib/select/input/select-input.model.ts
packages/ng/libraries/core/src/lib/select/input/select-input.module.ts
packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.html
packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.ts
packages/ng/libraries/core/src/lib/user/select/input/user-select-input.module.ts

add a displayer interface with 2 methods
- getELtRef(value)
- getViewRef(value)
then the selects tries displaying the value as view first, then as element ref
displaying with the elementref uses the renderer and nativeelt so its not super duper great

Select.display

---

packages/ng/docs/demo/src/app/api/select/api-select.component.html
packages/ng/docs/demo/src/app/api/select/api-select.component.ts
packages/ng/docs/demo/src/app/api/select/api-select.module.ts
packages/ng/docs/demo/src/app/api/select/basic/basic.html
packages/ng/docs/demo/src/app/api/select/basic/basic.ts
packages/ng/libraries/core/src/lib/api/select/api-select.module.ts
packages/ng/libraries/core/src/lib/api/select/feeder/api-feeder.component.ts
packages/ng/libraries/core/src/lib/api/select/feeder/api-feeder.model.ts
packages/ng/libraries/core/src/lib/api/select/feeder/index.ts
packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.html
packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.ts
packages/ng/libraries/core/src/lib/api/select/input/api-select-input.module.ts
packages/ng/libraries/core/src/lib/api/select/input/index.ts
packages/ng/libraries/core/src/lib/api/select/pager/api-pager.component.ts
packages/ng/libraries/core/src/lib/api/select/pager/api-pager.model.ts
packages/ng/libraries/core/src/lib/api/select/pager/index.ts
packages/ng/libraries/core/src/lib/api/select/searcher/api-searcher.component.ts
packages/ng/libraries/core/src/lib/api/select/searcher/api-searcher.model.ts
packages/ng/libraries/core/src/lib/api/select/searcher/index.ts

adds component `<lu-api-select>` which is a generic version of what you can do with the select + option picker + api-operator

Api.select

---

packages/ng/docs/demo/src/app/app.module.ts
packages/ng/docs/demo/src/app/navigation/navigation.router.ts
packages/ng/docs/demo/tsconfig.app.json
packages/ng/libraries/formly/src/lib/formly.module.ts
packages/ng/libraries/formly/src/lib/types/select.html
packages/ng/libraries/formly/src/lib/types/user.html

Formly.select

---

packages/ng/libraries/core/src/lib/option/item/option-item.component.scss
packages/ng/libraries/core/src/lib/option/operator/options/options.component.scss
packages/ng/libraries/core/src/lib/option/operator/searcher/option-searcher.component.scss
packages/ng/libraries/core/src/lib/option/picker/option-picker.component.scss
packages/ng/libraries/core/src/lib/select/clearer/select-clearer.component.scss
packages/ng/libraries/core/src/lib/select/input/select-input.common.scss

Adds `mod-search`, fixes the search input and handle clearer aspect through `is-clearable` state

[ng][enh] Select additionnal styles

---

packages/ng/docs/demo/src/app/select/basic/basic.html
packages/ng/docs/demo/src/app/select/multiple/multiple.html
packages/ng/docs/demo/src/app/select/multiple/multiple.ts
packages/ng/docs/demo/src/app/select/select.component.html
packages/ng/docs/demo/src/app/select/select.component.ts
packages/ng/docs/demo/src/app/select/select.module.ts
packages/ng/libraries/core/src/lib/input/displayer/input-displayer.directive.ts
packages/ng/libraries/core/src/lib/input/displayer/input-displayer.model.ts
packages/ng/libraries/core/src/lib/input/picker/input-picker.model.ts
packages/ng/libraries/core/src/lib/option/picker/option-picker.component.html
packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts
packages/ng/libraries/core/src/lib/option/picker/option-picker.model.ts
packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
packages/ng/libraries/core/src/lib/select/input/select-input.model.ts

Select.support.multiple

---

packages/ng/docs/demo/src/app/api/select/basic/basic.html
packages/ng/docs/demo/src/app/api/select/basic/basic.ts
packages/ng/docs/demo/src/app/user/select/basic/basic.html
packages/ng/docs/demo/src/app/user/select/basic/basic.ts
packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.html
packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.ts
packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
packages/ng/libraries/core/src/lib/select/input/select-input.model.ts
packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.html
packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.ts

`api-select` and `user-select` multiple
i had to rewrite the way it is displayed to go through a displayer and be more iso with the way the select classic works

Api.select.multiple

---

packages/ng/docs/demo/src/app/select/multiple/multiple.html
packages/ng/docs/demo/src/app/select/multiple/multiple.ts
packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.html
packages/ng/libraries/core/src/lib/option/item/option-item.component.scss
packages/ng/libraries/core/src/lib/option/operator/searcher/option-searcher.component.scss
packages/ng/libraries/core/src/lib/select/input/select-input.common.scss
packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.html
packages/ng/libraries/core/src/style/_theming.overridable.scss
packages/ng/libraries/core/src/style/_theming.scss
packages/ng/libraries/core/src/style/theme/_options.theme.scss
packages/ng/libraries/core/src/style/theme/_select.theme.scss

Adds style for select multiple & specific theme stylesheet

[NG] Style for select multiple

---

packages/ng/docs/demo/src/app/shared/redirect/redirect.module.ts
packages/ng/libraries/core/src/lib/input/input.directive.ts
packages/ng/libraries/core/src/lib/input/input.module.ts

when there are 2 control value accessor on the same tag, it throws an error and thats kind of normal
so luInput isnt a cva anymore, cuz it just reads the value, it doesnt write it

Input.directive

---

packages/ng/libraries/core/src/lib/option/operator/for-options/for-options.directive.ts
packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts

- fix the bug i showed you with the picker being all white
- fix the class `is-selected` not being reapplied when the option displed changed

Api.select.fix

---

packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts
packages/ng/libraries/core/src/lib/select/input/select-input.model.ts

Fix #392 	
Fix cannot read property element of undefined

Fix.lu select

---

packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
packages/ng/libraries/core/src/style/definitions/select/_select-input.scss
packages/ng/libraries/core/src/style/theme/_select.theme.scss

Adapts style for Select.
Adds auto is-clearable class when a clearer is given.
Handles overflow & alignment better.

[FIX][NG] Style for Select

---

packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.ts
packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts
packages/ng/libraries/core/src/lib/option/picker/option-picker.model.ts
packages/ng/libraries/core/src/lib/select/clearer/select-clearer.component.html
packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.ts
packages/scss/src/components/inputs/field/_field.scss
packages/scss/src/components/inputs/textfield/_textfield.framed.scss
packages/scss/src/components/inputs/textfield/_textfield.scss

Allows luSelect to be focusable

[NG] Select is focusable

---

packages/ng/docs/demo/src/app/formly/basic/basic.ts
packages/ng/libraries/core/src/lib/option/picker/option-picker.model.ts
packages/ng/libraries/formly/src/lib/formly.config.ts
packages/ng/libraries/formly/src/lib/formly.module.ts
packages/ng/libraries/formly/src/lib/types/api.html
packages/ng/libraries/formly/src/lib/types/api.ts
packages/ng/libraries/formly/src/lib/types/select.scss
packages/ng/libraries/formly/src/lib/types/user.ts

adds support for type `api` in formly

Formly.api.select

---

packages/scss/src/_typo.scss
packages/scss/src/components/inputs/field/_field.scss

[scss] button font

---

packages/ng/libraries/core/src/lib/select/input/select-input.model.ts

Fix the issue of empty array of values not being considered as an empty select

[ng][fix] Select - isEmpty if empty array

---

packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.ts
packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.ts

Selects should use `disabled` attribute rather than `is-disabled` class

[NG][FIX] Select disabled state

---

packages/scss/demo/components/templates.html
packages/scss/demo/demo.css
packages/scss/demo/templates/compact-withBanner.html
packages/scss/demo/templates/full-withBanner.html
packages/scss/src/components/_main.scss
packages/scss/src/components/_nav-side.scss
packages/scss/src/theming/components/_nav-side.theme.scss

Bottom section on compact navSide has its style.
Fixing few bugs remaining on this menu to reduce shame file in our solutions

[fix] scss - Bottom section on compact

---

.travis.yml
package-lock.json
package.json
packages/icons/package-lock.json
packages/icons/package.json
packages/ng/package-lock.json
packages/ng/package.json
packages/scss/package-lock.json
packages/scss/package.json

run npm audit on all packages, also moved icons dependencies to devdependencies

[fix] update package.json for security alerts

---

packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
packages/scss/src/components/inputs/textfield/_textfield.scss

hotfix for you bug boris
closes #457 
there are still some shenanigans happening

Fix.select.disabled

---

packages/ng/docs/demo/src/app/tooltip/basic/basic.html
packages/ng/libraries/core/src/lib/tooltip/trigger/tooltip-trigger.directive.ts

Add `luTooltipDisabled` as an input for `luTooltip`

[feat] ng - Add luTooltipDisabled option

---

packages/ng/docs/demo/src/app/shared/redirect/redirect.component.ts
packages/ng/docs/demo/src/app/user/select/basic/basic.ts
packages/ng/docs/demo/src/app/user/select/scoped/scoped.html
packages/ng/docs/demo/src/app/user/select/scoped/scoped.ts
packages/ng/docs/demo/src/app/user/select/user-select.component.html
packages/ng/docs/demo/src/app/user/select/user-select.component.ts
packages/ng/docs/demo/src/app/user/select/user-select.module.ts
packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.ts
packages/ng/libraries/core/src/lib/user/select/searcher/user-searcher.component.ts
packages/ng/libraries/core/src/lib/user/select/searcher/user-searcher.model.ts

fixes #414 
added `@Input` appInstance and operations to user select input and user-searcher components
- if none are specified, it uses `/api/v3/users/search`
- if some are specified, it switches to /api/v3/users/scopedSearch`

[feat] user select scoped search

---

packages/ng/libraries/core/src/lib/api/select/pager/api-pager.model.ts

[fix] api-pager which called get paged before api could be initialized

---

packages/ng/docs/demo/src/app/select/option-picker/operator/operator.html
packages/ng/docs/demo/src/app/select/option-picker/operator/operator.ts
packages/ng/libraries/core/src/lib/option/operator/for-options/for-options.directive.ts

same as #546, i just cleaned some unwanted commits cuz rc wasnt up to date
---------
optims of directive lu-for-options, so it just extends ngforof directive, and supports trackbyFn n stuff
-------
fixes #547

[feat] lu for options optimizations

---

packages/scss/src/components/_loading.scss
packages/scss/src/mixins/_loading.scss
packages/scss/src/theming/components/_loading.theme.scss

- Reduce rotatating speed
- 3px width for all big loaders
- add a dialog / sidePanel mod
--------
fix #556

[feat] Scss loading

---

packages/scss/CHANGELOG.md
packages/scss/src/components/inputs/radio-buttons/_radio-buttons.scss
packages/scss/src/theming/components/_radio-buttons.theme.scss

- Add default color in theme
-------
fixes #555

[feat] Scss radio button.theme

---

packages/ng/libraries/core/src/style/definitions/option/_option-picker.scss

Add a min width to options (fix small select issues)

[feat] add a min width to select's options

---

packages/scss/src/components/_container.scss

Container responsive width was broken as it wasn't calculated but juste putting value in a string

[fix] Container width wasn't properly calculated

---

packages/ng/docs/demo/src/app/formly/basic/basic.ts
packages/ng/libraries/formly/src/lib/types/date.html

fixes #553 
-----
add possibility to set a min or max in template options of a date input in formly

[feat] formly-date - add min/max

---

packages/scss/demo/components/lists.html
packages/scss/src/components/_list.scss

[feat] 552 add draggable list mod

---

packages/scss/demo/components/forms/forms-textfields.html
packages/scss/demo/demo.css
packages/scss/src/components/inputs/textfield/_textfield.scss

[feat] 563 textfield white

---

packages/scss/src/components/_table.scss

[feat] deemphasis table heads

---

packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.html
packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.ts
packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.html
packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.ts

lu-api-select and lu-user-select were not properly handling the multiple layout due to missing HostBidings.

[FIX][NG] Api & User select multiple weren't properly styled

---

packages/ng/docs/demo/src/theme/overrides/_palettes.override.scss
packages/scss/demo/demo.css
packages/scss/src/components/inputs/textfield/_textfield.scss
packages/scss/src/theming/_palettes.scss
packages/scss/src/theming/components/_textfield.theme.scss

[520] primary & secondary are grey

---

packages/scss/demo/templates/side-header-nav.html
packages/scss/src/_ie11.scss
packages/scss/src/components/_filters.scss
packages/scss/src/components/_header.scss
packages/scss/src/components/_main.scss
packages/scss/src/components/_nav-side.scss
packages/scss/src/main.scss
packages/scss/src/theming/components/_filters.theme.scss
packages/scss/src/theming/components/_header.theme.scss

- Set minimum height for headers / filters 
- Fix sticky position 
-----
fixes #565

[fix] header misc

---

packages/ng/libraries/core/src/style/definitions/option/_option-picker.scss
packages/ng/libraries/core/src/style/definitions/option/_option-searcher.scss

Fix select option's height in IE11
------
fixes #586

[fix] options height for IE11

---

packages/ng/libraries/core/src/style/theme/_tooltip.theme.scss
packages/scss/src/components/_toasts.scss
packages/scss/src/theming/_commons.scss
packages/scss/src/theming/components/_toasts.theme.scss

[feat] toast/tooltip same color

---

packages/scss/src/components/_table.scss

Ascending arrow now goes up and descending arrow goes down

[fix][SCSS] Tables sorting arrows were inverted

---

packages/ng/applications/sandbox/src/app/issues/issues.router.ts
packages/ng/applications/sandbox/src/app/issues/refacto-overlay-advanced/refacto-overlay-advanced.component.html
packages/ng/applications/sandbox/src/app/issues/refacto-overlays-reposition/index.ts
packages/ng/applications/sandbox/src/app/issues/refacto-overlays-reposition/refacto-overlays-reposition.component.html
packages/ng/applications/sandbox/src/app/issues/refacto-overlays-reposition/refacto-overlays-reposition.component.ts
packages/ng/applications/sandbox/src/app/issues/refacto-overlays-reposition/refacto-overlays-reposition.module.ts
packages/ng/applications/sandbox/src/app/issues/refacto-tooltip/index.ts
packages/ng/applications/sandbox/src/app/issues/refacto-tooltip/refacto-tooltip.component.html
packages/ng/applications/sandbox/src/app/issues/refacto-tooltip/refacto-tooltip.component.ts
packages/ng/applications/sandbox/src/app/issues/refacto-tooltip/refacto-tooltip.module.ts
packages/ng/libraries/core/src/lib/overlay/popover/panel/popover-panel.model.ts
packages/ng/libraries/core/src/lib/overlay/popover/target/popover-target.model.ts
packages/ng/libraries/core/src/lib/overlay/popover/trigger/popover-trigger.model.ts
packages/ng/libraries/core/src/lib/overlay/tooltip/animation/index.ts
packages/ng/libraries/core/src/lib/overlay/tooltip/animation/tooltip.animation.ts
packages/ng/libraries/core/src/lib/overlay/tooltip/index.ts
packages/ng/libraries/core/src/lib/overlay/tooltip/panel/tooltip-panel.component.html
packages/ng/libraries/core/src/lib/overlay/tooltip/panel/tooltip-panel.component.ts
packages/ng/libraries/core/src/lib/overlay/tooltip/trigger/tooltip-trigger.directive.ts
packages/ng/libraries/core/src/style/components/_popover.scss
packages/ng/libraries/core/src/style/definitions/tooltip/_tooltip.scss

- scroll strat (scroll strat block does not work :'(, but the old version didnt either, so we're iso feature)
- refacto tooltip to be super close to popover

[BC] refacto overlays - scroll strat and repositionning

---

packages/ng/applications/sandbox/src/app/issues/issues.router.ts
packages/ng/applications/sandbox/src/app/issues/refactor-api-select/index.ts
packages/ng/applications/sandbox/src/app/issues/refactor-api-select/refactor-api-select.component.html
packages/ng/applications/sandbox/src/app/issues/refactor-api-select/refactor-api-select.component.ts
packages/ng/applications/sandbox/src/app/issues/refactor-api-select/refactor-api-select.module.ts
packages/ng/applications/sandbox/src/app/issues/refactor-select/index.ts
packages/ng/applications/sandbox/src/app/issues/refactor-select/refactor-select.component.html
packages/ng/applications/sandbox/src/app/issues/refactor-select/refactor-select.component.ts
packages/ng/applications/sandbox/src/app/issues/refactor-select/refactor-select.module.ts
packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.ts
packages/ng/libraries/core/src/lib/index.ts
packages/ng/libraries/core/src/lib/input/input.model.ts
packages/ng/libraries/core/src/lib/input/picker/input-picker.model.ts
packages/ng/libraries/core/src/lib/module.ts
packages/ng/libraries/core/src/lib/option/picker/option-picker.component.html
packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts
packages/ng/libraries/core/src/lib/option/picker/option-picker.model.ts
packages/ng/libraries/core/src/lib/option/picker/option-picker.module.ts
packages/ng/libraries/core/src/lib/overlay/popover/panel/popover-panel.component.html
packages/ng/libraries/core/src/lib/overlay/popover/panel/popover-panel.model.ts
packages/ng/libraries/core/src/lib/select/input/select-input.model.ts
packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.ts

after the refacto of the popover, the select and its picker were broken, now its fixed
same for api select and user-select

[BC] refactor popovers - fix select and option picker

---

packages/ng/libraries/core/src/lib/option/picker/option-picker.model.ts
packages/ng/libraries/core/src/lib/overlay/popover/panel/popover-panel.model.ts
packages/ng/libraries/core/src/lib/overlay/popover/trigger/popover-trigger.directive.ts
packages/ng/libraries/core/src/lib/overlay/popover/trigger/popover-trigger.model.ts
packages/ng/libraries/core/src/lib/overlay/tooltip/panel/tooltip-panel.component.ts
packages/ng/libraries/core/src/lib/overlay/tooltip/trigger/tooltip-trigger.directive.ts

[BC] popover refactor - clean up crew

---

packages/scss/src/components/_callout.scss
packages/scss/src/components/_label.scss
packages/scss/src/theming/_palettes.scss

[632] new state colors

---

packages/scss/src/components/_label.scss

[629] labels new ui

---

packages/scss/src/_ie11.scss
packages/scss/src/components/_container.scss
packages/scss/src/components/_filters.scss
packages/scss/src/components/_header.scss
packages/scss/src/components/_main.scss
packages/scss/src/components/_nav-side.scss
packages/scss/src/theming/_commons.scss

Add the possibility to change the breakpoint where UI toggle between mobile & standard view.
(under discussion)

[631] set mobile layout toggle in a variable

---

packages/ng/libraries/core/src/lib/index.ts
packages/ng/libraries/core/src/lib/overlay/modal/modal-panel.component.ts
packages/ng/libraries/core/src/lib/overlay/modal/modal.intl.ts
packages/ng/libraries/core/src/lib/overlay/modal/modal.translate.ts
packages/ng/libraries/core/src/lib/translate/index.ts
packages/ng/libraries/core/src/lib/translate/intl.model.ts
packages/ng/libraries/core/src/lib/translate/translation.model.ts

waiting for this pr https://github.com/microsoft/TypeScript/pull/26797 to have better interface declaration

Translate typing

---

packages/ng/applications/sandbox/src/app/issues/tree-picker-advanced/tree-picker-advanced.component.html
packages/ng/applications/sandbox/src/app/issues/tree-picker-advanced/tree-picker-advanced.component.ts
packages/ng/libraries/core/src/lib/tree/option/operator/searcher/index.ts
packages/ng/libraries/core/src/lib/tree/option/operator/searcher/tree-option-searcher.component.html
packages/ng/libraries/core/src/lib/tree/option/operator/searcher/tree-option-searcher.component.scss
packages/ng/libraries/core/src/lib/tree/option/operator/searcher/tree-option-searcher.component.ts
packages/ng/libraries/core/src/lib/tree/option/operator/searcher/tree-option-searcher.module.ts
packages/ng/libraries/core/src/lib/tree/option/operator/tree-option-operator.model.ts
packages/ng/libraries/core/src/lib/tree/option/operator/tree-option-operator.module.ts

tree-searcher operator similar to option-searcher operator

[feat] tree searcher operator

---

packages/scss/src/components/inputs/field/_field.framed.scss
packages/scss/src/components/inputs/textfield/_textfield.material.scss

Fixes disabled state being overriden for material and framed style

[fix] adds state class for is disabled is readonly

---

packages/ng/libraries/core/src/lib/user/tile/user-tile.component.html

sam eas #665 but for released in a patch

[LF][FIX] user-tile > avoid error when user is undefined

---

packages/ng/libraries/core/src/lib/overlay/modal/modal-config.default.ts
packages/ng/libraries/core/src/lib/overlay/popup/popup-config.default.ts
packages/ng/libraries/core/src/lib/overlay/sidepanel/sidepanel-config.default.ts
packages/ng/libraries/core/src/lib/overlay/sidepanel/sidepanel-panel.component.html
packages/ng/libraries/core/src/style/_components.scss
packages/ng/libraries/core/src/style/components/_popup.scss
packages/ng/libraries/core/src/style/components/_sidepanel.scss
packages/ng/libraries/core/src/style/theme/_popup.theme.scss

Adds sidepanel styles and basic overlay animations using CSS.
I opted for CSS animations rather than Angular Animations due to the complexity of implementing and overriding Angular ones.

[3.0] SidePanel styles + overlay animations

---

packages/scss/demo/components/tables.html
packages/scss/src/components/_table.scss

Add feature table align right

---

packages/scss/demo/components/forms/forms-textfields.html
packages/scss/src/components/inputs/textfield/_textfield.scss

Add clearable textfield

---

packages/ng/applications/sandbox/src/app/issues/fix-modal/fix-modal.component.ts
packages/ng/applications/sandbox/src/app/issues/poc-popup/poc-popup.template.html
packages/ng/libraries/core/src/lib/overlay/modal/modal-panel.component.html
packages/ng/libraries/core/src/lib/overlay/modal/modal-panel.component.ts
packages/ng/libraries/core/src/lib/overlay/sidepanel/sidepanel-config.default.ts
packages/ng/libraries/core/src/lib/overlay/sidepanel/sidepanel-panel.component.html
packages/ng/libraries/core/src/lib/overlay/sidepanel/sidepanel-panel.component.ts
packages/ng/libraries/core/src/style/components/_popover.scss
packages/ng/libraries/core/src/style/components/_popup.scss
packages/ng/libraries/core/src/style/components/_sidepanel.scss
packages/ng/libraries/core/src/style/theme/_popup.theme.scss

- Improve UI 
- Add content scroll with automatic height
- Fix responsive issues
---------
fixes #707

[fix] 707 modale ui

---

packages/ng/applications/sandbox/src/app/issues/refacto-overlays/refacto-overlays.component.html
packages/ng/libraries/core/src/lib/overlay/popover/panel/popover-panel.component.html
packages/ng/libraries/core/src/lib/overlay/popover/panel/popover-panel.component.ts

[Feat-732] lu-popover template context

---

packages/scss/demo/components/buttons.html
packages/scss/src/components/_button.scss

[button] Add a invert mod to mod-link

---

packages/scss/src/components/_gauge.scss

Add a fast transition on gauge bar

---

packages/scss/demo/components/utilities.html
packages/scss/src/utilities/_misc.scss

Add utilities Help on icons

---

packages/scss/src/components/_table.scss

[table] Improve body row mod filter

---

packages/scss/src/components/_breadcrumb.scss

[Breadcrumb] Increase intems spacing

---

packages/scss/src/components/_button.scss

[button] mod-link should have a button style (weight 600/no underline)

---

packages/scss/src/components/_link.scss

[link] Should forced to be inline or inline block

---

packages/ng/libraries/core/src/style/definitions/option/_option-item.scss
packages/ng/libraries/core/src/style/theme/_options.theme.scss
packages/scss/src/theming/components/_checkbox.theme.scss

#701 
Allow to override option's checkbox

[701] options checkbox theming

---

packages/ng/libraries/core/src/style/definitions/option/_option-item.scss
packages/scss/src/theming/_commons.scss

#704 
Bind select options with commons selected color

[704] bind options with commons.selected

---

packages/scss/src/components/_table.scss

[Table] Table clickable and Filters

---

packages/scss/demo/components/utilities.html
packages/scss/src/utilities/_text.scss

[Utilities] Add a responsive image utility

---

packages/scss/demo/components/tables.html
packages/scss/src/components/_table.scss

- :sparkles: Cette PR est une nouveauté ou un remaniement fonctionnel 
-----

Add mod borderless for table

---

packages/scss/src/components/_callout.scss

[692] improve callout links

---

packages/ng/applications/sandbox/src/app/issues/fix-472/fix-472.component.html
packages/ng/docs/demo/src/app/select/multiple/basic/basic.html
packages/ng/docs/demo/src/app/user/select/scoped/scoped.html
packages/ng/libraries/core/src/lib/department/select/input/department-select-input.component.html
packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.html
packages/ng/libraries/core/src/style/definitions/option/_option-item.scss
packages/ng/libraries/core/src/style/definitions/select/_select-input.scss
packages/ng/libraries/core/src/style/theme/_select.theme.scss

#708 
Improve select multiples (style standardization, baseline alignments...)

Feat.708.select.multiple

---

packages/scss/src/components/_grid.scss

fixes #716 
correction of PR #752 and #749

[grids] u-first / u-last don't work anymore

---

packages/scss/src/components/inputs/field/_field.scss
packages/scss/src/components/inputs/textfield/_textfield.scss

[fix] textfiled vertical alignment

---

packages/ng/applications/sandbox/src/app/issues/poc-popup/poc-popup.template.html
packages/ng/libraries/core/src/lib/overlay/modal/modal-panel.component.html
packages/ng/libraries/core/src/lib/overlay/sidepanel/sidepanel-panel.component.html

[fix] modale close button style

---

packages/scss/src/components/inputs/textfield/_textfield.scss

[textfield] Give a light border to mod-white

---

packages/scss/src/components/_button.scss

[button-group] remove margins

---

packages/scss/demo/components/utilities.html
packages/scss/src/_utilities.scss
packages/scss/src/utilities/_textfield.scss

- :sparkles: Cette PR est une nouveauté ou un remaniement fonctionnel 
-----

[utilities] add an utility to remove textfields number spin buttons

---

packages/scss/src/components/_loading.scss
packages/scss/src/components/inputs/field/_field.scss

[loading] Refactor fullPage #770

---

packages/scss/src/components/inputs/field/_field.scss

[textfield] Fix mod-inline left alignment

---

packages/ng/libraries/core/src/style/definitions/option/_option-searcher.scss

[select] search background should be white

---

packages/scss/src/components/_table.scss

[table] add cursor pointer on mod clickable

---

packages/scss/src/components/inputs/textfield/_textfield.framed.scss
packages/scss/src/mixins/_forms.scss

[textfield] Framed placeholder should be visible in neutral state

---

packages/ng/libraries/core/src/lib/option/picker/option-picker-advanced.component.html
packages/ng/libraries/core/src/lib/option/picker/option-picker.component.html
packages/ng/libraries/core/src/lib/tree/option/picker/tree-option-picker-advanced.component.html
packages/ng/libraries/core/src/lib/tree/option/picker/tree-option-picker.component.html

[Fix][Option-picker] add class

---

packages/ng/applications/sandbox/src/app/issues/refactor-api-select/refactor-api-select.component.html
packages/ng/applications/sandbox/src/app/issues/refactor-select/refactor-select.component.html
packages/ng/libraries/core/src/style/definitions/select/_select-input.scss
packages/ng/package-lock.json
packages/scss/demo/components/forms/forms-textfields.html
packages/scss/package-lock.json
packages/scss/src/components/inputs/textfield/_textfield.scss
packages/scss/src/theming/components/_textfield.theme.scss

Create a filter display for textfields

Feat.795.textfield.filters

---

packages/ng/applications/sandbox/src/app/issues/formly-framed/formly-framed.component.html
packages/ng/applications/sandbox/src/app/issues/formly-framed/formly-framed.component.ts
packages/ng/applications/sandbox/src/app/issues/formly-framed/formly-framed.module.ts
packages/ng/applications/sandbox/src/app/issues/formly-framed/index.ts
packages/ng/applications/sandbox/src/app/issues/formly-wrappers/formly-wrappers.component.html
packages/ng/applications/sandbox/src/app/issues/formly-wrappers/formly-wrappers.component.ts
packages/ng/applications/sandbox/src/app/issues/formly-wrappers/formly-wrappers.module.ts
packages/ng/applications/sandbox/src/app/issues/formly-wrappers/index.ts
packages/ng/applications/sandbox/src/app/issues/formly/formly.component.html
packages/ng/applications/sandbox/src/app/issues/formly/formly.component.ts
packages/ng/applications/sandbox/src/app/issues/formly/formly.module.ts
packages/ng/applications/sandbox/src/app/issues/formly/index.ts
packages/ng/applications/sandbox/src/app/issues/issues.router.ts
packages/ng/applications/sandbox/tsconfig.aot.json
packages/ng/applications/sandbox/tsconfig.app.json
packages/ng/libraries/formly/src/lib/wrappers/error.ts

fixes #799 
added sandbox issue to make sure formly is sill working
added more permissive condition for the error wrapper to appear

Feat/formly - qw

---

packages/scss/demo/components/buttons.html
packages/scss/src/components/_button.scss

https://github.com/LuccaSA/lucca-front/issues/647

Feat.button.moreactions

---

packages/scss/demo/demo.css
packages/scss/src/components/_filters.scss
packages/scss/src/components/_header.scss

fixes #772 
Give sticky filters / headers banner height information

[772] fix sticky element vertical position

---

packages/scss/demo/components/containers.html
packages/scss/demo/components/main.html
packages/scss/demo/includes/demo-main-content.html
packages/scss/demo/includes/demo-menu.html
packages/scss/src/components/_container.scss

[layout] mod-withStickyHeader refactor

---

packages/ng/libraries/core/src/style/components/_sidepanel.scss
packages/ng/libraries/core/src/style/theme/_popup.theme.scss

[side panel] Default size should be 39 rem

---

packages/scss/src/components/_loading.scss

fixes #805 
Remove width on loading mod-fullPage
closes #844

[loading] fullPage should accept a label

---

packages/ng/libraries/core/src/style/components/_popup.scss

fixes #896 
Fix modal / sidepanels content padding bottom with a fix found by @almonais 😋

modal bottom padding

---

packages/scss/demo/components/tables.html
packages/scss/src/components/_table.scss

[Table] Draggable header alignment

---

packages/scss/demo/components/tables.html
packages/scss/src/components/_table.scss

[table] mod no padding for first/last cell

---

packages/ng/applications/sandbox/src/app/issues/date-minmax/date-minmax.component.html
packages/ng/applications/sandbox/src/app/issues/date-minmax/date-minmax.component.ts
packages/ng/applications/sandbox/src/app/issues/date-minmax/date-minmax.module.ts
packages/ng/applications/sandbox/src/app/issues/date-minmax/index.ts
packages/ng/applications/sandbox/src/app/issues/formly/formly.module.ts
packages/ng/applications/sandbox/src/app/issues/issues.router.ts
packages/ng/libraries/date/src/lib/calendar/calendar-input.component.ts
packages/ng/libraries/date/src/lib/input/date-input.directive.ts
packages/ng/libraries/date/src/lib/native/native-date.module.ts
packages/ng/libraries/date/src/lib/picker/date-picker.component.html
packages/ng/libraries/date/src/lib/picker/date-picker.component.ts
packages/ng/libraries/date/src/lib/select/date-select-input.component.html
packages/ng/libraries/date/src/lib/select/date-select-input.component.ts
packages/ng/libraries/formly/package.json
packages/ng/libraries/formly/src/lib/formly.module.ts
packages/ng/libraries/formly/src/lib/types/date.html
packages/ng/libraries/formly/src/lib/types/date.ts
packages/ng/libraries/formly/src/lib/types/select.scss
packages/ng/libraries/formly/src/lib/wrappers/icon.ts
packages/ng/libraries/root/src/index.ts

added inputs min max to components
- luDateInput direcive
- lu-calendar component
- lu-date-picker
- lu-date-select
and the ones being control value accessor now also implement validator with min/max
also added class `is-disabled` in lu-calendar fro items not in the min/max range, for any granularity, and added class is-today and is-active in monthly view and yearly view
it needs some style @jeremie-lucca

[feat] date - min/max inputs and validation

---

packages/ng/applications/sandbox/src/app/issues/date-minmax/date-minmax.component.html
packages/ng/applications/sandbox/src/app/issues/date-minmax/date-minmax.component.ts
packages/ng/applications/sandbox/src/app/issues/date-minmax/date-minmax.module.ts
packages/ng/applications/sandbox/src/app/issues/date-minmax/index.ts
packages/ng/applications/sandbox/src/app/issues/date-select/date-select.component.html
packages/ng/applications/sandbox/src/app/issues/date-select/date-select.component.ts
packages/ng/applications/sandbox/src/app/issues/date-select/date-select.module.ts
packages/ng/applications/sandbox/src/app/issues/date-select/index.ts
packages/ng/applications/sandbox/src/app/issues/formly/formly.module.ts
packages/ng/applications/sandbox/src/app/issues/issues.router.ts
packages/ng/libraries/date/src/lib/calendar/calendar-input.component.ts
packages/ng/libraries/date/src/lib/date.module.ts
packages/ng/libraries/date/src/lib/index.ts
packages/ng/libraries/date/src/lib/input/date-input.directive.ts
packages/ng/libraries/date/src/lib/native/native-date.module.ts
packages/ng/libraries/date/src/lib/picker/date-picker.component.html
packages/ng/libraries/date/src/lib/picker/date-picker.component.ts
packages/ng/libraries/date/src/lib/select/date-select-input.component.html
packages/ng/libraries/date/src/lib/select/date-select-input.component.scss
packages/ng/libraries/date/src/lib/select/date-select-input.component.ts
packages/ng/libraries/date/src/lib/select/date-select-input.module.ts
packages/ng/libraries/date/src/lib/select/index.ts
packages/ng/libraries/formly/package.json
packages/ng/libraries/formly/src/lib/formly.module.ts
packages/ng/libraries/formly/src/lib/types/date.html
packages/ng/libraries/formly/src/lib/types/date.ts
packages/ng/libraries/formly/src/lib/types/select.scss
packages/ng/libraries/formly/src/lib/wrappers/icon.ts
packages/ng/libraries/root/src/index.ts

all in one `lu-date-select` component

[feat] date-select

---

packages/ng/applications/sandbox/src/app/issues/fix-modal/fix-modal.component.ts
packages/ng/applications/sandbox/src/app/issues/poc-modal/poc-modal.component.ts
packages/ng/applications/sandbox/src/app/issues/poc-popup/poc-popup.component.ts
packages/ng/applications/sandbox/src/app/issues/sidepanel/sidepanel.component.ts
packages/ng/libraries/date/src/lib/picker/date-picker.component.html
packages/ng/libraries/modal/src/lib/modal-config.default.ts
packages/ng/libraries/modal/src/lib/modal-config.model.ts
packages/ng/libraries/modal/src/lib/modal-panel.component.html
packages/ng/libraries/modal/src/lib/modal-panel.component.ts
packages/ng/libraries/modal/src/lib/modal-ref.factory.ts
packages/ng/libraries/modal/src/lib/modal.model.ts
packages/ng/libraries/modal/src/lib/modal.module.ts
packages/ng/libraries/modal/src/lib/modal.service.ts
packages/ng/libraries/popup/src/lib/popup-config.default.ts
packages/ng/libraries/popup/src/lib/popup-config.model.ts
packages/ng/libraries/popup/src/lib/popup-ref.model.ts
packages/ng/libraries/popup/src/lib/popup.service.ts
packages/ng/libraries/sidepanel/src/lib/sidepanel-config.default.ts
packages/ng/libraries/sidepanel/src/lib/sidepanel-panel.component.html
packages/ng/libraries/sidepanel/src/lib/sidepanel-panel.component.ts
packages/ng/libraries/sidepanel/src/lib/sidepanel-ref.factory.ts
packages/ng/libraries/sidepanel/src/lib/sidepanel.module.ts
packages/ng/libraries/sidepanel/src/lib/sidepanel.service.ts
packages/ng/libraries/user/src/lib/display/user-display.pipe.ts

- user-select - default display frpomat `lastname firstname` - fixes #890 
- modals/sp - can change the submit button palette
- modals/popup/sp - added option `size` - @jeremie-lucca i need some stylin' of that
- modals/sp - added config option `cahngeDetection` (default onpush) to open modals/sidepanels with different change detection strat - closes #913

some quick wins

---

packages/ng/libraries/user/src/lib/select/input/user-select-input.component.ts
packages/ng/libraries/user/src/lib/select/searcher/user-searcher.component.ts
packages/ng/libraries/user/src/lib/select/searcher/user-searcher.model.ts
packages/ng/libraries/user/src/lib/select/searcher/user-searcher.service.ts

in PR #908 i started a unnecessary and unwarranted refactor of /user (especially the ALuUserSrervice and other stuff)
it broke a lot for little gain so this PR undoes it
i will still refactor it a dn /api at some point, but not in this major

undid the refactor i did on the /user subpackage

---

packages/ng/libraries/date/src/lib/calendar/calendar-input.component.scss
packages/ng/libraries/date/src/lib/input/date-input.directive.ts
packages/ng/libraries/date/src/lib/input/date-input.intl.ts
packages/ng/libraries/date/src/lib/input/date-input.module.ts
packages/ng/libraries/date/src/lib/input/date-input.token.ts
packages/ng/libraries/date/src/lib/input/date-input.translate.ts
packages/ng/libraries/date/src/lib/input/index.ts
packages/ng/libraries/date/src/lib/picker/date-picker.component.html
packages/ng/libraries/date/src/lib/select/date-select-input.component.html
packages/ng/libraries/root/src/style/components/_picker.scss
packages/ng/libraries/root/src/style/components/_popover.scss
packages/ng/libraries/select/src/lib/input/select-input.component.ts

datepicker inner input styl

---

packages/scss/demo/components/tables.html
packages/scss/demo/demo.css
packages/scss/src/components/_table.scss
packages/scss/src/components/inputs/checkbox/_checkbox.scss
packages/scss/src/components/inputs/radio/_radio.scss
packages/scss/src/components/inputs/switch/_switch.scss
packages/scss/src/theming/_palettes.scss
packages/scss/src/theming/components/_checkbox.theme.scss
packages/scss/src/theming/components/_radio.theme.scss
packages/scss/src/theming/components/_switch.theme.scss
packages/scss/src/theming/components/_table.theme.scss

New guidelines components update

Pdn 413.newguideline.components.batch2

---

packages/scss/demo/templates/compact-withBanner.html
packages/scss/demo/templates/full-withBanner.html
packages/scss/demo/templates/fullmenu.html
packages/scss/demo/templates/side-cards.html
packages/scss/demo/templates/side-filters.html
packages/scss/demo/templates/side-header-nav.html
packages/scss/demo/templates/side-header.html
packages/scss/demo/templates/side-sections-header.html
packages/scss/demo/templates/side-sections.html
packages/scss/demo/templates/side.html
packages/scss/src/components/_nav-side.scss
packages/scss/src/theming/components/_nav-side.theme.scss

This reverts commit e4643f57ea25e20ebb7d0423e20efaf59342e4e1.
The new aspect of the sideNav is postponed to 4.1 as it would be too tedious to handle it with the breaking change update.

[RC] Revert "[ui] navside"

---

packages/ng/libraries/root/src/style/definitions/option/_option-item.scss
packages/ng/libraries/root/src/style/definitions/option/_option-searcher.scss
packages/ng/libraries/root/src/style/definitions/select/_select-input.scss
packages/ng/libraries/root/src/style/definitions/tooltip/_tooltip.scss
packages/scss/src/components/_table.scss
packages/scss/src/components/inputs/checkbox/_checkbox.scss

Fixes :
- Select style was broken on IE
- Tooltips font was too small
- Checkboxes were not centered
- Tables use border-top again instead of border-bottom

[RC] Fixes post feedacks

---

packages/ng/applications/sandbox/src/app/issues/formly/formly.component.ts
packages/ng/libraries/formly/src/lib/types/checkboxes.html
packages/ng/libraries/formly/src/lib/types/input.html
packages/ng/libraries/formly/src/lib/types/radios.html
packages/ng/libraries/formly/src/lib/types/textarea.html

Adds input name for in templateOptions (for input, checkbox, textarea and radios)

[Formly][Fix] Input name templateOptions

---

packages/ng/libraries/root/src/style/components/_popup.scss
packages/ng/libraries/root/src/style/components/_sidepanel.scss

Adds styles for classes `.sizes-xxx` for modals & popups

[RC][fix][NG][add] styles for modal sizes

---

packages/ng/libraries/root/src/style/definitions/select/_select-input.scss
packages/scss/demo/components/buttons.html
packages/scss/src/components/_button.scss

Adds palette for `.button.mod-outline`
Fixes `label` style in `mod-multiple` for selects

[RC] Fixes post update Prism

---

packages/ng/libraries/select/src/lib/input/select-input.component.ts

settimeout to the rescue
----
bug can be seen here
http://lucca-front.lucca.local/master/ng/#/formly
and fixed here
http://lucca-front.lucca.local/PR-968/ng/#/formly

fix select display shenanigans

---

packages/ng/libraries/formly/src/lib/types/api.ts
packages/ng/libraries/formly/src/lib/types/checkboxes.ts
packages/ng/libraries/formly/src/lib/types/date.ts
packages/ng/libraries/formly/src/lib/types/department.ts
packages/ng/libraries/formly/src/lib/types/input.ts
packages/ng/libraries/formly/src/lib/types/radios.ts
packages/ng/libraries/formly/src/lib/types/select.scss
packages/ng/libraries/formly/src/lib/types/select.ts
packages/ng/libraries/formly/src/lib/types/textarea.ts
packages/ng/libraries/formly/src/lib/types/user.ts

some bug when enablig/disabling a field

[formly] change detection strategy = default

---

packages/ng/libraries/root/src/style/definitions/option/_option-selector.scss

it broke transpil without the right includepath

[fix]rem  unneedeed import

---

packages/scss/demo/templates/compact-withBanner.html
packages/scss/demo/templates/full-withBanner.html
packages/scss/demo/templates/fullmenu.html
packages/scss/demo/templates/side-cards.html
packages/scss/demo/templates/side-filters.html
packages/scss/demo/templates/side-header-nav.html
packages/scss/demo/templates/side-header.html
packages/scss/demo/templates/side-sections-header.html
packages/scss/demo/templates/side-sections.html
packages/scss/demo/templates/side.html
packages/scss/src/components/_nav-side.scss
packages/scss/src/theming/components/_nav-side.theme.scss

NavSide new UI

---

packages/scss/src/components/inputs/checkbox/_checkbox.scss
packages/scss/src/components/inputs/radio-buttons/_radio-buttons.scss
packages/scss/src/components/inputs/radio/_radio.scss
packages/scss/src/mixins/_utilities.scss
packages/scss/src/utilities/_visibility.scss

fix a11y for inputs radios and checkboxes with mask

---

packages/scss/demo/components/forms/forms-framed.html
packages/scss/demo/components/forms/forms-textfields.html
packages/scss/src/components/inputs/field/_field.framed.scss
packages/scss/src/components/inputs/field/_field.scss
packages/scss/src/components/inputs/textfield/_textfield.framed.scss
packages/scss/src/components/inputs/textfield/_textfield.material.scss
packages/scss/src/components/inputs/textfield/_textfield.scss
packages/scss/src/mixins/_forms.scss

- [issue #680](https://github.com/LuccaSA/lucca-front/issues/680) - Textfield palettes does not affect its placeholder nor its hover

textfield placeholder with palettes

---

packages/ng/applications/sandbox/src/app/issues/dropdown/dropdown.component.html
packages/ng/applications/sandbox/src/app/issues/dropdown/dropdown.component.ts
packages/ng/applications/sandbox/src/app/issues/dropdown/dropdown.module.ts
packages/ng/applications/sandbox/src/app/issues/dropdown/index.ts
packages/ng/applications/sandbox/src/app/issues/issues.router.ts
packages/ng/libraries/root/src/style/_components.scss
packages/ng/libraries/root/src/style/components/_dropdown.scss
packages/ng/libraries/root/src/style/components/cdk/_misc.scss

- the icon for folded/unfolded will be replaced by an expand/collapse, it is only there for capture ;
- the component is (almost 100%) accessible;
- borders are not added if the folded part is at the top or bottom of the component;
- fixed width, but defined max height and max width;
- you can put buttons such as links.

Style for Dropdown

---

packages/scss/demo/components/labels.html
packages/scss/src/components/_label.scss

[SCSS] [label] mod-number

---

packages/ng/applications/sandbox/src/app/issues/date-picker-width/date-picker-width.component.html
packages/ng/applications/sandbox/src/app/issues/date-picker-width/date-picker-width.component.ts
packages/ng/applications/sandbox/src/app/issues/date-picker-width/date-picker-width.module.ts
packages/ng/applications/sandbox/src/app/issues/date-picker-width/index.ts
packages/ng/applications/sandbox/src/app/issues/issues.router.ts
packages/ng/libraries/root/src/style/components/_picker.scss
packages/scss/src/components/_nav-side.scss

[Fix] Feedback Timmi

---

packages/ng/libraries/root/src/style/components/_picker.scss

[SCSS] Fix - Date-select

---

packages/ng/libraries/modal/src/lib/modal-panel.component.html
packages/ng/libraries/sidepanel/src/lib/sidepanel-panel.component.html

in accordance with new ui styleguide
should not have breaking changes

ng-modal - header is h3 and not h2

---

packages/scss/demo/components/buttons.html
packages/scss/src/components/_button.scss
packages/scss/src/theming/components/_button.theme.scss

Add mod smaller on button

---

packages/scss/src/components/_action-icon.scss

Update Action Icon style

---

packages/scss/src/components/_button.scss
packages/scss/src/components/inputs/radio-buttons/_radio-buttons.scss
packages/scss/src/components/inputs/radio/_radio.scss

Update Radios style

---

packages/ng/libraries/date/src/lib/calendar/calendar-input.component.scss

[INT][LF-963] date-select class `is-disabled` ignored in calendar

---

packages/scss/src/_typo.scss

- Small code refacto h1-h6
- adds h6 style
- adds 4 mods: body1, body2, body3, caption

[PDN-647] Adding font styles

---

packages/ng/libraries/department/src/lib/select/input/department-select-input.component.scss
packages/ng/libraries/option/src/lib/item/tree-option-item.component.scss

[INT][LF-1046] remove !important for optionItem:hover .optionItem-value + change color

---

packages/scss/demo/components/chips.html
packages/scss/src/components/_chips.scss

[SCSS][PDN-664] Chips

---

packages/ng/libraries/root/src/style/components/_dropdown.scss

[INT] add class is-disabled

---

packages/scss/demo/components/forms/forms-files.html
packages/scss/src/components/inputs/file/_file.scss

[PDN-656] Update - File upload

---

packages/scss/demo/components/labels.html
packages/scss/src/components/inputs/field/_field.framed.scss
packages/scss/src/components/inputs/field/_field.scss
packages/scss/src/components/inputs/textfield/_textfield.scss
packages/scss/src/mixins/_forms.scss
packages/scss/src/theming/components/_textfield.theme.scss

[LF-652] Update textfield

---

packages/scss/src/components/inputs/checkbox/_checkbox.scss
packages/scss/src/components/inputs/switch/_switch.scss

fix scss transpil error

---

packages/scss/src/components/_button.scss

Fix mod-smaller button

---

packages/scss/src/components/_table.scss

Fix table mod-Borderless

---

packages/scss/demo/components/buttons.html
packages/scss/src/components/_button.scss

Overload palettes for grouped buttons

---

packages/scss/demo/components/buttons.html
packages/scss/src/components/_button.scss
packages/scss/src/components/inputs/checkbox/_checkboxesfield.scss

- Add the same style to `checkboxesfield` as to `radiosfield`.

Fix checkboxes field

---

packages/scss/src/components/_callout.scss

Callout remove after from title

---

packages/scss/src/theming/_commons.scss

Adds/updates shadow styles from the styleguides

[add] new shadows

---

packages/ng/libraries/formly/src/lib/types/api.html
packages/ng/libraries/formly/src/lib/types/api.ts

added standard to supported templateoptions of type api

---

packages/scss/src/_shame.scss

manual overide of cancel-button for input search. was done by normalize previously, but no more

fix normalize ^7 + input type=search

---

packages/scss/src/components/inputs/radio-buttons/_radio-buttons.scss

same goal as PR #1109, i just forgot one reference

fix radio buitton default palette

---

packages/ng/libraries/establishment/src/lib/select/searcher/establishment-searcher.component.html
packages/ng/libraries/user/src/lib/select/searcher/user-searcher.component.html

fix user/api-select placeholder showing while loading

---

packages/scss/demo/components/timelines.html
packages/scss/demo/includes/demo-main-content.html
packages/scss/demo/includes/demo-menu.html
packages/scss/src/_components.scss
packages/scss/src/components/_timeline.scss

feat(scss) Timelines

---

packages/scss/demo/components/utilities.html
packages/scss/src/_utilities.scss
packages/scss/src/utilities/_flex.scss

- Classes;
- documentation;
- exemple;
- closes #791.

feat(scss) Flex utilities

---

packages/scss/demo/components/collapse.html
packages/scss/src/components/_collapse.scss

- Replace old structure by a details/summary structure for better accessibility ;
- add a fallback for I.E. 11.

feat(scss) Collapse with details/summary

---

packages/ng/libraries/root/src/style/definitions/option/_option-searcher.scss
packages/ng/libraries/user/src/lib/select/searcher/user-searcher.component.html

fix(ng) add style for FormerEmployee checkbox

---

packages/ng/CHANGELOG.md
packages/ng/applications/sandbox/src/app/issues/formly/formly.component.ts
packages/ng/libraries/formly/src/lib/formly.config.ts
packages/ng/libraries/formly/src/lib/formly.module.ts
packages/ng/libraries/formly/src/lib/types/establishment.html
packages/ng/libraries/formly/src/lib/types/establishment.ts
packages/ng/libraries/formly/src/lib/types/index.ts

Added a formly field for establishments

feat(ng-formly) establishment field

---

README.md
packages/scss/demo/components/mixins.html
packages/scss/demo/demo.css
packages/scss/src/mixins/_responsiveness.scss
packages/scss/src/theming/_breakpoints.scss
packages/scss/src/theming/components/_container.theme.scss

- Removing breakpoint at 0;
- new mixins for media_larger_than and media_larger_than with the possibility to pass values directly, with inversion of media queries and with a conversion into em;
- larger max-width for container.

feat(scss) Refactoring responsive utilities

---

packages/scss/demo/components/forms/forms-framed.html
packages/scss/src/components/_form.scss
packages/scss/src/components/_pagination.scss
packages/scss/src/components/_table.scss
packages/scss/src/utilities/_elevation.scss

fix(scss) mod framed standalone

---

packages/ng/libraries/formly/src/lib/types/radios.html
packages/ng/libraries/formly/src/lib/wrappers/radiosfield-layout.html
packages/ng/libraries/formly/src/style/_components.scss

should fix checkboxes and radios in a formly-form in a `.form.mod-framed`

fix(ng-formly) checkboxes and radios in mod-framed

---

packages/scss/src/components/inputs/textfield/_textfield.framed.scss

fix(scss) remove pointer event on label

---

packages/ng/libraries/department/src/lib/select/feeder/department-feeder.component.ts
packages/ng/libraries/option/src/lib/operator/option-operator.model.ts
packages/ng/libraries/option/src/lib/operator/pager/option-pager.component.ts
packages/ng/libraries/option/src/lib/operator/pager/tree-option-pager.component.ts
packages/ng/libraries/option/src/lib/operator/searcher/option-searcher.component.ts
packages/ng/libraries/option/src/lib/operator/searcher/tree-option-searcher.component.ts
packages/ng/libraries/option/src/lib/picker/option-picker.component.ts
packages/ng/libraries/option/src/lib/selector/all/select-all.component.ts
packages/ng/libraries/option/src/lib/selector/all/tree-select-all.component.ts

due to an override of a prop from an abstract class via a setter

fix(ng) ts transpil error with typescript 4

---

packages/scss/src/components/inputs/file/_file.scss

Remove z-index on file-content:before for appear border !
-----

fix(scss) Remove z-index and fix position text

---

packages/ng/libraries/date/src/lib/select/date-select-input.component.ts

complement to PR #1167, same problem, different day.

fix(ng) last ts4 transpil error

---

packages/scss/src/_components.overridable.scss
packages/scss/src/components/_timeline.scss

both componetns werent loaded when importing the overridable version of lf/scss

fix(scss) timeline and pagination imports

---

packages/scss/demo/components/utilities.html
packages/scss/src/_utilities.scss
packages/scss/src/utilities/_position.scss

Added atomic classes for positioning.
Fix #1162

feat(scss) Positions and placements utilities

---

packages/scss/src/_components.overridable.scss
packages/scss/src/components/_layout.scss

fix(scss) add layout to overridable distrib

---

packages/ng/applications/sandbox/src/app/issues/modal-a11y/modal-a11y.component.ts
packages/ng/libraries/modal/src/lib/modal-panel.component.html
packages/ng/libraries/modal/src/lib/modal-panel.component.ts
packages/ng/libraries/modal/src/lib/modal.model.ts
packages/ng/libraries/sidepanel/src/lib/sidepanel-panel.component.html
packages/scss/src/components/_button.scss

closes #1160 
added `submitCounter` to `IModalContent`
fix wrong bg-color for button-counter

feat(ng) modals enhancements

---

packages/scss/src/components/_nav-side.scss

Inversion of the arrows for the unfolded sections of the main navigation.
The icons in the buttons describe a future state.

feat(scss) arrows in nav

---

packages/scss/src/components/_timeline.scss

Sass side calculations and corrected values.

fix(scss) timelines values

---

packages/scss/src/components/_table.scss

Fix for https://github.com/LuccaSA/lucca-front/issues/922

fix(scss) loading actionIcon in table with mod-actions

---

packages/scss/src/components/inputs/checkbox/_checkbox.scss

fix for https://github.com/LuccaSA/lucca-front/issues/1165

fix(scss) checkboxes : palette take precedence over disabled on hover

---

packages/scss/src/components/inputs/radio-buttons/_radio-buttons.scss

Fix for https://github.com/LuccaSA/lucca-front/issues/1171

fix(scss) radioButton : palette color at root level doesn't works

---

packages/icons/src/_classes.scss
packages/icons/src/_font.scss
packages/icons/src/_icons.scss
packages/icons/src/_mixins.scss
packages/icons/src/_partials.scss
packages/icons/src/main.scss
packages/scss/src/_icons.scss
packages/scss/src/components/_callout.scss
packages/scss/src/components/_chips.scss
packages/scss/src/theming/_icons.scss

- Remove duplication of style
- Allow renaming the font
- gives access to classes generation as a mixin

feat(icons) clean up how icons package works

---

packages/ng/libraries/select/src/lib/input/select-input.component.ts
packages/ng/libraries/select/src/lib/input/select-input.model.ts

fix(ng-select) add sub clean up on destroy

---

packages/scss/src/components/_collapse.scss

Remove icon from summary, 
and vertical align the other icon

fix(scss) collapse

---

packages/ng/libraries/establishment/src/lib/select/input/establishment-select-input.component.html
packages/ng/libraries/establishment/src/lib/select/input/establishment-select-input.component.scss
packages/ng/libraries/establishment/src/lib/select/select-all/establishment-select-all.translate.ts
packages/ng/libraries/root/src/style/definitions/option/_option-item.scss
packages/ng/libraries/root/src/style/theme/_options.theme.scss

Style to be closer to this
https://www.figma.com/file/2oSrMzYVl9t1lff2G0XNgb/PROD-Lucca-Etablishment-Picker?node-id=960%3A5845

Establishment Picker Style

---

packages/scss/demo/components/gauge.html
packages/scss/demo/components/timelines.html
packages/scss/demo/includes/demo-main-content.html
packages/scss/demo/includes/demo-menu.html
packages/scss/src/_icons.scss
packages/scss/src/components/_button.scss
packages/scss/src/components/_callout.scss
packages/scss/src/components/_chips.scss
packages/scss/src/components/_gauge.scss
packages/scss/src/components/_nav-side.scss
packages/scss/src/components/_table.scss
packages/scss/src/components/_timeline.scss
packages/scss/src/components/inputs/field/_field.scss
packages/scss/src/theming/components/_gauge.theme.scss

- Gauges managed with borders to be able to play on the type of border.
- Gauges that can pass vertically.
- Timelines that can take a smaller numbering.
- Timelines that can have a last step of addition.
- Timlines that can have a between step of addition.
-----

feat(scss) Timelines with small numbers and add step option

---

packages/scss/demo/components/forms/forms-textfields.html
packages/scss/src/components/inputs/textfield/_textfield.outlined.scss
packages/scss/src/components/inputs/textfield/_textfield.scss
packages/scss/src/theming/components/_textfield.theme.scss

feat(scss) textfield mod-outline

---

packages/scss/demo/components/utilities.html
packages/scss/src/mixins/_utilities.scss
packages/scss/src/utilities/_misc.scss

https://codepen.io/vincent-valentin/pen/KKNXojm

feat(scss) u-listReset for dl

---

packages/ng/libraries/root/src/style/definitions/select/_select-input.scss

Fix https://github.com/LuccaSA/lucca-front/issues/1237
Add ellipsis on chips inside lu-select

fix(scss) add ellipsis on chip in lu-select to prevent multiline

---

packages/scss/src/components/_timeline.scss

Timeline gauge => modification of the left position by adding 'calc()' element.

fix(scss) timeline gauge left position

---

packages/scss/src/_typo.scss

The [addition made to the icon package](https://github.com/LuccaSA/lucca-front/pull/1231) is not enough.

fix(scss) icon rendering

---

packages/scss/demo/components/pagination.html

- `type="button"`;
- “–” instead of “—”;
- `</ul>`;
- icons with classes.

nolog(scss) pagination examples

---

packages/ng/libraries/option/src/lib/operator/for-groups/for-groups.directive.ts

and also fix for-group directive

fix(ng) ets-select loading

---

packages/scss/demo/components/forms/forms-textfields.html
packages/scss/src/components/_button.scss
packages/scss/src/components/_communicationBanner.scss
packages/scss/src/components/_divider.scss
packages/scss/src/components/_toasts.scss
packages/scss/src/components/inputs/textfield/_textfield.scss

Added a button to show/hide the password on dedicated form fields.

feat(scss) password toggle

---

packages/ng/libraries/api/src/lib/select/input/api-select-input.component.html
packages/ng/libraries/api/src/lib/select/input/api-select-input.component.ts
packages/ng/libraries/user/src/lib/select/input/user-select-input.component.html
packages/ng/libraries/user/src/lib/select/input/user-select-input.component.ts

fix(ng-api|user) rem injection of xxxservice in macro component

---

packages/scss/src/components/inputs/textfield/_textfield.scss

Disable native toggle with Edge.

Edge + mod-password

---

packages/ng/libraries/establishment/src/lib/select/input/establishment-select-input.translate.ts
packages/ng/libraries/modal/src/lib/modal.translate.ts
packages/ng/libraries/sidepanel/src/lib/sidepanel.translate.ts
packages/ng/libraries/user/src/lib/select/input/user-select-input.translate.ts
packages/ng/libraries/user/src/lib/select/searcher/user-searcher.translate.ts

Ajout de quelques traductions en espagnol

fix(ng): add es translations

---

packages/scss/src/_utilities.scss
packages/scss/src/utilities/_print.scss
stories/qa/icon/icon.stories.html
stories/scss/button/button-basic.stories.ts
stories/scss/utilities/print.stories.html
stories/scss/utilities/print.stories.ts

closes #1292 
Add some utilities didicated to hide or show content on print media

feat(scss) print utilities

---

packages/scss/src/mixins/_utilities.scss
packages/scss/src/utilities/_misc.scss
stories/scss/utilities/clearfix.stories.html
stories/scss/utilities/clearfix.stories.ts

closes #1287
I apply the clearfix [as defined in this article](http://nicolasgallagher.com/micro-clearfix-hack/) and I take the opportunity to set up a mixin.

feat(scss) Clearfix utils

---

packages/scss/src/components/inputs/field/_field.scss
packages/scss/src/theming/components/_field.theme.scss

Use theme variable for field label color
Fix https://github.com/LuccaSA/lucca-front/issues/1266

feat(scss) use theme variable for field label color

---

Jenkinsfile

drive npm publish process through git tags

tech(all) publish on tag

---

stories/qa/gauge/gauge.stories.html
stories/qa/gauge/gauge.stories.ts

nolog(sb) add qa/gauge stories

---

stories/qa/grid/grid.stories.html
stories/qa/grid/grid.stories.ts

nolog(sb) add qa/grid stories

---

Jenkinsfile
stories/qa/container/container.stories.html
stories/qa/container/container.stories.ts
stories/qa/divider/divider.stories.html
stories/qa/divider/divider.stories.ts
stories/qa/empty-state/empty-state.stories.html
stories/qa/empty-state/empty-state.stories.ts
stories/qa/gauge/gauge.stories.html
stories/qa/gauge/gauge.stories.ts
stories/qa/grid/grid.stories.html
stories/qa/grid/grid.stories.ts
stories/qa/icon/icon.stories.ts
stories/qa/label/label.stories.html
stories/qa/label/label.stories.ts
stories/qa/list/list.stories.html
stories/qa/list/list.stories.ts
stories/qa/table/table.stories.html
stories/qa/table/table.stories.ts

this contains things that do not impact released code but has some interesting things that should be nice on master
- use of volta in CI
- added a lot of stories to storybook

nolog(ci) sync rc-master

---

stories/qa/table-of-content/table-of-content.stories.html
stories/qa/table-of-content/table-of-content.stories.ts

nolog(sb) add qa/table-of-content stories

---

stories/qa/loadings/loadings.stories.html
stories/qa/loadings/loadings.stories.ts

nolog(sb) add qa/loadings stories

---

stories/qa/section/section.stories.html
stories/qa/section/section.stories.ts

nolog(sb) add qa/section stories

---

stories/qa/main/main.stories.html
stories/qa/main/main.stories.ts

nolog(sb) add qa/main stories

---

stories/qa/tags/tags.stories.html
stories/qa/tags/tags.stories.ts

nolog(sb) add qa/tags stories

---

stories/qa/timelines/timelines.stories.html
stories/qa/timelines/timelines.stories.ts

nolog(sb) add qa/timelines stories

---

stories/qa/typography/typography.stories.html
stories/qa/typography/typography.stories.ts

nolog(sb) add qa/typography stories

---

stories/qa/pagination/pagination.stories.html
stories/qa/pagination/pagination.stories.ts

nolog(sb) add qa/pagination stories

---

stories/qa/progress/progress.stories.html
stories/qa/progress/progress.stories.ts

nolog(sb) add qa/progress stories

---

Jenkinsfile

Use Lucca JenkinsSharedLibrary for common calls
Clean some stuff up

ref(ci) Jenkinsfile cleanup

---

packages/scss/src/_typo.scss
packages/scss/src/components/_card.scss
packages/scss/src/components/_title-section.scss
packages/scss/src/utilities/_text.scss

Add missing `!important` on some text utilities

fix(scss) add missing important on text utilities

---

packages/scss/src/components/_table.scss
stories/qa/table/table.stories.html
stories/qa/table/table.stories.ts

feat(scss) table add mod-stickyHeader

---

packages/scss/src/theming/_commons.scss

feat(scss) Change divider color to grey 200

---

packages/scss/src/components/_breadcrumbs.scss

feat(scss) Breadcrumb color

---

packages/ng/material/src/style/components/_tooltip.scss
packages/ng/root/src/style/definitions/tooltip/_tooltip.scss
packages/ng/root/src/style/theme/_tooltip.theme.scss

feat(ng) Tooltip background

---

packages/scss/src/components/_tag.scss
stories/qa/tags/tags.stories.html

feat(scss) tags

---

packages/scss/src/components/_label.scss
stories/qa/label/label.stories.html

feat(scss) Labels

---

stories/scss/callout/callout.stories.html
stories/scss/callout/callout.stories.ts

nolog(sb) add callout in scss

---

stories/scss/tags/tags.stories.html
stories/scss/tags/tags.stories.ts

nolog(sb) add tag on scss

---

stories/scss/progress/progress.stories.html
stories/scss/progress/progress.stories.ts

nolog(sb) add progress in scss

---

stories/scss/chip/chip.stories.html
stories/scss/chip/chip.stories.ts

nolog(sb) add chip on scss

---

stories/qa/menu/menu.stories.html
stories/qa/menu/menu.stories.ts
stories/scss/menu/menu.stories.html
stories/scss/menu/menu.stories.ts
to-migrate/scss/includes/demo-main-content.html
to-migrate/scss/includes/demo-menu.html

nolog(sb) add qa/menu and scss/menu stories

---

stories/scss/box/box-basic.stories.html
stories/scss/box/box-basic.stories.ts

nolog(sb) add scss/box story

---

stories/qa/card/card.stories.html
stories/scss/card/card-basic.stories.html
stories/scss/card/card-basic.stories.ts

nolog(sb) add scss/card story

---

stories/qa/breadcrumb/breadcrumb.stories.html
stories/scss/breadcrumb/breadcrumb-basic.stories.html
stories/scss/breadcrumb/breadcrumb-basic.stories.ts

nolog(sb) add scss/breadcrumbs story

---

packages/scss/src/components/_page-header.scss
stories/qa/page-header/page-header.stories.html
stories/scss/page-header/page-header-basic.stories.html
stories/scss/page-header/page-header-basic.stories.ts

nolog(sb) add scss/pageHeader story

---

packages/scss/src/components/_button.scss

feat(scss) Buttons outlined

---

packages/scss/src/components/_button.scss
stories/qa/button/button.stories.html

feat(scss) buttons

---

packages/scss/src/components/inputs/switch/_switch.scss
packages/scss/src/theming/components/_switch.theme.scss
stories/qa/forms/switches.stories.html

fix #1344 
and on prisme : https://github.com/LuccaSA/ux-prisme/pull/449

feat(scss) switch

---

stories/qa/table/table.stories.html

Rename breakpoint for responsive table layout fixed following https://github.com/LuccaSA/lucca-front/pull/1151

Table.layout fixed.breakpoint.change

---

packages/scss/src/components/_nav-side.scss
stories/scss/navSide/navSide.stories.html
stories/scss/navSide/navSide.stories.ts
stories/scss/navSideLegacy/navSideLegacy.stories.html
stories/scss/navSideLegacy/navSideLegacy.stories.ts

New structure for the menu, more accessible and which corrects some bugs in mobile.
A story shows how the legacy code works with this new CSS code.
-----

Navside v2

---

packages/scss/src/components/_main.scss

FIX issue not spotted in #1481

FIX sass encapsulation

---

packages/scss/src/components/inputs/checkbox/_checkbox.scss
packages/scss/src/components/inputs/radio/_radio.scss

Fix disabled state on checkboxes and radios buttons

---

packages/scss/src/components/inputs/switch/_switch.scss
packages/scss/src/theming/components/_switch.theme.scss
stories/scss/form/switch/switch.stories.html
stories/scss/form/switch/switch.stories.ts

- Uses grey palette for disabled state on both checked and unchecked switch component
- Fixes inconsistencies between different HTML syntaxes (with wrapping `<label>` or `<div>`)
- Adds story for switch components
-----

upd(scss) use grey palette for disabled state on switch component

---

packages/scss/src/components/inputs/textfield/_textfield.outlined.scss
packages/scss/src/components/inputs/textfield/_textfield.scss
packages/scss/src/theming/components/_textfield.theme.scss

[disabled-textfield] 

---

packages/scss/src/components/inputs/radio-buttons/_radio-buttons.scss
stories/scss/form/radio-button/radio-button.stories.html
stories/scss/form/radio-button/radio-button.stories.ts

- uses grey palette for disabled state on radioButtons component
- adds story for radioButtons component
-----

feat(scss) use grey palette for disabled state on radioButtons component

---

packages/scss/src/components/inputs/checkbox/_checkbox.scss
packages/scss/src/components/inputs/radio/_radio.scss
packages/scss/src/mixins/_forms.scss
stories/scss/form/checkbox/checkbox.stories.html
stories/scss/form/checkbox/checkbox.stories.ts
stories/scss/form/framed/framed.stories.ts
stories/scss/form/radio/radio.stories.html
stories/scss/form/radio/radio.stories.ts
stories/scss/form/textfields/textfield.stories.html
stories/scss/form/textfields/textfield.stories.ts

- adds radio story,
- adds textfield story,
- adds controls to checkbox story,
- fixes background color on radio and checkbox faked inputs,
- fixes hover on disabled radio inputs with state,
- fixes checkbox with state in framed form.

feat(scss) disabled states extra fixes

---

packages/scss/src/components/_button.scss
packages/scss/src/components/_form.scss
packages/scss/src/components/inputs/checkbox/_checkbox.scss
packages/scss/src/components/inputs/radio-buttons/_radio-buttons.scss
packages/scss/src/components/inputs/radio/_radio.scss
packages/scss/src/components/inputs/switch/_switch.scss
packages/scss/src/components/inputs/textfield/_textfield.framed.scss
packages/scss/src/components/inputs/textfield/_textfield.outlined.scss
packages/scss/src/components/inputs/textfield/_textfield.scss
packages/scss/src/mixins/_forms.scss
packages/scss/src/theming/_commons.scss
packages/scss/src/theming/components/_radio.theme.scss
packages/scss/src/theming/components/_switch.theme.scss
packages/scss/src/theming/components/_textfield.theme.scss
stories/scss/button/button-basic.stories.html
stories/scss/button/button-basic.stories.ts
stories/scss/form/checkbox/checkbox.stories.html
stories/scss/form/checkbox/checkbox.stories.ts
stories/scss/form/framed/framed.stories.html
stories/scss/form/framed/framed.stories.ts
stories/scss/form/radio-button/radio-button.stories.html
stories/scss/form/radio-button/radio-button.stories.ts
stories/scss/form/radio/radio.stories.html
stories/scss/form/radio/radio.stories.ts
stories/scss/form/switch/switch.stories.html
stories/scss/form/switch/switch.stories.ts
stories/scss/form/textfields/textfield.stories.html
stories/scss/form/textfields/textfield.stories.ts

FIX(scss) disabled states for interactive elements

---

packages/scss/src/utilities/_text.scss

feat(scss) utilities color grey

---

packages/scss/src/utilities/_flex.scss

`.u-gapReset`
`.u-gapSmallest`
`.u-gapSmaller`
`.u-gapSmall`
`.u-gapStandard`
`.u-gapBig`
`.u-gapBigger`
`.u-gapBiggest`
`.u-columnGapReset`
`.u-columnGapSmallest`
`.u-columnGapSmaller`
`.u-columnGapSmall`
`.u-columnGapStandard`
`.u-columnGapBig`
`.u-columnGapBigger`
`.u-columnGapBiggest`
`.u-rowGapReset`
`.u-rowGapSmallest`
`.u-rowGapSmaller`
`.u-rowGapSmall`
`.u-rowGapStandard`
`.u-rowGapBig`
`.u-rowGapBigger`
`.u-rowGapBiggest`

Add utilities for gap

---

packages/ng/api/src/lib/select/input/api-select-input.component.html
packages/ng/api/src/lib/select/input/api-select-input.component.ts
packages/ng/api/src/lib/select/searcher/api-searcher.component.ts
packages/ng/qualification/src/lib/select/input/qualification-select-input.component.html
packages/ng/qualification/src/lib/select/input/qualification-select-input.component.ts
stories/ng/api/select/api-select.stories.html

add api v4 sorting on LuApiPagedSearcher
`<lu-api-select ... standard='v4' [sort]='' ></lu-api-select>`
-----

add api v4 sorting on LuApiPagedSearcher

---

CODEOWNERS

Move some things around
closes #1472

REF Update codeowners

---

packages/ng/input/src/lib/clearer/clearer.component.ts
packages/ng/select/src/lib/input/select-input.model.ts

**BREAKING** emit empty array when clearing multiple select
-----

FIX emit empty array when clearing multiple select

---

packages/scss/src/components/_timeline.scss
stories/qa/timelines/timelines.stories.html
stories/scss/timeline/timeline.stories.html
stories/scss/timeline/timeline.stories.ts

feat(scss) Timeline

---

packages/scss/src/components/_menu.scss
packages/scss/src/components/_page-header.scss
stories/qa/menu/menu.stories.html
stories/qa/page-header/page-header.stories.html
stories/scss/menu/menu.stories.html
stories/scss/menu/menu.stories.ts
stories/scss/page-header/page-header-basic.stories.html

feat(scss&qa) tabs bars

---

packages/ng/style/components/cdk/_global.scss

remove useless selector

---

packages/scss/src/_typo.scss
packages/scss/src/mixins/_typo.scss
packages/scss/src/theming/_sizes.scss
stories/qa/typography/typography.stories.html

Line height for titles

---

packages/ng/style/definitions/select/_select-clearer.scss
packages/ng/style/definitions/select/_select-input.scss
packages/ng/style/theme/_select.theme.scss
stories/ng/date/select/date-select.stories.ts

[Select] Cover palettes on icons / placeholders 

---

packages/scss/src/components/_callout.scss
packages/scss/src/components/_link.scss
stories/qa/links/links.stories.html

Modification du lien, avec la classe .link
fix #1337

feat(scss) Link

---

stories/scss/button/button-basic.stories.ts

Legacy dark background demo

---

packages/ng/modal/src/lib/modal-panel.component.html
packages/ng/modal/src/lib/modal-panel.component.ts
packages/ng/modal/src/lib/modal.module.ts
packages/ng/modal/src/lib/modal.translate.ts
packages/ng/sidepanel/src/lib/sidepanel-panel.component.html
packages/ng/sidepanel/src/lib/sidepanel.module.ts
packages/ng/sidepanel/src/lib/sidepanel.translate.ts
stories/ng/modal/modal.stories.html
stories/ng/modal/modal.stories.ts
stories/ng/sidepanel/sidepanel.stories.html
stories/ng/sidepanel/sidepanel.stories.ts

Small changes on the modal and sidePanel panels : 
+ Fix cross icon accessibility
+ Translated the hidden message corresponding to the close action button
+ Added a tooltip on the close action button

Enh modal panel accessibility

---

packages/scss/src/components/_link.scss
stories/qa/links/links.stories.html

[fix] Links style on button element

---

packages/ng/department/src/lib/select/feeder/department-feeder.component.ts
packages/ng/department/src/lib/select/input/department-select-input.component.html
packages/ng/department/src/lib/select/input/department-select-input.component.ts
packages/ng/department/src/lib/service/department-v3.service.ts
packages/ng/formly/src/lib/types/department.html
stories/documentation/forms/department/department-select.stories.html
stories/documentation/forms/department/department-select.stories.ts

Add filter input to departments picker for the api

Add filter input to departments picker

---

packages/scss/src/_components.scss

We suspect the current import to generate compilation issues.

Scss import

---

packages/scss/src/components/_callout.scss

[1569] Change color of callouts'text

---

packages/scss/src/components/index.scss
packages/scss/src/components/pageHeader/component.scss
packages/scss/src/components/pageHeader/exports.scss
packages/scss/src/components/pageHeader/index.scss
packages/scss/src/components/pageHeader/mods.scss
packages/scss/src/components/pageHeader/vars.scss

Add new pageHeader component on next project

---

.storybook/src/styles.scss
packages/scss/src/components/index.scss
packages/scss/src/components/mainContent/component.scss
packages/scss/src/components/mainContent/exports.scss
packages/scss/src/components/mainContent/index.scss
packages/scss/src/components/mainContent/mods.scss
packages/scss/src/components/mainContent/states.scss
packages/scss/src/components/mainContent/vars.scss

Add main content component

---

packages/scss/src/components/inputs/switch/_switch.scss
packages/scss/src/theming/components/_switch.theme.scss
stories/documentation/forms/switches/switch-basic.stories.ts

https://user-images.githubusercontent.com/25581936/162931894-afb6b8f9-e671-426b-aad8-ec421742dcba.mov

[DS to LF] Switch

---

packages/scss/src/commons/base.scss
packages/scss/src/commons/config.scss
packages/scss/src/components/index.scss
packages/scss/src/components/link/component.scss
packages/scss/src/components/link/exports.scss
packages/scss/src/components/link/index.scss
packages/scss/src/components/link/states.scss
packages/scss/src/components/link/vars.scss

FEAT link component

---

packages/scss/src/components/index.scss
packages/scss/src/components/titleSection/component.scss
packages/scss/src/components/titleSection/exports.scss
packages/scss/src/components/titleSection/index.scss
packages/scss/src/components/titleSection/mods.scss
packages/scss/src/components/titleSection/vars.scss

TitleSection

---

packages/scss/src/components/inputs/radio/_radio.scss
packages/scss/src/theming/components/_radio.theme.scss
stories/documentation/forms/radio/radio-basic.stories.ts

https://user-images.githubusercontent.com/25581936/163393197-0aed69a2-a3ec-4b5f-8448-b4907cb218e6.mov

[DS to LF] Radios

---

packages/scss/src/components/inputs/radio-buttons/_radio-buttons.scss
packages/scss/src/theming/components/_radio-buttons.theme.scss
stories/documentation/forms/radio-button/radio-button-basic.stories.ts

https://user-images.githubusercontent.com/25581936/163423166-3fc29ed5-1bd3-45e7-b64a-40ec149e236e.mov

[DS to LF] Split default & active/focus palette

---

.storybook/preview.js
packages/scss/src/components/_table-of-content.scss
packages/scss/src/theming/components/_table-of-content.theme.scss
stories/documentation/navigation/table-of-content/table-of-content-basic.stories.ts
stories/qa/table-of-content/table-of-content.stories.html

- Apply new UI
- Cover `<button>` element
- Rework theming
https://user-images.githubusercontent.com/25581936/164192113-a9df58c8-c029-4a14-8829-1dae9a853a09.mov

[DS to LF] Table of Content / Anchor

---

packages/scss/src/components/timeline/component.scss
packages/scss/src/components/timeline/index.scss
packages/scss/src/components/timeline/mods.scss
packages/scss/src/components/timeline/structure.scss
packages/scss/src/components/util/index.scss

Add timeline component for LF Next

Next.timeline

---

packages/scss/src/components/_nav-side.scss

https://github.com/LuccaSA/lucca-front/issues/1620

[navside] Fix safari hover issue

---

packages/scss/src/components/_menu.scss

https://github.com/LuccaSA/lucca-front/issues/1619

[menu] Legacy margin

---

packages/scss/src/components/_label.scss
packages/scss/src/components/_menu.scss
stories/documentation/navigation/menu/menu-basic.stories.ts
stories/documentation/navigation/menu/menu-count.stories.ts

- Fix counter color & size
- mod-small documentation
- `<button>` link support
- Fix palette injection 
https://user-images.githubusercontent.com/25581936/163405759-df722603-b191-44a8-9902-317000aab146.mov

counter fix + mod-small doc + button html coverage

---

packages/scss/src/components/inputs/checkbox/_checkbox.scss
packages/scss/src/theming/components/_checkbox.theme.scss
stories/documentation/forms/checkbox/checkbox-basic.stories.ts

https://user-images.githubusercontent.com/25581936/164031168-786d00f4-b704-4647-875f-91e106572c01.mov
- Remove global palette
- Set grey as a mod (might be deleted later as it's not covered by design guidelines but used in a few contexts.)
- Fix icon size

[DS to LF] Checkbox

---

packages/scss/src/theming/components/_button.theme.scss

[Button] Size small height

---

packages/scss/src/components/_timeline.scss

Fix specific content cases like using cards in vertical timeline.

[Timeline] Vertical step 100%

---

stories/documentation/overlays/popover/popover.stories.ts

Popover story get erased by 8.2. 
This is a rollback PR for this specific story.

[Storybook] Fix popover story 

---

packages/scss/src/commons/base.scss

Example for override after:
```
html {
--palettes-primary-text: #ffffff;
--palettes-primary-50: #f0fff2;
--palettes-primary-100: #e3fde7;
--palettes-primary-200: #d5fbdb;
--palettes-primary-300: #c3f9cc;
--palettes-primary-400: #abf2b7;
--palettes-primary-500: #90ea9f;
--palettes-primary-600: #74d884;
--palettes-primary-700: #5fc871;
--palettes-primary-800: #4baf5c;
--palettes-primary-900: #2e7a3b;
}
```

Better palettes

---

.browserslistrc
tsconfig.json

- Update browserlist to latest version supported by Angular (see https://angular.io/guide/browser-support)
- Update tsconfig to most recent values
-----
Made by The Guilde Front™

UPD tsconfig + browsersList

---

packages/scss/src/components/label/component.scss
packages/scss/src/components/label/vars.scss
packages/scss/src/components/tag/component.scss
packages/scss/src/components/tag/mods.scss
packages/scss/src/components/tag/vars.scss

Next labels & tags

---

packages/ng/establishment/src/lib/select/select-all/establishment-select-all.component.html
packages/ng/option/src/lib/item/option-item.component.html
packages/ng/option/src/lib/item/option-item.component.scss
packages/ng/option/src/lib/item/option-item.component.ts
packages/ng/option/src/lib/item/option-item.model.ts
packages/ng/option/src/lib/item/tree-option-item.component.ts
packages/ng/option/src/lib/picker/option-picker.component.ts
packages/ng/popover/src/lib/trigger/popover-trigger.model.ts
packages/ng/select/src/lib/input/select-input.component.ts

Adds https://github.com/LuccaSA/lucca-front/pull/1636 to the next branch

Disabled select & lu-options (#1636)

---

packages/scss/src/components/navside/vars.scss
packages/scss/src/components/pagination/index.scss
packages/scss/src/components/table/mods.scss
stories/documentation/loaders/loadings/loadings-basic.stories.ts

Fix some components

---

packages/scss/src/components/timeline/index.scss
packages/scss/src/components/timeline/mods.scss
stories/documentation/listings/timelines/timelines-progress.stories.ts
stories/documentation/loaders/progression/progression-basic.stories.ts

Timelines : fix color + add story control

---

.storybook/src/styles.scss
packages/scss/src/commons/core.scss
packages/scss/src/components/callout/vars.scss
packages/scss/src/components/field/component.scss
packages/scss/src/components/textfield/component.scss
packages/scss/src/components/textfield/states.scss
packages/scss/src/components/textfield/vars.scss
packages/scss/src/main.dist.scss

-  NG style declaration
- u-textLight / Placeholder
- Callout default background
- Calendar / Textfield issues

Next — Fixes

---

packages/scss/src/commons/utils/index.scss

Fix forward

---

packages/ng/title/src/lib/title.service.spec.ts
packages/ng/title/src/lib/title.service.ts

prependTitle can now add an additional prefix or replace the first one

feat(ng) Allow Title service to replace first prefix

---

packages/ng/input/src/lib/clearer/clearer.component.ts
packages/scss/src/components/button/mods.scss

Fix button and clearer

---

packages/ng/style/components/cdk/_overlay.scss
packages/ng/style/definitions/select/_select-clearer.scss
packages/scss/src/commons/config.scss
packages/scss/src/commons/utils/loading.scss
packages/scss/src/components/button/mods.scss
packages/scss/src/components/chip/component.scss
packages/scss/src/components/file/component.scss
packages/scss/src/components/gauge/component.scss
packages/scss/src/components/navside/component.scss

Seen with Clément, we replace all black occurrences by G900.

Black to G900

---

packages/scss/src/components/timeline/component.scss

Fix timeline title

---

packages/scss/src/components/timeline/component.scss

This reverts commit 2dab91c3c7fa3b562e9197d20e8d1e7c22912e1d.

Revert "Fix timeline title (#1734)"

---

packages/icons/src/icon/component.scss
packages/scss/src/commons/config.scss
packages/scss/src/commons/core.scss
packages/scss/src/components/card/states.scss
packages/scss/src/components/grid/index.scss
packages/scss/src/components/titleSection/component.scss
packages/scss/src/components/titleSection/index.scss
packages/scss/src/components/toast/component.scss
packages/scss/src/components/util/index.scss

Remove prefix

---

.storybook/src/styles.scss
README.md
angular.json
gulpfile.js
packages/ng/style/components/_input.scss
packages/ng/style/definitions/select/_select-input.scss
packages/scss/src/_icons.scss
to-migrate/scss/components/mixins.html

I'm trying to solve this: https://bundlephobia.com/package/@lucca-front/scss@9.0.1

Fix imports

---

packages/scss/src/components/index.scss
packages/scss/src/components/skipLinks/component.scss
packages/scss/src/components/skipLinks/exports.scss
packages/scss/src/components/skipLinks/index.scss
packages/scss/src/components/skipLinks/vars.scss
stories/documentation/navigation/skipLinks/skipLinks-basic.stories.ts

Skip links component

---

packages/scss/src/components/util/index.scss

The order of the utilities is important.
Here I quickly try to reverse them, but perhaps it will be necessary to copy the order of LF 9 precisely.

Fix order declaration

---

packages/scss/src/commons/core.scss
packages/scss/src/components/util/index.scss

Add removed utilities: 
- `.u-textDefault` ;
- `.u-textDecorationUnderline` ;
- `.u-textDecorationNone` ;

Add removed utilities

---

packages/ng/styles/definitions/option/_option-item.scss

[Options multiple] Fix checkbox cliping + icon size harmonization

---

packages/scss/src/components/radioButtons/component.scss
packages/scss/src/components/radioButtons/vars.scss

- Fix default color
- Remove unused variables

[Radio buttons] States colors

---

stories/documentation/navigation/pagination/pagination-basic.stories.ts
stories/documentation/navigation/pagination/pagination-pages.stories.ts
stories/qa/pagination/pagination.stories.html

Actions icons should have a .mod-small (32x32px)

Pagination - actionIcon with mod-small

---

packages/ng/styles/definitions/select/_select-input.scss
packages/scss/src/components/field/component.scss
packages/scss/src/components/field/mods.scss
packages/scss/src/components/field/states.scss
packages/scss/src/components/textfield/mods.scss

[Textfield] Framed placeholder color

---

packages/scss/src/components/navside/component.scss

[Navside] Arrows size

---

packages/ng/schematics/lib/scss-ast.ts
packages/ng/schematics/migrations/css-vars/migration.ts
packages/ng/schematics/migrations/css-vars/tests/colors-white.input.scss
packages/ng/schematics/migrations/css-vars/tests/colors-white.output.scss
packages/ng/schematics/migrations/css-vars/tests/get-set.input.scss
packages/ng/schematics/migrations/css-vars/tests/get-set.output.scss
packages/ng/schematics/migrations/css-vars/updaters/color.ts
packages/ng/schematics/migrations/css-vars/updaters/theme.ts
packages/ng/schematics/migrations/css-vars/updaters/warning.ts

fix(schematics): more schematics fixes

---

packages/ng/material/style/components/_datepicker.scss
packages/ng/ng-package.json

FIX ng styles export (wrong paths)
FIX some weird stuff in scss files

FIX material / formly scss export

---

stories/documentation/forms/select/select-advanced.stories.ts

Ajout d'un story pour montrer un exemple de select advanced

[ADD] Select advanced stories

---

packages/scss/src/components/file/component.scss
packages/scss/src/components/file/mods.scss
packages/scss/src/components/file/states.scss
stories/qa/forms/files.stories.html

[DS to LF] Form File

---

packages/ng/option/src/lib/item/tree-option-item.component.ts

FIX #1829 
J'ai remis la notation deprecated mais avec des eslint disable

fix(department select): issue with angular 12

---

packages/scss/src/components/util/index.scss

Animations : fix css vars

---

packages/ng/department/src/lib/department-select.spec.ts
packages/ng/establishment/src/lib/establishment-select.spec.ts
packages/ng/establishment/src/lib/select/searcher/establishment-searcher.component.html
packages/ng/establishment/src/lib/select/searcher/establishment-searcher.component.ts
stories/documentation/actions/action-icon/action-icon-basic.stories.ts
stories/documentation/actions/action-icon/action-icon.spec.ts
stories/documentation/actions/button/button-basic.stories.ts
stories/documentation/actions/button/button-counter.stories.ts
stories/documentation/actions/button/button-group.stories.ts
stories/documentation/actions/button/button-icon.stories.ts
stories/documentation/actions/button/button.spec.ts
stories/documentation/actions/links/link-basic.stories.ts
stories/documentation/actions/links/links.spec.ts
stories/documentation/forms/department/department-select.stories.html
stories/documentation/forms/establishment-select/establishment-select.stories.ts

Plus de spec
un peu de refacto avec @shajz

[Tech] Toujours plus de spec

---

stories/documentation/feedback/box/box-toggle.stories.ts

[Box] Toggle story

---

packages/scss/src/components/table/component.scss
packages/scss/src/components/table/index.scss
packages/scss/src/components/table/mods.scss
packages/scss/src/components/tableFixed/index.scss
packages/scss/src/components/tableSticked/index.scss
packages/scss/src/components/tableSticked/mods.scss

Fix #1843 
Add table foot classes.

Table foot

---

packages/scss/src/components/tag/mods.scss

[Tag] Allow outlined + palette

---

stories/documentation/texts/labels/label-icon.stories.ts

[Label] Documentation for mod-icon

---

packages/ng/modal/src/lib/modal-panel.component.ts

Ajouts d'un comportement lorsque l'observable d'une submitAction d'une modal est "completed"

Ajouts d'un comportement lorsque l'observable d'une submitAction d'une modal est "completed"

---

packages/ng/title/src/lib/index.ts
packages/ng/title/src/lib/title.model.ts
packages/ng/title/src/lib/title.module.ts
packages/ng/title/src/lib/title.service.ts
packages/ng/title/src/lib/title.strategy.spec.ts
packages/ng/title/src/lib/title.strategy.ts

Replace custom system by the new Angular page title strategy
-----

[Title] Use page title strategy from Angular

---

packages/scss/src/components/textfield/component.scss
packages/scss/src/components/textfield/index.scss
packages/scss/src/components/textfield/mods.scss
packages/scss/src/components/textfield/vars.scss
stories/documentation/forms/textfields/textfield-basic.stories.ts
stories/qa/forms/textfields.stories.html

[Textfield] add mod-small

---

packages/scss/src/components/textfield/mods.scss
stories/qa/forms/textfields.stories.html

delete cross on type search hover and focus

---

packages/scss/src/components/util/index.scss

Fix #1813 
Add selectors font font weights.
(And remove duplicate seletor.)

fontWeight

---

packages/scss/src/components/textfield/component.scss

Fix #1848
Remove clear action and search decoration.

Fix type search

---

packages/scss/src/commons/base.scss
packages/scss/src/commons/exports.scss
packages/scss/src/commons/index.scss
packages/scss/src/commons/vars.scss
packages/scss/src/main-all.scss
packages/scss/src/main.scss

Normal use in styles.scss:
```
@forward '@lucca-front/icons/src/main';
@forward '@lucca-front/ng/src/main';
@forward '@lucca-front/scss/src/main';
```
Custom use in styles.scss:
```
@forward '@lucca-front/ng/src/main';
@forward '@lucca-front/icons/src/main';
@use '@lucca-front/scss/src/commons/exports' as commons;
:root {
@include commons.base;
}
:root,
.customCommons {
@include commons.vars;
}
.customCommons {
--commons-border-radius: 8px;
}
```

custom commons

---

packages/ng/styles/definitions/user/user-picture.scss
stories/documentation/users/picture/picture.stories.ts

https://github.com/LuccaSA/lucca-front/issues/1351

LF-1351 UPD lu-user-picture

---

packages/scss/src/components/index.scss
packages/scss/src/components/status/component.scss
packages/scss/src/components/status/exports.scss
packages/scss/src/components/status/index.scss
packages/scss/src/components/status/states.scss
packages/scss/src/components/status/vars.scss
stories/documentation/texts/status/status-basic.stories.ts

Status component

---

packages/ng/modal/src/lib/modal-panel.component.html
packages/ng/modal/src/lib/modal-panel.component.ts
packages/ng/modal/src/lib/modal.model.ts
packages/ng/sidepanel/src/lib/sidepanel-panel.component.html
stories/documentation/overlays/modal/modal.stories.ts
stories/documentation/overlays/sidepanel/sidepanel.stories.ts

Following `title`, `submitLabel` and `cancelLabel`, properties `submitDisabled` and `submitCounter` now supports Observable values.
-----

[Sidepanel/Modal] More observable properties

---

packages/scss/src/components/menu/component.scss

Fix vertical gap when collapsing
-----
-----

[Tabbar] Fix vertical gap when collapsing

---

packages/ng/styles/definitions/select/_select-input.scss
packages/scss/src/components/field/vars.scss
packages/scss/src/components/textfield/index.scss
packages/scss/src/components/textfield/mods.scss
packages/scss/src/components/textfield/states.scss
packages/scss/src/components/textfield/vars.scss
stories/qa/forms/textfields.stories.html

Fix outlined textfield/select UI
-----
-----

[DS to LF] Forms : outlined

---

packages/scss/src/components/pageHeader/index.scss
packages/scss/src/components/pageHeader/mods.scss
stories/documentation/structure/headers/headers-basic.stories.ts
stories/documentation/structure/page-header/page-header-basic.stories.html
stories/documentation/structure/page-header/page-header-basic.stories.ts

Add a _mod-sticky_ option to page header
-----

[Page header] Sticky

---

packages/scss/src/components/status/component.scss

**BEFORE** : 
https://user-images.githubusercontent.com/77682210/199503164-4188dc48-31c7-4c1f-bcb3-096f2fbcc7a4.mov
**AFTER** : 
https://user-images.githubusercontent.com/77682210/199503023-e2cf66a2-f998-46a2-94f4-8163ee578bc3.mov
-----
-----

Review status animation on dot important

---

Jenkinsfile

Deploy servers have changed
-----

[TECH] Change deploy servers

---

packages/ng/styles/components/_dropdown.scss

Handle a responsive width (from 10 to 30rem, width a max width of 90vh on container) instead of a 14rem fix width.
-----
https://user-images.githubusercontent.com/25581936/201149930-ed02600a-1f0b-4949-821d-fdeb6a0f77cd.mov
-----

[Dropdown] Improve component width 

---

packages/ng/styles/definitions/user/user-picture.scss
packages/ng/styles/definitions/user/user-tile.scss
packages/ng/user/src/lib/picture/user-picture.component.scss
packages/ng/user/src/lib/tile/user-tile.component.html
packages/ng/user/src/lib/tile/user-tile.component.scss
stories/documentation/users/tile/user-tile.stories.html
stories/documentation/users/user.mocks.ts

- Fix user tiles mods
- Apply LF10 vars logic
-----
https://github.com/LuccaSA/lucca-front/issues/1919
-----

[User tiles] Fix mods

---

packages/scss/src/components/index.scss
packages/scss/src/components/timepicker/component.scss
packages/scss/src/components/timepicker/exports.scss
packages/scss/src/components/timepicker/index.scss
packages/scss/src/components/timepicker/mods.scss
packages/scss/src/components/timepicker/states.scss
packages/scss/src/components/timepicker/vars.scss
stories/documentation/forms/timepicker/timepicker-basic.stories.ts

Add desktop component covering default and outlined style and disabled state.
Incrementing buttons still need to be plugged by apps while the Angular component is still in development.
-----
https://user-images.githubusercontent.com/25581936/203570993-5e9bc8e8-51f1-4312-a085-a1da1de80e25.mov
-----

[timepicker] CSS component

---

packages/scss/src/components/textfield/mods.scss
packages/scss/src/components/textfield/states.scss

Makes white mod compatible with palettes
-----
-----

[Textfield] Makes white mod compatible with palettes

---

stories/documentation/navigation/pagination/pagination-compact.stories.ts

[Pagination] Add compact story

---

packages/scss/src/components/radioButtons/component.scss
packages/scss/src/components/radioButtons/mods.scss
packages/scss/src/components/radioButtons/vars.scss

- Fix mod-small size
- Improve css vars coverage
-----
-----

[Radio button] Fix mod small size

---

packages/ng/modal/src/lib/modal-panel.component.html
packages/ng/sidepanel/src/lib/sidepanel-panel.component.html
packages/ng/styles/components/_popup.scss

**BEFORE** :
**AFTER** : 
-----
-----

Fix height of div role doc on sidepanel

---

packages/ng/user/src/lib/display/user-display.pipe.ts

Allow user rendering without having to provide a pipe
-----
-----

Enh - expose function luUserDisplay

---

packages/ng/popover/src/lib/trigger/popover-trigger.module.ts
packages/ng/tooltip/src/lib/trigger/tooltip-trigger.module.ts

Fix missing import of overlaymodule in [directive]Module
-----

Fix missing overlaymodule

---

packages/ng/sidepanel/src/lib/sidepanel-panel.component.html
packages/ng/styles/components/_sidepanel.scss

Fix sidepanel overflow
-----
-----

fix sidepanel overflow

---

packages/ng/core/src/lib/date/native/native-date.adapter.ts
packages/ng/core/src/lib/date/string/string-date.adapter.spec.ts
packages/ng/core/src/lib/date/string/string-date.adapter.ts

Fix date selection
-----
-----

Fix date select

---

packages/ng/establishment/src/lib/select/searcher/establishment-searcher.component.html
packages/ng/establishment/src/lib/select/searcher/establishment-searcher.component.ts

- wrong page when searching something
- does not stop on the last page
-----

fix(establishment): pagination issues

---

packages/ng/simple-select/src/lib/input/select-input.component.ts
packages/ng/simple-select/src/lib/panel/panel.component.ts

Fix rxjs imports to support 6.x.x version in the simple select component
-----

Fix rxjs imports to support 6.x.x version in simple-select

---

packages/ng/simple-select/src/lib/input/select-input.component.ts
packages/ng/simple-select/src/lib/panel/panel.component.ts

Fix rxjs import to support 6.x.x version in the simple select component
-----

[v10.4.0] Fix rxjs imports to support 6.x.x version in simple-select

---

.storybook/preview-head.html

Minor css fixes for sb7 update
-----

fix doc table margin

---

.storybook/preview-head.html
stories/documentation/toolbox/animations/fade-animations.stories.ts
stories/documentation/toolbox/animations/scale-animations.stories.ts
stories/documentation/toolbox/animations/slide-animations.stories.ts
stories/documentation/users/select/user-homonyms.stories.ts
stories/documentation/users/select/user-select.stories.ts

- Fix stories css
- split stories
-----

[SB7] Fix css + split stories

---

stories/documentation/integration/utilities/shadows.stories.ts

Fix shadows story

---

.storybook/preview-head.html

[Storybook] Update fixes

---

packages/scss/src/commons/base.scss

Source sans pro is now hosted locally to meet RGPD expectations.
-----
-----

Source sans local

---

packages/scss/src/components/label/component.scss
packages/scss/src/components/label/index.scss
packages/scss/src/components/label/mods.scss
stories/documentation/texts/labels/label-icon.stories.ts
stories/qa/label/label.stories.html

label.mod-icon changes position when you alternate the position of the icon
-----
Before
After
-----

[fix] [label] .mod-icon position

---

packages/scss/src/commons/core.scss

add line-trough class

---

packages/ng/toast/src/toasts.component.html
packages/ng/toast/src/toasts.model.ts
packages/ng/toast/src/toasts.service.ts
packages/scss/src/components/toast/component.scss
packages/scss/src/components/toast/index.scss
packages/scss/src/components/toast/mods.scss
packages/scss/src/components/toast/vars.scss
stories/documentation/overlays/toasts/toasts.stories.ts

- Add optional title on toast
- Improve toast display
-----
- Add optional parameter `title` on `LuToasInput`
- Changed toast graphics rendering to best match Figma components
-----

1962 toasts add title option

---

package-lock.json
packages/ng/modal/src/lib/modal-panel.component.html
packages/ng/sidepanel/src/lib/sidepanel-panel.component.html
packages/ng/styles/components/_popup.scss
stories/documentation/overlays/modal/modal.stories.ts

Refactoring UI Modal
-----
-----

[DS to LF] Modal

---

packages/ng/a11y/src/lib/skip-links/skip-links.component.html
packages/scss/src/components/toast/vars.scss

Background as a variable
-----

[Toast] Background as a variable

---

.storybook/tsconfig.json
build.js
package-lock.json
package.json
packages/ng/schematics/lib/local-deps/postcss-selector-parser.ts
packages/ng/schematics/lib/local-deps/postcss-value-parser.ts
packages/ng/schematics/tsconfig.json

fix: tshirt migration import issues

---

packages/ng/styles/components/_popup.scss

Harmonize popup / modal / sidepanel with Figma
-----

[popup] Fix spacings

---

packages/ng/styles/components/_popup.scss
packages/ng/styles/components/_sidepanel.scss
packages/scss/src/components/label/component.scss
stories/documentation/texts/labels/label-basic.stories.ts

- Remove label margin
- Improve popup / side panel animations
-----

[15.1] Minor UI improvements

---

packages/ng/schematics/lib/html-ast.ts
packages/ng/schematics/migrations/tshirt-size/migration.ts
packages/ng/schematics/migrations/tshirt-size/tests/styles.input.scss
packages/ng/schematics/migrations/tshirt-size/tests/template.input.html
packages/ng/schematics/migrations/tshirt-size/tests/template.output.html

* fix: do not use replace for class replacement
* feat: remove @lucca-front/scss/src/components/skipLinks
-----

Fix.schematics

---

packages/ng/schematics/lib/angular-template.ts
packages/ng/schematics/lib/file-update.ts
packages/ng/schematics/lib/html-ast.ts
packages/ng/schematics/lib/scss-ast.ts
packages/ng/schematics/migrations/tshirt-size/index.ts
packages/ng/schematics/migrations/tshirt-size/mapping.ts
packages/ng/schematics/migrations/tshirt-size/migration.spec.ts
packages/ng/schematics/migrations/tshirt-size/migration.ts
packages/ng/schematics/migrations/tshirt-size/tests/component.input.ts
packages/ng/schematics/migrations/tshirt-size/tests/component.output.ts
packages/ng/schematics/migrations/tshirt-size/tests/styles.input.scss
packages/ng/schematics/migrations/tshirt-size/tests/styles.output.scss
packages/ng/schematics/migrations/tshirt-size/tests/template.input.html
packages/ng/schematics/migrations/tshirt-size/tests/template.output.html

* fix(schematics): ngClass migration was not keeping classes not in migration
* feat: handle rules in declaration in schematics
* feat: migrate string literals too
-----

Fix.tshirt.migration again

---

packages/ng/schematics/migrations/tshirt-size/mapping.ts
packages/ng/schematics/migrations/tshirt-size/tests/template.input.html
packages/ng/schematics/migrations/tshirt-size/tests/template.output.html

fix(schematics): some errors on grid classes
-----

fix(schematics): some errors on grid classes

---

stories/documentation/actions/action-icon/action-icon-basic.stories.ts
stories/documentation/feedback/callout/callout-basic.stories.ts
stories/documentation/feedback/callout/callout-icons.stories.ts
stories/documentation/forms/files/files-basic.stories.ts
stories/documentation/forms/files/files-droppable.stories.ts
stories/documentation/forms/files/files-error.stories.ts
stories/documentation/forms/files/files-success.stories.ts
stories/documentation/forms/files/files-uploading.stories.ts
stories/documentation/forms/framed/framed-basic.stories.ts
stories/documentation/forms/radio-button/radio-button-basic.stories.ts
stories/documentation/forms/radio/radio-basic.stories.ts
stories/documentation/forms/switches/switch-basic.stories.ts
stories/documentation/integration/utilities/borders-radius.stories.ts
stories/documentation/listings/table/table-basic.stories.ts
stories/documentation/loaders/loadings/loadings-basic.stories.ts
stories/documentation/navigation/menu/menu-count.stories.ts
stories/documentation/toolbox/animations/fade-animations.stories.ts
stories/documentation/toolbox/animations/scale-animations.stories.ts
stories/documentation/toolbox/animations/slide-animations.stories.ts

Fix documentation issues for 15.1
-----

15.1 fix documentation

---

packages/scss/src/components/util/index.scss

Fix utility `.u-noSpinButtons`
-----

[Utilities] Fix u-noSpinButtons

---

packages/ng/styles/components/_dropdown.scss

Icons margin as gap
-----
-----

[Dropdown] Icons margin as gap

---

packages/scss/src/components/card/component.scss
packages/scss/src/components/card/mods.scss
packages/scss/src/components/card/vars.scss

[Card] Fix vars for grey mod

---

.storybook/main.mjs

Generate stories.json for new zeroheight x storybook integration.
-----

generate stories.json

---

packages/scss/src/components/callout/component.scss
packages/scss/src/components/callout/index.scss
packages/scss/src/components/callout/mods.scss
packages/scss/src/components/callout/vars.scss
stories/documentation/feedback/callout/callout-basic.stories.ts
stories/documentation/feedback/callout/callout-icons.stories.ts
stories/documentation/feedback/callout/callout-killable.stories.ts
stories/qa/callout/callout.stories.html

Callout as flex element to prevent content overlapping icons
-----
-----

[Callout] As flex element

---

packages/ng/option/src/lib/item/tree-option-item.component.scss
stories/documentation/forms/department/department-select.stories.html

Fix padding for overrided spacings
-----
Notes: 
- Few spacings variables are replaced by raw values as they were not used as spacings.
- Checkbox for options would need a refactor but Front teams are currently working on a new multiple select.
-----

[Tree] Fix padding for overrided spacings

---

packages/ng/schematics/migrations/tshirt-size/mapping.ts
packages/ng/schematics/migrations/tshirt-size/tests/template.input.html
packages/ng/schematics/migrations/tshirt-size/tests/template.output.html

migrate lu-modal-header-close
-----

feat(schematics): migrate lu-modal-header-close

---

.storybook/main.mjs
stories/documentation/actions/button/button.mdx

[POC] docs(button): add dedicated mdx file

---

packages/ng/api/src/lib/select/input/api-select-input.component.scss
packages/ng/department/src/lib/select/input/department-select-input.component.scss
packages/ng/establishment/src/lib/select/input/establishment-select-input.component.scss
packages/ng/styles/definitions/select/_select-clearer.scss
packages/ng/styles/definitions/select/_select-input.scss
packages/ng/user/src/lib/select/input/user-select-input.component.scss
packages/scss/src/components/actionIcon/component.scss
packages/scss/src/components/textfield/index.scss
packages/scss/src/components/textfield/mods.scss
packages/scss/src/components/textfield/states.scss

Increase cross size + fix colors cross color
-----
-----

[textfield/select] Increase cross size & fix colors

---

packages/scss/src/components/checkbox/component.scss
packages/scss/src/components/checkbox/mods.scss

Fix vertical alignment + Small tick
-----
-----

[Checkbox] Fix vertical alignment

---

packages/scss/src/components/button/component.scss

Fix vertical alignement 
-----

[Button] Fix vertical alignement if button have icon

---

packages/ng/modal/src/lib/modal-panel.component.ts
packages/ng/popup/src/lib/popup-ref.model.ts
stories/documentation/overlays/modal/modal.stories.ts
stories/documentation/overlays/sidepanel/sidepanel.stories.ts

Add an event when there is a click on the modal backdrop.
-----

ref(modal): add backdropclick to modal

---

stories/documentation/overlays/sidepanel/sidepanel.stories.ts

Story Sidepanel

---

packages/scss/src/components/button/index.scss
packages/scss/src/components/button/mods.scss

Allow combination of `.mod-text` & `.mod-XS`
-----

[Button] Text & XS

---

packages/ng/styles/definitions/select/_select-input.scss

Fix clearer position for mod-S
-----
-----

[Select] mod-S clearer position

---

packages/ng/core/src/lib/tree/tree.model.ts
packages/ng/option/src/lib/item/tree-option-item.component.html
packages/ng/option/src/lib/item/tree-option-item.component.scss
packages/ng/option/src/lib/item/tree-option-item.component.ts

Ajouts d'une option `disabled` dans `ILuTree` pour désactiver des éléments d'un lu-tree-select
-----
-----

Ajouts d'une option pour désactiver des champs de lu-tree-select

---

packages/scss/src/components/StatusBadge/component.scss
packages/scss/src/components/StatusBadge/exports.scss
packages/scss/src/components/StatusBadge/index.scss
packages/scss/src/components/StatusBadge/vars.scss
packages/scss/src/components/index.scss
stories/documentation/texts/status-badge/status-badge-basic.stories.ts
stories/qa/status-badge/status-badge.stories.html
stories/qa/status-badge/status-badge.stories.ts

New component : Status badge
-----
-----

Status Badge

---

packages/scss/src/components/actionIcon/component.scss
packages/scss/src/components/actionIcon/mods.scss
packages/scss/src/components/actionIcon/vars.scss

Remove useless theming options (default palette, color, states...) 
-----
Don't pay attention to branch name 🤦 
-----

[Action Icon] Remove useless vars 

---

packages/scss/src/commons/base.scss
packages/scss/src/commons/core.scss
packages/scss/src/components/title/component.scss
packages/scss/src/components/title/mods.scss
stories/qa/typography/typography.stories.html

Add black and bold weights for titles.
-----
-----

Change font weight for titles

---

.storybook/preview.mjs
.storybook/wrapper.component.ts

Fix default code opening state.
-----

fix(docs): no more hacky way of opening code blocks

---

stories/documentation/forms/date/select/date-select.stories.ts
stories/documentation/forms/select/simple-select.stories.ts
stories/helpers/stories.ts

- docs: Rework date select documentation
-----
[Apercu](http://lucca-front.lucca.local/PR-2081/storybook/?path=/docs/documentation-forms-date-select--docs#selectmonthwithdisplayer)
-----

Date select story

---

.storybook/preview-head.html

Add margin between main SB sections for ZH documentation
-----

SB Sections margin

---

.storybook/preview-head.html

Improve margin between sections
-----

improve margins SB

---

.storybook/preview-head.html

sections margin 🙈

---

packages/scss/src/commons/utils/a11y.scss
packages/scss/src/components/button/component.scss
packages/scss/src/components/button/mods.scss
packages/scss/src/components/button/states.scss
packages/scss/src/components/button/vars.scss
packages/scss/src/components/buttonGroup/component.scss
packages/scss/src/components/buttonGroup/mods.scss
stories/qa/button/button.stories.html

Update button UI
-----
https://user-images.githubusercontent.com/25581936/233431080-8ebbceeb-9622-41ff-bcca-9f3c73579584.mov
-----

[Components V3] Button

---

packages/scss/src/commons/utils/a11y.scss
packages/scss/src/components/actionIcon/component.scss
packages/scss/src/components/actionIcon/index.scss
packages/scss/src/components/actionIcon/mods.scss
packages/scss/src/components/actionIcon/states.scss
stories/documentation/actions/action-icon/action-icon-basic.stories.ts

Action icon UI update
-----
We will probably update button component in the future to cover icons without text, which will make Action Icons deprecated. For now, we can allow to have Ghost mode (Text) by default and Outlined as option to avoid breakings.
-----

[Components V3] Action icons

---

packages/scss/src/components/radioButtons/component.scss
packages/scss/src/components/radioButtons/index.scss
packages/scss/src/components/radioButtons/mods.scss
packages/scss/src/components/radioButtons/vars.scss
stories/qa/forms/radio-buttons.stories.html

Update Radio Buttons UI
-----
https://user-images.githubusercontent.com/25581936/234002336-c6ce0451-b5e5-4478-8caf-63e0716170c2.mov
-----

[Components v3] Radio buttons

---

packages/scss/src/commons/base.scss
packages/scss/src/commons/utils/a11y.scss
packages/scss/src/components/actionIcon/mods.scss
packages/scss/src/components/link/component.scss
packages/scss/src/components/link/index.scss
packages/scss/src/components/link/mods.scss
stories/documentation/actions/links/link-basic.stories.ts
stories/qa/links/links.stories.html

- Update links UI
- Add border radius option to focus mixin
-----
-----

[Components v3] Links

---

packages/ng/date/src/lib/calendar/calendar-input.component.html
packages/ng/date/src/lib/select/date-select-input.component.html
packages/ng/input/src/lib/clearer/clearer.component.html
stories/documentation/feedback/box/box-killable.stories.ts
stories/qa/box/box.stories.html
stories/qa/callout/callout.stories.html
stories/qa/forms/files.stories.html
stories/qa/forms/textfields.stories.html
stories/qa/icon/icon.stories.html
stories/qa/table/table.stories.html

- Remove legacy icon usages to avoid auto-translation on them.
- Disable auto-translate on date-select displayer
-----
Fix #2082 
-----

Fix auto-translate

---

packages/scss/src/components/breadcrumbs/component.scss
stories/documentation/navigation/breadcrumbs/breadcrumbs-basic.stories.ts
stories/documentation/navigation/breadcrumbs/breadcrumbs-compact.stories.ts
stories/qa/breadcrumb/breadcrumb.stories.html

Update breadcrumb UI
-----
https://user-images.githubusercontent.com/25581936/234879154-cc91ceb6-d274-4894-9c39-03fe6f1ad29f.mov
-----

[Components v3] Breadcrumbs

---

packages/ng/modal/src/lib/modal-panel.component.html
packages/ng/styles/components/_popup.scss
packages/scss/src/commons/config.scss
packages/scss/src/commons/vars.scss

- Update modal UI
- Add common values for borders
- Update box shadow common variables 
-----
-----

[Components v3] Modal

---

packages/scss/src/components/radio/component.scss
packages/scss/src/components/radio/mods.scss
packages/scss/src/components/radio/states.scss
packages/scss/src/components/radio/vars.scss
stories/documentation/forms/radio/radio-helper.stories.ts
stories/qa/forms/radios.stories.html

[Components v3] Radio

---

packages/scss/src/components/switch/component.scss
packages/scss/src/components/switch/index.scss
packages/scss/src/components/switch/mods.scss
packages/scss/src/components/switch/states.scss
packages/scss/src/components/switch/vars.scss
stories/documentation/forms/switches/switch-basic.stories.ts
stories/documentation/forms/switches/switch-helper.stories.ts
stories/qa/forms/switches.stories.html

Update switch UI
-----
https://user-images.githubusercontent.com/25581936/234840606-2f49ae51-aa29-44ea-b86a-7bcf77ea1f76.mov
-----

[Components v3] Switch

---

packages/ng/input/src/lib/clearer/clearer.component.html
packages/ng/simple-select/src/lib/input/select-input.component.html
packages/ng/styles/components/_picker.scss
packages/ng/styles/components/_popover.scss
packages/ng/styles/definitions/option/_option-item.scss
packages/ng/styles/definitions/option/_option-searcher.scss
packages/ng/styles/definitions/select/_select-clearer.scss
packages/ng/styles/definitions/select/_select-input.scss
packages/scss/src/commons/config.scss
packages/scss/src/components/field/component.scss
packages/scss/src/components/field/mods.scss
packages/scss/src/components/field/states.scss
packages/scss/src/components/field/vars.scss
packages/scss/src/components/textfield/component.scss
packages/scss/src/components/textfield/index.scss
packages/scss/src/components/textfield/mods.scss
packages/scss/src/components/textfield/states.scss
packages/scss/src/components/textfield/vars.scss
stories/documentation/forms/textfields/textfield-basic.stories.ts
stories/documentation/forms/textfields/textfield-clearable.stories.ts
stories/documentation/forms/textfields/textfield-filter.stories.ts
stories/documentation/forms/textfields/textfield-messages.stories.ts
stories/documentation/forms/textfields/textfield-multiline.stories.ts
stories/documentation/forms/textfields/textfield-password.stories.ts
stories/documentation/forms/textfields/textfield-suffixes.stories.ts
stories/qa/forms/textfields.stories.html

Update Textfield / Select UI
-----
-----

[Components v3] Textfield / Select

---

packages/ng/material/style/main.scss
packages/scss/src/components/button/component.scss
packages/scss/src/components/field/component.scss
packages/scss/src/components/link/component.scss
stories/qa/typography/typography.stories.html

Rather than declare the used family font several times, we take advantage of the inheritance when possible.
-----
This will make it easier to override the font when necessary, with one call instead of several.
-----

Font family inherit for button and forms

---

README.md

Add command lines to update LF
-----

[Readme] Update LF

---

packages/scss/src/components/progress/component.scss
packages/scss/src/components/progress/index.scss
packages/scss/src/components/progress/mods.scss
packages/scss/src/components/progress/states.scss
packages/scss/src/components/progress/vars.scss

…and a little less mixins and duplicated CSS code.
-----
-----

More css vars for progress component

---

packages/scss/src/components/button/states.scss

Fix cursor on disabled button

---

stories/documentation/overlays/modal/modal.stories.ts

Remove XXS from story
-----
-----

[Modal] Remove XXS from story

---

packages/scss/src/components/radio/component.scss
packages/scss/src/components/radio/mods.scss

Fix radio height without label
-----

Fix radios without labels

---

packages/scss/src/commons/config.scss
packages/scss/src/commons/utils/loading.scss
packages/scss/src/components/loading/component.scss
packages/scss/src/components/loading/mods.scss
packages/scss/src/components/loading/vars.scss

Update loading component UI
-----
-----

[Componentsv3] Loading

---

packages/scss/src/components/checkbox/mods.scss
packages/scss/src/components/table/component.scss
packages/scss/src/components/table/mods.scss
packages/scss/src/components/table/vars.scss
packages/scss/src/components/tableSorted/mods.scss
packages/scss/src/components/tableSorted/states.scss
stories/documentation/listings/table/table-basic.stories.ts
stories/qa/table/table.stories.html

[Components v3] Table

---

packages/scss/src/commons/config.scss
packages/scss/src/commons/vars.scss
packages/scss/src/components/navside/component.scss
packages/scss/src/components/navside/mods.scss
packages/scss/src/components/navside/vars.scss
stories/qa/main-menu/main-menu.stories.html

[Components v3] Main menu

---

packages/scss/src/components/file/component.scss
packages/scss/src/components/file/index.scss
packages/scss/src/components/file/mods.scss
packages/scss/src/components/file/states.scss
stories/documentation/forms/files/files-basic.stories.ts
stories/documentation/forms/files/files-droppable.stories.ts
stories/documentation/forms/files/files-error.stories.ts
stories/documentation/forms/files/files-success.stories.ts
stories/documentation/forms/files/files-uploading.stories.ts
stories/qa/forms/files.stories.html

[Components v3] File

---

packages/ng/date/src/lib/calendar/calendar-input.component.html
packages/ng/date/src/lib/calendar/calendar-input.component.scss
packages/ng/date/src/lib/calendar/calendar-input.component.ts
packages/ng/styles/components/_calendar.scss

Update calendar UI
-----
-----

[Components v3] Calendar 

---

packages/scss/src/components/timeline/component.scss
packages/scss/src/components/timeline/index.scss
packages/scss/src/components/timeline/mods.scss
packages/scss/src/components/timeline/states.scss
packages/scss/src/components/timeline/vars.scss
stories/qa/timelines/timelines.stories.html

Update timeline UI
-----
-----

[Components v3] Timeline

---

packages/scss/src/components/card/component.scss
packages/scss/src/components/card/index.scss
packages/scss/src/components/card/mods.scss
packages/scss/src/components/card/vars.scss
stories/documentation/structure/cards/cards-action.stories.ts
stories/documentation/structure/cards/cards-basic.stories.ts
stories/documentation/structure/cards/cards-footer.stories.ts
stories/qa/card/card.stories.html

[Components v3] Card 

---

packages/scss/src/components/pagination/component.scss
packages/scss/src/components/pagination/mods.scss

Remove border from pagination component
-----

[Pagination] Remove border

---

packages/ng/api/src/lib/select/input/api-select-input.component.html
packages/ng/department/src/lib/select/input/department-select-input.component.scss
packages/ng/establishment/src/lib/select/input/establishment-select-input.component.html
packages/ng/establishment/src/lib/select/input/establishment-select-input.component.scss
packages/ng/option/src/lib/item/tree-option-item.component.scss
packages/ng/option/src/lib/picker/option-picker.component.html
packages/ng/option/src/lib/picker/tree-option-picker-advanced.component.html
packages/ng/option/src/lib/picker/tree-option-picker.component.html
packages/ng/qualification/src/lib/select/input/qualification-select-input.component.scss
packages/ng/simple-select/src/lib/panel/panel.component.html
packages/ng/simple-select/src/lib/panel/panel.component.scss
packages/ng/styles/components/_dropdown.scss
packages/ng/styles/components/_picker.scss
packages/ng/styles/components/_popover.scss
packages/ng/styles/definitions/option/_option-item.scss
packages/ng/styles/definitions/option/_option-searcher.scss
stories/documentation/forms/select/select-advanced.stories.ts

Update dropdown UI
-----
Todo : Hover + highlighted style
-----

[Components v3] Dropdown

---

packages/ng/material/style/components/_mixins.scss
packages/scss/src/commons/config.scss
packages/scss/src/components/header/component.scss
packages/scss/src/components/textfield/component.scss
packages/scss/src/components/util/index.scss

Replace elevations vars by box shadow
-----

Replace elevations vars by box shadow

---

packages/scss/src/components/statusBadge/component.scss
packages/scss/src/components/statusBadge/index.scss
packages/scss/src/components/statusBadge/mods.scss
packages/scss/src/components/statusBadge/vars.scss
stories/documentation/texts/status-badge/status-badge-basic.stories.ts
stories/qa/status-badge/status-badge.stories.html

Add L size + update colors
-----
-----

[Status Badge] Add L size + update colors

---

packages/scss/src/components/chip/index.scss
packages/scss/src/components/chip/mods.scss
stories/qa/chip/chip.stories.html

- Revert clickable
- Revert unkillable
- Fix `.chip-kill` hover with `palette-primary`
-----

[Fix][Chip] Revert deprecated mixins

---

stories/documentation/structure/grids/grids-span.stories.ts

Fix Grid Colspan story

---

stories/documentation/actions/button/button-basic2.stories.ts
stories/documentation/actions/button/button-counter.stories.ts
stories/documentation/actions/button/button-disabled.stories.ts
stories/documentation/actions/button/button-group.stories.ts
stories/documentation/actions/button/button-icon.stories.ts
stories/documentation/actions/button/button-size.stories.ts
stories/documentation/actions/button/button-style.stories.ts

Test news SB integration

---

stories/documentation/actions/button/button-basic2.stories.ts
stories/documentation/actions/button/button-size.stories.ts
stories/documentation/listings/sortable-list/sortable-list-basic.stories.ts
stories/documentation/structure/grids/grids-alignments.stories.ts
stories/documentation/structure/grids/grids-auto.stories.ts
stories/documentation/structure/grids/grids-basic.stories.ts
stories/documentation/structure/grids/grids-form.stories.ts
stories/documentation/structure/grids/grids-gap.stories.ts
stories/documentation/structure/grids/grids-position.stories.ts
stories/documentation/structure/grids/grids-responsive.stories.ts
stories/documentation/structure/grids/grids-span.stories.ts
stories/documentation/texts/clear/clear.stories.ts
stories/documentation/texts/status-badge/status-badge-basic.stories.ts

Improve SB format for new ZH integration
-----

Storybook format

---

stories/documentation/actions/button/button-basic2.stories.ts

fix button story

---

packages/scss/src/components/button/states.scss
stories/qa/button/button.stories.html

Fix disabled style for outlined & text
-----

[Button] Fix disabled style for outlined & text

---

packages/ng/date/src/lib/calendar/calendar-input.component.scss

Fix calendar disabled state
-----

[Calendar] Fix disabled stated

---

packages/scss/src/components/navside/mods.scss

[Sidenav] Fix alert in compact/active
-----

[Sidenav] Fix alert in compact/active

---

packages/ng/styles/components/_picker.scss

Fix calendar select dropdown width
-----

Fix calendar select dropdown width

---

packages/scss/src/components/title/component.scss

We use the CSS variable defined in mixins.
-----
-----

Font weight for titles

---

.cd/qa.json

Setup de la UIDiff via CSV
-----

MOD: uidiff x csv

---

packages/ng/styles/definitions/select/_select-input.scss

Fix Select padding width mod-S
-----

[Fix] Select padding width mod-S

---

README.md
stories/documentation/actions/action-icon/action-icon-basic.stories.ts
stories/documentation/actions/links/link-basic.stories.ts
stories/documentation/texts/code/code.stories.ts
stories/documentation/texts/icons/icon-colors.stories.ts
stories/documentation/texts/icons/icon-sizes.stories.ts
stories/documentation/texts/labels/label-basic.stories.ts
stories/documentation/texts/labels/label-icon.stories.ts
stories/documentation/texts/tags/tags.stories.ts
stories/documentation/texts/text/text.stories.ts

Improve stories displayed code
-----

Improve stories displayed code

---

README.md
packages/scss/src/components/formLabel/component.scss
packages/scss/src/components/formLabel/exports.scss
packages/scss/src/components/formLabel/index.scss
packages/scss/src/components/formLabel/mods.scss
packages/scss/src/components/formLabel/states.scss
packages/scss/src/components/formLabel/vars.scss
packages/scss/src/components/index.scss
stories/documentation/forms/form-label/form-label.stories.ts
stories/qa/form-label/form-label.stories.html
stories/qa/form-label/form-label.stories.ts

New component : form label
-----
-----

[Components v3] Form label

---

stories/documentation/users/tile/user-tile-format.stories.ts
stories/documentation/users/tile/user-tile.stories.ts

Fix UserTile stories.
Fixes #2197
-----

Fix UserTile stories
